### ISSUE TITLE
New species

### ISSUE THREAD

**Issue by Dmitriy-Filatov-A** [Cantera/cantera#1005]
Hello! I apologize in advance for opening this topic, but I do not know where this question will be appropriate.
In the process of using the Cantera, I did not find some substances in the "cantera/data/*.yaml" directory that I need to calculate so I searched for information about species (The NASA 7/9-Coefficient Polynomial Parameterization) on the Internet but to no avail.
I found this site https://shepherd.caltech.edu/EDL/PublicResources/sdt/thermo.html, but the data presented on this site does not convert well to the yaml format (incorrect). 
Сould you give a link to the resources with the correct *.dat-files?
Thank you in advance!

**Comment by bryanwweber** [comment]
Hi @Dmitriy-Filatov-A This would be a question better asked on our Google Group, https://groups.google.com/g/cantera-users. Please feel free to reopen this issue if you're not able to ask a question on Google. Please note that the list is moderated, so it may take up to a day for your message to appear. Thank you!
