### ISSUE TITLE
AnyMap cannot be compiled with system_yamlcpp on Ubuntu 18.04

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#1029]
**Problem description**

Using the system `libyaml-cpp-dev` on Ubuntu 18.04 results in a compilation error for `AnyMap.cpp`. The version of `libyaml-cpp-dev` appears to be 0.5.2: https://packages.ubuntu.com/bionic/libyaml-cpp-dev

**Steps to reproduce**

1. `apt install libyaml-cpp-dev`
2. `scons build system_yamlcpp=y`
3. 
```
g++ -o build/src/base/AnyMap.os -c -std=c++0x -pthread -O3 -Wno-inline -g -Wall -include src/pch/system.h -fPIC -DNDEBUG -Iinclude -Iinclude/cantera/ext -Ibuild/src -I/usr/include/eigen3 src/base/AnyMap.cpp
src/base/AnyMap.cpp: In static member function 'static bool YAML::convert<Cantera::AnyMap>::decode(const YAML::Node&, Cantera::AnyMap&)':
src/base/AnyMap.cpp:224:28: error: 'const class YAML::Node' has no member named 'Mark'
         target.setLoc(node.Mark().line, node.Mark().column);
                            ^~~~
src/base/AnyMap.cpp:224:46: error: 'const class YAML::Node' has no member named 'Mark'
         target.setLoc(node.Mark().line, node.Mark().column);
                                              ^~~~
src/base/AnyMap.cpp:239:44: error: 'const class YAML::Node' has no member named 'Mark'
             const auto& loc = child.second.Mark();
                                            ^~~~
src/base/AnyMap.cpp: In static member function 'static bool YAML::convert<Cantera::AnyValue>::decode(const YAML::Node&, Cantera::AnyValue&)':
src/base/AnyMap.cpp:414:28: error: 'const class YAML::Node' has no member named 'Mark'
         target.setLoc(node.Mark().line, node.Mark().column);
                            ^~~~
src/base/AnyMap.cpp:414:46: error: 'const class YAML::Node' has no member named 'Mark'
         target.setLoc(node.Mark().line, node.Mark().column);
                                              ^~~~
scons: *** [build/src/base/AnyMap.os] Error 1
scons: building terminated because of errors.
```

It appears that the `Mark` member was released in 0.5.3: https://github.com/jbeder/yaml-cpp/commit/ec8aa4fa625257b0db7254460b91b517e2b16a7e

**System information**

- Cantera version: `main`
- OS: Ubuntu 18.04
- Python/MATLAB/other software versions: System installs of everything, but Python 3 running SCons

**Comment by speth** [comment]
The minimum version of `libyaml-cpp` is documented as being 0.6.0: https://cantera.org/compiling/dependencies.html#sec-dependencies.

I didn't want to forego the ability to provide error messages pointing to specific lines in YAML input. And since we provide a submodule for `libyaml-cpp`, it's pretty easy to get a sufficiently recent version, even if you can't use the official Ubuntu package.

To build the Ubuntu packages for 18.04, I backported `libyaml-cpp` version 0.6.2: https://launchpad.net/~cantera-team/+archive/ubuntu/cantera.

As far as I'm aware, `yaml-cpp` doesn't provide a macro to tell you its version, which is why there's no check for this in our `SConstruct`.

**Comment by bryanwweber** [comment]
Great that this is documented :+1: I agree about the utility of the `Mark` attribute. Does it make sense to check if `Mark()` is available on a `Node` instance in `SConstruct`? I'm not sure how involved that'd be, but I can add it as I refactor that file if it makes sense.

**Comment by speth** [comment]
Yes, you could do that if you wanted to provide a better error message for this situation.
