### ISSUE TITLE
floating point error in pre exponential factor when using .yaml file

### ISSUE THREAD

**Issue by Naikless** [Cantera/cantera#1041]
**Problem description**

Creating a Solution object from a .yaml mech file adds floating point error to the pre exponential factor in the reaction rates which is not found when using the corresponding .cti file.  I am not sure if this is related to https://github.com/Cantera/cantera/issues/614, but I doubt it, because the numbers inside the yaml file itself look fine.

**Steps to reproduce**
```python
import cantera as ct

gas_cti = ct.Solution('h2o2.cti')
gas_yaml = ct.Solution('h2o2.yaml')

A_diff = []
A_diff_rel = []

for r_cti, r_yaml in zip(gas_cti.reactions(), gas_yaml.reactions()):
    if hasattr(r_yaml, 'rate') and hasattr(r_cti, 'rate'):
        A_diff.append(r_cti.rate.pre_exponential_factor - r_yaml.rate.pre_exponential_factor)
        A_diff_rel.append((r_cti.rate.pre_exponential_factor - r_yaml.rate.pre_exponential_factor)/r_cti.rate.pre_exponential_factor)  
    else:
        continue
```

**Behavior**

The above code snippet illustrates the error. While the relative errors are in the range of 1e-16 (so about machine precision) in my tests, this can still lead to rather erratic behavior in model calculations involving many time steps, e.g. when solving ODEs. This can lead to a situation where the solution converges when the cti file is used but fails for the yaml file of the same mechanism.

**System information**

- Cantera version: 2.5.0b1
- OS: Windows 10 64-bit
- Python version: 3.8.5

**Comment by bryanwweber** [comment]
Hi! Thanks for reporting this. Can you include one of the examples of a real case where this fails? Thank you!

**Comment by Naikless** [comment]
Gladly, although I suppose it is a rather specific example that requires [CalTechs shock and detonation toolbox](https://shepherd.caltech.edu/EDL/PublicResources/sdt/):

```python
import cantera as ct
from sdtoolbox.znd import zndsolve
from sdtoolbox.postshock import CJspeed, PostShock_fr

P = 1e5
T = 300
phi = 1.16
X = f'H2:{42*phi}, O2:21, N2:79'

mech = 'gri30.cti' # this converges 
# mech = 'gri30.yaml' # this does not

cj_speed = CJspeed(P, T, X, mech)
    
# Set up gas object of initial state
gas_init = ct.Solution(mech)
gas_init.TPX = T, P, X

# Find frozen post shock state for given speed
gas_fr = PostShock_fr(cj_speed, P, T, X, mech)

# solve ZND reactor
znd_out = zndsolve(gas_fr, gas_init, cj_speed)
```

What happens is that the implicit Radau ODE solver used in `zndsolve` struggles to integrate the system. Due to the slightly different errors in solving the collocation system when using the yaml input, we get to a point where the adaptive time stepping is inflating the time steps to a point where a negative pressure occurs. 

While this is clearly also a problem with the ODE solver, it is interesting to see that this problem does not occur when using the .cti file, because convergence is achieved before this critical point is reached. This caused me some serious head scratching initially.

Considering the fact that it appears to be related to local machine precision, this example might even be machine or os dependant.

**Comment by ischoegl** [comment]
Interesting. I ran a (slightly) modified version of the code posted initially, which accounts for potentially changed reaction indices
```Python
import cantera as ct

gas_cti = ct.Solution('h2o2.cti')
gas_yaml = ct.Solution('h2o2.yaml')

A_diff = []

for r_cti in gas_cti.reactions():
    if hasattr(r_cti, 'rate'):
        for r_yaml in gas_yaml.reactions():
            if r_cti.equation == r_yaml.equation:
                break
        A_cti = r_cti.rate.pre_exponential_factor
        A_yaml = r_yaml.rate.pre_exponential_factor
        A_diff.append((r_cti.equation, A_cti - A_yaml, (A_cti - A_yaml)/A_cti))
    else:
        continue
```
and got the following:
```
In [10]: %run issue_1041.py

In [11]: A_diff
Out[11]: 
[('2 O + M <=> O2 + M', -1.52587890625e-05, -1.2715657552083334e-16),
 ('H + O + M <=> OH + M', -0.0001220703125, -2.44140625e-16),
 ('H2 + O <=> H + OH', 0.0, 0.0),
 ('HO2 + O <=> O2 + OH', -3.814697265625e-06, -1.9073486328125e-16),
 ('H2O2 + O <=> HO2 + OH', 0.0, 0.0),
 ('H + O2 + M <=> HO2 + M', -0.00048828125, -1.743861607142857e-16),
 ('H + 2 O2 <=> HO2 + O2', -0.00390625, -1.8780048076923077e-16),
 ('H + H2O + O2 <=> H2O + HO2', -0.001953125, -1.734569271758437e-16),
 ('AR + H + O2 <=> AR + HO2', -0.0001220703125, -1.743861607142857e-16),
 ('H + O2 <=> O + OH', -0.00390625, -1.474056603773585e-16),
 ('2 H + M <=> H2 + M', -0.000244140625, -2.44140625e-16),
 ('2 H + H2 <=> 2 H2', -1.52587890625e-05, -1.6954210069444444e-16),
 ('2 H + H2O <=> H2 + H2O', -0.0078125, -1.3020833333333334e-16),
 ('H + OH + M <=> H2O + M', -4.0, -1.8181818181818182e-16),
 ('H + HO2 <=> H2O + O', -4.76837158203125e-07, -1.201101154164043e-16),
 ('H + HO2 <=> H2 + O2', -7.62939453125e-06, -1.7029898507254465e-16),
 ('H + HO2 <=> 2 OH', -1.52587890625e-05, -1.816522507440476e-16),
 ('H + H2O2 <=> H2 + HO2', -1.8189894035458565e-12, -1.5032970277238484e-16),
 ('H + H2O2 <=> H2O + OH', -1.9073486328125e-06, -1.9073486328125e-16),
 ('H2 + OH <=> H + H2O', -2.9103830456733704e-11, -1.347399558182116e-16),
 ('2 OH <=> H2O + O', 0.0, 0.0),
 ('HO2 + OH <=> H2O + O2', -1.9073486328125e-06, -1.3154128502155173e-16),
 ('H2O2 + OH <=> H2O + HO2', -2.384185791015625e-07, -1.1920928955078126e-16),
 ('H2O2 + OH <=> H2O + HO2', 1699998000000000.0, 0.9999988235294117),
 ('2 HO2 <=> H2O2 + O2', -1.4901161193847656e-08, -1.146243168757512e-16),
 ('2 HO2 <=> H2O2 + O2', 419870000000.0, 0.9996904761904762),
 ('HO2 + OH <=> H2O + O2', 4985500000000.0, 0.9971)]
```
As far as I can tell, the only differences are for duplicate reactions, which are easily explained.

I modified the code after initially finding discrepancies that are well beyond machine precision. Please note that there are other differences also:
```
In [17]: gas_yaml.species()
Out[17]: 
[<Species H2>,
 <Species H>,
 <Species O>,
 <Species O2>,
 <Species OH>,
 <Species H2O>,
 <Species HO2>,
 <Species H2O2>,
 <Species AR>,
 <Species N2>]

In [18]: gas_cti.species()
Out[18]: 
[<Species H2>,
 <Species H>,
 <Species O>,
 <Species O2>,
 <Species OH>,
 <Species H2O>,
 <Species HO2>,
 <Species H2O2>,
 <Species AR>]
```
I.e. the YAML file includes `N2` as an alternative non-reactive diluent, which was previously not included. ~I believe that either having different reaction indices or having the additional species may be a more likely culprit.~

**Edit:** as the actual failures are for GRI-mech, h2o2-specific observations may be not directly relevant.

**Comment by Naikless** [comment]
Thanks for expanding on this!

> **Edit:** as the actual failures are for GRI-mech, h2o2-specific observations may be not directly relevant.

I believe the question whether these small differences actually lead to real world problems is entirely up to the specific use case. However, they seem to be present regardless of the choice of mechanism.

And since it was possible to have "clean" numbers with cti (and xml) files, there should be a way to achieve the same with yaml input, right?

**Comment by ischoegl** [comment]
> I believe the question whether these small differences actually lead to real world problems is entirely up to the specific use case. However, they seem to be present regardless of the choice of mechanism.

Having those minuscule differences cause failures would not be my first guess. I am unfortunately not familiar enough with the SD toolbox, but there may be some differences outside of Cantera. There is an extensive test suite in place that should ascertain that CTI and YAML produce consistent results within Cantera, although it’s not impossible that there are things that haven’t been anticipated.

Is it possible to trigger the same failures without using external code?

**Comment by Naikless** [comment]
> > I believe the question whether these small differences actually lead to real world problems is entirely up to the specific use case. However, they seem to be present regardless of the choice of mechanism.
> 
> Having those minuscule differences cause failures would not be my first guess. I am unfortunately not familiar enough with the SD toolbox, but there may be some differences outside of Cantera. There is an extensive test suite in place that should ascertain that CTI and YAML produce consistent results within Cantera, although it’s not impossible that there are things that haven’t been anticipated.
> 
> Is it possible to trigger the same failures without using external code?

Maybe to clarify: The reason for the failure is with the implementation of the Radau solver in the SciPy package used by sdtoolbox. 

My point is not that it fails for yaml and succeeds for cti. This is a mere coincidence in this particular case and might very well be just the other way around in a different case. This example just highlights the fact that there can be cases were these miniscule differences can tip a fragile calculation one way or the other and thus cause some confusion as to why they seemingly sometimes succeed and sometimes don't. Because I stumbled on this by accident and there is some randomness involved, it would be hard to come up with another example right off the bat, although I believe it should be possible. 

So, if these errors can be avoided when importing a yaml mech, I would believe it to be a worthwhile goal.

**Comment by speth** [comment]
Well, running the provided example worked fine for me using either CTI or YAML inputs, so the integrator used here is indeed very sensitive to small changes in conditions if you're seeing a failure here.

The underlying issue here is exactly what's described in #614, but in this case the behavior of `ctml_writer` is what is providing the "nice" values that you get when using a CTI file. The reason for the accumulation of some roundoff error here is the conversion of the rate constants from CGS units to Cantera's SI+kmol system.

For a CTI file, these conversions are applied as part of generating the XML version of the input file, since the XML file only allows the SI+kmol system for rate constants. In this case, the value gets truncated to only 7 significant digits by the format string `%14.6E`, and you get a nice, round result.

In the YAML file, we leave the rate constant in the original unit system, and the conversion to SI+kmol happens entirely using `double` values which are never truncated.

The fact that there are small roundoff errors is a slight annoyance for display and serialization purposes, where it would be nice not to have values like 500000000000.0001 lying around, but I don't think we should be that worried about it that much from a numerical accuracy standpoint, given that the original rate constant in this case really only has one significant figure anyway.

**Comment by Naikless** [comment]
Yes, I agree that it should not be considered a numerical problem. I suppose it is then just the question whether it might confuse people to obtain (ever so) slightly different results for the "same" kinetic input data, which in random edge cases can lead to a different "macroscopic" outcome. 

To give some additional context: I was testing calling cantera from within a julia script using PyCall. For some reason, the PyCall wrapper didn't work with cti files, so I used the corresponding yaml. I then ran into the situation that the code failed via julia but ran just fine via python. Naturally I suspected some weird inter-language problem and it took me quite a while to track it down to the choice of the mech file. 

So, coming from this experience, I would probably suggest to unify the roundoff behavior. But this might be an exotic case and I understand if this is not a high priority. And, as pointed out in https://github.com/Cantera/cantera/issues/614, if the phase out of the CTI files is imminent anyway, this might be a moot point.

**Comment by speth** [comment]
Yes, the CTI format is deprecated and will be removed in Cantera 3.0. We're just giving it a little bit longer transition period than some other deprecations, to give people a chance to adapt their workflows. I do have a couple ideas on how to modify the unit conversion calculations that might help in some cases, but haven't had time to actually test them out. I don't think we should make any changes to the CTI/XML workflow at this point.

Fundamentally, I don't we should insist on preserving the exact behavior of `ctml_writer`, given that it was throwing away information in the general case (if the rate constant ever had more than 7 significant figures). The sensitivity of the downstream algorithm here to these small perturbations is unfortunate, but I think you'd run into a problem with this algorithm sooner or later anyway. All it might take is a change in your compiler or some library (e.g. #1033).
