### ISSUE TITLE
Not sure how does Cantera calculate equilibrium constants

### ISSUE THREAD

**Issue by yilangtufts** [Cantera/cantera#1042]
**Problem description**

Not sure how does Cantera calculate equilibrium constants. Does it calculate as K = exp(-ΔG/RT) with thermo data at state of 1 kmol m-3, or K = exp(-ΔG/RT)*(RT*(1000 mol/kmol)/100000 (Pa/bar))^m with thermo data at standard condition? Factor (RT*(1000 mol/kmol)/100000 (Pa/bar))^m appears to be used to make the unit as combination of kmol m-3.

**Steps to reproduce**

Run the attached python code with attached input file (change c2h6_vox_stick_20210514.txt to c2h6_vox_stick_20210514.cti)

Run following code in separate cell to print equilibrium constant for reaction C2H6 + VO(S) <=> C2H6_VO(S)
print(rsurf.kinetics.equilibrium_constants[0])
(This prints out 4.774313072685758)

Run following code in separate cell to print equilibrium constant for reaction C2H5 + O2 <=> C2H5OO
print(r.kinetics.equilibrium_constants[0])
(This prints out 4659.09907731277)

**Behavior**

Cantera derived equilibrium constant of reaction C2H6 + VO(S) <=> C2H6_VO(S) is 4.774. However, based on thremo data in input file, K = exp(-ΔG/RT) = 0.08304 

Cantera derived equilibrium constant of reaction C2H5 + O2 <=> C2H5OO is 4659. However, based on thremo data in input file, K = exp(-ΔG/RT) = 81.13 

**System information**

- Cantera version: 2.5.1
- OS: Ubuntu 20.04.1 LTS
- Python/MATLAB/other software versions: Python

**Attachments**

[code.txt](https://github.com/Cantera/cantera/files/6494765/code.txt)

[c2h6_vox_stick_20210514.txt](https://github.com/Cantera/cantera/files/6494774/c2h6_vox_stick_20210514.txt)

**Additional context**

**Comment by bryanwweber** [comment]
Hi, thanks for asking this question! I'm not sure I completely understand the question, but at least for the ideal gas phase, the standard change in Gibbs energy is used in the calculation. https://github.com/Cantera/cantera/blob/627e21e95e2dc534dabf9fb8fda1e4093177704e/src/kinetics/GasKinetics.cpp#L125-L142

It'd be helpful if you could clarify how you are calculating the equilibrium constants by hand. Thanks!

**Comment by ischoegl** [comment]
Closing, as I assume that @bryanwweber’s response provided the clarification needed. If there are any additional questions, feel free to follow up on the [user group](https://groups.google.com/g/cantera-users).
