### ISSUE TITLE
How can I add one specific specie from a .cti?

### ISSUE THREAD

**Issue by adrianfernandez00** [Cantera/cantera#1044]
Hi everyone

I am new to Cantera and I still do not understand really well how it works. I want to compute the adiabatic flame temperature with the function equil.m (I am using Matlab) I want to mix C2H4 and C3H8 (50/50) but I do not know why I can not get the properties of this species. I write 

`gas = Solution('gri30.cti', 'C2H4') `

but command windows shows:

"CanteraError thrown by newPhase:
Couldn't find phase named "C2H4" in file, gri30.cti". 

How can I do this computation?
`

**Comment by speth** [comment]
I would suggest that this question is more appropriate for the [Cantera Users' Group](https://groups.google.com/g/cantera-users).
