### ISSUE TITLE
Is the fixed temperature in freely-propagating flame fixed in computing domain?

### ISSUE THREAD

**Issue by Serenade600** [Cantera/cantera#1046]
I realized that there is a fixed temperature point in code for computation of free flame speed . But I am stumped by another issue then. Where the fixed temperature is positioned in the computing domain?

I met two articles which has different realizations of the spatial position for the fixed temperature using Cantera. One is in _Propagation velocity of a deflagration front in a preheated autoigniting mixture_, where the flames is anchored at specified position by the author. The other is in _The transition from autoignition to propagation at elevated temperatures obtained from 1-D flame simulations_, in which the flame is located between one fourth and half of domain length. So is the latter the default setting of Cantera?  And Cantera also offer functions to call to redefine the fixed position?

I'm not sure whether the copywrite allows spread of digital format of the two articles in this situation. But if they are interested, the barrier can be tackled by common effort.

**Comment by bryanwweber** [comment]
Hi, thanks for posting this! I think this question would be better asked at our Users' Group, https://groups.google.com/g/cantera-users. You can link to the official version of those papers, or at least provide a complete citation (authors, journal, etc.) so others can find them more easily.

Thanks!

**Comment by ischoegl** [comment]
I agree that this is a question for the user group - incidentally, there was a question about this very recently (not sure whether you were the person who asked). 

The relevant portion of the code is: https://github.com/Cantera/cantera/blob/01bf417683a015fe85393273c9f5aab8ebc32a0a/include/cantera/oneD/StFlow.h#L120-L132

i.e. the energy equation is disabled in a grid point to 'anchor' the flame. Beyond, both temperature and location of the fixed point can be set, see [Documentation](https://cantera.org/documentation/docs-2.5/sphinx/html/cython/onedim.html#cantera.Sim1D.fixed_temperature).
