### ISSUE TITLE
Error when building cantera 

### ISSUE THREAD

**Issue by JamXJH** [Cantera/cantera#1054]
**Problem description**

**Steps to reproduce**

1. Run 'scons build'
2. See error '/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
scons: *** [build/lib/libcantera_shared.so.2.5.1] Error 1
'

**Behavior**

**System information**

- Cantera version: [ 2.5.0 ]
- OS: [Centos7]
- Python/MATLAB/other software versions: python 3.9.5, gcc 9.3.0, yaml-cpp 0.6.3

**Attachments**

Hi, 
I got an error when building Cantera and still couldn't fixed it after trying everything. Could you please give some advice?
The error turn out like the following:
/usr/bin/ld: //usr/local/lib/libyaml-cpp.a(scantoken.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libyaml-cpp.a(simplekey.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libyaml-cpp.a(singledocparser.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libyaml-cpp.a(stream.cpp.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
...
/usr/bin/ld: //usr/local/lib/libyaml-cpp.a(scantag.cpp.o): relocation R_X86_64_32 against symbol `_ZZN4YAML3Exp3TagEvE1e' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libyaml-cpp.a(exp.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt9basic_iosIcSt11char_traitsIcEE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
scons: *** [build/lib/libcantera_shared.so.2.5.1] Error 1
scons: building terminated because of errors.

Thank you for help!!
**Additional context**

**Comment by bryanwweber** [comment]
Hi, Thanks for reporting this! Can you please attach the full contents of the build log? Thank you!

**Comment by speth** [comment]
You need to do one of the following:
1. Compile the shared library for `yaml-cpp` 
2. As the error message suggests, have it compile the static library components with the `-fPIC` flag
3. Let Cantera compile its own version of the `yaml-cpp` library by specifying the option `system_yamlcpp=n`

I think the third option is probably the simplest.

**Comment by JamXJH** [comment]
[config.log](https://github.com/Cantera/cantera/files/6641762/config.log)



> Hi, Thanks for reporting this! Can you please attach the full contents of the build log? Thank you!

Thank you for your replying!! Here is the file named Config.log

**Comment by JamXJH** [comment]
> You need to do one of the following:
> 
> 1. Compile the shared library for `yaml-cpp`
> 2. As the error message suggests, have it compile the static library components with the `-fPIC` flag
> 3. Let Cantera compile its own version of the `yaml-cpp` library by specifying the option `system_yamlcpp=n`
> 
> I think the third option is probably the simplest.

Hi, speth! Thank you for your advice, but the third option seems no work for me, it tells me about 'ERROR: yaml-cpp is missing. Install source in ext/yaml-cpp.', and here is the log. Actually, I have had to install all the library like boost, fmt, eigen, sundials by myself which are supposed to be compiled by Cantera. And is the second option means building contera with the command'scons build -fPIC'? It successly finished build but  ran the same error when I installed it. I guess the static library didn't compiled, could you give some details about first or second option? Thanks a lot!
  
[config.log](https://github.com/Cantera/cantera/files/6641770/config.log)

**Comment by bryanwweber** [comment]
Hi, If you install `git` on your system, and you're building from a clone of this repository, then Cantera will automatically clone the yaml-cpp source code if it can't be found in that folder.

**Comment by speth** [comment]
> And is the second option means building contera with the command'scons build -fPIC'?

Sorry, I wasn't very clear. I meant that you have to specify that compiler option when building `yaml-cpp`. I just looked at the CMake configuration for `yaml-cpp`, and unfortunately there doesn't seem to be a good place to add this. So perhaps (1) is a better option than (2). For that, when you are running cmake, you'd just need to set `YAML_BUILD_SHARED_LIBS` to `ON`.

However, cloning the Cantera git repository and letting it do the work, as @bryanwweber suggests, is probably easier still.

**Comment by JamXJH** [comment]
I have successfully installed Cantera, thank you for your help!!
