### ISSUE TITLE
Documentation for coverage-dependence E parameter

### ISSUE THREAD

**Issue by rwest** [Cantera/cantera#1068]
I suggest/request an improvement to the documentation for coverage-dependencies that shows up at 
https://cantera.org/documentation/dev/sphinx/html/yaml/reactions.html#interface

> coverage-dependencies
> A mapping of species names to coverage dependence parameters, where these parameters are contained in a mapping with the fields:
> 
> a
> Coefficient for exponential dependence on the coverage
> 
> m
> Power-law exponent of coverage dependence
> 
> E
> Activation energy dependence on coverage
> Example:
> 
> `equation: 2 H(s) => H2 + 2 Pt(s)`
> `rate-constant: {A: 3.7e21 cm^2/mol/s, b: 0, Ea: 67400 J/mol}`
> `coverage-dependencies: {H(s): {a: 0, m: 0, E: -6000 J/mol}}`

It's factually correct, but you need to cross-reference with the documentation at 
https://cantera.org/science/reactions.html#surface-reactions
and read the equations carefully and think to be sure that you get the sign right on $E_k$.

Some researchers publish using $\eplison_i$ which is the negative of $E_k$, and Detchem uses that convention.

There's no mistake in Cantera's documentation, and it's consistent with Chemkin's, but given the high potential for error here (speaking from experience), I think we could be more explicit and can afford a few extra words (especially as the chosen example has a negative value for E). 

I can open a PR if nobody beats me to it, but wanted to at least open an issue before I forget.

**Comment by ischoegl** [comment]
@rwest … thanks for creating this issue. As you’re very familiar with what needs to be done, it would be great if you could clarify the documentation with a short PR.
