### ISSUE TITLE
deltastar fits degree 6 but evaluates as degree 5

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [Cantera/cantera#1070]
MMCollisionInt.cpp defines 
const int DeltaDegree = 6;
used to fit m_o22poly and co.
but then they are evaluated using poly5.
I.e the last coefficient is ignored.
If there is any numerical reason for this, it is not documented.

**Comment by ischoegl** [comment]
Thanks @Matthias-Fauconneau for reporting. I looked at the source code and confirmed that `polyfit` uses a degree of 6, while the polynomial appears to be evaluated with `poly5`. I ran a quick test with changing `DeltaDegree` to 5, which (expectedly) broke the test suite, specifically
```
Failed tests:
    - transport: TransportPolynomialsTest.viscosityPolynomials
    - transport: TransportPolynomialsTest.conductivityPolynomials
    - mixGasTransport
    - multiGasTransport
    - cxx-flamespeed
```
The difference in results isn't dramatic, but there does appear to be a discrepancy. I am not an expert on the underlying theory, but there appears to be a glitch in the code.
