### ISSUE TITLE
Issues recreating SolutionArray objects from stored data in csv file

### ISSUE THREAD

**Issue by stijn76** [Cantera/cantera#1073]
I'm very new to this forum (and to any development forum for that matter), so my apologies in case my remark is not formulated at the right place or in the right way. I was using the latest cantera version, and trying to recreate a SolutionArray objects from stored data, but got a ValueError. The problems does not seem to be solved in the composite.py source code files which I found here at github.

The minimal code to reproduce the problem is:

```
import cantera as ct

premix = ct.Solution('gri30.yaml')
states = ct.SolutionArray(premix)
test1 = ct.SolutionArray(premix)
test2 = ct.SolutionArray(premix)

T_in = 300
P_in = 101300
air2gas = 7.6
premix.X = 'N2:'+str(air2gas*0.79) + ', O2:'+str(air2gas*0.21) + ', CH4:'+str(1.0)
premix.TP = T_in , P_in
states.append(T=premix.T, P=premix.P, X=premix.X)
states.write_csv('test1.csv')

# Reading the csv file with only 1 data line, throws an IndexError
# test1.read_csv('test1.csv')

air2gas = 8.3
premix.X = 'N2:'+str(air2gas*0.79) + ', O2:'+str(air2gas*0.21) + ', CH4:'+str(1.0)
premix.TP = T_in , P_in
states.append(T=premix.T, P=premix.P, X=premix.X)
states.write_csv('test2.csv')

# Reading the csv file with more than 1 data line, throws a ValueError
test2.read_csv('test2.csv')
```

I believe the problem is situation in de definition of the "join" function in the "composite.py" file. More specifically, within that definition, valid species is declared as:
```
valid_species = {s[2:]: labels.index(s) for s in spc
                             if s in labels}
```
but should be declared as
```
valid_species = {s[:]: labels.index(s) for s in spc
                             if s in labels}
```
or else the ValueError will always be thrown because valid_species represents species_names without prefixes ('X_', or 'Y_') while all_species represents species_names with those prefixes.
```
if len(valid_species) != len(all_species):
                    incompatible = list(set(valid_species) ^ set(all_species))
                    raise ValueError('incompatible species information for '
                                    '{}'.format(incompatible))
```

Warm regards, Stijn

_Originally posted by @stijn76 in https://github.com/Cantera/cantera/issues/687#issuecomment-880855365_

**Comment by stijn76** [comment]
Hi all,

When solving the problem as proposed above, a new problem was generated. The 'gri30.yaml' file contains a species 'CH2(S)' which is written to the csv file as 'CH2(S)', but read from the csv-file as 'CH2S'. 

This can be solved in composites.py, by specifying the "deletechars" parameter in the read_csv routine:
'''
data = np.genfromtxt(filename, delimiter=',',
                                 dtype=None, names=True, encoding=None, deletechars='')
'''

In fact, this last error is the reason why the error reported above in the "join" function popped up when using "gri30.yaml". This last error caused the length of all_species and valid_species to differ (because one had CH2S in it, and the other skipped CH2(S) altogether), triggering further error checking. Still, in my humble opinion the modification to the "join" function as mentioned above should be made for the code to work as intended.

Kind regards,

Stijn

**Comment by ischoegl** [comment]
Thanks for reporting this issue @stijn76.

**Comment by stijn76** [comment]
Still struggling my way through this... My original solution for the "join" routine in composite.py solved the original problem, but created another one when reading the _csv file. I believe/hope I got to the correct solution now.

In "composite.py", the definitions of valid_species and all_species in "def join" should become
'''
            # solution species names also found in labels
            valid_species = {s[2:]: labels.index(s) for s in spc
                             if s in labels}

            # labels that start with prefix (indicating concentration)
            all_species = [l[2:] for l in labels if l.startswith(prefix)]
''' 
as opposed to both the current released version and my first solution in a previous post. For later use in the "join" routine, it's important that both refer to the species name only, and not to the labels refering to the X_ or Y_ fractions of those species.

**Comment by ischoegl** [comment]
I think what you posted above is the same as what is proposed in #1074 (which fixes all issues), so I believe you got this correct.

**Comment by stijn76** [comment]
Great! Thanks for confirming!
