### ISSUE TITLE
IdealSolidSolnPhase::getPartialMolarEnthalpies - needs pressure dependence?

### ISSUE THREAD

**Issue by decaluwe** [Cantera/cantera#1080]
**Problem description**
The `getPartialMolarEnthalpies` routine in `IdealSolidSolnPhase` would appear to be missing the required pressure dependence implemented elsewhere in the model.

All other enthalpy (and, by association, chemical potential) calculations involve some form of `(P - Pref)*molarVolume` (where `molarVolume` is of either the phase or the individual species).

`IdealSolidSolnPhase::getPartialMolarEnthalpies` does not:

```
void IdealSolidSolnPhase::getPartialMolarEnthalpies(doublereal* hbar) const
{
    const vector_fp& _h = enthalpy_RT_ref();
    scale(_h.begin(), _h.end(), hbar, RT());
}
```
I think this ought to be replaced with:
```
void IdealSolidSolnPhase::getPartialMolarEnthalpies(doublereal* hbar) const
{
    const vector_fp& _h = enthalpy_RT_ref();
    scale(_h.begin(), _h.end(), hbar, RT());
    double delta_p = (m_Pcurrent - m_Pref);
    for (size_t k = 0; k < m_kk; k++) {
        hbar[k] += delta_p * m_speciesMolarVolume[k];
    }
}
```
**System information**

- Cantera version: 2.6.0a2

Wanted to check if I was missing something, before fixing it.

**Comment by speth** [comment]
Seems correct to me. If you follow through the more convoluted logic for the similar `IdealSolnGasVPSS` class, the `(P - Pref)*molarVolume` term does get added to the standard state enthalpy, which then gets carried through to the partial molar enthalpies.

**Comment by decaluwe** [comment]
Sorry if this is dense, but: "seems correct to me" meaning "the current implementation seems correct," or "your critique seems correct?"  🙄

Since `IdealSolidSolnPhase` does not add the pressure term to the  standard state values, I'll assume you mean the latter 😉. Just to make sure, I did a little check:

```python
import cantera as ct
import numpy as np

gas = ct.Solution('IdealSolidSolnPhaseExample.yaml',"solidSolutionExample")

# At standard pressure: h_mole = sum(X_k*h_k)
h_mole = gas.enthalpy_mole
h_k = gas.partial_molar_enthalpies

h_check = np.dot(h_k,gas.X)
print(h_mole, h_check)
5895465.481744414 5895465.481744414

# At non-standard pressure, h_mole shows the correct pressure dependence, but the partial molar enthalpies do not:
gas.TP = None, 3*ct.one_atm
h_mole = gas.enthalpy_mole
h_k = gas.partial_molar_enthalpies
h_check = np.dot(h_k,gas.X)
print(h_mole, h_check)
6199440.481744414 5895465.481744414

```

When I originally created this issue, I thought we were considering folding `IdealSolnGasVPSS` into this class.  But since the opposite is true, I will hold off on doing anything about this, for now.

**Comment by speth** [comment]
Yes, I meant your interpretation seems correct and `IdealSolidSolnPhase` does not.

**Comment by decaluwe** [comment]
lol, thanks for the confirmation :)
