### ISSUE TITLE
SolutionArray.append sometimes fails

### ISSUE THREAD

**Issue by stijn76** [Cantera/cantera#1085]
In some cases, the .append function to a SolutionArray object fails.

A minimal problem code is shown below:
'''
premix = ct.Solution('h2o2.yaml')
states = ct.SolutionArray(premix)
test1 = ct.SolutionArray(premix)
test2 = ct.SolutionArray(premix)

premix.X = 'N2:'+str(0.79) + ', O2:'+str(0.21) 
premix.TP = 300 , 101300
states.append(premix.state)

premix.X = 'N2:'+str(0.70) + ', O2:'+str(0.30)
premix.TP = 300 , 101300
states.append(premix.state)

states.write_csv('test1.csv')
test1.read_csv('test1.csv')

premix.X = 'N2:'+str(0.65) + ', O2:'+str(0.35)
premix.TP = 300 , 101300
test1.append(premix.state)
'''

The error refers to the composites.py append function, in particular the line (around line 715 in the composites.py file)
'''
self._indices.append(len(self._indices))
'''
_indices is a range object and does no longer have an append function in Python 3. 

One possible solution is to cast the range object into a list:
'''
self._indices=list(self._indices) 
self._indices.append(len(self._indices))    
'''

Kind regards,

Stijn

**Comment by bryanwweber** [comment]
Thanks for reporting this! If you feel comfortable making a Pull Request, please feel free to do so.

**Comment by stijn76** [comment]
Hi, I don't feel comfortable making a Pull Request -sorry. I lack any experience in how large collaborative software projects are managed...

**Comment by ischoegl** [comment]
@stijn76 ... thanks for reporting also! Per your suggestion, I believe changing https://github.com/Cantera/cantera/blob/ec67ed1096b51c0963a22565643e6125fc083654/interfaces/cython/cantera/composite.py#L931
to 
```Python
            self._indices = list(range(rows))
```
should take care of this? (this is also done on line 527)

Submitting a pull request is actually easier than it appears (at least if you know your way around `git`) - simply fork the repository on GitHub, create a new branch, change the file(s) and push it back to your fork. Then you navigate to the main repository, check the Pull request tab and should see your new branch being suggested for a new pull request. The rest is fairly self-explanatory. 

Let me know if you should have any questions, and thanks again for helping to improve Cantera! (regardless whether you create the PR yourself or someone else takes care of it).

**Comment by stijn76** [comment]
Yes, your proposal addresses the root cause. I've done some homework on github and made a pull request. It's my first ever, so please be alert when reviewing it.

Thanks for your guidance and work on Cantera -which promises to become of great help to my own work.
