### ISSUE TITLE
Chemical equilibrium (a question).

### ISSUE THREAD

**Issue by Dmitriy-Filatov-A** [Cantera/cantera#1091]
Hello! I'm using Cantera 2.5.0 in C++ and I have a question about solving the chemical equilibrium.
Can I solve the chemical equilibrium if I have the Pressure and Enthalpy parameters? For example, the "equilibrate" function gets the Temperature and Pressure parameters but not the Temperature and Enthalpy parameters.

**Comment by bryanwweber** [comment]
Hi @Dmitriy-Filatov-A! I think this question would be better suited for the [Users' Group](https://groups.google.com/g/cantera-users). Please make sure to attach some sample code that compiles to the post. Thank you!
