### ISSUE TITLE
Yaml file backwards compatibility

### ISSUE THREAD

**Issue by abimren** [Cantera/cantera#1092]
**Problem description**
Yaml file used in the stable release 2.5.1 did not work in the current development release 2.6.0.a2. I get duplicate reaction error.

Error on lines 126 and 129 of ./chem.yaml:
Undeclared duplicate reactions detected:
Reaction 3: 2 H + M <=> H2 + M
Reaction 2: 2 H + H2 <=> H2 + H2
<pre>|  Line |
|   121 | reactions:
|   122 | - equation: H + O2 + M &lt;=&gt; HO2 + M  # Reaction 1
|   123 |   type: three-body
|   124 |   rate-constant: {A: 3.61e+17, b: -0.72, Ea: 0.0}
|   125 |   efficiencies: {H2O: 18.6, H2: 2.86}
&gt;   126 &gt; - equation: H + H + M &lt;=&gt; H2 + M  # Reaction 2
            ^
|   127 |   type: three-body
|   128 |   rate-constant: {A: 1.0e+18, b: -1.0, Ea: 0.0}
&gt;   129 &gt; - equation: H + H + H2 &lt;=&gt; H2 + H2  # Reaction 3
            ^
|   130 |   rate-constant: {A: 9.2e+16, b: -0.6, Ea: 0.0}
|   131 | - equation: H + H + H2O &lt;=&gt; H2 + H2O  # Reaction 4
|   132 |   rate-constant: {A: 6.0e+19, b: -1.25, Ea: 0.0}
</pre>
**Steps to reproduce**

1. Generate yaml file from a chemkin mechanism file in stable release 2.5.1.
2. Run constant pressure reactor problem
3. Use same yaml file in current development release

**Behavior**

Current development release complain about yaml file. In mechanism file, if those reactions are declared as DUP and if yaml file is re-generated, it works.
**System information**

- Cantera version: 2.5.1 and 2.6.0
- OS: Ubuntu
- Python/C++ interface:

**Attachments**

**Additional context**

**Comment by bryanwweber** [comment]
Hi! Thanks for reporting this. Can you please attach a minimal YAML file that reproduces this issue? Thank you!

**Comment by abimren** [comment]
Hi Bryan,
I attached 2 files:
h2 CT 2.5.1 did not work in the current development release 
[h2ct251.yaml.txt](https://github.com/Cantera/cantera/files/7138857/h2ct251.yaml.txt)
h2 CT 2.6.0.a2 worked unless I declare reactions created problem as DUP 
[h2ct260a2.yaml.txt](https://github.com/Cantera/cantera/files/7138860/h2ct260a2.yaml.txt)

**Comment by ischoegl** [comment]
Hi @abimren ... there was a recent change in Cantera 2.6.0a where implicitly defined three-body reactions like
```yaml
- equation: H + H + H2 <=> H2 + H2  # Reaction 3
  rate-constant: {A: 9.2e+16, b: -0.6, Ea: 0.0}
```
are recognized as such (note that `H2` appears on both sides). In 2.5.1 and before, `H2` would have been treated as a regular reactant, where concentrations are handled in a slightly different fashion (see bug report related to real gas behavior https://github.com/Cantera/cantera/issues/967).

You apparently have discovered an edge case where the logic used for the detection of duplicate reactions needs to be updated. Before this change, the reaction types were different, which explains why this used to work.

**Comment by mefuller** [comment]
I've also observed this recently, but I genuinely thought this was a feature, not a bug:
I would personally consider the reactions as duplicates where either a collider efficiency for H2 should be give in reaction 3 and reaction 2 eliminated or  `duplicate: true` passed, i.e. @ischoegl I would recommend against updating the logic used to detect duplicate reactions.
The current behavior has proved very useful to me in properly merging mechanisms.

**Comment by ischoegl** [comment]
@mefuller ... thanks for the comment.

**Comment by speth** [comment]
Hi @abimren, can you provide the original Chemkin-format file that was used to generate these YAML files?

Generally, I agree that this should be considered an error unless the reactions are either declared duplicates or the reaction with `M` has the efficiency for `H2` set to zero.

**Comment by abimren** [comment]
Hi @speth, I attached CK files. Thanks for your attention and other comments. 
[chem.inp.txt](https://github.com/Cantera/cantera/files/7325439/chem.inp.txt
[therm.dat.txt](https://github.com/Cantera/cantera/files/7325440/therm.dat.txt)
)

**Comment by ischoegl** [comment]
@abimren ... thank you for posting. I don't have a way to check here, but does Chemkin itself generate warnings when importing this mechanism? I generally agree with @mefuller and @speth that this duplicate check is a feature, but one issue here may be that we need to catch those undeclared third-body reactions during the conversion via `ck2yaml`. Another way would be to set a flag that depends on the cantera version (or user action) to override this error.

**Comment by abimren** [comment]
You are welcome. I don't think that CK will give a warning. Default CT version does not complain.

**Comment by speth** [comment]
`ck2yaml` does complain about this, assuming you have the full Python module installed. All mechanism validation issues are handled by importing the input file and seeing if any problems are found. `ck2yaml` then does an extra step to update the error message so it refers to the problematic lines in the original input file. In this case:
```
Wrote YAML mechanism file to 'chem.yaml'.
Mechanism contains 9 species and 20 reactions.
Validating mechanism...
FAILED
Undeclared duplicate reaction H + H + M <=> H2 + M
found on lines 8 and 9 of the kinetics input file.
```

**Comment by ischoegl** [comment]
> `ck2yaml` does complain about this, assuming you have the full Python module installed. 

:+1: Perfect, thanks! I was under the impression that `ck2yaml` was independent from the actual `cantera` package - my bad! It's well hidden in the guts of the code, but it's certainly there: https://github.com/Cantera/cantera/blob/a27eb1fff413beddf6d64d013a0ceb4dc08b4139/interfaces/cython/cantera/ck2yaml.py#L2206-L2226

That makes a resolution much simpler :tada:

**Comment by speth** [comment]
`ck2yaml` from Cantera 2.5.1 and the current `main` branch produce identical YAML files for this input. The only change is the result of #1015, where these two reactions are now seen as being duplicates with respect to H2 as the third body collider, and I think that is definitely the correct behavior in this case.

I suspect that the mechanism should have third-body efficiencies of 0 specified for `H2` and `H2O` for the reaction `H+H+M=H2+M`. If this change is made, Cantera does not flag it as an error.

I am curious as to whether Chemkin flags this as a problem or not, but I don't have a machine where I can run it right now, and I'm not curious enough to keep this issue open.
