### ISSUE TITLE
Fails to install into the stage directory

### ISSUE THREAD

**Issue by yurivict** [Cantera/cantera#1094]
**Problem description**

I build with:
```
                scons build -j 8 \
                        prefix=/usr/local \
                        system_eigen='y' \
                        system_sundials='y' \
                        system_fmt='y' \
                        sundials_include='/usr/local/include/sundials' \
                        extra_inc_dirs="${LOCALBASE}/include:${LOCALBASE}/include/eigen3" \
                        extra_lib_dirs="${LOCALBASE}/lib"
```

and install with:
```
                ${MAKE_CMD} install \
                        prefix=/disk-samsung/freebsd-ports/science/cantera/work/stage/usr/local
```

Problem:
Installed files contain the stage directory:
```
Error: 'include/cantera/Cantera.mak' is referring to /disk-samsung/freebsd-ports/science/cantera/work/stage
Error: 'share/cantera/samples/cxx/flamespeed/Makefile' is referring to /disk-samsung/freebsd-ports/science/cantera/work/stage
Error: 'share/cantera/samples/cxx/flamespeed/CMakeLists.txt' is referring to /disk-samsung/freebsd-ports/science/cantera/work/stage
Error: 'share/cantera/samples/cxx/flamespeed/SConstruct' is referring to /disk-samsung/freebsd-ports/science/cantera/work/stage
Error: 'share/cantera/samples/cxx/rankine/Makefile' is referring to /disk-samsung/freebsd-ports/science/cantera/work/stage
Error: 'share/cantera/samples/cxx/rankine/SConstruct' is referring to /disk-samsung/freebsd-ports/science/cantera/work/stage
Error: 'share/cantera/samples/cxx/rankine/CMakeLists.txt' is referring to /disk-samsung/freebsd-ports/science/cantera/work/stage
Error: 'share/cantera/samples/cxx/openmp_ignition/Makefile' is referring to /disk-samsung/freebsd-ports/science/cantera/work/stage
```

If to install w/out the prefix= argument it breaks because it attempts to write into /usr/local/.

**Comment by yurivict** [comment]
The FreeBSD port: https://cgit.freebsd.org/ports/tree/science/cantera/Makefile

Build is done with arguments from the variable ```MAKE_ARGS```.
Install is done by the command in ```do-install```.

**Comment by bryanwweber** [comment]
Hi, what does `${MAKE_CMD}` do? What command is that calling? If you aren't calling `scons install` with the prefix, then that might be why the stage paths are still present. You may want to take a look at how the Debian installer is managed in the SCons scripts in this repo for how that is done, I imagine it is similar in some ways to what you need to do for FreeBSD.

**Comment by yurivict** [comment]
```MAKE_CMD``` is just ```scons```.

I looked at Gentoo and Arch install scripts - they do the same. But their frameworks probably don't check if stage directory path appears in installed files so they might just produce broken python files.

**Comment by yurivict** [comment]
It seems to ignore ```stage_dir="${STAGEDIR}"```

**Comment by speth** [comment]
It doesn't ignore `stage_dir` in general -- can you provide the log output of running `scons install` with `stage_dir` set as you indicated?

**Comment by yurivict** [comment]
The log: https://people.freebsd.org/~yuri/cantera-broken-python-option.log

This message is wrong:
```
File locations:

  applications                /usr/local/bin
  library files               /usr/local/lib
  C++ headers                 /usr/local/include
  samples                     /usr/local/share/cantera/samples
  data files                  /usr/local/share/cantera/data  
  Python package (cantera)    /disk-samsung/freebsd-ports/science/cantera/work/stage/$prefix/lib/python3.8/site-packages
  Python samples              /disk-samsung/freebsd-ports/science/cantera/work/stage/$prefix/lib/python3.8/site-packages/cantera/examples
```

For python files it reports a different location - one containing the stage directory and ```$prefix``` in it.

**Comment by speth** [comment]
This issue was just fixed in #1100. Can you update your copy of Cantera and try again?

**Comment by yurivict** [comment]
rev. 37599a79e still has this problem.

**Comment by speth** [comment]
Can you please post an updated log? And also the log of running `scons build dump` (along with your other options to SCons)?

**Comment by yurivict** [comment]
I updated https://people.freebsd.org/~yuri/cantera-broken-python-option.log

scons build dump: https://people.freebsd.org/~yuri/cantera-scons-build-dump.txt

**Comment by speth** [comment]
I don't see any sign of anything being installed to a directory with the literal name `$prefix`, so the previously-identified issue is resolved and it would help to be a little more specific about the remaining issues.

From the log, it looks like the only files that incorrectly contain the stage directory name are `setup_cantera.csh` and `setup_cantera`. The rest of the warnings are about `.pyc` files which you presumably don't want to include in the package anyway.

**Comment by yurivict** [comment]
> From the log, it looks like the only files that incorrectly contain the stage directory name are setup_cantera.csh and setup_cantera. The rest of the warnings are about .pyc files which you presumably don't want to include in the package anyway.

No, all files that it complains about are included in the package.

**Comment by speth** [comment]
I just opened PR #1102 which fixes the issue with `setup_cantera` and `setup_cantera.csh`.

Regarding the `.pyc` files, I'm sort of surprised that you would want to bundle them in the package. For Debian/Ubuntu, and for Python wheels, I know they are not packaged but instead generated when the package is installed. But if that is the practice for FreeBSD, how is this handled for other Python packages? The same issue of doing the byte-compilation with the files installed in a stage directory must come up for just about every other Python package as well.

More broadly, the fact that the path appears in the file seems to have no impact -- after moving the staged package to the actual installation location, Python is able to use the `.pyc` files as is and does not regenerate them.

**Comment by yurivict** [comment]
On FreeBSD *.pyc files are generated as part of build, during the ```install``` stage.

I am not sure how this works exactly, but they are generated without containing the stage directory path.

One notable difference is ```scons```. Very few ports use ```scons```.

**Comment by speth** [comment]
Can you point me to the build scripts and a log of the build process for a different Python package, that shows all of the commands that are being executed and the environment variables that are being set? I assume it would have to be something that influences `setuptools` via the `python setup.py install ...` command, but I have no idea what.

I don't think the use of SCons has anything to do with this -- it's not like autotools knows anything about how to build or install Python packages, either.

**Comment by yurivict** [comment]
Here's the log of math/py-numexpr: https://people.freebsd.org/~yuri/py-numexpr.log

**Comment by speth** [comment]
@yurivict, can you try using the latest commit on PR #1102 (36e7019) to see if it fixes this issue for you?

**Comment by yurivict** [comment]
PR#1102 solved this problem.

Thank you for fixing it.

I updated the FreeBSD port with the enabled PYTHON option in it.

**Comment by speth** [comment]
Thanks for confirming this works for you. Please note that #1102 is not merged to the `main` branch yet, so this isn't fixed there yet, and I'd like to leave this issue open until then. I need some confirmation that I haven't broken any of the other numerous installation options.
