### ISSUE TITLE
Missing semicolon in causes unnecessary command window spam

### ISSUE THREAD

**Issue by rasmusfagerlund** [Cantera/cantera#1104]
**Problem description**

There is a missing semicolon in matlab/toolbox/@Reactor/setEnergy.m, line 29. This causes an unnecessary output to the command window. If running multiple cases this cause clutter in the command window.

Changing line 29 in setEnergy.m
`reactormethods(9, r.index, iflag)`
to
`reactormethods(9, r.index, iflag);`
fixes the problem.

**Steps to reproduce**

1. Run following code in command window or as a script
```
gas = Solution('gri30.cti');
r = IdealGasReactor(gas);
for i = 1:5
    setEnergy(r,'off');
end
```
2. Watch five instances of
```
ans =

     0
```
in the command window

**System information**

- Cantera version: 2.5.1
- OS: Windows 10
- MATLAB R2021a

**Comment by bryanwweber** [comment]
Thanks for reporting this! If you are familiar with GitHub, feel free to submit a pull request with this fix.
