### ISSUE TITLE
Usability for geochemical modelling

### ISSUE THREAD

**Issue by arjenmarkus** [Cantera/cantera#1118]
I recently learned of this project (via fortran-lang/fpm as it happens) and I am curious if it is useable for geochemical modelling. A quick inspection of the data directory showed me most of the databases are leaning towards industrial applications. So, my question is: are there any databases useful for, say, calculating pH and alkalinity in seawater?

**Comment by bryanwweber** [comment]
Hi! Welcome to Cantera 😀 This issue tracker is used for bugs and/or feature requests for the code. For general questions, it's better to ask on our Google Group, https://groups.google.com/g/cantera-users More people read the group, so you're more likely to get a useful answer. Thanks!
