### ISSUE TITLE
Backport path fix to 2.5.1?

### ISSUE THREAD

**Issue by mefuller** [Cantera/cantera#1126]
**Problem description**
When attempting to build  an RPM in a `chroot`, there are at least two files (`setup_cantera`, `setup_cantera.csh`) that improperly list the complete system path, causing the build to fail:
```
+ /usr/lib/rpm/check-buildroot
/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/bin/setup_cantera:if [ "/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/lib64/python3.10/site-packages" != "" ]; then
/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/bin/setup_cantera:        PYTHONPATH=/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/lib64/python3.10/site-packages
/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/bin/setup_cantera:        PYTHONPATH=/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/lib64/python3.10/site-packages:$PYTHONPATH
/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/bin/setup_cantera.csh:if ("/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/lib64/python3.10/site-packages" != "") then
/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/bin/setup_cantera.csh:        setenv PYTHONPATH /home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/lib64/python3.10/site-packages
/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/bin/setup_cantera.csh:        setenv PYTHONPATH /home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64/usr/lib64/python3.10/site-packages:$PYTHONPATH
Found '/home/fuller/rpmbuild/BUILDROOT/cantera-2.5.1-1.fc35.x86_64' in installed files; aborting
```

**Steps to reproduce**

1. On a local or remote (e.g. COPR) build environment, use the spec file at https://github.com/mefuller/cantera/blob/copr/rpm/cantera-2.5.1.spec and the tarball at https://github.com/Cantera/cantera/archive/refs/tags/v2.5.1.tar.gz
2. Execute build (either local rpmbuild -ba <spec> or remote)
3. See error provided above
4. N.B. this is also consistent when the system is Enterprise Linux (minor modifications to spec file required, but end result is same)

**Behavior**

Successful builds using latest code show now error and proceed to building the RPM packages.
See https://copr.fedorainfracloud.org/coprs/fuller/Cantera/monitor/ , https://github.com/mefuller/mefuller.github.io/tree/master/software/el8

**System information**

- Cantera version: 2.5.1
- OS: Fedora 35, Rocky Linux 8
- Python/MATLAB/other software versions: Python 3.10

**Attachments**

**Additional context**

**Comment by speth** [comment]
I think the `setup_cantera` script should be irrelevant for a "system" installation of Cantera, since the Python module should be in a directory that's already on Python's search path. Likewise Cantera shouldn't depend on any libraries that aren't in system directories so setting `LD_LIBRARY_PATH` is also unnecessary.

For the Ubuntu packages, I specifically exclude the `setup_cantera` script from being installed.

**Comment by mefuller** [comment]
Thanks - I'll have to look to see how to do that in the most minimally invasive way.
I believe the package builder will balk if I allow `scons install` to install `setup_cantera` and then I ignore it when packaging, so I need to prevent the install. 
```
Do you think I can just delete 
    if os.name != 'nt':
        env['setup_cantera'] = pjoin(env['ct_bindir'], 'setup_cantera')
        env['setup_cantera_csh'] = pjoin(env['ct_bindir'], 'setup_cantera.csh')
        install_message += textwrap.dedent("""
            Setup scripts to configure the environment for Cantera are at:
              setup script (bash)         {setup_cantera!s}
              setup script (csh/tcsh)     {setup_cantera_csh!s}
            It is recommended that you run the script for your shell by typing:
              source {setup_cantera!s}
            before using Cantera, or else include its contents in your shell login script.
        """.format(**env_dict))

    print(install_message)
```

from SConstruct or is that a bit too kludgy?

EDIT: those files also aren't doing any harm, so I'm content to just leave them for 2.6.0 going forward

**Comment by speth** [comment]
That's just the post-install message. The place where they are built/installed is here:
https://github.com/Cantera/cantera/blob/6d2760b76c91b5946ba79e8163229f87a65a9985/platform/posix/SConscript#L14-L27

I assume the RPM packaging infrastructure has a way of patching the "pristine" source distribution. Using that, you can either patch `platform/posix/SConscript` to eliminate the above before building, or apply the relevant change from the main branch (29587eeba59477a1d7faaf3d45ce3daf8bbb17b9) so these files are at least not wrong. Or you can delete the file from the stage directory after running `scons install` as part of your build script.

**Comment by speth** [comment]
Also, I have no objection to cherry-picking 29587eeba59477a1d7faaf3d45ce3daf8bbb17b9 onto the `2.5` branch -- that's quick and easy. But I kind of doubt that we will do a 2.5.2 release, so I don't know if that will help your packaging efforts.

**Comment by mefuller** [comment]
I still need to learn about patching, etc.
Right now I'm battling with COPR (equivalent to Ubuntu PPA, I think) which has starting telling me it can't fid the SConstruct on a rebuild. Meanwhile local and koji  builds are fine, so I added some personal hosting
