### ISSUE TITLE
 compiling UWPFLOW from scratch

### ISSUE THREAD

**Issue by kingdiatso** [Cantera/cantera#1134]
****Hello everyone 
I used the PSAT/MATLAB toolbox to calculate the power flow of a power system and i want to use also UWPFLOW integrated in that toolbox, so i've read the guide of PSAT 
[psat-20080214.pdf](https://github.com/Cantera/cantera/files/7426678/psat-20080214.pdf)
 when i arrived to this point in page 331-332 i could'nt continue
**1**. After installing the Windows version of UWPFLOW, look for the UWPFLOW
folder and rename the uwpflow.exe (e.g. uwpflow ide.exe). Remember to
change the path in the UWPFLOW desktop icon if you have one. These
changes do not affect the Windows version of UWPFLOW, which will just
keep working fine.
**2**. Move to the UWPFLOW source folder and compile UWPFLOW from scratch.
I used make and gcc for win32 provided by CygWin.
 If you are using gcc as C compiler, remember to modify the UWPFLOW makefile, i.e. changethe first line as follows: CC = gcc. If you are using the CygWin package, the compiler will produce two files, uwpflow.exe and cygwin1.dll.3
**3**. Copy the UWPFLOW executable file(s) created at the previous step in a
Windows system folder, such as C:\Windows\system32.

can anyone help here i use **matlab r2015b** and **psat 2.1.10**

thanks in adance

**Comment by wandadars** [comment]
Are you sure this is the right place for this question? This is the repository for Cantera, a chemical kinetics software.

**Comment by bryanwweber** [comment]
Hi @kingdiatso As @wandadars mentioned, this repository is for Cantera. I think the UWPFLOW repository is over here: https://github.com/OpportunityLiu/UWPFlow Thank you!

**Comment by kingdiatso** [comment]
> 
> 
> Are you sure this is the right place for this question? This is the repository for Cantera, a chemical kinetics software.

Maybe you're right, but I found here many posts talking about the PSAT, so I thought that I could find some help here!!

**Comment by bryanwweber** [comment]
@kingdiatso The "PSAT" we refer to is more likely the saturation pressure of a fluid/vapor equilibrium mixture, unfortunately nothing to do with power systems 😄

**Comment by kingdiatso** [comment]
> 
> 
> Hi @kingdiatso As @wandadars mentioned, this repository is for Cantera. I think the UWPFLOW repository is over here: https://github.com/OpportunityLiu/UWPFlow Thank you!

Thanks or guide me to the right place
and sorry for this mistake it was my 1st post here
regards!
