### ISSUE TITLE
Attribute error during build

### ISSUE THREAD

**Issue by mefuller** [Cantera/cantera#1147]
**Problem description**

Local build on Enterprise Linux fails with `Attribute Error`

**Steps to reproduce**

1. `scons-3 build system_sundials=y f90_interface=y renamed_shared_libraries=n python_package=full system_eigen=y extra_inc_dirs=/usr/include/eigen3 system_fmt=y`
2. `scons: *** [build/ext/LICENSE.txt] AttributeError : 'dict_values' object has no attribute 'get_ninfo'
scons: building terminated because of errors.`

**Behavior**

**System information**
    Cantera version: 0805854
    OS: EL 8 x86_64
    Python/MATLAB/other software versions: Python 3.6

**Extra Information**
   Error described in #1146 not present in this local build

**Comment by bryanwweber** [comment]
Thanks @mefuller for reporting this. Can you paste the entire stack trace from SCons? Grepping for `dict_values` and `get_ninfo` doesn't return anything in the source code.

**Comment by mefuller** [comment]
Here's the build log from COPR: https://download.copr.fedorainfracloud.org/results/fuller/Cantera-EL/epel-8-x86_64/02995051-cantera/builder-live.log.gz

I can run a local build tomorrow when I'm back in the office at my EL machine - @bryanwweber can you remind me what to pass to scons to get _all_ the output (that would be useful to you)?

**Comment by bryanwweber** [comment]
Hi @mefuller The build log is just fine. This appears to be a bug in SCons itself, that's the only place I can find `get_ninfo`. The version 3.0.1 is quite old, any chance that can be updated?

**Comment by mefuller** [comment]
Thanks @bryanwweber - the old version is what's in the Enterprise Linux repos.
I'll file a bug report with Red Hat or wherever the package is maintained.

**Comment by bryanwweber** [comment]
Well, I wouldn't swear this is a bug in SCons. It's odd that it's only showing up now. Can you do a `git bisect` and track down which commit causes this?

**Comment by mefuller** [comment]
Ah, ok - I misunderstood.
I will look up what `git bisect` is and how to use it in the morning

**Comment by mefuller** [comment]
ok, I have a smoking gun from `git bisect`:

```
088b2c9cf98cc4cf3d06d926977352fed504a157 is the first bad commit
commit 088b2c9cf98cc4cf3d06d926977352fed504a157
Author: Bryan Weber <bryan.w.weber@gmail.com>
Date:   Fri Jul 16 12:35:04 2021 -0400

    [SCons] Use pathlib to write combined License file
    
    Use a dictionary to collect the license file paths and names. This data
    structure is more natural for this mapping of packages to files. It also
    simplifies the loop to collect the files.

 ext/SConscript | 44 +++++++++++++++++++++++++-------------------

```

**Comment by bryanwweber** [comment]
> Author: Bryan Weber <bryan.w.weber@gmail.com>

:cry: Thanks for tracking this down, I'll try to figure out what could be happening

**Comment by bryanwweber** [comment]
@mefuller I think I tracked this down. Can you try the commit from #1145 and see if it fixes this?

**Comment by mefuller** [comment]
@bryanwweber Works great! Successful builds and logs here: https://copr.fedorainfracloud.org/coprs/fuller/Cantera-EL/build/3030314/
