### ISSUE TITLE
scons install places some files in wrong location on latest Fedora Linux

### ISSUE THREAD

**Issue by mefuller** [Cantera/cantera#1149]
**Problem description**
Building for latest/greatest Fedora Rawhide, scripts are installed to `/usr/local/bin` not `/usr/bin` as anticipated from building with `scons build prefix=/usr libdirname=lib64 system_sundials=y f90_interface=y renamed_shared_libraries=n python_package=full system_eigen=y extra_inc_dirs=/usr/include/eigen3 system_fmt=y`
```
Installing ck2cti script to /builddir/build/BUILDROOT/cantera-2.6.0-0.1.a3.fc36.x86_64/usr/local/bin
Installing ck2yaml script to /builddir/build/BUILDROOT/cantera-2.6.0-0.1.a3.fc36.x86_64/usr/local/bin
Installing cti2yaml script to /builddir/build/BUILDROOT/cantera-2.6.0-0.1.a3.fc36.x86_64/usr/local/bin
Installing ctml2yaml script to /builddir/build/BUILDROOT/cantera-2.6.0-0.1.a3.fc36.x86_64/usr/local/bin
Installing ctml_writer script to /builddir/build/BUILDROOT/cantera-2.6.0-0.1.a3.fc36.x86_64/usr/local/bin
```
```
    File not found: /builddir/build/BUILDROOT/cantera-2.6.0-0.1.a3.fc36.x86_64/usr/bin/ck2cti
    File not found: /builddir/build/BUILDROOT/cantera-2.6.0-0.1.a3.fc36.x86_64/usr/bin/ck2yaml
    File not found: /builddir/build/BUILDROOT/cantera-2.6.0-0.1.a3.fc36.x86_64/usr/bin/cti2yaml
    File not found: /builddir/build/BUILDROOT/cantera-2.6.0-0.1.a3.fc36.x86_64/usr/bin/ctml2yaml
    File not found: /builddir/build/BUILDROOT/cantera-2.6.0-0.1.a3.fc36.x86_64/usr/bin/ctml_writer
```
see buildlog at https://download.copr.fedorainfracloud.org/results/fuller/Cantera/fedora-rawhide-x86_64/03000194-cantera/builder-live.log.gz

Files install properly for earlier versions, e.g. current Fedora 35: https://download.copr.fedorainfracloud.org/results/fuller/Cantera/fedora-35-x86_64/03000194-cantera/builder-live.log.gz

**Steps to reproduce**

1. On current Fedora Rawhide with up-to-date system, `scons build prefix=/usr libdirname=lib64 system_sundials=y f90_interface=y renamed_shared_libraries=n python_package=full system_eigen=y extra_inc_dirs=/usr/include/eigen3 system_fmt=y`
2. `scons install`
3. Observe that scripts are placed in wrong directory

**Behavior**
Based on `scons build prefix=/usr`, expect `ck2cti` and other scripts mentioned above to be placed at `/usr/bin` not at `/usr/local/bin`

**System information**

- Cantera version: d5e075ac1e687df0133dc3854b2052419a1748cf
- OS: Fedora Linux - 36/rawhide
- Python/MATLAB/other software versions: python 3.10.0-4.fc36, python3-scons 4.3.0-1.fc36
(Successful build on Fedora 35 is scons 4.2, also python 3.10)

**Comment by mefuller** [comment]
Update: there is one successful build for Rawhide on armhfp, but no other architectures: https://download.copr.fedorainfracloud.org/results/fuller/Cantera/fedora-rawhide-armhfp/03000194-cantera/builder-live.log.gz
https://copr.fedorainfracloud.org/coprs/fuller/Cantera/build/3000194/

Unclear to me as yet what the distinction is

**Comment by bryanwweber** [comment]
Without really digging in to this, the install location of these scripts is managed by Setuptools and the Python interface builder. You may also need to set `python_prefix=/usr` when calling `scons build`, can you try that and see if it resolves?

Aside from that, we could maybe have a conversation about whether these scripts should be installed in `/usr/bin`. Does Fedora distribute a Python 3 in `/usr/bin`? If not, in my opinion, these scripts should be co-located with the Python that will be running them. Especially because `/usr/bin` is usually reserved for system-level software, where `/usr/local/bin` is usually for user-installed software. I know this distinction isn't always practiced, but if Python 3 has to be installed separately, and gets installed into `/usr/local/bin` then to me it's pretty clear that's where these scripts should end up.

**Comment by speth** [comment]
If you look at the build logs that @mefuller provided, The Python 3 being used is indeed `/usr/bin/python3`, so I think that if Cantera is packaged as a `.rpm`, its executable scripts should end up in in `/usr/bin` as well.

**Comment by mefuller** [comment]
@speth yes, `/usr/bin` is the proper location for a Fedora/RHEL-compliant package (and I hope to get this packed into the standard repos after v2.6 is released)
@bryanwweber Unfortunately, the suggested `python_prefix=/usr` has no effect.
Python still places [rawhide](https://download.copr.fedorainfracloud.org/results/fuller/Cantera/fedora-rawhide-x86_64/03031184-cantera/builder-live.log.gz) scripts in `/usr/local/bin` while other releases, e.g. [F35](https://download.copr.fedorainfracloud.org/results/fuller/Cantera/fedora-35-x86_64/03031184-cantera/builder-live.log.gz) build as expected.
[Full set of builds for Fedora](https://copr.fedorainfracloud.org/coprs/fuller/Cantera/build/3031184/)

**Comment by speth** [comment]
Sorry, GitHub was a bit too aggressive with closing this based on the wording in #1145.

**Comment by jose-matos** [comment]
Some further elements from the work done to import for Fedora.
The main difference between Fedora 35 and Rawhide (that it will become Fedora 36) is that Rawhide has scons 4.3.

The architectures where it fails are those where lib name is lib64. In the 32 bit architectures where lib name is lib the script works correctly, the files are installed on /usr/bin.

**Comment by speth** [comment]
@mefuller - Can you try the patch here: https://github.com/speth/cantera/commit/25cb5388716397017d8cbcbc26cb3bbcf67b6161 (the `fedora-scriptpath` branch on my fork).

**Comment by mefuller** [comment]
> @mefuller - Can you try the patch here: [speth@25cb538](https://github.com/speth/cantera/commit/25cb5388716397017d8cbcbc26cb3bbcf67b6161) (the `fedora-scriptpath` branch on my fork).

that works - I confirmed that Rawhide/F36 now builds and installs as expected and that there is no regression for F35.
