### ISSUE TITLE
Optimized Cantera build with the LLVM-based Intel compilers do not work correctly

### ISSUE THREAD

**Issue by tpg2114** [Cantera/cantera#1150]
I know the [compilation instructions recommend against the Intel compilers](https://cantera.org/compiling/special-cases.html), but the now-called classic Intel compilers `icc` and `icpc` have worked for us over the past year. However, the new LLVM-based compilers `icx` and `icpx` in the Intel oneAPI 2021 release are causing issues for us. 

When the `optimize=y` flag is passed to scons and the `icx`, `icpx`, and `ifort` compilers are used, all of the thermodynamic routines return nonsense results:

```
>>> gas2 = cantera.Solution('gri30.cti')
>>> gas2.partial_molar_cp
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])
>>> gas2.partial_molar_entropies
array([-1.84618157e-12,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06])
```

Rebuilding with `optimize=n` gives logical results:

```
>>> gas.partial_molar_cp
array([28850.78499483, 20786.1565461 , 21900.310829  , 29388.07113248, 
       29877.9662108 , 33596.45144474, 34929.99364444, 42458.34282025, 
       20837.772867  , 29175.01279838, 35041.92327681, 33796.1755915 , 
       38476.66517763, 35760.53544168, 29143.05598224, 37217.74697861, 
       34620.17089036, 35443.46293798, 48473.38874297, 37990.95184739, 
       44154.86358601, 42047.04769266, 44134.49205447, 42846.9589907 , 
       43054.5662317 , 50667.04415886, 52719.37349824, 48539.96252103, 
       51898.37630042, 58510.53771334, 20786.15654538, 29192.46893339, 
       33869.64884343, 35699.25554991, 34695.31836395, 29858.13985786, 
       37234.10116356, 38710.67916751, 33901.48770831, 29158.80082924, 
       35925.14870757, 38337.31040521, 49223.39253868, 46913.04968495, 
       46367.88873358, 46574.66814261, 40180.03990305, 29075.48227818, 
       20786.15654538, 71585.98993627, 73950.0234428 , 55131.64313731, 
       55506.3227774 ])
>>> 
```

Building with `g++`, `gcc`, and `ifort` with `optimize=y` gives the right answers, as does `icpc`, `icc`, and `ifort`. 

We can deal with the workaround of using the GNU compilers for C and C++ or the classic Intel compilers, but I thought I'd bring it to your attention because the classic compilers will be retired and mixing the GNU compilers and Intel is messy on many of the HPC machines we use, so the workaround is not always trivial to implement.

**Comment by ischoegl** [comment]
I recently looked at these compilers (within the context of #1144) and as far as I can see, some flags will need to be adjusted. While things did compile for me also, the test suite resulted in segfaults.

**Comment by ischoegl** [comment]
@tpg2114 … could you please provide some more information about what version of Cantera you are trying to compile? There have been some recent changes in the compilation setup scripts on the `main` branch, so I want to make sure that we are on the same page. If a solution is found, it won’t be available for the current stable version. FWIW, I do have an Intel tool chain on hand, so it’s possible to investigate outside of a HPC environment.

**Comment by tpg2114** [comment]
@ischoegl The initial report was on 2.5.0, however I just built a fresh clone of the latest version and have the same issue:

```
$ git clone https://github.com/Cantera/cantera.git
...
$ scons build optimize=y prefix=<redacted> CXX=icpx CC=icx FORTRAN=ifort python_package=full matlab_toolbox=n f90_interface=y -j 40
...
scons install
PYTHONPATH=<redacted>lib/python3.7/site-packages:$PYTHONPATH python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cantera
>>> gas = cantera.Solution('gri30.cti')
>>> gas.partial_molar_cp
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])
>>> 
```

And this is done on my personal workstation as well, so the extra complications of HPC aren't here -- but we use Cantera coupled to our combustion solver on HPC and getting 0's back for cp and H were causing problems there! We ruled out all the possibilities in our code and then decided to check just Cantera through python and found it is an issue there too.

If there's other information or things I can do to help, let me know and I'll get it to you.

**Comment by tpg2114** [comment]
Looking at the compilation output, the only thing the Intel compiler reports -- pretty much everywhere -- that the GNU compilers do not report is:

```
include/cantera/ext/fmt/format.h:1733:18: warning: comparison with infinity always evaluates to false in fast floating point modes [-Wtautological-constant-compare]
      auto str = std::isinf(value) ? (fspecs.upper ? "INF" : "inf")
```

with notes explaining where it gets used.

**Comment by ischoegl** [comment]
@tpg2114 ... I can confirm that compilation with `optimize=no` does indeed work (which was somewhat surprising to me). For the non-optimized compilation, the test suite passes, which is a good sign. Once any level of optimization is specified, things go south, where I can replicate what you reported (curiously with the exact same numerical results for `gas2.partial_molar_entropies`); in this case, the test suite segfaults, which I had already noticed before this issue report. Based on what is known at the moment, I updated #1144 to include rudimentary support for `icx` (especially `ifx` needs some updated handling). 

Not sure why optimization would cause this behavior.

**Comment by tpg2114** [comment]
I think `ifx` is not recommended by Intel at the moment, they suggest continuing to use `ifort` -- at least in the 2021 release of oneAPI. I think `ifx` is based on FLANG, which is very beta. 

We've had problems with optimizations and the Intel compiler before... our combustion code couldn't run on higher than O1 from Intel 2012 until 2019 when they fixed a bug in their optimizer (it didn't detect something was changing in a loop and had pulled it out -- so it never changed during the loop like it should have). I'm not surprised, exactly, that optimization might break something unfortunately. 

I've had good luck with the Intel support team in the past when we've hit optimizer bugs, if somebody on the Cantera team has a support contract (or somebody works for/uses clusters that have a support contract).

**Comment by ischoegl** [comment]
Thanks, @tpg2114 ... interesting that optimization has created issues in the past. While figuring out what the root cause is will be difficult, I added experimental support for `icx`/`icpx` in #1144 (where I disabled optimization for the time being).

**Comment by ischoegl** [comment]
Presumably the next steps would involve [optimization report files](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/optimization-report-options/qopt-report-qopt-report.html).

**Comment by tpg2114** [comment]
@ischoegl Some good news and bad news:

I threw the kitchen sink at the debug flags and then incrementally added more optimization (through `O0`, `O1`, `O2`, and `O3`). All of them generated the correct result. The build step looked like (for `O3`):

```
scons build optimize=y optimize_flags="-O3" debug=y debug_flags="-g -traceback -fp-model strict -fstack-protector-all -fstack-security-check -ftrapv" prefix=<redacted> CXX=icpx CC=icx FORTRAN=ifort python_package=full matlab_toolbox=n f90_interface=y -j 40
```

So then I started backing off of the debug options until I found the one that made it work with `O3` -- the winner is `fp-model strict`, which disables floating point optimizations and ensures strict IEEE 754 compliance. In other words,

```
scons build optimize=y optimize_flags="-O3" debug=y debug_flags="-fp-model strict" prefix=<redacted> CXX=icpx CC=icx FORTRAN=ifort python_package=full matlab_toolbox=n f90_interface=y -j 40
```

or 

```
scons build optimize=y optimize_flags="-O3 -fp-model strict" prefix=<redacted> CXX=icpx CC=icx FORTRAN=ifort python_package=full matlab_toolbox=n f90_interface=y -j 40
```

work, while:

```
scons build optimize=y optimize_flags="-O3" debug=y debug_flags="" prefix=<redacted> CXX=icpx CC=icx FORTRAN=ifort python_package=full matlab_toolbox=n f90_interface=y -j 40
```

does not work. 

So the good news -- there is a set of optimization flags that can be turned on and the build works, provided `fp-model strict` is included in that list. The bad news is there is something with the floating point math optimizations that breaks Cantera -- this is something I have seen before in our codes and we just eat the performance penalty of not having fast math in exchange for correct and platform independent results. 

Without the `fp-model strict`, it also breaks on `O2` and `O1`, so if you really wanted to get into the weeds, you could look at what floating point optimizations happen between `O0` and `O1` and see if you could turn them on/off to identify which, specifically, break things and then maybe see which routines are impacted and try to modify the operations to work correctly.

**Comment by ischoegl** [comment]
:tada: Thanks for the detective work, @tpg2114! ... I can confirm that `-fp-model strict` works, and updated options in #1144. Co-incidentally, all the `-Wtautological-constant-compare` warnings disappeared. Most of the warnings pointed to upstream code in `{fmt}`; but as this is for *output* I'm not sure that this is the root cause here.

**Comment by tpg2114** [comment]
The messages about comparing to infinity disappeared because `fp-model strict` enforces the IEEE 754 compliance, which says that infinite operands with the same sign should compare to true. But I guess one of Intel's fast math approximations makes it always compare to false instead. Since it only warned about lines preparing a message to print, it probably isn't the issue. 

If I were to speculate wildly, I'd say there is probably an underflow that happens with the fast math but not with IEEE math, and the underflow leads to a division or multiplication by zero. I'll think about possible ways to suss that out -- it is possible to turn on/off certain floating point exceptions in the source code using `fenv` that is part of `libm` while still compiling with the fast math options. That might reveal something or a place in the code causing it. It could also be a wild goose chase -- I'm not very familiar with dealing with floating point errors in C/C++, I only found out about `fenv` a few days ago while chasing an issue with `numpy`. 

At any rate, glad it worked and there's at least a workaround! This issue can be closed if it's "fixed," or I guess left open if more digging will be done on what the problem is, exactly.

**Comment by ischoegl** [comment]
@tpg2114 … thanks for the comments! Myself, I’m probably not the right person to chase floating point exceptions down (don’t have much of a background in compiling). Your insights certainly helped to find a workaround, but I don’t think that the issue itself is fixed. For the time being, #1144 establishes experimental support.

**Comment by ischoegl** [comment]
Funny enough, I stumbled across [this post](https://community.intel.com/t5/Intel-C-Compiler/What-options-are-appropriate-to-optimize-both-speed-and-accuracy/td-p/1181890), which mentions that `icc` uses significantly different default optimization options than `gcc`. Compiling Cantera on Ubuntu 20.04 as:
```
$ scons build optimize_flags="-O3 -ffast-math -fno-cx-limited-range" -j4
```
I can reproduce almost the exact same failures as the ones reported at the top, so they do not appear to be specific to Intel compilers.

@tpg2114 ... did you try any of the other `-fp-model` options?

**Comment by tpg2114** [comment]
I have not tried others -- `fp-model strict` implies `fp-model precise,except`. The full documentation [is available here](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/floating-point-options/fp-model-fp.html#fp-model-fp) if you wanted to see other options and/or implications for a particular option.

**Comment by ischoegl** [comment]
Using `gcc`, I was able to track down the culprit as
```
$ scons build optimize_flags="-O3 -ffinite-math-only" -j4
```
which toggles "*Allow optimizations for floating-point arithmetic that assume that arguments and results are not NaNs or +-Infs.*"  There are some instances where Cantera does use NaN internally which presumably breaks the 'fast math' optimizations.

FWIW, here's the output for `gcc` with fast math ...
```
In [3]: gas2 = ct.Solution('gri30.yaml')

In [4]: gas2.partial_molar_cp
Out[4]: 
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [5]: gas2.partial_molar_entropies
Out[5]: 
array([-1.84618157e-12,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06,  5.74342730e+06,  5.74342730e+06,  5.74342730e+06,
        5.74342730e+06])
```
