### ISSUE TITLE
"a4" in cantera version conflicts with Python requirements (EL8, not F35)

### ISSUE THREAD

**Issue by mefuller** [Cantera/cantera#1164]
**Problem description**

This issue was specifically identified when building from the latest commit (see below).
(Clean) build, test, and install all occurred without issue, but I am unable to use the conversion utility as-is owing to the requirement being `Cantera==2.6.0` and the detected version is `Cantera 2.6.0a4`

**Steps to reproduce**

1. Checkout, build, test, install as normal on EL 8.5 with Python 3.6.8
2. Run `ck2yaml --help`
3. See error 
```
❯ ck2yaml --help
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (Cantera 2.6.0a4 (/usr/lib64/python3.6/site-packages), Requirement.parse('Cantera==2.6.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fuller/.local/bin/ck2yaml", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Cantera==2.6.0' distribution was not found and is required by the application
```

**Behavior**
Unable to use conversion tools owing to version mismatch.

**System information**

- Cantera version: 76e205760ecc2b4c4855847ab39c404683b5f655
- OS: Enterprise Linux 8.5
- Python/MATLAB/other software versions: Python 3.6.8

**Attachments**

**Additional context**
I'll try to track down where this is caused and patch appropriately/create a PR.
I'll also hopefully add a test to pick up this problem going forward.

**Comment by mefuller** [comment]
Changing the version in the top-level `SConstruct` from `2.6.0a4` to `2.6.0` does fix this problem, but it's not the desired solution.
I don't really know what is looking where to grab the version per the error, but `SConstruct` contains the `2.6.0` and `2.6` versions for contingencies, so it seems like editing whatever is making the Python version requirements to use the shortened version is the correct approach.
Does that sound right?

**Comment by bryanwweber** [comment]
That check is in `ck2yaml.py` and it probably just needs to be loosened there

**Comment by mefuller** [comment]
For whatever reason, I cannot find exactly what is showing up in the error - I see `2.6.0a4` in `ck2yaml`, but no version check or comparison.
This looks to me more like something with how `ck2yaml` is installed and the requirements list is generated at that time.
I have checked on my Fedora machine and there's no problem there, so this has something to do with running an older Python.

**Comment by bryanwweber** [comment]
Ah, yes, this seems like something that `setuptools`/`pip` is doing then. It seems as though EL8 and its `setuptools`/`pip` are really unfortunately too old. We're discussing dropping Python 3.6 support in Cantera 2.6 anyways, since 3.6 went EOL last month. You can install newer versions of Python on EL, right? I think I recall, you just need to add a repository or something...

**Comment by mefuller** [comment]
Of course - EL8 has Python 3.8 and 3.9 (but not 3.7) also available.
It's done not by adding a repository, but by switching modules.
I didn't realize 3.6 had just gone EOL - I've been testing that since it is the default on a fresh install (as of very recently at least).
Anyway, moving to 3.8 fixes everything - no reinstall or rebuild or anything needed, so closing this as a non-issue.

**Comment by bryanwweber** [comment]
Awesome, thanks @mefuller!
