### ISSUE TITLE
Documentation typo: wrong variable printed in equivalenceRatio.py

### ISSUE THREAD

**Issue by blackrabbit17** [Cantera/cantera#1170]
In the documentation here:
[documentation link](https://cantera.org/examples/python/thermo/equivalenceRatio.py.html)

The last line of the code is:
`
print("Z(burnt) = {:1.3f}".format(Z))
`

this should be:
`
print("Z(burnt) = {:1.3f}".format(Z_burnt))
`

**Comment by bryanwweber** [comment]
Thank you for reporting this! Feel free to create a pull request with the fix, if you'd like to.

**Comment by blackrabbit17** [comment]
OK cool, I have opened a pull request
