### ISSUE TITLE
fortran interface bug 

### ISSUE THREAD

**Issue by lucask81** [Cantera/cantera#1186]
Hi, I found a bug in the fortran interface.
The problem is that if you set the molar fraction and then the internal energy and density, the internal energy is not correctly set.
However, if the assignment of the molar fraction is avoided the internal energy is correctly set.
I tried with the python interface and the problem does not appear, so it seems to be related with the fortran interface.
I attach a short example that triggers this problem: we imposed the internal energy with the value -837.45*1000d0 at line 24 and at line 29 we get a completely different value. However if line 26 is commented then the internal energy is correctly set.

**System information**

- Cantera version: 2.6.0a4
- OS: MacOs Catalina 10.15.7 

[demo.tar.gz](https://github.com/Cantera/cantera/files/7996707/demo.tar.gz)

**Comment by bryanwweber** [comment]
Thanks for reporting this @lucask81! Since the program is relatively short, I'll copy the text of it below:

```fortran
program main
  ! use the Cantera module
  use cantera

  implicit none

  ! objects representing phases of matter have type 'phase_t'
  type(phase_t) gas
  integer nsp, nrxns
  double precision ::  u,v

  gas = importPhase('h2o2.yaml','ohmech')

  u=-837.45*1000d0
  v=1d0/(6.9371d-1)
  call setMoleFractionsByName(gas,'H2:1, O2:1, AR:2')
  
  call setState_UV(gas, u,v)
  write(*,*)'energy equi 0= ',intenergy_mass(gas)   
end program main
```

**Comment by speth** [comment]
This value of the internal energy is impossible for this composition. In Python, the following code:
```python
import cantera as ct
gas = ct.Solution('h2o2.yaml')
gas.X = 'H2:1, O2:1, AR:2'
gas.UV = -837.45*1000e0, 1e0/(6.9371e-1)
```
results in the exception:
```
*******************************************************************************
CanteraError thrown by ThermoPhase::setState_HPorUV (UV):
No convergence in 500 iterations
        Target Internal Energy  = -837450.0
        Current Specific Volume = 0.0
        Starting Temperature    = 300.0
        Current Temperature     = 2.475227660582825e-236
        Current Internal Energy = -253463.50569072584
        Current Delta T         = -4.95045532116565e-236
*******************************************************************************
```
As you can see, even at a temperature of essentially 0 K, the internal energy only goes to -253 kJ/kg, which is still much higher than your specified value of -837 kJ/kg.

The problem with the Fortran example is that you aren't checking for an error condition after the call to `setState_UV`. It indicates an error by setting a non-zero value for `gas%err` (-1 in this case). and you can get the error message using the `getCanteraError` method.

**Comment by lucask81** [comment]
Thank you @speth !  It was my mistake because I used a little different example code with python and I didn't investigate deep enough! 
I'm sorry that I thought it was a bug with the fortran interface and thank you so much for the rapid answer!!
