### ISSUE TITLE
Any compiler failure during configuration shows the message about `std::isnan`

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#1188]
**Problem description**

I had a misconfigured compiler (Conda clang, macOS, missing sysroot configuration, the specifics here aren't too important) and Cantera's configuration step was failing, with the error message about `std::isnan` not being available, introduced in #1161. However, inspecting the `config.log` showed me other errors, mostly that the linker couldn't find a few standard libraries.

The problem is that the failure was _not_ due to missing `std::isnan`, so I think the error message is too eager.

**Steps to reproduce**

I'm not sure what an easy way to reproduce this is... perhaps move one of the standard libraries out of the search path temporarily?

**System information**

- Cantera version: I'm building from a branch off main, but any commit after #1161 was merged should do.
- OS: macOS, but I don't think it's important

**Comment by ischoegl** [comment]
@bryanwweber  ... could you post the `config.log`? I don't think that there's anything wrong with the check introduced by #1161, but perhaps there's another test that should be run before, simply to ensure that the C++ environment is configured correctly, where failure would trigger a more suitable error message?

**Comment by bryanwweber** [comment]
> I don't think that there's anything wrong with the check introduced by #1161,

I agree, but the message is misleading in this case

> but perhaps there's another test that should be run before, simply to ensure that the C++ environment is configured correctly, where failure would trigger a more suitable error message?

There is a check before the `std::isnan` check that `cmath` is present, but that doesn't require linking. It seems the `std::isnan` test is the first one that requires linking, thus running into problems when linking is caught here. Perhaps the `cmath` test should be extended slightly to actually return a value and use `TryRun`, so it has to be linked?

*Edit:* I'll add the `config.log` tonight when I get a chance to regenerate it :smile:

**Comment by speth** [comment]
Changing the configuration "sanity check" to include linking makes sense to me. I think it could look more or less exactly like the `isnan` check with a different statement. You might want to mimic the `isnan` check by including an expression that can't be evaluated as a `constexpr` at compile time, such as one that depends on `argc`, so that it will actually require linking to `libm`.
