### ISSUE TITLE
Applications fail to install in `bin` on Windows

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1192]
**Problem description**

While the post-install message claims to install **applications** in
```
[...]
postInstallMessage(["finish_install"], [])

Cantera has been successfully installed.

File locations:

  applications                C:\Users\<user>\cantera\bin
  library files               C:\Users\<user>\cantera\lib
  C++ headers                 C:\Users\<user>\cantera\include
  samples                     C:\Users\<user>\cantera\samples
  data files                  C:\Users\<user>\cantera\data
  Python package (cantera)    C:\Users\<user>\miniconda3\envs\cantera-dev\Lib\site-packages
  Python samples              C:\Users\<user>\miniconda3\envs\cantera-dev\Lib\site-packages\cantera\examples
scons: done building targets.
```
nothing is installed in `cantera\bin` (the folder is actually not even created). While this may be a limitation of the OS, the post-install message is pointing at an issue.

**Steps to reproduce**

Compile & install Cantera from source.

**System information**

- Cantera version: 2.6.0a4
- OS: Windows 10
- Python/MATLAB/other software versions: Python 3.9 from miniconda (see [toolchain](https://gist.github.com/ischoegl/ab777f871a48d7f40ecc32c1c849faa3))

**Attachments**

Initial SCons output
```
scons: Reading SConscript files ...
INFO: SCons is using the following Python interpreter: C:\Users\<user>\miniconda3\envs\cantera-dev\python.exe
Compiling with MSVC 14.2
Compiling for architecture: amd64
Compiling using the following toolchain(s): ['default']
INFO: Building Cantera from git commit '63b7d27de'
Configuration variables read from 'cantera.conf' and command line:
    prefix = 'C:\\Users\\<user>\\cantera'
    boost_inc_dir = 'C:/Users/<user>/miniconda3/envs/cantera-dev/Library/include'
    verbose_tests = True
```

**Comment by bryanwweber** [comment]
I'm removing the Applications line in "add package workflow" #1158 and replacing it with the location of the converter scripts read from pip, which should be correct (one hopes...).

**Comment by ischoegl** [comment]
That should work (🤞) ... this came up in #1191 btw

**Comment by ischoegl** [comment]
fwiw, the current installation location is ` C:\Users\<user>\miniconda3\envs\cantera-dev\Scripts`

**Comment by ischoegl** [comment]
Interestingly, this doesn't affect installations where `conda` is used (the install location is correct). On the other hand, the issue persists when a user-defined `prefix` is specified. 

On further inspection, things end up in the conda folder despite specifying `prefix` as a different location ...
```
Installing ck2cti-script.py script to C:\Users\ischo\miniconda3\envs\cantera-dev\Scripts
Installing ck2cti.exe script to C:\Users\ischo\miniconda3\envs\cantera-dev\Scripts
Installing ck2yaml-script.py script to C:\Users\ischo\miniconda3\envs\cantera-dev\Scripts
Installing ck2yaml.exe script to C:\Users\ischo\miniconda3\envs\cantera-dev\Scripts
Installing cti2yaml-script.py script to C:\Users\ischo\miniconda3\envs\cantera-dev\Scripts
Installing cti2yaml.exe script to C:\Users\ischo\miniconda3\envs\cantera-dev\Scripts
Installing ctml2yaml-script.py script to C:\Users\ischo\miniconda3\envs\cantera-dev\Scripts
Installing ctml2yaml.exe script to C:\Users\ischo\miniconda3\envs\cantera-dev\Scripts
Installing ctml_writer-script.py script to C:\Users\ischo\miniconda3\envs\cantera-dev\Scripts
Installing ctml_writer.exe script to C:\Users\ischo\miniconda3\envs\cantera-dev\Scripts
```

(per post-install message, the converters are expected in `C:\Users\ischo\cantera\bin`)
