### ISSUE TITLE
Looping over a `SolutionArray` does not include `extra` items

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#1203]
**Problem description**

Accessing `extra` items from a `SolutionArray` in a loop gives an `AttributeError`.

**Steps to reproduce**

```python
import cantera as ct
import numpy as np
gas = ct.Solution("gri30.yaml")

T = np.arange(900, 1000, 50)
estimated_ignition_delay_times = np.ones_like(T) * 0.005
ignition_delays = ct.SolutionArray(gas, shape=T.shape, extra={"tau": estimated_ignition_delay_times})
ignition_delays.TP = T, 40.0 * 101325.0
for state in ignition_delays:
    print(state._extra)
```

Output:

```
OrderedDict()
...
```

**Behavior**

Looping should include the extra information.

**System information**

- Cantera version: main, https://github.com/Cantera/cantera/commit/041559d56d25945d25f5c94b160538b7e091f2a2

**Comment by bryanwweber** [comment]
Hmm, similarly, accessing a single row of the `SolutionArray` also does not include the `extra` information:

```python
>>> ignition_delays[0]._extra
Ordered_Dict()
```

**Comment by ischoegl** [comment]
@bryanwweber ... I can reproduce this. As `ignition_delays[0]` returns a `SolutionArray`, the `_extra` property should be propagated.
