### ISSUE TITLE
Changing the value of electron mobility [compiling]

### ISSUE THREAD

**Issue by AndreySchadel** [Cantera/cantera#1228]
**Problem description**
Changing the value of electron mobility in cantera/src/transport/IonGasTransport.cpp (line 388) doesn't affect the electron distribution and other ions distribution after the compilation.

**System information**

    Cantera version: 2.6.0a4
    OS: N/A
    Python/MATLAB/other software versions: N/A

**Comment by speth** [comment]
Can you provide a more complete example of what output you're looking at? What do you mean by "the electron distribution" or "other ions distribution"?

**Comment by AndreySchadel** [comment]
[Comparement.ods](https://github.com/Cantera/cantera/files/8359729/Comparement.ods)

Greetings, in this file i have used Chen et. al. mechanism and changed the value of electron mobility from 0.4 to 4 and then to 4000, and as you can see it didn't affect any value of electrons and other ionic species (in reactions with electron). The code which i used to calculate these calculations:

```python
"""
A burner-stabilized premixed ethylen-O2 flame with charged species studied by us 
"""

import cantera as ct
import numpy as np

p = ct.one_atm
tburner = 368.0
reactants = 'C2H4:0.05, O2:0.375, Ar:0.575'  # premixed gas composition
width = 0.006 # m
loglevel = 1  # amount of diagnostic output (0 to 5)
refine_grid = True  # 'True' to enable refinement

gas = ct.Solution(r'/home/cherepanov/source/mechanism/Mech_KGK_mod.yaml')
gas.TPX = tburner, p, reactants
mdot = 0.221 # kg/m^2/s

#fi 0.4

f = ct.BurnerFlame(gas, width=width)
f.burner.mdot = mdot
f.set_refine_criteria(ratio=2.0, slope=0.2, curve=0.5)
f.set_initial_guess()
#f.restore(r'/home/cherepanov/source/repos/Tester/Result_08,09,21_phi_0.4_160mbar.xml', 'Mix')
f.set_profile('H', [0.0, 0.05, 1.0], [0.0, 0.001, 0.0])
f.set_profile('OH', [0.0, 0.05, 1.0], [0.0, 0.001, 0.0])
f.set_profile('CH3', [0.0, 0.05, 1.0], [0.0, 0.001, 0.0])
f.set_profile('O', [0.0, 0.05, 1.0], [0.0, 0.0001, 0.0])
f.energy_enabled = True
f.show_solution()

f.transport_model = 'Mix'
f.solve(loglevel, refine_grid)
f.save(r'/home/cherepanov/source/repos/Tester/Result_mu_4.0_phi_0.4_2.xml', 'Mix', 'solution with Mix transport')
f.write_csv(r'/home/cherepanov/source/repos/Tester/Result_mu_4.0_mix_phi_0.4_2.txt', quiet=False)


g = ct.IonBurnerFlame(gas, width=width)
g.burner.mdot = mdot
g.set_initial_guess()
g.restore(r'/home/cherepanov/source/repos/Tester/Result_mu_4.0_phi_0.4_2.xml', 'Mix')
g.set_refine_criteria(ratio=2.0, slope=0.2, curve=0.5, prune=0.01) #(ratio=3.0, slope=0.1, curve=0.3, prune=0.01)
g.energy_enabled = True
g.electric_field_enabled = True
g.show_solution()

g.transport_model = 'Ion'
g.solve(loglevel, refine_grid)
g.save(r'/home/cherepanov/source/repos/Tester/Result_mu_4.0_phi_0.4_2.xml', 'Ion', 'solution with Ion transport')
g.write_csv(r'/home/cherepanov/source/repos/Tester/Result_mu_4.0_ion_phi_0.4_2.txt', quiet=False)
```

It is important to us to change the value of electron mobility, because we work in argon medium, and we suppose that it will improve the conformity of experiment and calculations.

**Comment by BangShiuh** [comment]
What is the species name for electron? It was E- in the csv file.

**Comment by BangShiuh** [comment]
I think the temporary solution is to change the name of electron species to "E". And I will make electron species to have any name instead of only "E".

**Comment by AndreySchadel** [comment]
Yes, it was E-, i have changed the species name, and after the test, i will tell, if this works.

**Comment by AndreySchadel** [comment]
Unfortunately, it didn't change anything. It seems, that the electron is calculated as regular ion, and it is unknown to me, how to set it as electron species. Old calculations were made in previous version of cantera(2.4.0)
[Comparement_fixedE.ods](https://github.com/Cantera/cantera/files/8376940/Comparement_fixedE.ods)

**Comment by speth** [comment]
I can't replicate the problem described. Changing the value of the electron mobility does affect the electron species profile. Perhaps of note is the fact that the changes are most dramatic when decreasing the electron mobility, rather than increasing it. Here are some results based on running the sample `ion_burner_flame.py` with different values of the electron mobility:

![electron-profile](https://github.com/Cantera/cantera/assets/644977/acc69d79-88cf-4bfd-bd44-7795f4c534e5)
