### ISSUE TITLE
1D Flame to/from pandas dataframe

### ISSUE THREAD

**Issue by ShJPatel** [Cantera/cantera#1235]
**Problem description**

The to/from pandas dataframe methods, which use the to/from solution array methods, do not work as expected

**Steps to reproduce**

I created counterflow twin premixed diffusion flame and then wrote the solution vector as a dataframe. I then created a second flame and tried to initialize it with data from the data frame and got this error
<img width="464" alt="image" src="https://user-images.githubusercontent.com/22532698/161409275-f9b662bd-d770-4854-a40e-2d2b322c5a1d.png">

**Behavior**
Screenshots below are from the "onedim.py" file in the cantera installation. Line 516 tries to pass a "restore_boundaries" argument to from_solution_array() but line 463 shows that from_solution_array() doesn't take this keyword argument

<img width="374" alt="image" src="https://user-images.githubusercontent.com/22532698/161409298-e1cc7799-840e-4195-99ed-ea787b1325e3.png">

<img width="321" alt="image" src="https://user-images.githubusercontent.com/22532698/161409355-07328436-8de5-4454-a6bd-ec35e046242e.png">

**System information**

- Cantera version: 2.5.1
- OS: Win10 
- Python

**Attachments**

**Additional context**

**Comment by bryanwweber** [comment]
Hi! Thanks for reporting this. It seems like the fix is fairly straightforward, do you want to take a crack at it? No pressure either way!

**Comment by ischoegl** [comment]
@ShJPatel and @bryanwweber ... looks like some keyword arguments from `read_hdf` were copied over. None of them apply ... will push a fix shortly.

**Comment by ischoegl** [comment]
@ShJPatel ... as there is some discussion on the purpose of this method: could you expand on what your objective is in using `from_pandas` here? The issue here is that this method doesn't really allow for a simple transfer of boundary conditions as these are not part of the `DataFrame` (at least not at the moment).

**Comment by ShJPatel** [comment]
All, Honestly, I was just testing out the functionality, but my ideal goal was to save many different flames to individual dataframes. This would allow me to easily extract and manipulate data from this library of flame data frames. Then I wanted to take one of the dataframes from my library, convert it back to a flame object, and operate on it with Cantera functions. This would have required saving boundary conditions in the dataframe.  I hope this clarifies my goals, thanks,Shivam

**Comment by ischoegl** [comment]
@ShJPatel ... thank you for your response! Personally, I would recommend the `write_hdf`/`read_hdf` route for this scenario, as it also allows you to efficiently save data to disk. HDF file I/O does conserve the entire configuration of a flame object, and was specifically implemented for this purpose (only limitation: it is only available for the Python interface, but the same is also true for pandas).

**Comment by ShJPatel** [comment]
When I realized to/from pandas wasn't working as I expected, I tried hdf and it was exactly what I was looking for. Thanks
________________________________
