### ISSUE TITLE
Reaction parsed (incorrectly?) as three-body reaction using different versions of cantera

### ISSUE THREAD

**Issue by marchdf** [Cantera/cantera#1251]
**Problem description**

Using 2 different versions of Cantera, I am getting a reaction that is parsed (incorrectly maybe?) as a three-body reaction in one version and not in another.

**Steps to reproduce**

Using the attached yaml file, with versions `<= 2.6.0a1` (including 2.5), installed with `conda install --channel cantera/label/dev cantera`:

```
In [2]: import cantera as ct

In [3]: ct.__version__
Out[8]: '2.6.0a1'

In [4]: drm = ct.Solution('mechanism.yaml')

In [5]: r17 = drm.reaction(17)

In [6]: r17
Out[6]: <ElementaryReaction: H + 2 O2 <=> HO2 + O2>
```

And this is with version `2.6.0b2`, installed via `conda install --channel cantera/label/dev cantera==2.6.0b2`:

```
In [1]: import cantera as ct

In [2]: ct.__version__
Out[2]: '2.6.0b2'

In [3]: drm = ct.Solution('mechanism.yaml')

In [4]: r17 = drm.reaction(17)

In [5]: r17
Out[5]: H + O2 + O2 <=> HO2 + O2    <ThreeBodyReaction(Arrhenius)>
```

The relevant reaction in the yaml file is:
```
- equation: H + 2 O2 <=> HO2 + O2  # Reaction 18
  rate-constant: {A: 3.0e+20, b: -1.72, Ea: 0.0}
```

**Behavior**

Reaction 17 (labelled 18 in the yaml file) is parsed as a three body reaction in 2.6.0b2 and not in previous versions. Maybe this is expected and I am missing something? I apologize in advance if that's the case.

**System information**

- Cantera version: 2.5.0, 2.6.0a1, 2.6.0b2
- OS: OSX
- Python/MATLAB/other software versions: python 3.8

**Attachments**

Attached input file: [mechanism.yaml.txt](https://github.com/Cantera/cantera/files/8557211/mechanism.yaml.txt)

**Comment by ischoegl** [comment]
Thanks for the report. This behavior is indeed expected as O2 acts as a third-body collider. Previous Cantera versions did not detect implicitly specified three-body reactions. For additional context, see #1015 and #967 (specifically https://github.com/Cantera/cantera/issues/967#issuecomment-769364265)

**Comment by marchdf** [comment]
Ok that makes sense! Thanks for the quick response.
