### ISSUE TITLE
Changes to Python test suite requires building of wheels

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1258]
**Problem description**

The new wheels-based Python package requires rebuilding of wheels for every change to the test suite.

**Steps to reproduce**

1. Open any file in `interfaces/cython/cantera/tests/test_<any>.py` and introduce a change
3. Run `scons test-python-<any>`
4. As the test suite is part of the package, the wheel needs to be rebuilt, leading to inefficient testing.

**Behavior**

**System information**

- Cantera version: 2.6.0b2
- OS: any
- Python/MATLAB/other software versions: any

**Additional context**

One potential option would be to no longer package the Python tests in the wheel ... resolution should not prevent the release of 2.6 though.

**Comment by bryanwweber** [comment]
My experience is that the wheel takes ~10 seconds to build locally, is this really a problem?

**Comment by ischoegl** [comment]
> My experience is that the wheel takes ~10 seconds to build locally, is this really a problem?

For some test cases (I typically run only parts), building the wheel takes longer than running the tests, so it is a nuisance ...

**Comment by bryanwweber** [comment]
Fair enough, it is a bit annoying since we don't install the wheel to test from either.

**Comment by speth** [comment]
Yeah, the fact that setuptools/wheel/whatever doesn't have any understanding of incremental builds does bloat this test iteration time a little, which is unfortunate. Nothing compared to making even a minimal change to the Cython code, though.

I've actually been wondering if we shouldn't move the Python test suite out of the Python module. While it's kind of interesting to be able to run it on an installed copy of Cantera, I can't think of any cases where that's been a huge help in investigating bugs, and it's not like we provide a similar capability for the C++ test suite. I think doing so would also make it easier to run parts of the Python test suite in an interactive debugger (say, through VS Code), where there wouldn't be any conflict between "the copy of the tests that are in source control and can be edited" and "the copy you can run and actually import the Python module".

**Comment by ischoegl** [comment]
> I've actually been wondering if we shouldn't move the Python test suite out of the Python module. While it's kind of interesting to be able to run it on an installed copy of Cantera, I can't think of any cases where that's been a huge help in investigating bugs, and it's not like we provide a similar capability for the C++ test suite.

👍 … I’m very much in favor of this approach (see ‘Additional Context’ at the top).

**Comment by bryanwweber** [comment]
> I've actually been wondering if we shouldn't move the Python test suite out of the Python module. While it's kind of interesting to be able to run it on an installed copy of Cantera, I can't think of any cases where that's been a huge help in investigating bugs

I think it was much more common to include the test suite in the distributed package before CI became a commonly available thing, so you could make sure the built copy worked on your machine. Nowadays, I think many projects are moving away from this bundling, so I'd be :+1: on this change as well.

**Comment by speth** [comment]
> 👍 … I’m very much in favor of this approach (see ‘Additional Context’ at the top).

Sorry, I overlooked that bit in your initial post. But also, agreed that this can wait for after the 2.6 release.

**Comment by ischoegl** [comment]
@speth and @bryanwweber … With the unavoidable merge conflicts that #1334 is introducing, it may be good to move the test suite around the same time so merge conflicts may be limited?
