### ISSUE TITLE
Lithium-ion battery example (and unit tests) missing from Python

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1259]
**Problem description**

While the `lithium_ion_battery.m` example is available in MATLAB, it is missing from Python, meaning that corresponding code portions are not covered by CI, see discussion in #1256 (specifically, the only instances where `lithium_ion_battery.cti/yaml` are used are the MATLAB example, plus a conversion test that is not designed to probe any meaningful features).

While this isn't a bug specifically, I view it as a critical omission that hopefully will get fixed prior to the release of 2.6. At the minimum, the MATLAB test should be converted to a unit test similar to `test_kinetics.py::TestSofcKinetics`.

**System information**

- Cantera version: 2.6.0b2
- OS: any
- Python/MATLAB/other software versions: any

**Comment by bryanwweber** [comment]
Can you clarify the corresponding code portions? Frankly, if it works for now, I don't see this as critical for the 2.6 release. Certainly afterwards we should prioritize this to avoid future regressions, but it doesn't seem like a blocker to me.

**Comment by ischoegl** [comment]
@bryanwweber … sure. Per @speth’s comment in #1256, the `exchangecurrentdensity` formulation is not covered at all:
```Python
surface_reaction("Li+[electrolyte] + V[NCA] + electron <=> Li[NCA]",
                 [2.62895E+10, 0.0, (61.0098120252686, 'kJ/mol')],
                 rate_coeff_type = "exchangecurrentdensity",
                 beta = 0.5,
                 id="NCA_reaction")
```
A unit test needs to hit a properly set up assembly of phases/interfaces in order to run any meaningful checks (see unit tests for SOFC in `test_kinetics.py`). The easiest would be to replicate the MATLAB structure for `lithium_ion_battery.yaml`.

**Comment by ischoegl** [comment]
To add context, turns out that there is an existing detailed [jupyter example](https://github.com/Cantera/cantera-jupyter/blob/main/electrochemistry/lithium_ion_battery.ipynb), but portions of the underlying code are not covered by CI.
