### ISSUE TITLE
[regression in 2.6.0][PYTHON] option --use-feature: invalid choice: 'in-tree-build' (choose from '2020-resolver', 'fast-deps')

### ISSUE THREAD

**Issue by yurivict** [Cantera/cantera#1269]
```
Create symlinks for: 'build/lib/libcantera_shared.so.2.6.0'
    'build/lib/libcantera_shared.so.2'->'build/lib/libcantera_shared.so.2.6.0'
    'build/lib/libcantera_shared.so'->'build/lib/libcantera_shared.so.2.6.0'
c++ -o build/python/cantera/_cantera.cpython-38.so -pthread -shared -Wl,-rpath,/usr/local/lib build/temp-py/_cantera.os -Lbuild/lib -L/usr/local/lib -lcantera -lfmt -lyaml-cpp -lomp
"/usr/local/bin/python3.8" -m pip wheel -v --no-build-isolation --use-feature=in-tree-build --no-deps --wheel-dir=build/python/dist build/python

Usage:   
  /usr/local/bin/python3.8 -m pip wheel [options] <requirement specifier> ...
  /usr/local/bin/python3.8 -m pip wheel [options] -r <requirements file> ...
  /usr/local/bin/python3.8 -m pip wheel [options] [-e] <vcs project url> ...
  /usr/local/bin/python3.8 -m pip wheel [options] [-e] <local project path> ...
  /usr/local/bin/python3.8 -m pip wheel [options] <archive url/path> ...

option --use-feature: invalid choice: 'in-tree-build' (choose from '2020-resolver', 'fast-deps')
scons: *** [build/python/dist/Cantera-2.6.0-cp38-cp38-freebsd_13_0_STABLE_amd64.whl] Error 2
scons: building terminated because of errors.
```

OS: FreeBSD 13

**Comment by speth** [comment]
I ran into this as well, while building the Ubuntu packages for releases older than the most recent one (22.04), and had to patch the `SConscript` file to remove the `--use-feature=in-tree-build` (which shows up in two places).

This flag was introduced in [pip 21.1](https://discuss.python.org/t/announcement-pip-21-1-has-now-been-released/8382). I'm not sure if the warning started with that version or a more recent one, but we added it to the Cantera build to get rid of the deprecation warning.

If we want to support older pip versions and avoid this warning, we'll need to check the `pip` version and use that to decide whether or not to include this flag.

**Comment by bryanwweber** [comment]
There's already a check of the `pip` version in `buildutils.py` so this shouldn't be too hard to make conditional

**Comment by mefuller** [comment]
It's also failing all the F34 builds: https://copr.fedorainfracloud.org/coprs/fuller/cantera-test/build/4357916/
e.g. https://download.copr.fedorainfracloud.org/results/fuller/cantera-test/fedora-34-x86_64/04357916-cantera/builder-live.log.gz

**Comment by speth** [comment]
Apparently, this feature was "opt in" for all of 6 months. The [release notes for pip 21.3](https://pip.pypa.io/en/stable/news/#v21-3) say:
> In-tree builds are now the default. --use-feature=in-tree-build is now ignored.

And using the `--use-feature=in-tree-build` on pip 22.0.3 gives the warning:
> `DEPRECATION: In-tree builds are now the default. pip 22.1 will enforce this behaviour change. A possible replacement is to remove the --use-feature=in-tree-build flag.`

So I think we should just not bother with this flag at all, since it only applies to a narrow range of pip versions, and we know that Cantera builds fine either way.
