### ISSUE TITLE
[regression in 2.6.0][MATLAB] ERROR: Path set for 'matlab_path' is not correct. Path was '/usr/local'

### ISSUE THREAD

**Issue by yurivict** [Cantera/cantera#1270]
Configure fails:
> ERROR: Path set for 'matlab_path' is not correct. Path was '/usr/local'

**Comment by speth** [comment]
Please provide more information about your system and build options, and a complete log of the scons output. This is not an actionable bug report.

**Comment by yurivict** [comment]
I use externally-installed Octave.

I had to patch out this:
```
    if not (os.path.isdir(matlab_path) and
            os.path.isdir(pjoin(matlab_path, "extern"))):
```
to proceed.

Not sure why it always expects "extern".

**Comment by bryanwweber** [comment]
@yurivict That's where MATLAB puts the headers. As we discussed elsewhere, if you want Octave support, you'll probably need to patch that in, we don't support it out of the box.

**Comment by yurivict** [comment]
Ok, thanks.
