### ISSUE TITLE
Add GH Action testing minimal GCC requirements

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1280]
**Problem description**

Per #1277, builds of Cantera 2.6.0 fail on GCC 4.8.5 (and actually require 5.4.0), despite code compliance with `c++11`. Current GH runners largely rely on `gcc` (which presumably is also widely used when compiling from source), while runners for different MSVC versions are already implemented.

While the minimal GCC version should also be ensured in `SConscript`, having a dedicated runner that probes the oldest supported GCC version would prevent future issues. (several versions of Python are already probed for similar reasons).

**Comment by speth** [comment]
One thing we can do that would be fairly straightforward would be to use the alternative GCC versions that are available for the versions of Ubuntu provided by GitHub Actions. Currently, this would let us test GCC versions 7.5.0 and 8.4.0 on Ubuntu 20.04 (in addition to 9.4.0, which is the default) and GCC versions 5.5.0 and 6.5.0 on Ubuntu 18.04 (in addition to the default of 7.4.0).

All we need to do in the runner  to use GCC 5.x, for example, is install the packages named `gcc-5` and `g++-5`, then set the SCons options `CC=gcc-5` and `CXX=g++-5`.

**Comment by ischoegl** [comment]
Linking [ubuntu 18.04 virtual environment specs](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-Readme.md). One thing I noticed is that it apparently has conda available as well, which may speed things up elsewhere.

**Comment by bryanwweber** [comment]
> One thing I noticed is that it apparently has conda available as well, which may speed things up elsewhere.

The `setup-miniconda` action already uses that Conda unless we change the options and use a different one. In any case, I don't think we should stop using the action.
