### ISSUE TITLE
segfault when using CustomRate

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#1282]
**Problem description**

Creating a reaction in Python using the base `Reaction` class and a `CustomRate` object for the rate function will segfault unless a reference to the `CustomRate` object is held elsewhere.

**Steps to reproduce**

The following will segfault:
```python
import cantera as ct
gas = ct.Solution('h2o2.yaml')
R = ct.Reaction(equation='H + OH <=> H2O', rate=ct.CustomRate(lambda T: 1.234))
gas.add_reaction(R)
print(gas.forward_rate_constants)
```

This problem can be worked around by either doing:
```python
R = ct.CustomReaction(equation='H + OH <=> H2O', rate=ct.CustomRate(lambda T: 1.234))
```
or 
```python
ratefunc = ct.CustomRate(lambda T: 1.234)
R = ct.Reaction(equation='H + OH <=> H2O', rate=ratefunc)
```
but neither of these should be required.

**Additional Context**

I ran into this in a case where I wanted to set a `CustomRate` on an existing `Reaction` object, created from an input file. The only way I could figure out how to do this was to create an elementary reaction with some dummy rate parameters, which gives an instance of the base `Reaction` class.

**System information**

- Cantera version: 2.6.0
- OS: macOS 12.2.1
- Python/MATLAB/other software versions: Python 3.10

**Comment by ischoegl** [comment]
@speth ... interesting. When `CustomReaction` was originally implemented, there wasn't a way to instantiate a `Reaction` directly, and blocking instantiation wasn't put in place in #1183.  Presumably, there may be also be unexpected behavior if you try to instantiate a `Reaction` with a `FalloffRate`-type rate object? 

Together with `ThreeBodyReaction` and `FalloffReaction`, `CustomReaction` is one of the objects listed in Cantera/enhancements#142 (where a resolution was deferred until after the release of 2.6).

**Comment by speth** [comment]
I ran into another instance of this, even when using `CustomReaction` explicitly:
```py
import cantera as ct

gas = ct.Solution('h2o2.yaml')
for i in range(5):
    R = ct.CustomReaction(equation='H + OH <=> H2O', rate=ct.CustomRate(lambda T: T))
    gas.add_reaction(R)

print(gas.forward_rate_constants)
```
I think this makes the problem more clear. There is no Python object that actually holds onto the Python `CustomReaction` and `CustomRate` objects that can keep them alive.
