### ISSUE TITLE
flame.set_initial_guess(data=df) gives error when passed a Pandas DataFrame

### ISSUE THREAD

**Issue by Nora-Khalil** [Cantera/cantera#1288]
**Problem description**

Calling  `flame.set_initial_guess(data=df)` where `df` is a `pandas.DataFrame` results in a `ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().` on the line `if not data:`

The documentation at https://cantera.org/documentation/dev/sphinx/html/cython/onedim.html#cantera.FlameBase.set_initial_guess suggest DataFrames should work.

**Steps to reproduce**

We had saved a flame using 
```
    flame.solve(loglevel=loglevel, auto=True)
    sltn = flame.to_solution_array()
    pd = sltn.to_pandas()
    pd.to_csv(f'data/test_{x}.csv')
```

then later loaded into a pandas dataframe
```
df = pd.read_csv('data/test_0.125.csv')
```
and tried to use it as the initial guess of a new flame using
```
flame.set_initial_guess(data=df)
```

**Behavior**
gives this error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_25684/2877753999.py in <module>
----> 1 flame.set_initial_guess(data=df)
      2 

~/.conda/envs/cantera_env/lib/python3.9/site-packages/cantera/onedim.py in set_initial_guess(self, locs, data, group)
    801             location. Locations are given as a fraction of the entire domain
    802         """
--> 803         super().set_initial_guess(data=data, group=group)
    804         if data:
    805             # set fixed temperature

~/.conda/envs/cantera_env/lib/python3.9/site-packages/cantera/onedim.py in set_initial_guess(self, data, group, *args, **kwargs)
    115         """
    116         super().set_initial_guess(*args, data=data, group=group, **kwargs)
--> 117         if not data:
    118             return
    119 

~/.conda/envs/cantera_env/lib/python3.9/site-packages/pandas/core/generic.py in __nonzero__(self)
   1535     @final
   1536     def __nonzero__(self):
-> 1537         raise ValueError(
   1538             f"The truth value of a {type(self).__name__} is ambiguous. "
   1539             "Use a.empty, a.bool(), a.item(), a.any() or a.all()."

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**System information**

- Cantera version: Running Cantera Version: 2.5.1
- OS: CentOS 7.9.2009
- Python: 3.8.8

**Comment by bryanwweber** [comment]
Hi! Thanks for reporting this ☺️ can you add which version of pandas you're using?

**Comment by Nora-Khalil** [comment]
`pd.__version__` is 1.3.5

**Comment by Nora-Khalil** [comment]
(this is @rwest at Nora's keyboard)
Might be a different issue, but for what it's worth
```
flame.write_hdf('data/testing.h5')
flame.set_initial_guess(data='data/testing.h5')
```
gives a `KeyError: "Unable to open object (object 'phase' doesn't exist)"`

I think what we really need here is more examples (as discussed yesterday).  In this case, examples of these interfaces to save and load things and restart flames.

**Comment by ischoegl** [comment]
@Nora-Khalil ... thanks for reporting! I verified that I get the same error on Cantera 2.6.0

While providing `pandas`  input directly to `flame.set_initial_guess(data=df)` should work according to documentation, you can use the work-around 
```Python
arr1 = ct.SolutionArray(gas)
arr1.from_pandas(df)
flame.set_initial_guess(data=arr1)
```
which works without issues.

Regarding the second HDF issue, providing a file name for restart data is currently not supported; the error message certainly could be improved. 

Overall, for recreation of data from CSV or HDF files, please refer to the [`SolutionArray` documentation](https://cantera.org/documentation/docs-2.6/sphinx/html/cython/importing.html#cantera.SolutionArray).
