### ISSUE TITLE
Unbalanced Reaction : checkReactionBalance

### ISSUE THREAD

**Issue by haspelstfs** [Cantera/cantera#1289]
Hi,

this issue it not a real bug, but an error in my specific case:

I am trying to optimize a global reaction model. It works fine for n-alkanes, but due to the definition ( I am not able to change without changing the kinetics) of pseudo species, the atom balance would yield in fractional rational number of atoms in these pseudo species. Of course in therm files/NASA Polynomials it is not possible to define e.g. number of C-Atoms as 2.5 I am running into the following error:

***********************************************************************
CanteraError thrown by checkReactionBalance:
The following reaction is unbalanced:  I1 => 2 Y
  Element    Reactants    Products
  C           20           40
  H           48           96
  O           32           64
***********************************************************************
The plausibility check in checkReactionBalance function is of course necessary, but would it be possible to create a "ignore_balance" switch for global mechanisms? From my literature knowledge so far most global models have these kind of issues, therefore it would be beneficial for the community to be able to extend cantera to global mechanisms.

I am using pyhton API of Cantera. 

Thanks in advance and for your work,

Philip

**Comment by ischoegl** [comment]
Hi @haspelstfs … could you provide a more complete (but minimal) example that results in the above behavior? (If possible, using the YAML input format.) Thank you in advance!

**Comment by haspelstfs** [comment]
Hi ischoegl,

I tried with *.yaml as well, but there directly a conversion error appears. In the minimal example I therefore used *.xml, I hope this works for you too. Anyhow both *yaml and *xml are are attached
[CTminimalExample.zip](https://github.com/Cantera/cantera/files/8785261/CTminimalExample.zip)
.
Thanks in advance! If you have any questions please contact me :)

Greets,

Philip

**Comment by ischoegl** [comment]
Hi @haspelstfs ... thanks for the examples. To document this behavior, here's the crux of the issue 
```yaml
- name: I1
  composition: {C: 5, H: 12, O: 8}
  [...]
- name: Y
  composition: {C: 2, H: 6, O: 4}
  [...]
```
and
```yaml
- equation: I1 => 2 Y  # Reaction 6
  rate-constant: {A: 4.79082e+06, b: 0.0, Ea: 1.19515e+04}
```
Cantera's current behavior makes sense, as mass is not conserved.

I was able to run your example after changing the `Y` definition to
```yaml
- name: Y
  composition: {C: 2.5, H: 6, O: 4}
  [...]
```
in the YAML format.

**Comment by haspelstfs** [comment]
Hi @ischoegl ,

Thanks for your workaround! I totally agree that Cantera works fine and the check for mass balance makes sense. I did not try your solution in advance, because I was formulating the mechanism in CHEMKIN Format, where as I said fractional rational numbers are not permitted. I assumed it is also not allowed in Cantera.
For now I think I will get along with the workaround. Thanks a lot!

Greets,
Philip
