### ISSUE TITLE
Loop through array to get properties from SolutionArray (Python interface)

### ISSUE THREAD

**Issue by lufire** [Cantera/cantera#1297]
**Problem description**

While accessing physical properties (density, viscosity, thermal_conductivity and cp) from a SolutionArray object I noticed algorithm slow-downs with increase of array size and number of accesses to the properties without any updates to the properties themselves. Looking at the source code I see that there's a property decorator preventing direct access to the already precalculated members (numpy arrays) of the SolutionArray object (named in parentheses above) and forcing the loop through all indices:

https://github.com/Cantera/cantera/blob/c040b1275c2c82ac6081de21fcb72406b8c5dd58/interfaces/cython/cantera/composite.py#L1569-L1576

I do not fully understand the logic here and assume there's a valid reason for the current implementation, but is there a way to access the property arrays directly, or if not, would it make sense to have it?

Thank you!

**System Information**

Python 3.8
Cantera 2.6.0

**Comment by bryanwweber** [comment]
HI! Thanks for reporting this. Can you include a code snippet that reproduces the slowdown you're seeing? Thanks!

**Comment by ischoegl** [comment]
Hi @lufire ... the way things are implemented, these properties are not precalculated: `SolutionArray` objects are implemented for convenient access and only store the thermodynamic state for each entry. Whenever you access properties, a single `Solution` object is used to extract those for each data point. The reason this is slower than expected is that the loop is written in regular Python, whereas actual calculations use C++ (or cythonized Python).

That said, the cost of operation should scale linearly with the `SolutionArray` size, although I have not tested this myself.

**Comment by lufire** [comment]
Hi @bryanwweber, hi @ischoegl,

thanks for your quick reply. As far as I can see right now are the internal property arrays of SolutionArray updated after applying a new state (e.g. temperature, pressure) as you can see in the image at the end. Here would be a short test script:

```python
import cantera as ct
import time
import numpy as np

nx = 100

temperature_init = 293.15
pressure = 101325
x_H2O = 0.2
x_O2 = 0.21 * (1.0 - x_H2O)
x_N2 = 0.79 * (1.0 - x_H2O)
composition = {'O2': x_O2, 'N2': x_N2, 'H2O': x_H2O}


# Initialize
solution = ct.Solution('gri30.yaml')
solution.X = composition
solution.TP = temperature_init, pressure
solution_array = ct.SolutionArray(solution, nx)
temperature = np.linspace(temperature_init, temperature_init + 10.0, nx)

# Loop
n_iter = 1000
start_time_ct = time.time()
for i in range(n_iter):
    temperature += 1.0
    solution_array.TP = temperature, pressure
    # density = solution_array.density
    # viscosity = solution_array.viscosity
    # thermal_conductivity = solution_array.thermal_conductivity
    # specific_heat = solution_array.cp
end_time_ct = time.time()
print('timing: ', end_time_ct - start_time_ct)
```

Uncommenting the four lines within the loop yields a slowdown of more than factor 2 on my machine. However using the faster version (i.e. commented properties) and inspecting the `solution_array` object attributes in debug mode after the loop yields correct densities at the highest temperatures as you can see in the screenshot:
![cantera_solutionarray_properties](https://user-images.githubusercontent.com/28864951/171001814-898957bb-a79e-471b-b706-4e5c2154df56.png)

**Comment by ischoegl** [comment]
@lufire ... I believe the behavior you're describing is due to Python overhead when you assign the variables as well as some strategies used by Cantera internally. The `solution_array.TP` setter calls into the C++ core, but many of the property evaluations use 'lazy' execution, i.e. they are not run unless they are actually used. The property inspection used in your debugger presumably forces an evaluation, which would explain that you still get the expected results.

**Comment by lufire** [comment]
@ischoegl 

Ok thank you! 
So it is then mainly the access for each array index within Python causing the overhead, not the variable assignment since I noticed the slowdown when comparing it to my own simple ndarray based property evaluations, where the pure Python variable assignment was similar. 
Now comparing the SolutionArray to a direct Python loop just using a Solution object, the latter is almost twice as fast:

```Python
import cantera as ct
import time
import numpy as np

nx = 100
temperature_init = 293.15
pressure = 101325
x_H2O = 0.2
x_O2 = 0.21 * (1.0 - x_H2O)
x_N2 = 0.79 * (1.0 - x_H2O)
composition = {'O2': x_O2, 'N2': x_N2, 'H2O': x_H2O}

# Initialize
solution = ct.Solution('gri30.yaml')
solution.X = composition
solution.TP = temperature_init, pressure
solution_array = ct.SolutionArray(solution, nx)
temperature = np.linspace(temperature_init, temperature_init + 10.0, nx)

# Loop
n_iter = 1000
start_time_ct = time.time()
for i in range(n_iter):
    temperature += 1.0
    solution_array.TP = temperature, pressure
    density = solution_array.density
    viscosity = solution_array.viscosity
    thermal_conductivity = solution_array.thermal_conductivity
    specific_heat = solution_array.cp
end_time_ct = time.time()
print('SolutionArray class timing: ', end_time_ct - start_time_ct)

start_time_ct = time.time()
for i in range(n_iter):
    temperature += 1.0
    density = np.zeros(nx)
    viscosity = np.zeros(nx)
    thermal_conductivity = np.zeros(nx)
    specific_heat = np.zeros(nx)
    for j in range(nx):
        solution.TP = temperature[j], pressure
        density[j] = solution.density
        viscosity[j] = solution.viscosity
        thermal_conductivity[j] = solution.thermal_conductivity
        specific_heat[j] = solution.cp
end_time_ct = time.time()
print('Solution class timing: ', end_time_ct - start_time_ct)
```
Output:
```
SolutionArray class timing:  2.491018295288086
Solution class timing:  1.3162927627563477
```

So I conclude as you hinted that the SolutionArray class is mainly for convenience and not for efficiency. I thought about using it for numerical calculations in combination with the FiPy-Library (https://www.ctcms.nist.gov/fipy/), which might be suitable for now, until I find a more efficient solution.

Thank you!
