### ISSUE TITLE
Confusion on meaning of "volume" for Surface / Edge phases

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#1312]
**Problem description**

For `Surface` phases, the definition of molar volume and how it should (or shouldn't be) used in certain calculations needs to be resolved. Currently, the `molarVolume` method for the surface phase returns the inverse of the site density, that is, a quantity in kmol/m^2 (which is not documented). This molar volume is then used in the calculation of the value returned by `density()` which then gives a value in kg/m^2. However, this mass density is not particular meaningful as it depends on how the surface species are defined, for example whether the substrate species is included in the composition of a surface "site" or not.

This definition of the molar volume is tricky, because it cannot then be used in the identity _h = u + P*v<sub>m</sub>_. The implementation of `intEnergy_mole` for the phase currently returns `enthalpy_mole()` to get around this. This would be consistent with the idea that the molar volume should just be zero (and that the density would be infinity).

```python
>>> import cantera as ct
>>> s = ct.Solution('test/data/surface-phases.yaml', 'Pt-surf')

>>> s.site_density
2.7063000000000002e-08

>>> 1/s.volume_mole
2.7063000000000005e-08

>>> s.density
5.3337681873e-06

>>> s.site_density * s.mean_molecular_weight
5.3337681873e-06
```

Also, there seems to be some inconsistency with whether the phase is compressible and what therefore the equation of state is:

```python
>>> s.is_compressible
True

>>> s.TD = None, s.density * 1.5
>>> s.density
8.00065228095e-06

>>> s.site_density * s.mean_molecular_weight
5.3337681873e-06  # no longer corresponds to density (site density has not changed)
```

**System information**

- Cantera version: 2.6.0 or `main` at 1ab81ace5

**Additional context**

This behavior was identified as part of https://github.com/Cantera/cantera/pull/1299, which implements https://github.com/Cantera/enhancements/issues/114.

**Comment by bryanwweber** [comment]
> The implementation of intEnergy_mole for the phase currently returns enthalpy_mole() to get around this. This would be consistent with the idea that the molar volume should just be zero (and that the density would be infinity).

I think this is consistent with the phase being incompressible, not necessarily that the volume is zero. Writing the relationship as h2-h1 = u2 - u1 + v(P2-P1), you can neglect the second term if that product is much smaller than the change of internal energy due to temperature change. This is perhaps a somewhat restrictive assumption, but I don't think it necessarily means density goes to infinity. 

This is not to say that the method is correct as is, just that there's a physically relevant case for it 😊

**Comment by speth** [comment]
> you can neglect the second term if that product is much smaller than the change of internal energy due to temperature change

I think that's a big "if" to build into this (or any) phase definition, and not one that's necessary. Why shouldn't these methods return consistent results if you consider a change in state that changes P but not T?

For an incompressible phase with finite density, I don't think it can be true that both enthalpy and internal energy are functions of temperature alone. That's a pretty special property of the ideal gas. For a substance with constant density, the entropy is a function of T only. Then, from the first law, du = T ds - P dv, you have that u = u(T only) since dv = 0. So dh = du + v dP then requires that h = h(T, P).

**Comment by bryanwweber** [comment]
> I think that's a big \"if\" to build into this (or any) phase definition,

It doesn't seem like that big an _if_ for a surface... I don't think pressure is well defined for a surface/solid, but that could be wrong. Certainly the pressure of the fluid above the surface is well-defined, but within the solid? Which pressure would affect the thermodynamic properties of the surface? Also, the dimensions don't make sense here, you need another length if the "volume" is defined in mol/m**2

In another direction, it'd be interesting to compare orders of magnitude of the change of u and h between two T/P pairs, with v*(P2-P1). I wonder if the second term is comparable, and if so, under what conditions.

**Comment by decaluwe** [comment]
I think more to the point is that it’s a pretty common assumption made for incompressible phases. You’re right that it leads to internally inconsistent results like Cp = Cv, h = u ≠ u + Pv. But it is a pretty standard “undergrad thermo text” approach. FWIW. 

I have more thoughts than I do time, right now, but stepping back, what even is the enthalpy of a surface phase? Is there a mechanism for energy storage when pressure increase? I’m somewhat skeptical.

**Comment by speth** [comment]
> Certainly the pressure of the fluid above the surface is well-defined, but within the solid? Which pressure would affect the thermodynamic properties of the surface? 

What's the problem with defining the pressure in the solid? If you assume a flat surface, the pressure on each side of the interface has to be the same to satisfy mechanical equilibrium.

> Also, the dimensions don't make sense here, you need another length if the "volume" is defined in mol/m**2

Yes, that's precisely my point. I think one way to resolve this is to decide that the the surface is infinitesimally thin, and therefore that its volume is zero, at which point you end up with h = u.

> stepping back, what even is the enthalpy of a surface phase? Is there a mechanism for energy storage when pressure increase? I’m somewhat skeptical.

Well, I think we need a definition for the enthalpy, at least for individual species, as this is how we calculate the chemical potentials and therefore reverse rate constants.

**Comment by bryanwweber** [comment]
> the pressure on each side of the interface has to be the same to satisfy mechanical equilibrium.

But that's the pressure of the fluid on the surface, not the pressure inside the solid, at least in my interpretation. I suppose if the surface is infinitesimally thin, then the pressure "in" the surface is the same as the fluid? But then we end up with h = u, as you say, so the point is moot.

**Comment by decaluwe** [comment]
Been thinking on this, and I think we are in agreement. The surface is a 2D phase, and as such the volume is either undefined or zero. 

Agreed that we need an enthalpy definition, but was more just pondering if u = h by definition for a surface.

**Comment by ischoegl** [comment]
I also agree that a suitable definition is needed. But I don’t think that the concept of volume applies to surfaces … area should take the place of volume, meaning that pressure needs to be replaced by something more suitable?

**Comment by decaluwe** [comment]
A thought experiment: if you measure Cp and Cv for a surface species, via an experiment that takes the names literally, would the two be any different? I suspect not, but need to have a chat with a friendly whiteboard to know for sure.

**Comment by ischoegl** [comment]
I think that the concept of Cv breaks down also, as this is no longer 3D? It is probably now a property for constant area? (Fixed geometry)

*PS: regarding thought experiments … I think a soap bubble for fixed P may be an interesting analogy. Deformation involves work which may yield a concept for what would lead to 2D enthalpy?*
