### ISSUE TITLE
ArrheniusRate lost nice repr

### ISSUE THREAD

**Issue by cdeil** [Cantera/cantera#1329]
The Cantera tutorial shows this nice example:

```
>>> g = ct.Solution('gri30.yaml')
>>> r = g.reaction(2) # get a Reaction object
>>> r
<ElementaryReaction: H2 + O <=> H + OH>

>>> r.reactants
{'H2': 1.0, 'O': 1.0}
>>> r.products
{'H': 1.0, 'OH': 1.0}
>>> r.rate
Arrhenius(A=38.7, b=2.7, E=2.61918e+07)
```

However for me with Cantera 2.6.0 I get this:
```
>>> r.rate
<ArrheniusRate at 17aa79230>
```

Was this on purpose or is this a regression that the nice `repr` for `ArrheniusRate` is gone?

**Comment by ischoegl** [comment]
This is not a regression, but an effect of a revised way of handling reaction rates (all objects have been replaced). The information you are looking for can be accessed by the property `input_data`; the `repr` string is simple for Arrhenius, but non-trivial for other parameterizations.

**Comment by cdeil** [comment]
@ischoegl - well, from a new user standpoint it could be considered a regression?
Is there a reason not to add back a nice repr (e.g. too long outputs for common cases) or could / should it be done?

If `rate.input_data` is the way to see the parameters now, it would be good to teach that directly in the tutorial:
https://cantera.org/tutorials/python-tutorial.html

Being able to see the parameters is pretty basic functionality.

**Comment by bryanwweber** [comment]
> If `rate.input_data` is the way to see the parameters now, it would be good to teach that directly in the tutorial:
> https://cantera.org/tutorials/python-tutorial.html

Yep, definitely agree! This is just a case where we missed an update after this change :smile: The website and the tutorial live over here: https://github.com/cantera/cantera-website, if you don't mind making an issue over there to update this. Thanks!

I'll let @ischoegl address whether or not this is something we can support.

**Comment by ischoegl** [comment]
I agree that we overlooked the tutorial, which will be a simple fix. I am somewhat hesitant to update the repr, as other parameterizations are difficult to summarize in a succinct expression (e.g. falloff or chebychev)

**Comment by cdeil** [comment]
Moved to https://github.com/Cantera/cantera-website/issues/212
