### ISSUE TITLE
Url of objects.inv  for intersphinx mapping

### ISSUE THREAD

**Issue by erwanp** [Cantera/cantera#1347]
I cannot find the url of sphinx's generated `objects.inv` to be used in intersphinx_mapping to reference Cantera from other package documentations.

`https://www.cantera.org/documentation/docs-2.6/sphinx/html/` does not work. 

Which url should I use?

**Comment by bryanwweber** [comment]
I think you need one folder higher, did you try `https://www.cantera.org/documentation/docs-2.6/sphinx` ?

**Comment by erwanp** [comment]
I still get
```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://www.cantera.org/documentation/docs-2.6/sphinx/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://www.cantera.org/documentation/docs-2.6/sphinx/objects.inv
```

**Comment by bryanwweber** [comment]
Thanks for following up, I'll have to log in to the web server and check out what's happening. Might be a few days till I can get to it!

**Comment by ischoegl** [comment]
@bryanwweber … were you ever able to track this one down?

**Comment by bryanwweber** [comment]
No I never checked the web server 😞

**Comment by speth** [comment]
Oops! Looks like this is an error on my part. I excluded the `objects.inv` file from the [repo](https://github.com/Cantera/api-docs) that contains the built docs for all previous releases because I didn't know what it was for. I'll see if I can regenerate it and upload for 2.6, at least, and fix the process for future versions.

**Comment by erwanp** [comment]
Thanks

**Comment by erwanp** [comment]
Thanks it worked, I can retrieve it through `https://www.cantera.org/documentation/docs-2.6/sphinx/html/objects.inv`
