### ISSUE TITLE
Python `dist-info` tag is `a1` when building, not `a2`

### ISSUE THREAD

**Issue by mefuller** [Cantera/cantera#1355]
Package builds are failing as the current build is creating `%{_libdir/python3.11/site-packages/Cantera-3.0.0a1.dist-info}` and not `%{_libdir/python3.11/site-packages/Cantera-3.0.0a2.dist-info}`

I don't know where this should be set and trying to search the source code isn't turning up anything

Build log: https://download.copr.fedorainfracloud.org/results/fuller/cantera-test/fedora-rawhide-x86_64/04708187-cantera/builder-live.log.gz

Relevant excerpt:
```
"/usr/bin/python3" -m pip install --prefix=/usr --ignore-installed --root=/builddir/build/BUILDROOT/cantera-3.0.0-a2.fc37.x86_64 --no-build-isolation --no-deps -v --force-reinstall build/python
Using pip 22.2 from /usr/lib/python3.11/site-packages/pip (python 3.11)
Processing ./build/python
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-to8jr4qh/Cantera.egg-info
  writing /tmp/pip-modern-metadata-to8jr4qh/Cantera.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-to8jr4qh/Cantera.egg-info/dependency_links.txt
  writing entry points to /tmp/pip-modern-metadata-to8jr4qh/Cantera.egg-info/entry_points.txt
  writing requirements to /tmp/pip-modern-metadata-to8jr4qh/Cantera.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-to8jr4qh/Cantera.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-to8jr4qh/Cantera.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-to8jr4qh/Cantera.egg-info/SOURCES.txt'
  adding license file 'LICENSE.txt'
  writing manifest file '/tmp/pip-modern-metadata-to8jr4qh/Cantera.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-to8jr4qh/Cantera-3.0.0a1.dist-info'
  adding license file "LICENSE.txt" (matched pattern "LICENSE.txt")
  Preparing metadata (pyproject.toml): finished with status 'done'
```

**Comment by speth** [comment]
This doesn't look like a problem with Cantera to me. Rather, it looks like your build is using an archive of the Cantera repo from a point where the version was `3.0.0a1`. Note the following excerpt from early on in the SCons output:
```
INFO: Generating build/src/config.h.build with the following settings:
    CANTERA_SHORT_VERSION               "3.0"
    CANTERA_VERSION                     "3.0.0a1"
```
I don't quite understand how this build process is getting the contents of the cantera repository -- it downloads a file `https://copr-dist-git.fedorainfracloud.org/repo/pkgs/fuller/cantera-test/cantera/main.tar.gz/md5/0de3b764be1d9be809ca97afec76d715/main.tar.gz`, but I don't know where that comes from.

**Comment by mefuller** [comment]
let me check what's going on here
