### ISSUE TITLE
man page missing for `yaml2ck`

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1361]
**Problem description**

While `ck2yaml`, `cti2yaml` and `ctml2yaml` have man pages, it is missing for `yaml2ck` (new in Cantera 3.0; introduced with #1286).

**Steps to reproduce**

```
$ man yaml2ck
No manual entry for yaml2ck
```

**System information**

- Cantera version: 3.0.0a2
- OS: any
- Python/MATLAB/other software versions: N/A

**Comment by bryanwweber** [comment]
Does anyone use these? `yaml2ck --help` seems like it'd work and is already done?

**Comment by ischoegl** [comment]
> Does anyone use these? `yaml2ck --help` seems like it'd work and is already done?

Agreed. But in this case we probably should remove the other ones for consistency?

**Comment by mefuller** [comment]
I volunteer to write the missing man page this coming weekend.

And I would say yes, many Linux users instinctively type "man x" as a first resort.
There's a reason for "RTFM"

**Comment by bryanwweber** [comment]
> I volunteer to write the missing man page this coming weekend.

Thanks @mefuller!

> Linux users instinctively type "man x" as a first resort

Guess I'm not a true believer, as Google is my first resort 😝
