### ISSUE TITLE
Error LNK2019 & Error LNK1120

### ISSUE THREAD

**Issue by Isaac-Ji** [Cantera/cantera#1373]
**Problem description**

I installed Cantera through the official method, see the website: https://www.cantera.org/install/compiling-install.html#sec-compiling. Then I tested it with vs2022 and had some problems.

**Steps to reproduce**

1. Follow the steps on the official website to install Cantera. Website is: https://www.cantera.org/install/compiling-install.html#sec-compiling.
2. After compiling, install Cantera to the specified folder with command "scons install".
3. Create project in Visual Studio Professional 2022.
4. Set the include and library directories of Cantera for the project.
5. Reproducing the case of Cantera official website. see https://www.cantera.org/tutorials/cxx-guide/simple-example.html.
6. Build Solution.
7. An error has occurred.

**System information**

- Cantera version: [2.6.0]
- OS: [Windows 10]
- Visual Studio Professional 2022
- SCons 4.4.0
- Boost 1.80.0
- Submodules are downloaded automatically

**Attachments**

My Code:
#include "cantera/base/Solution.h"
#include "cantera/thermo.h"
#include <iostream>

using namespace Cantera;

int main()
{
	auto sol = newSolution("G:\\CAS\\DEMO\\DEMO1\\cantera\\data\\h2o2.yaml", "ohmech", "None"); //The location where the exception occurred
	return 0;
}

Error Information:

Build started...
1>------ Build started: Project: Project1, Configuration: Debug x64 ------
1>main.obj : error LNK2019: unresolved external symbol "class std::shared_ptr<class Cantera::Solution> __cdecl Cantera::newSolution(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class std::shared_ptr<class Cantera::Solution>,class std::allocator<class std::shared_ptr<class Cantera::Solution> > > const &)" (?newSolution@Cantera@@YA?AV?$shared_ptr@VSolution@Cantera@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@00AEBV?$vector@V?$shared_ptr@VSolution@Cantera@@@std@@V?$allocator@V?$shared_ptr@VSolution@Cantera@@@std@@@2@@3@@Z) referenced in function main
1>G:\c++\exp\exp13\Project1\x64\Debug\Project1.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "Project1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Additional context**
I ran some other tests, and here are the results:
1.Using const variables in Cantera: passed;
2.Using default constructor of class to create instance: passed;
3.Calling functions which argument's type is std::string: failed.

One Successful Case:
Code:
#include "cantera/base/Solution.h"
#include "cantera/thermo.h"
#include <iostream>

using namespace Cantera;

int main()
{
	cout << OneAtm << endl;
	return 0;
}

Build Information:
Build started...
1>------ Build started: Project: Project1, Configuration: Debug x64 ------
1>main.cpp
1>G:\Tools\cantera\include\cantera\ext\fmt\core.h(327,35): warning C4566: character represented by universal-character-name '\u00B5' cannot be represented in the current code page (936)
1>Project1.vcxproj -> G:\c++\exp\exp13\Project1\x64\Debug\Project1.exe
1>Done building project "Project1.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by speth** [comment]
Can you post your project file? Are you specifying the need to link to the Cantera library (not just the library directory)?

**Comment by Isaac-Ji** [comment]
> Can you post your project file? Are you specifying the need to link to the Cantera library (not just the library directory)?

I have checked VS settings again and I found I forgot to add the lib file. Now the problem has been solved. Thank you for your kindly reply.
