### ISSUE TITLE
Successful Build Cantera Arm64 Android Termux

### ISSUE THREAD

**Issue by defencedog** [Cantera/cantera#1388]
Previously there has been an [issue](https://github.com/Cantera/cantera/issues/1386#issuecomment-1242847535)  related to `pthread_cancel` Android NDK simply doesn't implement this function. 

Because I have `python3.9` with `pip` so it was more neat to have `cantera` python source but `pip install cantera` will not work!

This was solved as below by downloading tarball from pypi
Dependencies
```
pkg i boost-headers boost eigen fmt libgtest libsundials
pip install scons ruamel.yaml wheels
wget https://files.pythonhosted.org/packages/4a/fd/321bbaace30e4230b8fdd0f214c5ad26930298f2839a43022741f49233c6/Cantera-2.6.0.tar.gz
```
After extracting
```
cd Cantera-2.6.0
cd ext/libexecstream/posix
nano exec-stream-helpers.cpp
```
Patches, explained [here](https://www.reddit.com/r/termux/comments/xbae09/comment/inzp5nd/?utm_source=share&utm_medium=web2x&context=3) . Thanks to Termux devs
Only x1 instance of `pthread_cancel` exists at following line, change it from
This `if( int code=pthread_cancel( m_thread ) ) {`
To `if( int code=pthread_kill( m_thread,0 ) ) {`

Now navigate to root & start compiling (logging via `tee` is optional)
`export BOOST_INCLUDE=/data/data/com.termux/files/usr/include/ && pip install . -v 2>&1 | tee cantera.log`

Success
```
Python 3.9.13 (main, Jul  5 2022, 04:09:08)                                                                      
[Clang 12.0.9 (https://android.googlesource.com/toolchain/llvm-project c935d99d on linux                         
Type "help", "copyright", "credits" or "license" for more information.                                           
>>> import cantera as ct                                                                                         
>>> ct.__version__                                                                                               
'2.6.0'
```
[Link](https://github.com/defencedog/miscBuildLogs/raw/main/Termux/cantera.log)  to log file... This was my 3rd try of build!

**Comment by bryanwweber** [comment]
Great, thanks for updating this! As @speth said, this will no longer be an issue with the `main` branch because we've dropped the dependency on `libexecstream`.
