### ISSUE TITLE
f77-demo test fails for OpenBLAS / MKL

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1393]
**Problem description**

The `f77-demo` test fails for optimized LAPACK libraries. See referenced GH runner output below (which uses Intel MKL for the OneAPI toolset). Similar behavior can be observed for OpenBLAS.

**Steps to reproduce**

1. Enable optimized LAPACK libraries (Intel MKL or OpenBLAS).
2. Run `scons test-f77-demo`

**Behavior**

See OneAPI runner - [GH Actions output](https://github.com/Cantera/cantera/actions/runs/3033761690/jobs/4882196311)

**System information**

- Cantera version: latest `main`
- OS: all(?)
- Python/MATLAB/other software versions: N/A

**Comment by speth** [comment]
In case GitHub eventually decides to delete these logs, the relevant part of the output that's failing the diff comparison is:
```
 2 O + M <=> O2 + M            0.42989E-01   0.42989E-01   0.83267E-16 kmol/m3/s
 H + O + M <=> OH + M          0.17491E+00   0.17491E+00   0.36082E-15 kmol/m3/s
-H2 + O <=> H + OH             0.50168E+04   0.50168E+04   0.15461E-10 kmol/m3/s
+H2 + O <=> H + OH             0.50168E+04   0.50168E+04  -0.45475E-11 kmol/m3/s
 HO2 + O <=> O2 + OH           0.70916E+00   0.70916E+00   0.51070E-14 kmol/m3/s
 H2O2 + O <=> HO2 + OH         0.10086E+00   0.10086E+00   0.45797E-15 kmol/m3/s
 H + O2 + M <=> HO2 + M        0.43569E+00   0.43569E+00  -0.22760E-14 kmol/m3/s
 H + O2 + O2 <=> HO2 + O2      0.19108E-01   0.19108E-01  -0.10061E-15 kmol/m3/s
-H + O2 + H2O <=> HO2 + H2O    0.42676E+01   0.42676E+01  -0.22204E-13 kmol/m3/s
+H + O2 + H2O <=> HO2 + H2O    0.42676E+01   0.42676E+01  -0.71054E-14 kmol/m3/s
 H + O2 + N2 <=> HO2 + N2      0.00000E+00   0.00000E+00   0.00000E+00 kmol/m3/s
 H + O2 + AR <=> HO2 + AR      0.00000E+00   0.00000E+00   0.00000E+00 kmol/m3/s
-H + O2 <=> O + OH             0.74625E+03   0.74625E+03   0.90949E-12 kmol/m3/s
+H + O2 <=> O + OH             0.74625E+03   0.74625E+03  -0.45475E-12 kmol/m3/s
 2 H + M <=> H2 + M            0.73983E-01   0.73983E-01   0.00000E+00 kmol/m3/s
 2 H + H2 <=> H2 + H2          0.81791E-01   0.81791E-01   0.13878E-16 kmol/m3/s
 2 H + H2O <=> H2 + H2O        0.84795E+00   0.84795E+00   0.00000E+00 kmol/m3/s
```

The three columns are the forward, reverse, and net rates of progress for a mixture that has been set to an equilibrium state. The last column should therefore be zero, and it basically is, within a double precision roundoff level based on the forward / reverse rates. The two that show up as failing are just those where the forward / reverse rates are the largest, and it's exceeding the relatively simple tolerances that are used for these regression tests.

I'm not sure why we aren't seeing a similar problem with the `cxx_demo` test, which generates a similar output, though for slightly different initial conditions.

**Comment by ischoegl** [comment]
It is indeed a trivial error, but I’m not familiar with that part of the test suite.
