### ISSUE TITLE
Attributeerror A-Factor cannot be changed

### ISSUE THREAD

**Issue by NUSCondy** [Cantera/cantera#1407]
**Problem description**
Hi I am trying to change A-Factor in the mechanism but failed with the following info:
**AttributeError: attribute 'pre_exponential_factor' of 'cantera._cantera.Arrhenius' objects is not writable**
The command I use is as hown following:
**gas = ct.Solution(fname, phase='gas', thermo_warnings=False)
reaction=gas.reaction(937) # Falloff reaction
reaction.high_rate.pre_exponential_factor*=2**
Do you know How could I change it? or is there some way to change it?
**System information**

- Cantera version: 2.6.0
- OS:  Windows 10
- Python

**Comment by ischoegl** [comment]
@NUSCondy … updating reaction rate parameters directly is not implemented at the moment (see #1211). If you want to update things, you need to use `modify_reaction` - see [Cantera documentation](https://cantera.org/documentation/docs-2.6/sphinx/html/cython/kinetics.html#cantera.Kinetics.modify_reaction). If you have any additional questions, please post on the user group.
