### ISSUE TITLE
yaml2ck converting format error with third body reaction

### ISSUE THREAD

**Issue by knkwon1** [Cantera/cantera#1415]
Please bear with my poor English.

Recently, I used new feature yaml2ck to convert Cantera mechanism to Chemkin.
yaml2ck is working fine, but error occurred when I use converted mechanism file with Chemkin.
As shown in below, reactions that have notified third body make error with efficiency.
If I remove error line, it works fine with Chemkin.
Probably, it related with output format from yaml2ck.

I know it is not released feature,
But I hope it will be helpful before releasing it.

### Some lines from converted mechanism file ###

H2O + M <=> H + OH + M       6.100000000000001e+27 -3.322 120790.0
H2/3.000E+00/ H2O/0.000E+00/ N2/2.000E+00/ O2/1.500E+00/
H2O + H2O <=> H + OH + H2O   1.0060000000000001e+26 -2.44 120180.0
H2O/1.000E+00/          ### <-- this line makes an error ###

### some lines from chemkin validation error ###
  11. H2O+M<=>H+OH+M                                 6.10E+27   -3.3   120790.0
      H2              Enhanced by    3.000E+00
      H2O             Enhanced by    0.000E+00
      N2              Enhanced by    2.000E+00
      O2              Enhanced by    1.500E+00
  12. H2O+H2O<=>H+OH+H2O                             1.01E+26   -2.4   120180.0
      Error...3rd-body requires (+M) in reaction...H2O/1.000E+00/
      H2O             Enhanced by    1.000E+00

**System information**

- Cantera version: main : commit 7d86e2611224879d1666deb1a24de859b5175061
- OS: Windows 10
- Python 3.9
- Chemkin 2022 R2

**Comment by ischoegl** [comment]
@knkwon1 ... thank you for reporting this issue.
