### ISSUE TITLE
pkg-config does not work on conda

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1422]
**Problem description**

An attempt to compile the [very simple C++ program](https://cantera.org/tutorials/cxx-guide/simple-example.html) using the [`pkg-config` route](https://cantera.org/tutorials/cxx-guide/compiling.html#pkg-config) fails.

**Steps to reproduce**

1. Saved  [very simple C++ program](https://cantera.org/tutorials/cxx-guide/simple-example.html) as `simple.cpp`
2. Run the following

```
% export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib
% export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib/pkgconfig
% g++ simple.cpp -o myProgram $(pkg-config --cflags --libs cantera)
% ./myProgram
dyld[92219]: Library not loaded: @rpath/libsundials_cvodes.6.dylib
  Referenced from: <E62AB15F-607D-3047-996E-A59885DCC71C> /Volumes/Data/work/GitHub/cantera/myProgram
  Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/libsundials_cvodes.6.dylib' (no such file), '/usr/local/lib/libsundials_cvodes.6.dylib' (no such file), '/usr/lib/libsundials_cvodes.6.dylib' (no such file, not in dyld cache)
zsh: abort      ./myProgram
```

**System information**

- Cantera version: 3.0.0a3
- OS: macOS
- Python/MATLAB/other software versions: conda environment

**Attachments**

`cantera.pc` has the following content:
```
prefix=/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev
exec_prefix=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

Name: Cantera
Description: Cantera library
URL: https://cantera.org
Version: 3.0.0a3

Libs: -L${libdir} -L/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib -L/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib/python3.10/config-3.10-darwin -L/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib -lcantera -lsundials_cvodes -lsundials_ida -lsundials_nvecserial -lsundials_sunlinsollapackdense -lsundials_sunlinsollapackband -lfmt -lyaml-cpp -lpython3.10 -ldl
Cflags: -std=c++14 -framework Accelerate -I${includedir} -I/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/include -I
```

**Additional context**

Issue arose in the context of #1385

**Comment by ischoegl** [comment]
With shared libraries introduced in Cantera 3.0.0a4, the library can now be linked with `cantera_shared`, which causes a somewhat different error:

```
% g++ simple.cpp -o myProgram $(pkg-config --cflags --libs cantera_shared)
Package cantera_shared was not found in the pkg-config search path.
Perhaps you should add the directory containing `cantera_shared.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cantera_shared' found
simple.cpp:1:10: fatal error: 'cantera/base/Solution.h' file not found
#include "cantera/base/Solution.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

A fix requires renaming `cantera.pc` to `cantera_shared.pc`, and using shared libraries rather than static libraries.

**Comment by speth** [comment]
Given the improvements to handling the shared library, and the fact that using it is required for features like `ExtensibleRate`, I'm thinking we should just have `pkg-config --libs cantera` return flags suitable for linking to the shared library.

**Comment by speth** [comment]
After some recent updates, `pkg-config` *mostly* works. That is, the command:
```
g++ kinetics1.cpp -o kinetics1 $(pkg-config --cflags --libs cantera)
```
produces an executable with no warnings. Two minor issues remain.

1. Running the program requires providing information about the library path, either at run time:
```
LD_LIBRARY_PATH=$CONDA_PREFIX/lib ./kinetics1
```
or by recompiling with the RPATH embedded:
```
g++ kinetics1.cpp -o kinetics1 $(pkg-config --cflags --libs cantera) -Wl,-rpath,$CONDA_PREFIX/lib
```
This second solution can be baked into the `cantera.pc` file, of course.

Second, a path that only existed on the system where the package was built ends up in the `cantera.pc` file as an "include directory, e.g. `-isystem /usr/share/miniconda3/conda-bld/cantera-recipe_1687996688861/_build_env/include`. It would be nice to get rid of this, but it doesn't actually hurt anything.
