### ISSUE TITLE
Liquid water transport data via Matlab interface

### ISSUE THREAD

**Issue by Naikless** [Cantera/cantera#1425]
**Problem description**

Transport data for liquid water can be obtained using the Python interface (after [this related issue](https://github.com/Cantera/cantera/issues/289) was solved), but not via Matlab.

**Steps to reproduce**

While this works

```python
import cantera as ct

w = ct.Water()

w.viscosity
```

the equivalent commands in Matlab fail:

```matlab
w = Water()

viscosity(w)

Error using ctmethods

***********************************************************************
NotImplementedError thrown by Transport::viscosity:
Not implemented.
***********************************************************************
```

Is this just an oversight or are there technical reasons for this?

**System information**

- Cantera version: 2.5.1
- OS: CentOS7
- Python 3.10, Matlab R2019a

**Comment by speth** [comment]
No, there's no technical reason for this. You can instantiate a `Solution` object with access to water transport properties by creating a YAML file (say, `water_tran.yaml`) with these contents:
```yaml
phases:
- name: water
  thermo: pure-fluid
  species: [{liquidvapor.yaml/species: [H2O]}]
  state:
    T: 300.0
    P: 1.01325e+05
  pure-fluid-name: water
  transport: water
```
and instantiating it in Matlab as:
```matlab
w = Solution('water_tran.yaml')
```

Besides making this available via the convenience `Water()` method, it should also be possible to specify the transport model with the third argument to the `Solution` constructor, e.g.
```matlab
w = Solution('liquidvapor.yaml', 'water', 'water')
```
However, this is incorrectly blocked by some very outdated logic in `Solution.m` that only recognizes a few transport model names:
```matlab
if nargin == 3
    if (strcmp(trans, 'default') || strcmp(trans, 'None')...
        || strcmp(trans, 'Mix') || strcmp(trans, 'Multi'))
        tr = Transport(t, trans, 0);
    else
        error('Unknown transport modeling specified.')
    end
else
    tr = Transport(t, 'default', 0);
end

```

**Comment by Naikless** [comment]
Thanks a lot, the first solution works!

Just for the record, regarding the second one: For Cantera >= 2.6, just removing the if else logic from `Solution.m` makes it work as well. However, for Cantera 2.5.1, it still complains that `Not implemented for transport model 'None'.` when fed to `viscosity`, which I assume indicates that the explicitly set transport model doesn't make it to the C++ part.

**Comment by speth** [comment]
Please do not close the issue -- there is a problem that needs to be fixed here.
