### ISSUE TITLE
Error in kinetics test with _GLIBCXX_ASSERTIONS

### ISSUE THREAD

**Issue by musicinmybrain** [Cantera/cantera#1430]
**Problem description**

Compiling with `_GLIBCXX_ASSERTIONS` enabled appears to reveal an out-of-bounds read in the tests.

**Steps to reproduce**

1. `scons build cc_flags='-Wp,-D_GLIBCXX_ASSERTIONS' cxx_flags='-Wp,-D_GLIBCXX_ASSERTIONS -std=c++14' -j16`
2. `scons test -j16`

**Behavior**

```
[ RUN      ] Reaction.FalloffFromYaml2
/usr/include/c++/12/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::oper
ator[](size_type) [with _Tp = double; _Alloc = std::allocator<double>; reference = double&; size_type = long u
nsigned int]: Assertion '__n < this->size()' failed.
FAILED: Test 'kinetics' exited with code -6
```

Compare to

```
scons build -j16
scons test -j16
```

which succeeds.

**System information**

- Cantera version: c0ae563def4ba5a91e995194e2ec9d30a1413671
- OS: Fedora Linux 37 (x86_64)
- Python/MATLAB/other software versions: Python 3.11.1

**Attachments**

**Additional context**

**Comment by musicinmybrain** [comment]
FYI @mefuller

**Comment by mefuller** [comment]
Thanks @musicinmybrain
