### ISSUE TITLE
Question. Trying to implement NH3-SCR mechanism through the Cantera...

### ISSUE THREAD

**Issue by sleepy-yang** [Cantera/cantera#1431]
Hello. I am trying to implement NH3-SCR mechanism through the Cantera. 

Q1. I made a yaml file as follows, but it doesn't show the variation of species concentration.

![1](https://user-images.githubusercontent.com/123715436/215016245-c4de6ae7-1da4-40f7-9146-95669902fb57.png)

I have searched many Cantera's examples and their yaml files, but I could not find a reaction in which three species are used as reactants of reaction.
Can I use 3 species as reactants? If it is possible, please let me know how should it be used?
Additionally, I’d like to ask if there is someone who have a yaml file or an example file for solving NH3-SCR kinetics. It will be very helpful for my research. 

Q2. I have an another question. I’d like to make a “data of NH3(s)” in my YAML file. NH3(s) is the ammonia molecule adsorbed on a catalyst active site. Where can I obtain the data of enthalpy, entropy, and specific heat for “NH3(s)”?

![2](https://user-images.githubusercontent.com/123715436/215016277-14cb9cf3-946e-42b1-8259-270b27e84d38.png)

Q3. In the Cantera's surf_pfr example, the active site of the catalyst is only pt(s).
But in my problem, there are three active sites such as Cu+1, Cu+2, and Bronsted acid site. Is it possible to solve this problem with Cantera? I would very appreciate if you let me know how to approach this problem cleverly.

![3](https://user-images.githubusercontent.com/123715436/215016309-d003eea5-204a-43e6-9d4f-f04fa2d8646a.png)

Thanks in advance for your reply,
best regard. YH

**Comment by bryanwweber** [comment]
Good morning, as you've asked this same question on Google Groups, which is the appropriate place, I'll be closing this issue. Thanks for your understanding!
