### ISSUE TITLE
The Script for cti2yaml.py

### ISSUE THREAD

**Issue by AbdulHaseebawan12** [Cantera/cantera#1432]
I have been looking for this script 'cti2yaml.py' but its not available any where and how am I suppose to convert my file? 

https://cantera.org/tutorials/legacy2yaml.html 

This is the tutorial but no such file exist any where?

**Comment by bryanwweber** [comment]
Hi! Thank you for opening this issue. Unfortunately, it is hard to help without more details. Specifically, what version of Cantera did you install, how did you install it, on what operating system, and what is the exact error you received for the commands you tried?

**Comment by ischoegl** [comment]
@AbdulHaseebawan12 … we’re more than happy to help, but this appears to be better suited for a question on Cantera’s user group, see https://github.com/Cantera/cantera#users-group. As this shouldn’t be a problem with the code base, I am closing this issue.
