### ISSUE TITLE
gas->equivalentRatio("CH4:1", "O2:2") function returns "inf"

### ISSUE THREAD

**Issue by band-a-prend** [Cantera/cantera#1439]
**Problem description**

The [equivalenceRatio.py](https://github.com/Cantera/cantera/blob/main/samples/python/thermo/equivalenceRatio.py) example states about `equivalence_ratio`:
```
# This function can be used to compute the equivalence ratio for any mixture.
# The first two arguments specify the compositions of the fuel and oxidizer.
# An optional third argument "basis" indicates if fuel and oxidizer compositions
# are provided in terms of mass or mole fractions. Default is mole fractions.
# Note that for all functions shown here, the compositions are normalized
# internally so the species fractions do not have to sum to unity
```
and therefore user could expect to calculate fuel equivalence ratio before setup the mixture composition.
E.g. it could be useful to know fuel equivalence ratio of certain mixture and then to use it to setup the same value 
for other mixtures or blended fuels.

**Steps to reproduce**

1. Simple reproducer is to create file `test.py` (Python is for simplification, actually the same will be for C++ code):
```
import cantera as ct
gas = ct.Solution('gri30.yaml')
phi = gas.equivalence_ratio("CH4:1", "O2:2", 'mole')
print(f"phi = {phi:1.3f}")
```
3. Run 'python3 test.py'
4. See output `phi = inf`

**Behavior**

The output is `inf` while expected the `1.000` for presented `"CH4:1", "O2:2"` composition.

The `gas.equivalence_ratio()` call is expected to return inf because the fuel isn't specify while `gas.equivalence_ratio("CH4:1", "O2:2", 'mole')` call provides required info to calculate fuel equivalence ratio. It seems that `"CH4:1", "O2:2", 'mole'` actually aren't used.
Is it correct behaviour and mentioned function could be used only after gas composition initilisation?

**System information**

- Cantera version: 2.6.0 or 924bdf3
- OS: Windows 7, Gentoo Linux
- Python: 3.8 and 3.10

**Attachments**

**Additional context**

**Comment by band-a-prend** [comment]
I.e. It seemes that specified composition isn't taken into account in `gas.equivalence_ratio("CH4:1", "O2:2", 'mole')` (and `gas->equivalenceRatio("CH4:1", "O2:2", 'mole')`) call and it just calculates `gas.equivalence_ratio()` for uninitialized gas mixture composition.

**Comment by band-a-prend** [comment]
Another test:
```python
import cantera as ct

gas = ct.Solution('gri30.yaml')

phi_t1 = gas.equivalence_ratio("CH4:1", "O2:0.21,N2:0.79", 'mole') # expect phi = 2.0
print(f"phi = {phi_t1:1.3f}") # return phi = inf : ERROR

gas.set_equivalence_ratio(1.0, "CH4:1", "O2:0.21,N2:0.79") # set phi = 1.0
phi_t2 = gas.equivalence_ratio() # expect phi= 1.0
print(f"phi = {phi_t2:1.3f}") # return phi = 1.0 : OK

phi_t3 = gas.equivalence_ratio("CH4:1.0", "O2:0.21,N2:0.79") # expect phi = 2.0
print(f"phi = {phi_t3:1.3f}") # return phi = 1.0 : ERROR

phi_t4 = gas.equivalence_ratio("CH4:0.25", "O2:0.21,N2:0.79", 'mole') # expect phi = 0.5
print(f"phi = {phi_t4:1.3f}") # return phi = 1.0 : ERROR
```
Actual output:
```
phi = inf
phi = 1.000
phi = 1.000
phi = 1.000
```

**Comment by speth** [comment]
This seems to be a misunderstanding of what the arguments to `equivalence_ratio` mean. The [docstring](https://cantera.org/documentation/dev/sphinx/html/cython/thermo.html#cantera.ThermoPhase.equivalence_ratio) for `equivalence_ratio` starts off with:
>  Get the equivalence ratio $\phi$ of the current mixture, which is a conserved quantity.

which I think is fairly clear. This behavior is also consistent with basically every other accessor method of the `Solution` class in returning properties corresponding to the current state.

The purpose of the `fuel` and `oxidizer` arguments is for use in cases like when the reference fuel species contains oxygen, or the oxidizer contains some carbon or hydrogen, as in the example given in the docstring:
```py
>>> gas.set_equivalence_ratio(0.5, fuel='CH3:0.5, CH3OH:.5, N2:0.125', oxidizer='O2:0.21, N2:0.79, NO:0.01')
>>> gas.equivalence_ratio(fuel='CH3:0.5, CH3OH:.5, N2:0.125', oxidizer='O2:0.21, N2:0.79, NO:0.01')
0.5
```
And there is quite a bit more explanation in the `equivalenceRatio.py` example. 

Of course, if there are any additions to either the example or the docstrings that you think would help avoid this confusion, a pull request would be welcome.

**Comment by ischoegl** [comment]
I agree with that assessment. While renaming to `get_equivalence_ratio` may avoid future confusions (it is not an accessor for an internally stored quantity), I do not believe that there is anything wrong with the implementation itself.

**Comment by band-a-prend** [comment]
@speth 
thank you for reference to docstring. This clarifies and explains the actual behaviour of this function.

@ischoegl
I was misleading by description from  equivalenceRatio.py example where is stated 
> This function can be used to compute the equivalence ratio for any mixture.

It returns value based on current mixture composion of gas object. And didn't specify new composition just to calculation value.

So maybe there is no need of renaming function with get prefix. But update of example is required to provide similar explanation like in docstring where fuel has oxygen containing species.
