### ISSUE TITLE
Quantity.set_equivalence_ratio and other special setters not working

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#1446]
**Problem description**

Several "special" setters for `Solution` objects do not work on `Quantity` objects. While they appear to pass through the call to the parent `Solution` correctly, they don't update the state of the `Quantity` object afterwards. This affects at least `set_equivalence_ratio`, `set_unnormalized_mass_fractions` and `set_unnormalized_mole_fractions`. While the latter two are not that likely to be needed with `Quantity`, the first one is fairly important.

**Steps to reproduce**

```py
>>> import cantera as ct
>>> gas = ct.Solution('gri30.yaml')
>>> q = ct.Quantity(gas)
>>> q.set_equivalence_ratio(0.8, 'CH4:1.0', 'O2:1.0, N2:3.76')
>>> q.equivalence_ratio()
inf
>>> q.mole_fraction_dict()
{'H2': 1.0}
>>> q.set_unnormalized_mass_fractions([1]*53)
>>> q.Y
array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])
>>> q.set_unnormalized_mole_fractions([1]*53)
>>> q.X
Out[11]: 
array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])
```

**System information**

- Cantera version: 2.6.0 or `main` at c54e42947
- Python/MATLAB/other software versions: Python 3.11, though I presume this affects all versions

**Additional context**

Identified while trying to provide suggestions for [this question](https://groups.google.com/g/cantera-users/c/jMflYyFuwD8) on the Cantera Users' Group.

**Comment by ischoegl** [comment]
Confirmed on Python 3.10.5
