### ISSUE TITLE
Regression for overconstrained equilibrium on Intel CI

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1473]
**Problem description**

There's a new failure for CI runs on [Intel oneAPI](https://github.com/Cantera/cantera/actions/runs/4629308970/jobs/8189412237?pr=1411)

```
*********************************** Testing Summary ************************************
FAILED: One or more tests failed.

Tests passed: 5218
Up-to-date tests skipped: 0
scons: *** [test_results] Explicit exit, status 1
Tests failed: 1

Failed tests:
    - python: test_equilibrium.ChemEquilTest.test_equil_overconstrained2

****************************************************************************************
```

The relevant error stack is:

```
__________________ ChemEquilTest.test_equil_overconstrained2 ___________________

self = <python.test_equilibrium.ChemEquilTest testMethod=test_equil_overconstrained2>

    def test_equil_overconstrained2(self):
        gas = ct.Solution("equilibrium.yaml", "overconstrained-2")
        gas.TPX = 301, 100000, 'CH4:1.0, O2:1.0'
>       gas.equilibrate('TP', self.solver)

test/python/test_equilibrium.py:70: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   self.thermo.equilibrate(stringify(XY.upper()), stringify(solver), rtol,
E   cantera._utils.CanteraError: 
E   *******************************************************************************
E   CanteraError thrown by solve(DenseMatrix& A, double* b):
E   DGETRF returned INFO = 2. U(i,i) is exactly zero. The factorization has been completed, but the factor U is exactly singular, and division by zero will occur if it is used to solve a system of equations.
E   *******************************************************************************

build/python/cantera/thermo.pyx:438: CanteraError`
```

**Steps to reproduce**

Occurs on any recent CI run where the intel toolchain is successfully downloaded.

**Behavior**

**System information**

- Cantera version: current `main`
- OS: ubuntu / GH Action `linux-intel-oneapi`
- Python/MATLAB/other software versions: Python 3.8

**Comment by speth** [comment]
Before the build logs get automatically purged:
- The last run on the `main` branch with no errors for this builder:
  - https://github.com/Cantera/cantera/actions/runs/4585553964/jobs/8097766942
  - [logs_3986.zip](https://github.com/Cantera/cantera/files/11185995/logs_3986.zip)
- The first run on the `main` branch where this error occurred:
  - https://github.com/Cantera/cantera/actions/runs/4621007008/jobs/8171895078
  - [logs_4029.zip](https://github.com/Cantera/cantera/files/11185997/logs_4029.zip)

One observation is that this does correspond to a change in the version of most of the Intel tools/libraries from 2023.0.0 to 2023.1.0.
