### ISSUE TITLE
Convert .cti to .inp/.H/.cpp

### ISSUE THREAD

**Issue by bazharz** [Cantera/cantera#1475]
Hello everyone,
I am attempting to convert a particular mechanism from cantera .cti format to .inp, .H, and .cpp formats so that I can utilize it with a new solver. I have searched for a solution and discovered that there is a file called cti2ck.py that can accomplish this, but unfortunately, I am unable to locate it to run it with the mechanism.cti file. 
Does anyone here know where I can obtain this file or download it? I have only been able to find ck2cti.py in the cantera repository.
Thank you in advance for your help.

**Comment by ischoegl** [comment]
Hi @bazharz ... closing, as this is a question for [Cantera's Users' Group](https://groups.google.com/group/cantera-users).

**Comment by leskin** [comment]
Hi, @bazharz.  I found this GitHub repository that may be of help.


https://github.com/jiweiqi/cantera_cti2ck￼
jiweiqi/cantera_cti2ck: Convert Cantera Solution to Chemkin/CTI input file
github.com

//Leo

____________________________________________
Leo D. Eskin, Ph.D.
President/CEO
Cogent Science, LLC
13401 Chestnut Oak Drive
Darnestown, MD  20878
Phone:   +1 703 929-5500
FAX:     +1 240 206-3273
SkypeIN: +1 301 358-5201
Skype:   leskin1
***@***.*** ***@***.***>
www.cogentscience.net

 <http://www.cogentscience.net/>The information contained in this communication may be confidential,
is intended only for the use of the recipient named above, and may be legally privileged.
If the reader of this message is not the intended recipient, you are hereby notified that
any dissemination, distribution, or copying of this communication, or any of its contents,
is strictly prohibited.  If you have received this communication in error, please
re-send this communication to the sender and delete the original message and any
copy of it from your computer system.  Thank you.

**Comment by ischoegl** [comment]
@leskin … the link you posted looks like something that originates with @kyleniemeyer’s group (without attribution, as far as I can tell). Starting with Cantera 3.0, the officially supported route is `cti2yaml` (which converts the deprecated CTI format to YAML), followed by `yaml2ck`. I would rather have provided this information in the User’s Group, as information will be easier to find there.

**Comment by leskin** [comment]
Thanks for the insight. I just spotted the post and did a quick search to try to help answer the question.  I will respond/redirect to the user’s group in the future.  My apologies.

//Leo
____________________________________________
Leo D. Eskin, Ph.D.
President/CEO
Cogent Science, LLC
13401 Chestnut Oak Drive
Darnestown, MD  20878
Phone:   +1 703 929-5500
FAX:     +1 240 206-3273
SkypeIN: +1 301 358-5201
Skype:   leskin1
***@***.*** ***@***.***>
www.cogentscience.net

 <http://www.cogentscience.net/>The information contained in this communication may be confidential,
is intended only for the use of the recipient named above, and may be legally privileged.
If the reader of this message is not the intended recipient, you are hereby notified that
any dissemination, distribution, or copying of this communication, or any of its contents,
is strictly prohibited.  If you have received this communication in error, please
re-send this communication to the sender and delete the original message and any
copy of it from your computer system.  Thank you.

**Comment by ischoegl** [comment]
No worries.
