### ISSUE TITLE
Broken links in Cantera Documentation

### ISSUE THREAD

**Issue by alicharchi** [Cantera/cantera#1476]
**Problem description**
Several Broken links in this page:
[](https://cantera.org/documentation/docs-2.6/sphinx/html/yaml/species.html?highlight=shomat#sec-yaml-shomate)

**Steps to reproduce**
For example clicking "described here" link in "Shomate polynomials" section opens a 404 error page.

**Comment by decaluwe** [comment]
Thanks, @alicharchi -- could you provide a link to the page you are talking about, please?

**Comment by alicharchi** [comment]
Hi Steven,
Sorry, Looks like I messed up the markdown code for links.
I found a couple in this page:
https://cantera.org/documentation/docs-2.6/sphinx/html/yaml/species.html

For example,
the "described here" in the following sections are broken:
- NASA 7-coefficient polynomial
- NASA 9-coefficient polynomial
- Shomat polynomials
- Constant heat capacity

Best,
Ali

**Comment by bryanwweber** [comment]
I think this is a duplicate of https://github.com/Cantera/cantera/issues/1528
