### ISSUE TITLE
CustomReaction - NoneType error

### ISSUE THREAD

**Issue by FelixBiermann** [Cantera/cantera#1485]
**Problem description**
Using Python 3.8 and Cantera 2.6.0b2 

I implemented a custom reaction according to the example script "custom_reactions.py" (Error also reproducible with this script).
When checking whether the reactions are all set with "gas.reactions()" I get an "AttributeError: NoneType object has no attribute type" error. The reason seems to be the custom reaction as, "gas.reaction(idx)" works fine for other reactions but throws the same error when "idx" is the custom reaction.

CustomReactions seem to lack of a "type" property.
**Steps to reproduce**

1. Use Canteras latest dev version (2.6.0b2) with python (here 3.8)
2. Start the example script "custom_reactions.py" in debug mode
3.  Set break point after initializing the gas object with custom reactions (here: "gas1")
4. In Ipython console: "gas1.reactions()"

This will reproduce the error. One can also just set up an costum reaction and add it to the kinetics of a gas object and call "gas.reactions()".

**Behavior**

**System information**

- Cantera version: 2.6.0b2
- OS: Ubuntu 20.04
- Python: 3,8

**Attachments**

**Additional context**

**Comment by speth** [comment]
Hi, 2.6.0b2 is not the latest development version of Cantera. Do you observe this error with the main branch, checked out from GitHub (which should report the version as being 3.0.0a5).

While I realize that it is the latest version available from the [`cantera-unstable`](https://launchpad.net/~cantera-team/+archive/ubuntu/cantera-unstable) PPA channel, you should also add the stable [`Cantera`](https://launchpad.net/~cantera-team/+archive/ubuntu/cantera) PPA channel, which would give you the final 2.6.0 release version.

**Comment by FelixBiermann** [comment]
Hi, 

Seems like I have missed the final 2.6 release. (Some dependence issues didn't let me install it. Other now resolved story) I did the switch, but this error remains. For the unstable version 3.0.0a5 this bug seems to be solved. 

I will close this issue!

Thank you
