### ISSUE TITLE
Quantity addition in Python is incorrect when molar basis is used.

### ISSUE THREAD

**Issue by peterscherpelz** [Cantera/cantera#1493]
**Problem description**

Quantity addition in Python is incorrect when molar basis is used.

**Steps to reproduce**

Create two quantities and set their basis to `'molar'` before adding them. See script below.

**Behavior**

Enthalpy is not conserved even when both Quantities are set to `constant='HP'`. The resulting Quantity is different than if basis is kept as mass.

**System information**

- Cantera version: 2.6.0
- OS: Ubuntu 20.04
- Python 3.8:

**Attachments**

```
import cantera as ct

gas = ct.Solution('gri30.yaml')

# Stream A (air)
A = ct.Quantity(gas, constant='HP')
A.TPX = 300.0, ct.one_atm, 'O2:0.21, N2:0.78, AR:0.01'
A.moles = 1
# Stream B (methane)
B = ct.Quantity(gas, constant='HP')
B.TPX = 1200.0, ct.one_atm, 'CH4:1'
B.moles = 0.42

A.basis = 'molar'
B.basis = 'molar'

print(A.enthalpy + B.enthalpy)
# Gives -8521222

# Compute the mixed state
M = A + B
print(M.enthalpy)
# Gives -5408171
```
In contrast, when not setting to molar basis, everything works fine:
```
import cantera as ct

gas = ct.Solution('gri30.yaml')

# Stream A (air)
A = ct.Quantity(gas, constant='HP')
A.TPX = 300.0, ct.one_atm, 'O2:0.21, N2:0.78, AR:0.01'
A.moles = 1
# Stream B (methane)
B = ct.Quantity(gas, constant='HP')
B.TPX = 1200.0, ct.one_atm, 'CH4:1'
B.moles = 0.42

print(A.enthalpy + B.enthalpy)
# Gives -8521222

# Compute the mixed state
M = A + B
print(M.enthalpy)
# Gives -8521222
```

**Comment by peterscherpelz** [comment]
While I stumbled across this while using cantera, if my analysis is correct, the problem is fairly straightforward. See https://github.com/Cantera/cantera/blob/main/interfaces/cython/cantera/composite.py#L314 . Note that quantities are fetched from the underlying phase without checking that a mass basis is used - but they're always multiplied by the mass, even though the basis may have been set to molar.

**Comment by memachine1** [comment]
Thanks @speth for the fix!

**Comment by peterscherpelz** [comment]
Thanks @speth for the fix!
