### ISSUE TITLE
Compilation problem (related to Sundials) introduced by commit #98eb6dadd 

### ISSUE THREAD

**Issue by santoshshanbhogue** [Cantera/cantera#1512]
**Problem description**

I was updating to the latest commit (d717e8b) but I got the following error message. I traced it to the changes introduced as part of commit 98eb6dadd. Everything works fine (i am able to succesfully compile) one commit upstream of this, i.e e39d1e85b

I did the cursory updates too:
`git submodule sync`
`git submodule update`

to get the correct version of the libraries in the `ext` folder

**Steps to reproduce**
`scons build`

**Behavior**

This is the error that I get:

`scons: Reading SConscript files ...
SCons 4.1.0.post1 is using the following Python interpreter:
    /Users/santosh1/opt/anaconda3/envs/py39/bin/python (Python 3.9)
INFO: Compiling on 'Apple M1 Pro'
INFO: Building Cantera from git commit '98eb6dadd'
INFO: Configuration variables read from 'cantera.conf' and command line:
    prefix = '/Users/santosh1/packages/ct_dev_version'
    python_package = 'full'
    matlab_toolbox = 'n'
    matlab_path = '/Applications/MATLAB_R2021a.app/'
    f90_interface = 'n'
    system_eigen = 'n'
    system_fmt = 'n'
    system_sundials = 'n'
    boost_inc_dir = '/usr/local/include/boost/'

INFO: Adding conda include and library paths: /Users/santosh1/opt/anaconda3/envs/py39
Checking for C++ header file cmath... yes
INFO: Using private installation of fmt library.
INFO: Found fmt version 6.2.1
Checking for YAML::Node().Mark()... no
INFO: Using private installation of yaml-cpp library.
Checking for C++ header file gtest/gtest.h... no
Checking for C++ header file gmock/gmock.h... no
INFO: Using Googletest from Git submodule
INFO: Using private installation of Eigen.
INFO: Found Eigen version 
Checking whether __GLIBCXX__ is declared... no
Checking whether _LIBCPP_VERSION is declared... yes
Checking whether __clang__ is declared... yes
INFO: Not checking for OpenMP support due to using XCode compiler.
INFO: Found Boost version 1.76
Checking whether boost::core::demangle is declared... yes
Checking for CVodeCreate(CV_BDF, CV_NEWTON) in C++ library sundials_cvodes... no
Checking for CVodeCreate(CV_BDF) in C++ library sundials_cvodes... no
Checking for SUNContext ctx; SUNContext_Create(0, &ctx) in C++ library sundials_cvodes... no
Checking for double x; log(x) in C library None... yes
INFO: Using private installation of Sundials version 5.3.
Checking for C library hdf5... no
INFO: Using NumPy version 1.24.3
INFO: Using Cython version 0.29.33 (uses legacy NumPy API)
INFO: Building the full Python package for Python 3.9
INFO: MACOSX_DEPLOYMENT_TARGET = 10.15
target.dir:/Users/santosh1/packages/canteraSource/build/lib
target.dir:/Users/santosh1/packages/canteraSource/build/lib
target.dir:/Users/santosh1/packages/canteraSource/build/lib
target.dir:/Users/santosh1/packages/canteraSource/build/lib
INFO: Skipping sample 'openmp_ignition' because 'omp.h' was not found.
scons: done reading SConscript files.
scons: Building targets ...

g++ -o build/src/numerics/FuncEval.os -c -isystem include/cantera/ext -isystem /Users/santosh1/opt/anaconda3/envs/py39/include -isystem /usr/local/include/boost -std=c++17 -O3 -Wno-inline -g -Wall -include src/pch/system.h -fPIC -DNDEBUG -Iinclude -Ibuild/src src/numerics/FuncEval.cpp
g++ -o build/src/numerics/IDA_Solver.os -c -isystem include/cantera/ext -isystem /Users/santosh1/opt/anaconda3/envs/py39/include -isystem /usr/local/include/boost -std=c++17 -O3 -Wno-inline -g -Wall -include src/pch/system.h -fPIC -DNDEBUG -Iinclude -Ibuild/src src/numerics/IDA_Solver.cpp
src/numerics/IDA_Solver.cpp:289:24: error: use of undeclared identifier 'IDADlsSetJacFn'; did you mean 'IDADlsSetBandJacFn'?
            int flag = IDADlsSetJacFn(m_ida_mem, ida_jacobian);
                       ^~~~~~~~~~~~~~
                       IDADlsSetBandJacFn
/usr/local/include/ida/ida_direct.h:257:21: note: 'IDADlsSetBandJacFn' declared here
SUNDIALS_EXPORT int IDADlsSetBandJacFn(void *ida_mem, IDADlsBandJacFn jac);
                    ^
src/numerics/IDA_Solver.cpp:289:50: error: cannot initialize a parameter of type 'IDADlsBandJacFn' (aka 'int (*)(long, long, long, double, double, _generic_N_Vector *, _generic_N_Vector *, _generic_N_Vector *, _DlsMat *, void *, _generic_N_Vector *, _generic_N_Vector *, _generic_N_Vector *)') with an lvalue of type 'int (realtype, realtype, N_Vector, N_Vector, N_Vector, SUNMatrix, void *, N_Vector, N_Vector, N_Vector)' (aka 'int (double, double, _generic_N_Vector *, _generic_N_Vector *, _generic_N_Vector *, _generic_SUNMatrix *, void *, _generic_N_Vector *, _generic_N_Vector *, _generic_N_Vector *)'): different number of parameters (13 vs 10)
            int flag = IDADlsSetJacFn(m_ida_mem, ida_jacobian);
                                                 ^~~~~~~~~~~~
/usr/local/include/ida/ida_direct.h:257:71: note: passing argument to parameter 'jac' here
SUNDIALS_EXPORT int IDADlsSetBandJacFn(void *ida_mem, IDADlsBandJacFn jac);
                                                                      ^
src/numerics/IDA_Solver.cpp:439:20: error: use of undeclared identifier 'IDADlsSetLinearSolver'
            flag = IDADlsSetLinearSolver(m_ida_mem, (SUNLinearSolver) m_linsol,
                   ^
src/numerics/IDA_Solver.cpp:480:13: error: use of undeclared identifier 'IDADlsSetLinearSolver'
            IDADlsSetLinearSolver(m_ida_mem, (SUNLinearSolver) m_linsol,
            ^
src/numerics/IDA_Solver.cpp:492:20: error: use of undeclared identifier 'IDADlsSetJacFn'; did you mean 'IDADlsSetBandJacFn'?
            flag = IDADlsSetJacFn(m_ida_mem, ida_jacobian);
                   ^~~~~~~~~~~~~~
                   IDADlsSetBandJacFn
/usr/local/include/ida/ida_direct.h:257:21: note: 'IDADlsSetBandJacFn' declared here
SUNDIALS_EXPORT int IDADlsSetBandJacFn(void *ida_mem, IDADlsBandJacFn jac);
                    ^
src/numerics/IDA_Solver.cpp:492:46: error: cannot initialize a parameter of type 'IDADlsBandJacFn' (aka 'int (*)(long, long, long, double, double, _generic_N_Vector *, _generic_N_Vector *, _generic_N_Vector *, _DlsMat *, void *, _generic_N_Vector *, _generic_N_Vector *, _generic_N_Vector *)') with an lvalue of type 'int (realtype, realtype, N_Vector, N_Vector, N_Vector, SUNMatrix, void *, N_Vector, N_Vector, N_Vector)' (aka 'int (double, double, _generic_N_Vector *, _generic_N_Vector *, _generic_N_Vector *, _generic_SUNMatrix *, void *, _generic_N_Vector *, _generic_N_Vector *, _generic_N_Vector *)'): different number of parameters (13 vs 10)
            flag = IDADlsSetJacFn(m_ida_mem, ida_jacobian);
                                             ^~~~~~~~~~~~
/usr/local/include/ida/ida_direct.h:257:71: note: passing argument to parameter 'jac' here
SUNDIALS_EXPORT int IDADlsSetBandJacFn(void *ida_mem, IDADlsBandJacFn jac);
                                                                      ^
6 errors generated.
scons: *** [build/src/numerics/IDA_Solver.os] Error 1
scons: building terminated because of errors.`
**System information**

- Cantera version: 98eb6dadd 
- OS: Mac OS Ventura 13.4.1
- Python/MATLAB/other software versions: Python 3.9

**Attachments**

**Additional context**

**Comment by santoshshanbhogue** [comment]
What seems to be happening is that despite specifying that cantera use sundials shipped with it, scons seems find another copy of Sundials 5.3 located in /usr/local. After deleting the copy in /usr/local I don't get the compilation error

**Comment by santoshshanbhogue** [comment]
I am able to compile d717e8bc6 successfully, but multiple tests are failing. Is this normal? Output of `scons test` is below

*********************************** Testing Summary ************************************

Tests passed: 0
Up-to-date tests skipped: 41
Tests failed: 307

Failed tests:
    - clib.passed ***no results for entire test suite***
    - zeroD.passed ***no results for entire test suite***
    - python ***no results for entire test suite***
    - diamondSurf
    - surfSolver
    - surfSolver2
    - cxx-combustor
    - cxx-custom
    - cxx-kinetics1
    - clib-demo

****************************************************************************************

**Comment by speth** [comment]
There seems to be a bug/quirk in Apple's version of Clang* where `/usr/local/include` is always searched before any other location. See https://stackoverflow.com/a/66377265/310477. This is different from the behavior of GCC, which puts directories added with `-I` and `-isystem` before the built-in search path - see https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html.

I don't think there's anything we can do here. Besides your solution of removing Sundials from `/usr/local`, the other option would be to let Cantera use that one by not specifying `system_sundials=n`.

 *Note also that Apple also provides a misleading alias named `g++` that is actually their version of `clang++`, and this is the compiler you are actually using as indicated by some of the SCons checks.

**Comment by santoshshanbhogue** [comment]
Thanks Ray
