### ISSUE TITLE
Broken links from API docs to website "science" documentation

### ISSUE THREAD

**Issue by FrancoXM64** [Cantera/cantera#1528]
Dear Cantera programmers,
following your indication, please note that a click on the following links
https://cantera.org/science/science-species.html#the-nasa-7-coefficient-polynomial-parameterization
https://cantera.org/science/science-species.html#the-nasa-9-coefficient-polynomial-parameterization
raises a 404: Page Not Found message.
The entire web page https://cantera.org/science/science-species.htm seems missing.

Thank you a lot for your fantastic effort in developing Cantera.

Best regards,

Francesco

**Comment by speth** [comment]
Where did you find these links? Are they from a different page on cantera.org?

**Comment by FrancoXM64** [comment]
Dear Speth,
sorry for not having reported the page including the links. It is:
https://cantera.org/documentation/docs-2.6/sphinx/html/yaml/species.html#sec-yaml-species
The links are activated by clicking on the words "described here" under the sections explaining the NASA7 and NASA9 polynomials.
Best regards,
Francesco

**Comment by speth** [comment]
Transferring this to the main repository, as the broken link comes from API documentation that lives there.
