### ISSUE TITLE
Intel-oneAPI classic (icc) is deprecated

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1539]
**Problem description**

The `intel-oneAPI classic on Ubuntu, Python 3.8` runner is starting to generate the following warnings:
```
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
```

**Steps to reproduce**

Look at output from recent GH Action runs - [example](https://github.com/Cantera/cantera/actions/runs/5476211997/jobs/9974849840).

**Possible Solutions**

1. Remove GH Runner, and do not cover `icc` (risking breakages)
2. Remove support for `icc` starting with Cantera 3.0

**System information**

- Cantera version: `main`
- OS: any that are compatible with Intel-oneAPI
- Python/MATLAB/other software versions: N/A

**Comment by speth** [comment]
My inclination would be to defer any changes until after the 3.0 release and make Cantera 3.0 the last version supporting the "classic" compiler.
