### ISSUE TITLE
Doxygen autobrief does not work for `/*!`

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1560]
**Problem description**

`CONTRIBUTING.md` states a preference for `/*!` over `/**`. However, the former breaks Doxygen's autobrief feature. See, for example, documentation of the [C++ SolutionArray class](https://cantera.org/documentation/dev/doxygen/html/de/d8f/classCantera_1_1SolutionArray.html#pub-methods), where in the list of "public member functions" many instances of `@brief` documentation are not shown (i.e. the docstring is not broken at the dot `'.'`). The supported autobrief version should use `/**` per [Doxygen documentation](https://www.doxygen.nl/manual/docblocks.html).

Per documentation, this works:
```
/** Brief description which ends at this dot. Details follow
 *  here.
 */
```
as well as 
```
//! Brief description, which is
//! really a detailed description since it spans multiple lines.
/*! Another detailed description!
 */
```
While Doxygen is flexible, we apparently recommended a version that doesn't support autobrief, i.e.
```
/*! 
 * This is a detailed description. Autobrief does not work 
 * for this documentation style.
 */
```

I verified that this would work (although it is somewhat ugly):
```
//! Brief description.
/**
 * Detailed description. [...]
 */
```

As an aside, this is also true:
```
//! This is a brief description. It continues after the dot.
```

**System information**

- Cantera version: `main`
- OS: any
- Python/MATLAB/other software versions: doxygen=1.9.1

**Comment by speth** [comment]
The fact that `/*!` and `/**` differ only in whether they enable autobrief is a pretty surprising and subtle difference.

Currently, the style that seems to be used fairly often used with `/*!` (and isn't broken) is to have the "brief" comment first using `//!`, then a "details" block with `/*!`, for example:
```c++
    //! Return the name of the phase.
    /*!
     *   Names are unique within a %Cantera problem.
     */
    std::string name() const;
```
But this is probably the most complicated way of formatting a docstring.

If we'd like to make a recommendation for a single consistent style, I think my preference would be to exclusively use `//!` blocks, as they're just more compact and the indentation is simpler. In which case you can do either of the following to get distinct brief and detailed docstrings:
```c++
    //! Return the name of the phase.
    //! Names are unique within a %Cantera problem.
    std::string name() const;

    //! Return the name of the phase
    //! 
    //! Names are unique within a %Cantera problem.
    std::string name() const;
```
This is of course just a recommendation for `CONTRIBUTING.md`, not a plan to go through and reformat a bunch of existing documentation.

**Comment by ischoegl** [comment]
I was likewise surprised, as I thought that `/*!` was a great compromise.

Regarding preferences, I like the brevity / lack of clutter of 

```
//! Single line (brief) comment.
std::string name() const;
```

But when it comes to long comments, I found that 

```
/**
 * Return the name of the phase.
 * Names are unique within a %Cantera problem.
 */
std::string name() const;
```

is extremely comfortable to work with. It's easy on the eyes and seems to be consistent with some of the older documentation that is still present. It does help that my editor knows to continue lines after hitting ‘enter’ …

Comparing the two options, for C++ `//!` every single line needs Doxygen annotation, whereas for the C style, it's just the first line. 

I agree that there's no point in reformatting old documentation.

**Comment by ischoegl** [comment]
> If we'd like to make a recommendation for a single consistent style …

not sure that we need to make comments uniform going forward. From my perspective, having good docstrings that produce quality html is the main objective. The changes from backslash to @ are a little different, as I wanted to clearly identify doxygen commands for those less familiar with this system.

**Comment by speth** [comment]
> having good docstrings that produce quality html is the main objective.

Agreed. But I think the problem is that the various combinations of styles that work, e.g.:
```c++
    //! Return the name of the phase.
    /**
     *  Names are unique within a %Cantera problem.
     */
    std::string name() const;

    //! Return the name of the phase.
    /*!
     *  Names are unique within a %Cantera problem.
     */
    std::string name() const;

    /**
     *  Return the name of the phase.
     *  Names are unique within a %Cantera problem.
     */
    std::string name() const;
```
give a misleading impression that the following is valid by analogy:
```c++
    /*!
     *  Return the name of the phase.
     *  Names are unique within a %Cantera problem.
     */
    std::string name() const;
```
Perhaps the recommendation in #1562 should just be to use `//!` and `/**` and never to use `/*!`? That's even something we could catch as part of the CI.

**Comment by ischoegl** [comment]
> Perhaps the recommendation in #1562 should just be to use `//!` and `/**` and never to use `/*!`? That's even something we could catch as part of the CI.

I'd be 👍 with that.

What's your opinion on this one:
```
//! Brief description.
/**
 * Detailed description. [...]
 */
```
(fwiw, there are 1611 instances of `/*!`)

**Comment by speth** [comment]
Well, it seems like `//!` followed by `/*!` is currently much more common than `//!` followed by `/**` (1263 instances to 35, if I did my regexes correctly), so maybe we should just be on the lookout for the one usage option that Doxygen doesn't like (of which there seem to be ~83 uses).

**Comment by ischoegl** [comment]
I think I should have gotten most of the ones that are problematic in #1561 already (and just added a couple more).

~I did leave a couple that don't qualify as 'brief' comments.~
