### ISSUE TITLE
Cantera 3.0 website converter script documentation

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1577]
**Problem description**

The documentation of the CLI scripts is confusing, i.e. [`cti2yaml`](https://testing.cantera.org/documentation/docs-3.0/sphinx/html/yaml/cti_conversion.html), [`ctml2yaml`](https://testing.cantera.org/documentation/docs-3.0/sphinx/html/yaml/ctml_conversion.html) and [`yaml2ck`](https://testing.cantera.org/documentation/docs-3.0/sphinx/html/yaml/ck_conversion.html), while `ck2yaml` documentation *is absent*.

Example:
<img width="1304" alt="image" src="https://github.com/Cantera/cantera/assets/12603999/9b9042b2-6016-4d49-bf65-f8e6ad0d23ce">

Rather than using the module-level documentation at the top level, it would be preferable to document arguments used from the command line interface. For Sphinx, there is the option to use the [`sphinx-argparse`](https://sphinx-argparse.readthedocs.io/en/stable/) module, which generates documentation for CLI functions that are based on `argparse` (unfortunately this excludes `ck2yaml`).

While there is still an argument to be made for the inclusion of detailed documentation for "under-the-hood" functions used by the converter scripts, they probably should not appear at the top level in the left menu.

In terms of navigation, this becomes more apparent on the [Sphinx index page](https://cantera.org/documentation/dev/sphinx/html/index.html) ... the current documentation likely belongs into the "[Python Module Documentation](https://cantera.org/documentation/dev/sphinx/html/cython/index.html)" instead of the "[YAML Input File Reference](https://cantera.org/documentation/dev/sphinx/html/yaml/index.html)".

**Comment by speth** [comment]
The primary user documentation for the `ck2yaml`, `ctml2yaml`, and `cti2yaml` scripts is based at [`/tutorials/input-files.html`](https://testing.cantera.org/tutorials/input-files.html) and the pages linked to from there.

I think you're right that this documentation of the internals of these conversion scripts is a bit too prominent, and the more relevant documentation to link to from the YAML section would be [`/tutorials/ck2yaml-tutorial.html`](https://testing.cantera.org/tutorials/ck2yaml-tutorial.html) and friends (though that suffers from the fragility of linking from the API docs back to pages on `cantera-website`).
