### ISSUE TITLE
Convert Chemkin-format mechanisms to Cantera

### ISSUE THREAD

**Issue by czc-zju** [Cantera/cantera#1615]
When I use the **cantera.ck2yaml**  to convert the chemkin mechanism to Cantera, I encounter the following error:
_Skipping unexpected species "CHO" while reading thermodynamics entry.
Wrote YAML mechanism file to 'chem.yaml'.
Mechanism contains 102 species and 594 reactions.
Validating mechanism...
FAILED
Undeclared duplicate reaction HCOOH + M <=> CO + H2O + M
found on lines 744 and 748 of the kinetics input file._

The chemkin mechanism is in the attachment. Hope someone can help me. 
Thanks in advance
[chem.inp.txt](https://github.com/Cantera/cantera/files/12509034/chem.inp.txt)
[thermo.dat.txt](https://github.com/Cantera/cantera/files/12509036/thermo.dat.txt)
[trans.dat.txt](https://github.com/Cantera/cantera/files/12509038/trans.dat.txt)

**Comment by ischoegl** [comment]
Please try the `—permissive` option, per online documentation. If you have further questions, please ask on [Cantera’s user group](https://groups.google.com/group/cantera-users).
