### ISSUE TITLE
Add transport_model options to python module documentation

### ISSUE THREAD

**Issue by d-e-t** [Cantera/cantera#1658]
**Problem description**

The python module documentation for the [transport_model](https://cantera.org/documentation/docs-3.0/sphinx/html/cython/transport.html#cantera.Transport.transport_model) method lacks reference to the model options.  This documentation would be improved by adding the transport model labels, especially with the changes in label from Cantera 2.6 to 3.0. (for example from "Multi" to "multicomponent"). The [Matlab documentation](https://cantera.org/documentation/docs-3.0/sphinx/html/matlab/transport.html) includes transport model options.  

**Cantera versions** 

Applies to documentation for the current stable 3.0.0 and development 3.1

**Comment by ischoegl** [comment]
@d-e-t ... thank you for your suggestion. Adding documentation is relatively straight-forward - in case you should be sufficiently familiar, feel free to start a PR to address this issue.

**Comment by d-e-t** [comment]
@ischoegl - Yes, this is pretty minor, and I think it is clearer in my edit.

**Comment by d-e-t** [comment]
Approved by @decaluwe -- thanks!  Closing this now.
