### ISSUE TITLE
Capability Evaluation 

### ISSUE THREAD

**Issue by skr3178** [Cantera/cantera#1667]
Can cantera be used for electrochemical modeling of electrodialysis of seawater ?
Something to recreate this experiment on Cantera. 

CO2 extraction from seawater using bipolar membrane electrodialysis
[link](10.1039/c2ee03393c)

I’m new to this field and have limited knowledge. Any help is appreciated. @
![IMG_0643](https://github.com/Cantera/cantera/assets/79299617/678e17e8-8789-4ac0-a98e-9d2d1f5b96e1)

**Comment by speth** [comment]
Please post questions of this nature on the [Cantera Users' Group](https://groups.google.com/g/cantera-users).
