### ISSUE TITLE
DLL load failed while importing _cantera

### ISSUE THREAD

**Issue by zhanggh97** [Cantera/cantera#1707]
**Problem description**

DLL load failed while importing _cantera

**Steps to reproduce**

I use Anaconda and therefore installed Cantera by conda in anaconda powershell prompt. 

> conda install --channel cantera cantera

And I directly installed cantera in the environment 'base' without create a new environment.
After installation, I try to run a script. When it run to the ‘import’ line as followed, there will be an error
> import cantera as ct

**Behavior** (error infomation)

File "D:\Software\anaconda3\Lib\site-packages\cantera\__init__.py", line 4, in <module>
    from ._cantera import *
ImportError: DLL load failed while importing _cantera: 找不到指定的模块。

I try to run it in pycharm and anaconda powershell prompt, the error happen in both.

I also use dependency walker to check the file: _cantera.cp311-win_amd64.pyd, and there are lots of  dependency which was not found and most of them are 'API-MS-WIN' and 'EXT-MS-WIN'. I search it online and people said it always happened while using dependency walker. So I can't make sure which part is the real problem.

**System information**

- Cantera version: 3.0.0
- OS: windows 10 (after I update to win11, the error is still)
- Python/MATLAB/other software versions: 3.11

**Additional context**

About one week ago, I uninstall the old version anaconda, then install the last version. And I updated the BIOS of my cpu and windows system. Before that, I can use the old version cantera without any problem. Today is the fisrt time I try to use cantera after update, then the problem happened. I'm not sure whether there is a causal relationship.

**Comment by speth** [comment]
Using the modern version of the dependency walker (https://github.com/lucasg/Dependencies) I don't see any unresolved dependencies. You also need to make sure to run the Dependencies tool from your Conda environment so it has the same path as your Python interpreter. For example, from the Conda prompt run `start "C:\Program Files\Dependencies\DependenciesGUI.exe"`, adjusting the path to wherever you've installed it.

Here's what I see trying this on my system:
![image](https://github.com/Cantera/cantera/assets/644977/56beb0fb-ca9f-4ef6-a22b-14bae493c272)

Can you post a screenshot of what you see in the left panel when loading the `_cantera.cp311-win_amd64.pyd` file this way, and expanding at least the dependency on `cantera_shared.dll`? Also, can you share the output of the `conda list` command? What happens if you try following our instructions to install Cantera in a separate Conda environment?

**Comment by ischoegl** [comment]
As an aside, this may be a question for the User Group ... it looks like an installation issue to me (not a bug)

**Comment by zhanggh97** [comment]
> Using the modern version of the dependency walker (https://github.com/lucasg/Dependencies) I don't see any unresolved dependencies. You also need to make sure to run the Dependencies tool from your Conda environment so it has the same path as your Python interpreter. For example, from the Conda prompt run `start "C:\Program Files\Dependencies\DependenciesGUI.exe"`, adjusting the path to wherever you've installed it.
> 
> Here's what I see trying this on my system: ![image](https://private-user-images.githubusercontent.com/644977/338608140-56beb0fb-ca9f-4ef6-a22b-14bae493c272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTc3MTUsIm5iZiI6MTcxODExNzQxNSwicGF0aCI6Ii82NDQ5NzcvMzM4NjA4MTQwLTU2YmViMGZiLWNhOWYtNGVmNi1hMjJiLTE0YmFlNDkzYzI3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxNDUwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjI3ZTUwY2MzMjQ2MzcxODZjNDk0ZmRlMGNmMGI3ZGY2ZDVjNDNjZmY0NzY5MTFiN2FlZDYzMzM0NWFiMjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dHp_b8p-DroD3_VUxBmt7CVC06cQTovcwBxhiYfws4Q)
> 
> Can you post a screenshot of what you see in the left panel when loading the `_cantera.cp311-win_amd64.pyd` file this way, and expanding at least the dependency on `cantera_shared.dll`? Also, can you share the output of the `conda list` command? What happens if you try following our instructions to install Cantera in a separate Conda environment?



> Using the modern version of the dependency walker (https://github.com/lucasg/Dependencies) I don't see any unresolved dependencies. You also need to make sure to run the Dependencies tool from your Conda environment so it has the same path as your Python interpreter. For example, from the Conda prompt run `start "C:\Program Files\Dependencies\DependenciesGUI.exe"`, adjusting the path to wherever you've installed it.
> 
> Here's what I see trying this on my system: ![image](https://private-user-images.githubusercontent.com/644977/338608140-56beb0fb-ca9f-4ef6-a22b-14bae493c272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDU1MjEsIm5iZiI6MTcxODIwNTIyMSwicGF0aCI6Ii82NDQ5NzcvMzM4NjA4MTQwLTU2YmViMGZiLWNhOWYtNGVmNi1hMjJiLTE0YmFlNDkzYzI3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxNTEzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzc3MzUyZjU0YTVjMjMzM2VlNDk3ZGJlOTFjYmIxZjVkZmNmNThhYjY5ZmI3YjcwYzRhZGZmNjRhOTU1ZTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GCYn__eM_EJqsRFlgB5SBMNuTjZWVdztOwQxSlMDQ4c)
> 
> Can you post a screenshot of what you see in the left panel when loading the `_cantera.cp311-win_amd64.pyd` file this way, and expanding at least the dependency on `cantera_shared.dll`? Also, can you share the output of the `conda list` command? What happens if you try following our instructions to install Cantera in a separate Conda environment?

This is  the conda list:  
![1](https://github.com/Cantera/cantera/assets/81150100/77031080-32a8-4a74-b3f8-d50437457229)
![2](https://github.com/Cantera/cantera/assets/81150100/8cd3ad30-e54d-450d-a60f-419e80dfdb81)
![3](https://github.com/Cantera/cantera/assets/81150100/fd0c225a-c5b8-4183-9a42-a401b3aaafc4)
![4](https://github.com/Cantera/cantera/assets/81150100/a1d424f7-3906-47c3-b1c6-388970cb999d)
![5](https://github.com/Cantera/cantera/assets/81150100/498492d7-92d4-4df4-802d-fc052cc0cb0b)
![6](https://github.com/Cantera/cantera/assets/81150100/d5d3a736-74b8-4940-a94c-df88bd903b50)

**Comment by zhanggh97** [comment]
> Using the modern version of the dependency walker (https://github.com/lucasg/Dependencies) I don't see any unresolved dependencies. You also need to make sure to run the Dependencies tool from your Conda environment so it has the same path as your Python interpreter. For example, from the Conda prompt run `start "C:\Program Files\Dependencies\DependenciesGUI.exe"`, adjusting the path to wherever you've installed it.
> 
> Here's what I see trying this on my system: ![image](https://private-user-images.githubusercontent.com/644977/338608140-56beb0fb-ca9f-4ef6-a22b-14bae493c272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDU1MjEsIm5iZiI6MTcxODIwNTIyMSwicGF0aCI6Ii82NDQ5NzcvMzM4NjA4MTQwLTU2YmViMGZiLWNhOWYtNGVmNi1hMjJiLTE0YmFlNDkzYzI3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxNTEzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzc3MzUyZjU0YTVjMjMzM2VlNDk3ZGJlOTFjYmIxZjVkZmNmNThhYjY5ZmI3YjcwYzRhZGZmNjRhOTU1ZTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GCYn__eM_EJqsRFlgB5SBMNuTjZWVdztOwQxSlMDQ4c)
> 
> Can you post a screenshot of what you see in the left panel when loading the `_cantera.cp311-win_amd64.pyd` file this way, and expanding at least the dependency on `cantera_shared.dll`? Also, can you share the output of the `conda list` command? What happens if you try following our instructions to install Cantera in a separate Conda environment?


I created a new env for cantera with python=3.9.0, then I installed the cantera with version of 2.6.0. It runs well. So my problem is solved in some way. 
However, if you want to discuss this problem more. I will show the detail after I install the the modern version of the dependency walker.

**Comment by zhanggh97** [comment]
> As an aside, this may be a question for the User Group ... it looks like an installation issue to me (not a bug)

You are right. I'm sorry if I proposed this problem at a wrong place. Could you send me the link of User Group? Next time I get a problem I will try to propose it in a suitable way.

**Comment by speth** [comment]
> I created a new env for cantera with python=3.9.0, then I installed the cantera with version of 2.6.0. It runs well. So my problem is solved in some way.

Did you try creating a new environment for `python=3.11` and `cantera=3.0`? Does that work or fail with the same error?

**Comment by speth** [comment]
Closing in the absence of an update from the original poster.
