### ISSUE TITLE
Build fails with fmt 11.0.1

### ISSUE THREAD

**Issue by mefuller** [Cantera/cantera#1735]
**Problem description**

Cantera v3.0.0 fails to build on Fedora when moving to fmt 11 from fmt 10 (no other changes)

**Steps to reproduce**

The complete buildlog is here: https://kojipkgs.fedoraproject.org//work/tasks/6033/120566033/build.log

```
...
src/kinetics/InterfaceRate.cpp: In member function 'void Cantera::StickingCoverage::setContext(const Cantera::Reaction&, const Cantera::Kinetics&)':
src/kinetics/InterfaceRate.cpp:395:42: error: 'join' is not a member of 'fmt'
  395 |                 fmt::format("'{}'", fmt::join(anySpecies, "', '")), rxn.equation());
      |                                          ^~~~
src/kinetics/InterfaceRate.cpp:395:42: note: suggested alternatives:
In file included from /usr/include/boost/algorithm/string.hpp:24,
                 from src/pch/system.h:19:
/usr/include/boost/algorithm/string/join.hpp:46:9: note:   'boost::algorithm::join'
   46 |         join(
      |         ^~~~
/usr/include/boost/algorithm/string/join.hpp:46:9: note:   'boost::algorithm::join'
...
```

**Behavior**

Build fails

**System information**

- Cantera version: 3.0.0
- OS: Fedora Linux / Rawhide
- Python/MATLAB/other software versions:

**Additional context**
I see that @speth is currently working on some improvements/updates around fmt and C++20, so rather than work up a patch for just this issue, does it make more sense to roll this into that work?

Thanks for all that you do maintaining Cantera

**Comment by ischoegl** [comment]
Thanks for reporting. Looks like `fmt` tries to keep things interesting. We probably just need another custom function to ensure that this function is properly supported all the way back to 7.1 (which is the last version we’re currently routinely testing)

**Comment by bryanwweber** [comment]
The same thing happened in the conda forge auto update https://github.com/conda-forge/cantera-feedstock/pull/40
