### ISSUE TITLE
Broken name attribute for reactor `Wall` objects 

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1764]
**Problem description**

Reactor `Wall` objects do have documented name attributes, but they are not retrievable.

**Steps to reproduce**

On IPython, run
```
In [1]: %run samples/python/reactors/piston.py
time [s]    T1 [K]      T2 [K]      V1 [m^3]    V2 [m^3]    V1+V2 [m^3]  X(CO)
     0.004       900.0    900.0015         0.5         0.1         0.6      0.2853
[...]
     0.200      2319.4   2774.2346      0.4917      0.1083         0.6     0.03109
To view a plot of these results, run this script with the option --plot

In [2]: w.name  # 'w' is a variable holding a 'Wall' object
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 w.name

AttributeError: 'cantera.reactor.Wall' object has no attribute 'name'
```

**Behavior**

Although `name` is a documented parameter, it cannot be retrieved (even if no name is provided, a default name should be generated automatically).
https://github.com/Cantera/cantera/blob/32a8d4b8fde73e52ee7aa73dfd650bce68e46a03/interfaces/cython/cantera/reactor.pyx#L947-L972

**System information**

- Cantera version: current `main`
- OS: macOS
- Python/MATLAB/other software versions: Python 3.11

**Additional context**

Originally reported on UG, [see post](https://groups.google.com/g/cantera-users/c/V8T2Y2R1jhc)

**Comment by cpilko** [comment]
I can reproduce.

Further, running the following code:
``` python
for d in dir(w):  # w is a wall 
    if not d.startswith('_'): print(d)`
```

Produces this output with no `name` property in it:
```
area
emissivity
expansion_rate
expansion_rate_coeff
heat_flux
heat_rate
heat_transfer_coeff
qdot
set_heat_flux
set_velocity
type
vdot
velocity
wall_type
```

**System information**

Cantera version: 3.0.0
OS: Windows 10
Python/MATLAB/other software versions: Python 3.11
