### ISSUE TITLE
Possible unit ommision in `Overall heat transfer coefficient` in the DOCs

### ISSUE THREAD

**Issue by alongd** [Cantera/cantera#1789]
In the documentation for `class cantera.Wall()`, the unit for the overall heat transfer coefficient (`U`) is listed as `[W/m²]` on the following page: [Cantera Documentation](https://cantera.org/documentation/docs-3.0/sphinx/html/cython/zerodim.html#cantera.Wall).

I believe the correct unit should be `[W/m²·K]` to properly reflect the temperature dependency in the heat transfer coefficient.
If the original unit (`[W/m²]`) is indeed correct, could someone please clarify how to apply this unit in practice? For example, I have the thermal conductivity value of a wall in `[W/m·K]` and intended to calculate `U` by dividing the thermal conductivity by the wall thickness, which yields `[W/m²·K]`.
This seems to conflict with the current documentation.

**Comment by bryanwweber** [comment]
Hi @alongd! Thanks for asking this. The short answer is that the units are correct in the documentation. Perhaps heat transfer coefficient is a misnomer here, a better term might be the total rate of heat transfer per unit area. You can verify this by looking at the energy equation evaluation for the wall:

https://github.com/Cantera/cantera/blob/dd26e1835193d35ceace46f48e1b08ac18d76f45/src/zeroD/Wall.cpp#L86

The heat flux is simply multiplied by the wall area.

In your case, the conduction equation is something like

    \dot{Q} = k A dT/dx => \dot{Q}/A = k dT/dx

So you need to multiply your thermal conductivity by the temperature gradient in the wall (if it's constant) or possibly integrate it over the thickness.
