### ISSUE TITLE
CI Failures for "Windows 2022" builds

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#1794]
**Problem description**

As noted in #1792, unrelated to the changes in that PR, we're currently getting CI failures for the "Windows 2022" builds. Looking at the [logs](https://github.com/Cantera/cantera/actions/runs/11087803273/job/30806907137?pr=1792), it appears that the "Build Cantera" step is completing successfully, but for the separate "Build Tests" step, SCons is re-running the configuration checks and trying to use a version of MinGW that's installed on the GitHub runner.

The "Build Cantera" step's log starts with:
```
Run scons build system_eigen=y system_yamlcpp=y system_highfive=y logging=debug toolchain=msvc f90_interface=n debug=n  --debug=time -j4
scons: Reading SConscript files ...
SCons 4.7.0 is using the following Python interpreter:
    C:\Users\runneradmin\micromamba\envs\test-env\python.exe (Python 3.12)
Compiling with MSVC version 14.3
Compiling with MSVC toolset 14.3 (default)
Compiling for architecture: amd64
Compiling using the following toolchain(s): ['default']
INFO: Compiling on 'AMD64 Family 25 Model 1 Stepping 1, AuthenticAMD'
INFO: Configuration variables read from 'cantera.conf' and command line:
    f90_interface = 'n'
    system_eigen = 'y'
    system_highfive = 'y'
    system_yamlcpp = 'y'
    debug = False
    logging = 'debug'
```

But the "Build Tests" step starts with:
```
Run scons -j4 build-tests --debug=time
scons: Reading SConscript files ...
SCons 4.7.0 is using the following Python interpreter:
    C:\Users\runneradmin\micromamba\envs\test-env\python.exe (Python 3.12)
INFO: Building Cantera from git commit '94219d9'
Compiling for architecture: amd64
Compiling using the following toolchain(s): ['mingw', 'f90']
INFO: Compiling on 'AMD64 Family 25 Model 1 Stepping 1, AuthenticAMD'
INFO: Configuration variables read from 'cantera.conf' and command line:
    f90_interface = 'n'
    system_eigen = 'y'
    system_highfive = 'y'
    system_yamlcpp = 'y'
    debug = False
    logging = 'debug'
```

It seems like the value of the `toolchain` setting isn't getting saved in `cantera.conf`, which is as far as I've gotten so far.

**Comment by ischoegl** [comment]
It looks like newest actions no longer fail. This may have been a temporary issue on GH? It could be argued that there is an underlying issue as we don’t write variables to `cantera.conf` though.

**Comment by speth** [comment]
Yes, I still want to investigate. I've been traveling lately and haven't had access to my Windows machine at home where I was hoping to check on this.
