### ISSUE TITLE
Invalid MEX-file 'C:\[.....]\ctmethods.mexw64': The specified module could not be found.

### ISSUE THREAD

**Issue by a1gituser** [Cantera/cantera#1805]
**Problem description**
Executing the example throws an error related to the mex interface

Invalid MEX-file 'C:\Users\.....\ct-env\share\cantera\matlab\toolbox\ctmethods.mexw64': The specified module could not be found.

I have MS Visual Studio 2015-2022 redistributables installed both for 32 and 64 bits. Dependency walker shows missing DLLs that I cannot figure out where they're supposed to be or how to install:
![image](https://github.com/user-attachments/assets/07ee15c6-b41b-4c5f-9b4d-30203186357b)

**Steps to reproduce**

install python interface using conda as per the installation instructions
install matlab toolbox in the same way
from matlab run h2o = Solution('liquidvapor.yaml', 'water')

- Cantera version: 300
- OS: Windows 10
- Python/MATLAB/other software version
  - python 3.10
  - matlab 2023b

**Comment by speth** [comment]
Please ask questions about issues using and installing Cantera on the [Cantera Users' Group](https://groups.google.com/g/cantera-users).
