### ISSUE TITLE
Diamond CVD example produces incorrect growth rate

### ISSUE THREAD

**Issue by joelager** [Cantera/cantera#1806]
**Problem description**
Running the diamond CVD example as is yields a large negative (non-physical) rate for diamond

![image](https://github.com/user-attachments/assets/a027bf13-8929-43ce-a392-10a83e525bf9)

**Steps to reproduce**

Just run the script

**Behavior**

**System information**

- Cantera version: 3.0.0
- OS: Linux and MacOS
- Python/MATLAB/other software versions: 3.10, 3.11, 3.12

**Attachments**

Original code - yields index 8 which is actually hydrogen

      iC = d.kinetics_species_index(dbulk.species_index('C(d)'), 1)   # wrong, indexed to H

Correct code, yields the index for bulk diamond

      iC = d.kinetics_species_index('C(d)')

**Additional context**

This is what the result should look like
![image](https://github.com/user-attachments/assets/8b12cc03-b61d-4786-99a0-23fbd24ff16e)

**Comment by speth** [comment]
Thanks @joelager, good catch! Would you like to open a Pull Request fixing this issue?
