### ISSUE TITLE
How to Calculate Adiabatic Flame Temperature for zetropic Mixtures (e.g., R290 and R32) using Cantera?

### ISSUE THREAD

**Issue by SirichaiDD** [Cantera/cantera#1812]
I have written a MATLAB program with Cantera to calculate the adiabatic flame temperature for working fluids, and I obtained correct results for certain substances, such as R600 (C₄H₁₀), R601a (C₅H₁₂), methane (CH₄), and R290 (C₃H₈). However, I have some questions regarding the calculation for mixtures, such as R290 (C₃H₈) mixed with R32 (CH₂F₂). Could you advise on how to modify the program to get accurate results for such mixtures?

Additionally, if I want to use other working fluids, such as R32 (CH₂F₂) or R143a (CH₃-CF₃), what adjustments should I make in the program? Thank you in advance for your guidance!

**Comment by speth** [comment]
Thanks for your interest in Cantera. Please ask questions about how to use it on the [Cantera Users' Group](https://groups.google.com/g/cantera-users).
