### ISSUE TITLE
Website documentation for v 3.1 says "work in progress"

### ISSUE THREAD

**Issue by rwest** [Cantera/cantera#1832]
**Problem description**

The page at https://cantera.org/3.1/index.html says
> **Caution**
> This page is a work in progress. For documentation and tutorials for Cantera 3.0, please see [this page](https://cantera.org/index.html).

which is offputting. I think now 3.1 is the stable official release, this page should be updated?

I came across this page couple of times but I can't now remember where the links to it were.

**Comment by speth** [comment]
There aren't supposed to be any links directly to that page -- it exists mainly to keep Sphinx happy.

From browsing the web server logs, it looks like the referring page is usually https://cantera.org/3.0/sphinx/html/, which implies following a link from the version switcher, where in the case of a missing page (the 3.1 and newer docs do away with the `sphinx/html` subdirectories) it just backs up the tree until it finds a page). Given that page is only API docs, I think it makes the most sense to just automatically redirect to https://cantera.org/3.1/reference/index.html.

**Comment by rwest** [comment]
The version switcher sounds right.

**Comment by ischoegl** [comment]
The `doc/sphinx/index.md` file should likely be updated in #1833 to refer to Cantera 3.1 as stable, with the rest being a website issue?
