### ISSUE TITLE
equilibrium calculation appears dependent on order of constituents

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Cantera/cantera#212]
```
What steps will reproduce the problem?
1. run attached python script with attached files

What is the expected output? What do you see instead?
The following should print to the screen:
"DEBUG:root:Works worked!
ERROR:root:Fails worked!"
Instead I see:
"DEBUG:root:Works worked!
ERROR:root:Fails failed!"

What version of the product are you using? On what operating system?
v2.1.0 on Windows 7, 32-bit

Please provide any additional information below.
The only difference between these two phase descriptions is the order in which 
the constituents are declared.
```

Original issue reported on code.google.com by `kevin.ho...@gmail.com` on 12 Mar 2014 at 10:22

Attachments:
- [myelements.xml](http://cantera.org/issues/212/myelements.xml)
- [sample.xml](http://cantera.org/issues/212/sample.xml)
- [eqTest.py](http://cantera.org/issues/212/eqTest.py)

**Comment by ischoegl** [comment]
The linked files no longer open.

**Comment by bryanwweber** [comment]
We can probably close this as not reproducible since it was originally filed more than 10 years ago. We have more than enough examples of equilibrium solver failures documented here :smile:
