### ISSUE TITLE
Setting the fixed point for the T profile for laminar flame speed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Cantera/cantera#242]
```
What steps will reproduce the problem?
I run the code found at 
https://groups.google.com/forum/#!topic/cantera-users/ueLh3_kyz54, which was 
posted in 2012. Error still has not been fixed.

What is the expected output? What do you see instead?
Plots adiabatic premixed laminar flame speed. Code does not run.

What version of the product are you using? On what operating system?
Cantera 2.1.2 on Win8.1 using MATLAB 2014b

Please provide any additional information below.

```

Original issue reported on code.google.com by `andrewro...@gmail.com` on 9 Oct 2014 at 3:03

**Comment by bryanwweber** [comment]
Should this be closed as `wont-fix` given our discussion about the new Matlab toolbox and the 1D interface?

**Comment by speth** [comment]
Yes, but first I think we need to document the plan for the new Matlab toolbox somewhere, to clarify that no improvements will be made to the Matlab 1D toolbox.

**Comment by speth** [comment]
This method is implemented (if not yet tested) in the experimental Matlab toolbox.
