### ISSUE TITLE
Add support for Sundials 2.6

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#256]
Sundials 2.6.1 was recently released, and we should support it in the next Cantera version.

**Comment by skyreflectedinmirrors** [comment]
Ray, 
Two notes.  First, there has been a lot of activity / bug-fixes being posted on the Sundials listsrv.  I wouldn't be entirely surprised if 2.6.2 comes out relatively soon (though it shouldn't affect much on our end)
Second, the new ARKode solver appears to be a similar concept to the Hybrid Multi-Timescale integator (e.g. Gou et al, http://arc.aiaa.org/doi/abs/10.2514/6.2009-1369) and may be worth looking into

**Comment by speth** [comment]
I'm not too concerned about any differences between 2.6.1 and 2.6.2; hopefully there shouldn't be any API changes there. The bigger issue is the Cantera build scripts explicitly require either Sundials 2.4 or 2.5. I don't know if there are any changes that we need to special case for 2.6. At a minimum, the change in the Sundials build system to use CMake only means we need to update some of our build instructions.

Thanks for bringing up the potential usefulness of the ARKode solver. I had seen the mentions of it on the Sundials mailing list, but hadn't looked at it.
