### ISSUE TITLE
Unable to instantiate PureFluidPhase using RedlichKwong equation of state

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#263]
Although `ctml_writer` includes a class `redlich_kwong`, it is actually not possible to use this class. There appear to be implementation problems at every level required for this to work:
- `ctml_writer.redlich_kwong` can't be converted to XML because it doesn't know the value of the molecular weight. In principle, this could be discovered from the species info, but `ctml_writer` does not contain an easy way for the phase object to know about its species objects.
- It uses the wrong `substance_flag`; 7 is for carbon dioxide.
- There isn't any code that can instantiate the object from XML as a `PureFluidPhase` since there is no hook for calling the method `RedlichKwong::setParameters` from `PureFluidPhase`.
- The docstring for `ctml_writer.redlich_kwong` is just copied from `ctml_writer.liquid_vapor`

This should be resolved in one of the following ways, depending on whether having this equation of state available is actually a useful feature:
- Fix the above issues
- Remove `ctml_writer.redlich_kwong` and deprecate the `tpx::RedlichKwong` class.

Since the class `RedlichKwongMFTP` appears to provide a more general (multi-species) implementation of this equation of state, the second option may be the best choice.

**Comment by goldmanm** [comment]
in addition to the above issues, the docstring for `ctml_writer.redlich_kwong` and `ctml_writer.liquid_vapor` both reference `purefluids.py`, which does not exist, for information about `substance_flags`. Updating this information might be useful.
