### ISSUE TITLE
Possibly ambiguous index "H" in ConstPressureReactor::componentIndex

### ISSUE THREAD

**Issue by thomasfiala** [Cantera/cantera#274]
Using "H" to specify enthalpy is possibly ambiguous in functions like ConstPressureReactor::componentIndex:
https://github.com/Cantera/cantera/blob/master/src/zeroD/ConstPressureReactor.cpp#L131

If atomic hydrogen is contained in the reaction mechanism, calling this function with the argument "H" will yield the index of the atomic hydrogen species, and not enthalpy.

This might apply to other parts of the code as well.

**Comment by speth** [comment]
This was the result of changes made to resolve the problem identified in #193, which is that there was no way to get the mass fraction of the species "H", and introduced the full names "enthalpy" and "mass" for those state variables while still allowing the short names where possible.

I think using the full name "enthalpy" should be the preferred way of getting the enthalpy. Perhaps using "H" and "m" for enthalpy and mass should be deprecated and a warning issued? I think the other places this applies are just the implementations of `componentIndex` for the `Reactor` derived classes.

**Comment by thomasfiala** [comment]
Yes, I also think that making "enthalpy" and "mass" the preferred identifiers and gradually deprecating "H" and "m" is the best way to go.
This is probably just a tiny issue and in most cases it is irrelevant, but I just came across it and wanted to raise awareness.
