### ISSUE TITLE
Species thermodynamic data not available in Python module

### ISSUE THREAD

**Issue by kyleniemeyer** [Cantera/cantera#275]
Species thermodynamic data (e.g., coefficients) are not currently available through any of the `cantera.SpeciesThermo` derived classes, including `cantera.ConstantCp`, `cantera.NasaPoly2`, and `cantera.ShomatePoly2`.

**Comment by bryanwweber** [comment]
Discussion for reference: https://groups.google.com/d/topic/cantera-users/2xT9VC__SNU/discussion
