### ISSUE TITLE
Documentation of configuration options inconsistent with actual options

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#282]
As noted on the User's Group: https://groups.google.com/d/topic/cantera-users/nA80dUWmqQY/discussion

The documentation for SCons configuration options is out of date (in particular, the FORTRAN option hasn't been changed from F90). This is the case in the main documentation and the dev-docs.

**Comment by bryanwweber** [comment]
Fixed by 4273fe865d2cd5b4a388575d3a86dd213c88bf9f

**Comment by speth** [comment]
Well, mostly fixed. I think a version of this also needs to be done for the 2.2 maintenance branch, and then I need to update the published versions of the documentation.

**Comment by speth** [comment]
Fixed in the 2.2 branch in 4dc4a1446728. Published documentation on cantera.github.io and cantera.org has been updated as well.

**Comment by bryanwweber** [comment]
Thanks Ray!
