### ISSUE TITLE
Produce executable scripts for ck2cti and mixmaster on Windows

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#283]
The Windows installers don't currently produce command line-executable wrappers, they only produce the `*.py` files. Using an alternate build system such as `setuptools` (instead of `distutils`) would ease the process of generating executable wrappers on Windows and provide a consistent interface to generate executables on all operating systems. Further reference: https://groups.google.com/d/topic/cantera-users/ATFCtAyPm3Q/discussion

**Comment by speth** [comment]
Fixed in b979cea3d.
