### ISSUE TITLE
Access the WaterTransport Class from Python?

### ISSUE THREAD

**Issue by benhoff** [Cantera/cantera#289]
Tried digging through the documentation and code itself to no avail to figure out how to get the viscosity of water. Currently creating a cantera.Water() object, but PureFluids don't have the viscosity accessor, and I haven't been able to figure out how to create the Transport object in python. Using Cantera 2.1.0 for reference, so if it's been solved in a later API, this will be signal rather than noise.

**Comment by bryanwweber** [comment]
Hi Ben! I don't think the PureFluid Phases implement transport properties, which is what I think you're trying to use in the Python interface. Instead, you can try using a Solution with a simple mechanism, such as the included H2-O2 mechanism:

```
In [1]: import cantera as ct
In [2]: gas = ct.Solution('h2o2.cti')
In [3]: gas.viscosity
Out[3]: 9.0000285548489e-06
```

Of course, this provides gas-phase viscosities only. If you want liquid phase properties, I think you'll have to use the C++ interface in combination with the WaterProps class: https://github.com/Cantera/cantera/blob/master/src/thermo/WaterProps.cpp

Aside from any other issues, I would definitely recommend that you upgrade Cantera when you get the chance. There are a number of improvements and bug-fixes, so its always best to be on the most recent version unless you have a particular reason to stay on the old version.

Finally, questions like this are usually better posted in the User's Forum at https://groups.google.com/forum/#!forum/cantera-users. It's not a problem to post them here, but many more people read the Google Group, so you're likely to get a better response (and sometimes  faster too!) by posting there. It is a moderated list, so your first post might take a bit to show up, but after that there should be no restrictions.

Best,
Bryan

**Comment by speth** [comment]
I don't think there's any good reason for the `WaterTransport` class to be inaccessible from Python, though. It looks like it was just never added to `TransportFactory` and there's no prescribed way of specifying this transport model in a CTI or XML input file.

**Comment by benhoff** [comment]
@bryanwweber: Hey! You're right on multiple issues! I need the liquid water properties though so looks like I'm hosed for now as far as using Cantera. Switched to using a simple curve fit based on temperature for the time being, if anyone else runs into a similar issue. 

I think distributing c++ source and compiling is a treacherous business and I'd much rather see it rolled into the python module if possible. I work in a windows heavy environment and have run into compilation issues with python(x, y) [my institutions prescribed python package] using cygwin instead of visual studio on Windows. I have individually solved this issue with a simple config file, but that hack/fix is not an extensible solution for my user base, as I am leaving in ~8 months and cannot continue to support them. Thus I'd rather a sys admin be tagged to deal with such issues than me rolling my own solution. My user base will have dedicated sys admin support long after I am gone.

 On updating to the most recent version... I hear you. My organization is unfortunately super finicky about updating software without going through vulnerability testing and we primarily work on a sneaker-net, so the realities are what they are. I'm slightly curious how stable the cantera.Solution implementation has been, as that's what we're primarily using for Thermo property calculation, but I can be unlazy and look it up and assess whether we need to start compiling locally to incorporate the most recent fixes.

Also wasn't sure on the correct place to post this, as it definitely isn't implemented in python, so I hope I didn't step on any toes. If I need user support, I will default to the google groups. This seemed like more of a developmental issue, so I took a chance and posted it here.

@speth, would the prescribed method be to create a `Solution` object and set the `transport_model` to 'WaterTransport'? Because I'll wrap that functionality in a try/except block and implement that now if that looks likely.

**Comment by bryanwweber** [comment]
@benhoff I didn't realize exactly what you were trying to do; I agree that this is more of a development issue than it appeared to me at first, so this is a perfectly fine place to post! Just FYI, when this transport model gets added to the Python interface, you'll definitely have to update to be able to use it... I guess that's probably what you mean with the try...except block

On a separate note, if you don't mind explaining a bit, what troubles did you have with Cygwin?

**Comment by speth** [comment]
I wouldn't want to commit to any particular method for using the `WaterTransport` class at this time. It's a little more complicated than just specifying the `transport_model` since I think it only works if you're also using the IAPWS95-based equation of state, which can't currently be instantiated in Python, either (the existing two-phase EOS for water is different one, from the W.C. Reynolds book).

There's also the question of whether the `WaterTransport` implementation actually works and gives correct results. There are a lot of dusty, incomplete, and untested classes in the C++-only part of Cantera, and this could well be one of them.

**Comment by benhoff** [comment]
@bryanwweber Since we're sneaker-net status I've downloaded several python packages off pypi and put them on a shared drive so that users can install them via pip. Pip automatically assumes that the C++ compiler for Windows is Microsoft Visual C++. It'll throw you a real super helpful error of: "Error: Unable to find vcvarsall.bat" if that is not the case.

Relevant stackoverflow.
http://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat/5983696#5983696

More an issue with python packaging than Cygwin. Definitely a small issue but it's been enough to keep me away from distributing source as much as possible. Especially when our sys admins will go snag binaries and install/troubleshoot them for me.

**Comment by benhoff** [comment]
@speth Ah. I was hoping it would be pretty simple. Sounds like it's a funsie instead.

**Comment by speth** [comment]
Even if you don't specifically need this anymore, I still regard this issue as unresolved. The intent is that all Cantera models should be available from any interface.
