### ISSUE TITLE
Mistake in Cantera Documentation

### ISSUE THREAD

**Issue by TheBanksy** [Cantera/cantera#294]
I think I found a mistake in the documentation in the section:

Defining Phases -> Elements and Species -> The NASA 7-Coefficient Polynomial Parameterization:

The equation for the standard enthaply the last coefficient a5 must be divided by T:
a5/T

BR

**Comment by speth** [comment]
This was already fixed in 65741171f45a76447d7f832fe545049370758b12. It's just that the online version of the documentation hasn't been updated since then.
