### ISSUE TITLE
Hombrew install is broken in master (setuptools problem?)

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#296]
I thought the Homebrew install had been tested since we switched to using setuptools (#288), but it isn't working now (see [this thread](https://groups.google.com/forum/#!topic/cantera-users/-waoQDEN7HY)). For some reason, the Python package is being installed to:

```
/usr/local/Cellar/cantera/HEAD/lib/python/site-packages
```

instead of:

```
/usr/local/Cellar/cantera/HEAD/lib/python2.7/site-packages
```

But the only part of this path that we provide is `/usr/local/Cellar/cantera/HEAD` (by setting the `PYTHONUSERBASE` environment variable). The rest is determined by setuptools. We're running the command:

```
"/usr/local/opt/python/bin/python2.7" setup2.py build --build-lib=../../build/python2 install --user --prefix="" --record=../../build/python2-installed-files.txt --single-version-externally-managed
```

which seems to work correctly on other platforms. I'm wondering if we should be using `--root=...` instead of `--user` and `PYTHONUSERBASE`.

**Comment by bryanwweber** [comment]
There was a reason I didn't use the `--root` option, but now I can't remember what it was. I think it might have been that it required substantially more manual management of where things were installed, but again, that could be a totally wrong impression.

**Comment by speth** [comment]
Well, I figured out why we don't use `--root`. At least on Linux, if you specify `--root=/foo/bar`, the Python (2.7) package will be installed in `/foo/bar/usr/local/lib/python2.7/dist-packages/cantera` which is really not what we want.
