### ISSUE TITLE
scons build generates an extra (empty) directory

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#304]
Running `scons build` at https://github.com/Cantera/cantera/commit/6cca4cf55c5b886c0f296938d1590d01ac81d86a results in the creation of a folder in the root directory, `#include/cantera/ext`. This folder is not cleaned up by `scons clean`. No other problems are present, and all tests pass. It seems to be a result of the inclusion of the `cppformat` external library: https://github.com/Cantera/cantera/blob/master/ext/SConscript#L54

**Comment by speth** [comment]
I suppose the `include/cantera/ext` and its contents should be removed by `scons clean`. There are likely to be more headers copied to this directory from other submodules as part of the build process in the future.

**Comment by bryanwweber** [comment]
Thanks Ray. The directory actually comes out as `<root>/#include/cantera/ext` and in my experience, its empty. If there's supposed to be a directory added to the regular `include` folder, that would make sense, but it should still probably be cleaned, if only to prevent un-repeatable builds.

**Comment by speth** [comment]
Oh, I didn't it was creating a directory literally named `#include`. I expected SCons to interpolate that path to mean the `include` directory in the root of the source tree, as most of the other SCons commands that deal with paths do. A fix is on the way.
