### ISSUE TITLE
Undefined boost system reference error in cathermo tests

### ISSUE THREAD

**Issue by skyreflectedinmirrors** [Cantera/cantera#310]
I'm on the latest commit (03db1d3), and there seems to be some issues still where the tests are looking for the boost system libraries instead of the newer C++ standard libraries.
I can build and install without issue, and I can do simple CONV integrations without issue either, so it seems the issues is solely in the tests

[test_log.txt](https://github.com/Cantera/cantera/files/38384/test_log.txt)
[cantera_conf.txt](https://github.com/Cantera/cantera/files/38386/cantera_conf.txt)

**Comment by speth** [comment]
The problem is that it's finding a copy of `libcantera_shared.so` not from the build tree but from an installed copy of Cantera (and I'm guessing you have `~/.local/lib` in your `LD_LIBRARY_PATH`). I think the fix will be to change the order that `LD_LIBRARY_PATH` is modified in `test/SConscript` and `test_problems/SConscript` so that `build/lib` is prepended instead of appended to `LD_LIBRARY_PATH`.

**Comment by skyreflectedinmirrors** [comment]
Yup, removing ~/.local/lib from the LD_LIBRARY_PATH fixed the issue.  All tests passed.

**Comment by speth** [comment]
Can you try the commit here: https://github.com/speth/cantera/tree/test-lib-path with your original specification of `LD_LIBRARY_PATH` to see if it fixes the issue?

**Comment by skyreflectedinmirrors** [comment]
I didn't have the exact same cantera_shared.so anymore, so I built a version of 2.2 using thread_safe=True and installed it to ~/.local/lib

Seemingly this commit fixed the C++ library issue, but I now am failing several python3 tests with errors of the form:

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/ncurtis/cantera_test/build/python3/cantera/**init**.py", line 1, in <module>
    from ._cantera import *
ImportError: No module named _cantera

[test_log.txt](https://github.com/Cantera/cantera/files/39395/test_log.txt)

**Comment by skyreflectedinmirrors** [comment]
Actually, correction. I had changed my bashrc to source the setup_cantera script.  When I change it back to export LD_LIBRARY_PATH=~/.local/lib:$LD_LIBRARY_PATH the python issues dissappear

**Comment by speth** [comment]
So the patch I made fixes this problem then, at least for this specific case?

I'm not sure what's happening in the case where you have sourced `setup_cantera`. Maybe there's also an issue with the setting of `PYTHONPATH` that we need to look into. I thought that `build/pythonX` was always being put at the head of the path when running the tests, though.

**Comment by skyreflectedinmirrors** [comment]
Yes, I think we can close this particular issue.  I also suspect $PYTHONPATH was the issue for the python tests as well
