### ISSUE TITLE
Add examples from "Defining Phases" to the documentation

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#313]
This file: https://github.com/Cantera/cantera/blob/master/doc/sphinx/cti/example-combustion.rst is presently blank. Is it left over from an old version of the documentation?

As reported on the Google Group: https://groups.google.com/d/msg/cantera-users/h0s-vJ6iELY/RgqsyqGnCQAJ

**Comment by speth** [comment]
It's left over from when I was converting the "Defining Phases" guide ([SourceForge download](http://sourceforge.net/projects/cantera/files/cantera%20documentation/Input%20Files/)) to RST. I never got around to adding the examples from that guide to the CTI guide (and it's not entirely clear to me that they belong there anyway).

**Comment by bryanwweber** [comment]
OK I changed the title to reflect what could be done to resolve the issue.

**Comment by kyleniemeyer** [comment]
This is a somewhat stale issue, but adding an example/some documentation here seems like something I can do...

**Comment by sameshl** [comment]
I am new and would like to start contributing.Can I take up this issue?

**Comment by bryanwweber** [comment]
Sure, see [the comment on the other PR](https://github.com/Cantera/cantera/pull/518#issuecomment-376164976) for where a good place to get started it.

**Comment by speth** [comment]
Given the plans to deprecate the CTI format in the near future (#423, #584), I would hold off on this.

**Comment by bryanwweber** [comment]
@speth Is the example on page 52 (55 of the PDF, copied below) already in the examples? It seems functionally the same as https://cantera.org/examples/matlab/reactor2.m.html

```matlab
gas = importPhase(’h2mech.cti’,’hydrogen_oxygen’);
nsp = nSpecies(gas);
% set the initial conditions
set(gas,’T’,1001.0,’P’,0.1*oneatm,’X’,’H2:2, O2:1, AR:4’); % create a reactor, and insert the gas
r = Reactor(gas);
t = 0;
dt = 3.0e-4;
tnow = 0;
m = 0;
for n = 1:15
   t = t + dt;
   while tnow < t
      tnow = step(r, t); % take one internal timestep m = m + 1;
      tim(m) = tnow;
      temp(m) = temperature(r);
       xm(:,m) = moleFractions(gas);
   end
end
% make plots
figure(1);
plot(tim, temp);
xlabel(’time’);
ylabel(’Temperature’);
figure(2);
plot(tim, xm);
xlabel(’time’);
ylabel(’Mole Fraction’);
legend(speciesNames(gas));
```

**Comment by speth** [comment]
@bryanwweber Yes, I agree that these examples are functionally equivalent. I think the `reactor2.m` version is a better implementation than the one from the old CTI guide, as well.

The other example in the old CTI guide is the same as [diamond_cvd.py](https://cantera.org/examples/python/surface_chemistry/diamond_cvd.py.html), using [diamond.cti](https://github.com/Cantera/cantera/blob/master/test_problems/diamondSurf/diamond.cti) as the input file. The main additions are a bit of explanatory text and the plots, which could be brought over from the PDF and added to the Python script.

There's also the discrepancy between the two versions of `diamond.cti` in the repository -- the one in `data/inputs` versus the one in `test_problems/diamondSurf`. The latter looks to have more explanatory information, so we might want to replace the one in `data/inputs`.

**Comment by agarwalrounak** [comment]
@speth Should I open a PR to replace the diamond.cti in data/inputs with the one in test_problems/diamondSurf?

**Comment by agarwalrounak** [comment]
> There's also the discrepancy between the two versions of diamond.cti in the repository -- the one in data/inputs versus the one in test_problems/diamondSurf. The latter looks to have more explanatory information, so we might want to replace the one in data/inputs.

@bryanwweber Should I open a PR to replace the diamond.cti in data/inputs with the one in test_problems/diamondSurf?

**Comment by bryanwweber** [comment]
@agarwalrounak Sure. Please also update the diamond_cvd.py example, as mentioned by @speth
