### ISSUE TITLE
call ck2cti from within Python?

### ISSUE THREAD

**Issue by nickvandewiele** [Cantera/cantera#323]
Hi,

In the [documentation](http://www.cantera.org/docs/sphinx/html/cti/input-files.html#sec-input-files) it says the `ck2cti` utility is available from the command line.

Is the same functionality also available through the python API? E.g.:

```
from cantera import ck2cti
```

I don't seem to find it...

Thanks in advance!

**Comment by speth** [comment]
Yes, it is. In fact, it is used this way in the Python test suite. See [test_convert.py](https://github.com/Cantera/cantera/blob/master/interfaces/cython/cantera/test/test_convert.py), and in particular the definition of `convertMech`.

**Comment by nickvandewiele** [comment]
great thanks!
