### ISSUE TITLE
Incorrect implementation of incompressible phase chemical potential?

### ISSUE THREAD

**Issue by toastedcrumpets** [Cantera/cantera#325]
Hi,
I was browsing the code when I noticed that the total molar density is used in the calculation of the chemical potential for incompressible phases:

**ConstDensityThermo.cpp**

```
void ConstDensityThermo::getChemPotentials(doublereal* mu) const
  {
       doublereal vdp = (pressure() - m_spthermo->refPressure())/
                         molarDensity();
       doublereal rt = temperature() * GasConstant;
       const vector_fp& g_RT = gibbs_RT();
       for (size_t k = 0; k < m_kk; k++) {
           double xx = std::max(SmallNumber, moleFraction(k));
          mu[k] = rt*(g_RT[k] + log(xx)) + vdp;
       }
   }
```

If you have the same constant density for all species then above is correct, but if each species has its own particular density then I believe that it should be the molar volume of the particular species and therefore it should appear inside the loop. If I look at mixing of two incompressible phases with two different densities do I need to use a different class or is this a bug?
Marcus

**Comment by speth** [comment]
I think the `ConstDensityThermo` class is actually more limited than just representing an incompressible equation of state. There's no notion within the class of having the density be composition dependent, or of having different densities for each species in the phase. While such a model would certainly be useful, it would take a bit of work to get the `ConstDensityThermo` class to implement that model.

**Comment by speth** [comment]
Looking at this again, I think what you're looking for is actually class `IdealSolidSolnPhase`.
