### ISSUE TITLE
cantera 2.2.1 segfault for Python FalloffReaction().falloff attribute

### ISSUE THREAD

**Issue by connie** [Cantera/cantera#326]
Didn't find this amongst the issues, so not sure if it's already fixed in the current code.  I am using the anaconda version of cantera 2.2.1 through Python.  The `falloff` attribute of a newly initialized `cantera.FalloffReaction()` object leads to the following segfault error:

```
import cantera as ct
rxn = ct.FalloffReaction()
rxn.falloff
>> Segmentation fault: 11
```

However, setting the falloff reaction as a simple falloff object eliminates this error:

```
import cantera as ct
rxn = ct.FalloffReaction()
rxn.falloff = ct.Falloff()
rxn.falloff.parameters
>> array([], dtype=float64)
```

I guess this is pretty minor but perhaps the `falloff` attribute should be initialized to the base simple `Falloff` object so as to prevent segfaults?

**Comment by speth** [comment]
Confirmed in `master` as well, and I think your suggested fix is correct.
