### ISSUE TITLE
NasaThermo::reportParams fails...

### ISSUE THREAD

**Issue by nogenmyr** [Cantera/cantera#328]
I have a code that wants to access the Nasa polynomial coefficients for the loaded species. This I do through NasaThermo::reportParams(...). In that method there is a check that some two specie index variables match (if (n != index) {..)

It appears however that the integer n above is not set by the called NasaPoly1::reportParameters(...), but it remains zero at all times. Hence, I can only get the coefficients for specie 0 (when both n and index are 0). If I simply comment the check above the code works and the correct coefficients are returned. NasaPoly1::reportParameters(...) uses the deprecated integer m_index to set n, and m_index is not set properly anymore (this used to work a year ago)

Kalle

**Comment by speth** [comment]
What version of Cantera are you using? Class `NasaThermo` was deprecated in 2.2, and has since been removed. You should just be using class `GeneralSpeciesThermo` which works with all individual species thermo types.

**Comment by nogenmyr** [comment]
I use 2.1.2, where I had no issues with this. The problem occurred when a colleague wanted to use my code, but he installed Cantera 2.2 (downloaded in say, October). I just downloaded 2.2.1, but I can see the NasaThermo class code is still there. Maybe it is not intended to be used. Thank you for pointing me to the GeneralSpeciesThermo class... I will revise my code to use that class instead!
