### ISSUE TITLE
Incorrect handling of standard (reference) pressure

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#336]
The specification of species standard state pressure is not handled correctly, both in terms of default values and accepting user-specified values. For CTI input files, the default standard state pressure is specified to be 1 bar, and this is correctly reflected in input files by the `P0` parameter in the resulting XML file, e.g. (from `gri30.xml`):

``` xml
<NASA Tmax="1000.0" Tmin="200.0" P0="100000.0">
```

However, importing the GRI 3.0 mechanism in Python shows the following:

``` python
>>> import cantera as ct
>>> gas = ct.Solution('gri30.cti')
>>> gas.reference_pressure
101325.0
>>> gas.species('H2').thermo.reference_pressure
101325.0
```

This is the result of two places where the value specified in the XML file is ignored. First, in the function `newNasaThermoFromXML`, when the value of `P0` is read, it is then immediately replaced:

``` cpp
doublereal p0 = OneAtm;
if (f0.hasAttrib("P0")) {
    p0 = fpValue(f0["P0"]);
}
if (f0.hasAttrib("Pref")) {
    p0 = fpValue(f0["Pref"]);
}
p0 = OneAtm;
```

The same occurs in `newShomateThermoFromXML`. Second, the value that is stored in the resulting `SpeciesThermoInterpType` object is usually not read. Most places where the reference pressure is accessed is by calling `GeneralSpeciesThermo::refPressure` with no arguments, which returns the value `GeneralSpeciesThermo::m_p0`, which is always 101325, instead of the value from any of the `SpeciesThermoInterpType` objects.

Changing these two cases is not difficult, but it does unfortunately change a lot of numerical outputs, which results in ~50 test failures.

I believe that using 1 bar as the standard state pressure is more consistent with most input thermo data. The NASA polynomial format does not specify the standard state pressure, but some of the original tables in this form ([McBride and Gordon](http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19940013151.pdf)) do explicitly state that they use a standard state pressure of 1 bar. 

In addition, For the 9-coefficient NASA polynomials, a comment on the `Nasa9Poly1` class states:

> The standard state is assumed to be an ideal gas at the standard pressure of 1 bar, for gases. For condensed species, the standard state is the pure crystalline or liquid substance at the standard pressure of 1 atm.

This matches the referenced report (NASA/TP-2002-211556) but I don't think there is anything that imposes the distinction between gas and condensed phases in this regard.

**Comment by bryanwweber** [comment]
According to Goutham Kukkadapu at LLNL and Mani Sarathy at KAUST (formerly at LLNL), the reference pressure for their mechanisms is 1 atm. However, there doesn't appear to be any documentation available for THERM that might answer this somewhat more definitively.

**Comment by decaluwe** [comment]
I talked to Bob Kee, and he was pretty sure that they would have used 1 atm as the reference, in Chemkin.

**Comment by speth** [comment]
I took a look at an old copy of `cklib.f` and it appears to use 1 atm as the reference pressure.

**Comment by decaluwe** [comment]
So I was just looped into an email thread instigated at someone from KIT (DETCHEM) asking about this same issue.  Which mainly raised the question: did we ever do anything about this?  I see that the issue is still open, so I would guess not, but...

**Comment by ischoegl** [comment]
The issue seems to have carried over to the new YAML interface on 2.5.0a3, i.e.
```python
In [1]: import cantera as ct

In [2]: gas = ct.Solution('gri30.yaml')

In [3]: gas.reference_pressure
Out[3]: 101325.0

In [4]: gas.species('H2').thermo.reference_pressure
Out[4]: 101325.0
```
As far as I understand, the entry
```yaml
phases:
- name: gas
  thermo: ideal-gas
  ...
  state: {T: 300.0, P: 1 atm}
```

in `gri30.yaml` should set the reference state to 300K and 1 bar?

**Comment by ischoegl** [comment]
The issue appears to have carried over to the new YAML interface (which presumably bypasses XML).
```python
In [1]: import cantera as ct

In [2]: gas = ct.Solution('gri30.yaml')

In [3]: gas.reference_pressure
Out[3]: 101325.0

In [4]: gas.species('H2').thermo.reference_pressure
Out[4]: 101325.0
```
The `gri30.yaml` file doesn't specify the reference pressure, but it should nevertheless default to 100000 Pa, correct?

**Comment by speth** [comment]
Despite what I wrote in the initial issue report, I think the fact that Chemkin and at least some mechanism authors take 1 atm as the reference pressure means that Cantera should use that to. So, this is working as expected for `gri30.yaml`. The difference is that if you create a `.yaml` file and specify a different reference pressure, it should be reflected after importing.

I had been regarding the introduction of the YAML format as the back door way of resolving this issue by having all YAML files by default not specify a reference pressure, and having the default be 1 atm. For the `xml2yaml` converter, my idea was to by default ignore the reference pressure that is written into the file (which is probably 1 bar, since that's what `ctml_writer` sets it to) unless a specific flag is specified on conversion.

**Comment by speth** [comment]
I think this issue is as resolved as it's ever going to be with the release of Cantera 2.5.

* For new YAML format mechanisms, the default reference pressure is 1 atm, and the code will use other values if they are specified.
* For input files converted directly from Chemkin format, the `reference-pressure` field is not populated, so the default of 1 atm is used.
* For input files converted from CTI using `cti2yaml`, the `standard_pressure` function can be used to set the reference pressure to values other than the default of 1 atm, although I don't think I've ever seen this used in a CTI file.
* For input files converted from XML, `ctml2yaml` ignores the value of `P0` specified in the species thermo entries. Since this value is probably an erroneous value of 1 bar that will ultimately be (incorrectly) ignored when the XML file is loaded, this behavior means that using the converted input files will give consistent results.
