### ISSUE TITLE
Adding citation to the chem input file in the data folder

### ISSUE THREAD

**Issue by jiweiqi** [Cantera/cantera#339]
Using the chemical mechanism file in the system data of Cantera is very convenient. However, it seems that some of the mechanism files are not properly commented with the associated citation. I would suggest adding citation in all of the mechanism files, at least the chemical format mechanism files.

**Comment by bryanwweber** [comment]
Please feel free to submit a pull request, if this is something you are interested in doing.

**Comment by bryanwweber** [comment]
The `h2o2.cti` file is a subset of GRI-3.0: https://groups.google.com/d/msg/cantera-users/urFfNmZ0InI/KqTb7XCiFAAJ

**Comment by bryanwweber** [comment]
@jiweiqi I don't think this issue is fixed yet

**Comment by speth** [comment]
I think this was resolved as part of #768.
