### ISSUE TITLE
Using commas in choosing species in CTI file throws Runtime Error, contradicts documentation

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#341]
In the documentation here: http://cantera.github.io/dev-docs/sphinx/html/cti/phases.html#sec-defining-species it says that commas are optional in specifying the species in a CTI file. However, the following raises an exception:

```
cti_def = """ideal_gas(name='nasa', elements='C O H N', species='nasa: CH4, H2O', options=['skip_undeclared_elements'])"""
ct.Solution(source=cti_def)
...
RuntimeError:
***********************************************************************
CanteraError thrown by importPhase:
no data for species, "CH4,"
***********************************************************************
```

while the following does not

```
cti_def = """ideal_gas(name='nasa', elements='C O H N', species='nasa: CH4 H2O', options=['skip_undeclared_elements'])"""
ct.Solution(source=cti_def)
```

Cantera version 2.3.0a2, Windows 10, Python 3.5.1.

**Comment by speth** [comment]
I expect that this originates with 919d14e7. I think the simplest solution here is to just change the documentation to indicate that the species string is space-separated.
