### ISSUE TITLE
GasTransport::fitProperties looks wrong

### ISSUE THREAD

**Issue by Marupio** [Cantera/cantera#345]
Look at variable w2.  Currently it serves no purpose, and is wasted computations, or optimized out.  Compare it with variable w, and the call to polyfit.  Specifically, look at this excerpt from GasTransport.cpp:

```
  673                 w[n] = 1.0/(spvisc[n]*spvisc[n]);
  674                 w2[n] = 1.0/(spcond[n]*spcond[n]);
  675             }
  676         }
  677         polyfit(np, DATA_PTR(tlog), DATA_PTR(spvisc),
  678                 DATA_PTR(w), degree, ndeg, 0.0, DATA_PTR(c));
  679         polyfit(np, DATA_PTR(tlog), DATA_PTR(spcond),
  680                 DATA_PTR(w), degree, ndeg, 0.0, DATA_PTR(c2));

```

w looks like it deals with viscosity, and should be used with the polyfit call for viscosity (fist one).  But w2 looks like it is for conductivity, yet it is not used in the polyfit call for conductivity... w is used.  Shouldn't line 679-680 be:

```
  679         polyfit(np, DATA_PTR(tlog), DATA_PTR(spcond),
  680                 DATA_PTR(w2), degree, ndeg, 0.0, DATA_PTR(c2));

```

I think this is a bug.

**Comment by speth** [comment]
Indeed, it does look like `w2` should be used in the second call to `polyfit`. In practice, this will have minimal effect on the calculations, as all this does is set the weighting factors for each point in the polynomial fit. This should still be fixed, though.
