### ISSUE TITLE
Set Transport model for Octane.cti

### ISSUE THREAD

**Issue by prashbang** [Cantera/cantera#353]
Hi,

I am trying to use the octane_highT.cti mechanism on python. I am trying to modify one of the adiabatic flame codes in the samples folder to use the octane mechanism but every time I run the code I get an error saying: Procedure: setTransport; Error: unknown transport model.

How can I enter a transport model for this? I tried:
gas.addTransportModel('Mix')

But I get a response saying that it an unknown transport model. It is the same when I change Mix to Multi.

Please let me know if there is any help you can provide on this.

Thank you.

**Comment by speth** [comment]
Discussion moved to https://groups.google.com/forum/#!topic/cantera-users/TlMVLan-pew
