### ISSUE TITLE
Add ability to disable/redirect warnings when loading CTI file

### ISSUE THREAD

**Issue by kyleniemeyer** [Cantera/cantera#354]
The ability to (intentionally) disable the warning messages that print when loading a mechanism file would be quite nice, when dealing with files where a lot of these are printed. This was discussed on the user forum (see https://groups.google.com/d/topic/cantera-users/SQE1j4wT5Ac/discussion and https://groups.google.com/d/topic/cantera-users/QFeZhFrfk7U/discussion), so I just wanted to raise it here. 

It seems like there are a few options:
1. add method to globally disable these warnings, e.g., from Python with

```
import cantera
cantera.disable_thermo_warnings()
...
```

This could set a global variable that disables the `writelog` calls in `src/thermo/NasaPoly2.cpp`. Alternatively, this could be a function argument in `cantera.Solution(mech.cti, thermo_warnings=False)`, rather than a global variable that's toggled.
2. Rather than disable the warnings, they could instead be directed to `stderr` vs `stdout`, such that people who (somewhat) know what they are doing can direct to a different file when running from the command line.

I'm somewhat in favor of the former, since it requires an explicit, intentional action, and (as @speth pointed out in one of the forum threads) there are situations where `stderr` output can vanish.

If others are also in favor of option 1, I can take this on.

**Comment by speth** [comment]
I think the global function is probably the best bet. There are a lot of code paths that lead to the creation of `NasaPoly2` objects, and it would be annoying to have to add an additional argument to each of them. The implementation could follow the pattern of `suppress_deprecation_warnings` (and for consistency, maybe should be called `suppress_thermo_warnings`).

I still don't understand why so many mechanisms contain data that triggers these warnings.

**Comment by kyleniemeyer** [comment]
Nice! Sorry for not getting to this myself... so if I read the additions correctly, this is done through a new function (in Python): `cantera.suppress_thermo_warnings()`?

**Comment by speth** [comment]
Yep, that's it.
