### ISSUE TITLE
Missing functions from Matlab toolbox

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#379]
The Matlab toolbox is currently missing the following functions, for which `clib` wrapper functions already exist. For some of these, just the `.m` file is missing, and for others there is no implementation of the Matlab wrapper function. 

- `Kinetics.getDeltaEnthalpy` (via `kin_getDelta`)
- `Kinetics.getDeltaEntropy` (via `kin_getDelta`)
- `Kinetics.getDeltaGibbs` (via `kin_getDelta`)
- `Kinetics.getDeltaSSEnthalpy` (via `kin_getDelta`)
- `Kinetics.getDeltaSSEntropy` (via `kin_getDelta`)
- `Kinetics.getDeltaSSGibbs` (via `kin_getDelta`)
- `Surface.setSiteDensity`
- `Surface.siteDensity`
- `Mixture.nAtoms`
- `Mixture.speciesMoles`
- `Mixture.elementMoles`
- `FlowDevice.setMaster`
- `Wall.setEmissivity`
- `Reactor.addSensitivityReaction`
- `ReactorNet.setSensitivityTolerances`
- `ReactorNet.sensitivity`
- `ReactorSurface.addSensitivityReaction`
- `Domain.clear`
- `Domain.lowerBound`
- `Domain.upperBound`
- `Domain.rtol`
- `Domain.atol`
- `StFlow.setTransport`
- `StFlow.enableSoret`
- `StFlow.pressure`
- `Sim1D.clear`
- `Sim1D.getInitialSoln`
- `Sim1D.setGridMin`
- `Sim1D.setFixedTemperature`

Implementing these methods may not be worthwhile if a full rewrite of the Matlab toolbox is going to happen at some point.

**Comment by ssun30** [comment]
An update on this issue: I have added all functions listed above. I've also noticed some other new clib wrapper functions that are not mentioned here. There is a total of 358 of them and I'm making an automated scan tool to identify the missing ones and I'll add them in the next update.

**Comment by speth** [comment]
What's currently in `clib` should not be the determining factor for what's included in the Matlab toolbox -- the `clib` interface itself is quite incomplete, in terms of features that one might want to have available in an interactive environment like Matlab. For example, there's no notion of `Species` or `Reaction` objects at all.

**Comment by speth** [comment]
As noted, this is resolved in the "experimental" Matlab toolbox.
