### ISSUE TITLE
Improve handling of un-normalized mass/mole fractions

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#390]
When setting composition using un-normalized mass fractions, the mole fractions are still normalized, and vice versa. This is problematic for the normal use case of un-normalized mass fractions of calculating Jacobians because now perturbing the mass fraction for species *k* perturbs the mole fractions for all species, resulting in an incorrect Jacobian. For instance:
```py
>>> import cantera as ct
>>> gas = ct.Solution('gri30.xml')
>>> Y = np.zeros(53)
>>> Y[0] = 0.4
>>> Y[5] = 0.6
>>> gas.set_unnormalized_mass_fractions(Y)
>>> print(gas.mole_fraction_dict())
{'H2': 0.8562761715092376, 'H2O': 0.14372382849076246}
>>> Y[5] = 0.61
>>> gas.set_unnormalized_mass_fractions(Y)
>>> print(gas.mole_fraction_dict())
{'H2': 0.8542299515251598, 'H2O': 0.14577004847484037}
```

Instead, what we would like is for only the mole fraction of species *k* to change.

@decaluwe has suggested the following algorithm:

> If I set Y_k to something where sum(Y_k) =/= 1, then X_k should be calculated as Rho*Y_k/(C*W_k), where Rho is the mass density (kg/m3), C is the molar density (kmol/m3), and W_k is the molar mass of species k (kg/kmol). A similar equation could be derived for the opposite (Y_k based on a non-normalized X_k).

Originally discussed here: https://groups.google.com/forum/#!topic/cantera-users/qEgtxkn9P6o

**Comment by ischoegl** [comment]
I had a look at this, and it appears somewhat murky (unless I am overlooking something). In the current implementation, C uses $\rho/W_{mean}$, where $W_{mean}$ (aka `m_mmw`) implicitly assumes that the mass fractions sum up to unity, i.e.
```C++
 m_mmw = dot(x, x + m_kk, m_molwts.begin());
``` 
in `setMoleFractions_NoNorm` (or the less straight-forward version in `setMassFractions_NoNorm`)

The suggested solution would require that C is known, with $C=\rho/W_{mean}$. With density being straight forward, this still requires knowledge of $W_{mean}$, which is impossible to calculate if constituents are partially unknown (i.e. it's a circular problem). 

I do not see an obvious way around assuming that fractions sum up sufficiently _close to_ unity. For analytical Jacobians, there is obviously no issue.

For numerical Jacobians, a workable solution would be to _not_ update `m_mmw`, as changes (perturbations) are presumably small. Imho, the only way to implement this is by explicitly telling the function that the call involves a small perturbation (e.g. a `perturbation=true` flag) to indicate that `m_mmw` (and other properties) should not be updated (which technically leaves the solution in a dubious thermodynamic state).

**Comment by speth** [comment]
Having looked back to this multiple times and not having come up with much in the way of a solution, I think it's time to close this issue. I agree with @ischoegl's assessment that there isn't a general solution to this, and if you wanted to resolve this for case of perturbations about a consistent (sum == 1) mass fraction vector, you'd need to implement special handling.

But at this point, there's been more work towards analytical Jacobians which would not require such a feature, and some of the recent work that @anthony-walker has been doing may end up showing that it's preferable to just use the number of moles of each species in a reactor as the state variables, which I think would also resolve any issues with Jacobian consistency even when sticking with a finite difference implementation.
