### ISSUE TITLE
Picture of Dave Goodwin on Wiki gone

### ISSUE THREAD

**Issue by kyleniemeyer** [Cantera/cantera#391]
Hey @speth or @hkmoffat, I just noticed that on the [page](https://github.com/Cantera/cantera/wiki/Dave-Goodwin) in memoriam for Dave Goodwin on the wiki, the picture doesn't seem to be resolving anymore. Perhaps the link can be replaced with a more reliable one, maybe in the repo itself?

**Comment by speth** [comment]
Fixed.
