### ISSUE TITLE
ck2cti raises TypeError for a transport database

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#403]
### Cantera version
2.3.0b1 (730107c)
### Operating System
Win 10
### Python/MATLAB version
Python 3.5
### Expected Behavior
Conversion of the CK file to CTI
### Actual Behavior
A `TypeError` is raised:
```
Traceback (most recent call last):
  File "C:\Users\bww09001\AppData\Local\Continuum\Miniconda3\Scripts\ck2cti-script.py", line 5, in <module>
    sys.exit(cantera.ck2cti.script_entry_point())
  File "C:\Users\bww09001\AppData\Local\Continuum\Miniconda3\lib\site-packages\cantera\ck2cti.py", line 2294, in script_entry_point
    main(sys.argv[1:])
  File "C:\Users\bww09001\AppData\Local\Continuum\Miniconda3\lib\site-packages\cantera\ck2cti.py", line 2267, in main
    permissive=permissive)
  File "C:\Users\bww09001\AppData\Local\Continuum\Miniconda3\lib\site-packages\cantera\ck2cti.py", line 2199, in convertMech
    self.parseTransportData(lines, transportFile, 1)
  File "C:\Users\bww09001\AppData\Local\Continuum\Miniconda3\lib\site-packages\cantera\ck2cti.py", line 1947, in parseTransportData
    self.speciesDict[speciesName].transport = TransportData(*data)
TypeError: __init__() takes from 8 to 9 positional arguments but 10 were given
```
### Steps to reproduce
1. `ck2cti --input=MB_mech_GAIL.txt --thermo=MB_therm_GAIL.txt --transport=MB_transport_GAIL.txt --permissive`

[MB_mech_GAIL.txt](https://github.com/Cantera/cantera/files/631500/MB_mech_GAIL.txt)
[MB_therm_GAIL.txt](https://github.com/Cantera/cantera/files/631501/MB_therm_GAIL.txt)
[MB_transport_GAIL.txt](https://github.com/Cantera/cantera/files/631499/MB_transport_GAIL.txt)

See also: https://groups.google.com/forum/#!topic/cantera-users/jj_WmGbKHIs

**Comment by santoshshanbhogue** [comment]
Minor comment - the files uploaded have .txt extensions, but the command references .dat

But yeah, there is a problem, even on a Mac and py2.7

**Comment by bryanwweber** [comment]
@santoshshanbhogue Thanks, I fixed the command. GitHub only allows uploading TXT extensions, not DAT. Thanks for reproducing.

**Comment by santoshshanbhogue** [comment]
Not a bug in ck2cti. There is a bad entry in the transport file:
`SC2H4COC2H3        2   476.7       5.714     2.7 0.    0         1.0 !   WJP`
which, if corrected to
`SC2H4COC2H3        2   476.7       5.714     2.7        0         1.0 !   WJP`

the script runs fine with all tests passed. 

Here are the revised files: 

[MB_mech_GAIL.txt](https://github.com/Cantera/cantera/files/632957/MB_mech_GAIL.txt)
[MB_therm_GAIL.txt](https://github.com/Cantera/cantera/files/632958/MB_therm_GAIL.txt)
[MB_transport_GAIL.txt](https://github.com/Cantera/cantera/files/632959/MB_transport_GAIL.txt)

**Comment by santoshshanbhogue** [comment]
Here are the revised files: 

[MB_mech_GAIL.txt](https://github.com/Cantera/cantera/files/632957/MB_mech_GAIL.txt)
[MB_therm_GAIL.txt](https://github.com/Cantera/cantera/files/632958/MB_therm_GAIL.txt)
[MB_transport_GAIL.txt](https://github.com/Cantera/cantera/files/632959/MB_transport_GAIL.txt)

**Comment by speth** [comment]
I'm not surprised there's a bug in the input file, but we should certainly be able to generate a more informative error message in this situation.

**Comment by santoshshanbhogue** [comment]
@speth #405 provides more info to the user to debug.
