### ISSUE TITLE
Check reactions for balance of surface sites

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#412]
- Cantera version: b20c0c6
- Operating System: all
- Python/MATLAB version: all

### Expected Behavior
A reaction such as:
```
CH4(s) + 2 O2 => CO2 + 2 H2O
```
where `CH4(s)` is a surface species and all others are gas phase should be identified as problematic because it does not balance the number of surface sites.

### Actual Behavior
Incorrect rates are computed in reactor calculations -- if the only surface species are `CH4(s)` and a species representing open sites, then the coverages will not change.

### Proposed resolution
When validating surface reactions, require that `sum(species.size)` over the surface species is the same for the reactants and products.

Originally reported at https://groups.google.com/forum/#!topic/cantera-users/wlww4-RUC_E

**Comment by santoshshanbhogue** [comment]
Fundamentally, does creation of a reaction even check for stoichiometry? I mean, I can execute this line in the dev-version with Py2.7 without any error:

`r = ct.Reaction.fromCti(''' reaction('HO2 + O <=> H2O + O2',[1.0, 2, 3.4E+5] )''')`

Not that there is an imbalance of H on both sides

**Comment by santoshshanbhogue** [comment]
Let me know if you'd like just the open-sites issue to be checked for or stoichiometry in general

**Comment by santoshshanbhogue** [comment]
Ok, Cantera does when a solution object is created...

**Comment by bryanwweber** [comment]
I think the reason the first one is valid is because there is no atomic composition information associated with the species in a `Reaction`, that's stored in the `Species`, which has the thermo data.

**Comment by santoshshanbhogue** [comment]
Yup, but why do this much later in `Kinetics` and not when the `Reaction` object is created. This way depending on what the reaction type is, one can run a battery of tests during immediately upon creation of an object (elemental balance for all rxns, site balance for surface, charge balance for electrochem., etc) ?

**Comment by speth** [comment]
As Bryan says, when you create a Reaction object, all it knows is the name of the species, not its composition, or any other data that is contained in a Species object. So these checks are only possible at the point where the Reaction is added to a Kinetics object.
