### ISSUE TITLE
Cantera 2.3 compilation issue on OpenSuse 13.2

### ISSUE THREAD

**Issue by wandadars** [Cantera/cantera#414]
### Cantera version
2.3
### Operating System
LSB Version:	n/a
Distributor ID:	openSUSE project
Description:	openSUSE 13.2 (Harlequin) (x86_64)
Release:	13.2
Codename:	Harlequin

### Python/MATLAB version
Python - 2.7.8
Matlab - none

### Expected Behavior
Compile when running 'scons build'

### Actual Behavior
Crash during compilation. Full text leading up to failure shown below.
```
INFO: SCons is using the following Python interpreter: /usr/bin/python

scons: warning: EnsureSConsVersion is ignored for development version
File "/home/neal/codes/cantera/cantera-2.3/cantera/site_scons/site_tools/gch.py", line 53, in <module>
Configuration variables read from 'cantera.conf' and command line:

Checking for C++ header file cmath... yes
Checking for C++ header file fmt/ostream.h... no
INFO: Using private installation of fmt library.
Checking for C++ header file gtest/gtest.h... no
Checking for C++ header file Eigen/Dense... no
Checking for C header file sys/times.h... yes
Checking for C header file unistd.h... yes
Checking whether __GLIBCXX__ is declared... yes
Checking whether _LIBCPP_VERSION is declared... no
INFO: Found Boost version '1_54'
Checking for CVodeCreate(CV_BDF, CV_NEWTON) in C++ library sundials_cvodes... no
Checking for double x; log(x) in C library None... no
INFO: Using private installation of Sundials version 2.6.
INFO: Using 'gfortran' to build the Fortran 90 interface
INFO: Using Cython version 0.21.
WARNING: Cython not found or incompatible version: Found 0.21 but 0.23 or newer is required.
INFO: Building the full Python package for Python 2.7
WARNING: Couldn't find the 3to2 package. Python 2 examples will not work correctly.
CalledProcessError: Command '['python3', '-c', 'from distutils.sysconfig import *\nimport site\nimport numpy\nprint(get_python_version())\ntry:\n    print(site.getusersitepackages())\nexcept AttributeError:\n    print(site.USER_SITE)']' returned non-zero exit status 1:
  File "/home/neal/codes/cantera/cantera-2.3/cantera/SConstruct", line 1146:
    info = getCommandOutput(env['python3_cmd'], '-c', script)
  File "/home/neal/codes/cantera/cantera-2.3/cantera/site_scons/buildutils.py", line 603:
    data = subprocess.check_output([cmd] + list(args), stderr=subprocess.STDOUT, env=environ)
  File "/usr/lib64/python2.7/subprocess.py", line 573:
    raise CalledProcessError(retcode, cmd, output=output)
```

### Steps to reproduce
1. git clone https://github.com/Cantera/cantera.git
2. scons build
3.

**Comment by bryanwweber** [comment]
Can you please add the `VERBOSE` option to the build (`scons build VERBOSE=y`)? I suspect that you don't have a Python 3 installed anywhere and its crashing, but it shouldn't do that...

**Comment by bryanwweber** [comment]
@wandadars Do you have any updates here?

**Comment by bryanwweber** [comment]
I can't reproduce this on OpenSUSE Leap 42.2. I'll try again on 13.2.

**Comment by bryanwweber** [comment]
I can't reproduce this on 13.2 either. @wandadars Can you please provide some more information?

**Comment by bryanwweber** [comment]
OK I can finally reproduce this. The problem is that you have Python 3 installed, but you're missing numpy for Python 3. This causes an ImportError that's not being handled properly. The same error occurs for the Python 2 interface if Numpy isn't installed there either. Thank you for the report, I'll put together a fix.

**Comment by wandadars** [comment]
Thank you for looking into this Bryan. I haven't had much time to run that check. I can say that I do have python 3 installed, so it looks like the issue that you discovered is probably the issue that I'm seeing.
