### ISSUE TITLE
Deprecation of vecotr_fp

### ISSUE THREAD

**Issue by haowu80s** [Cantera/cantera#426]
vector_fp was originally written by Goodwin as a light-weight version of STL vector to resolve the iterator issue at that time. Now that vector<double> is used through out the code, there seems to be little point in keeping the vector_fp convention.

**Comment by speth** [comment]
I'm not sure what "the iterator issue" is, but `vector_fp` is a lot fewer characters than `std::vector<double>`. On top of that, I am expecting that many instances where it is currently used may be replaced by types from Eigen or a template parameter for the sake of automatic differentiation support, so I don't think this change would be worth the code churn even if it were desirable.

**Comment by haowu80s** [comment]
By "the iterator issue", I'm referring to

> Until recently, Cantera used the Standard Template Library vector<double> class for this purpose. It was convenient to use, and method begin() returned a double* pointer to the underlying contiguous data array. However, some recent implementations of vector<double> define method begin() to return an iterator of type vector<double>::iterator which is not convertible into a double* pointer. (Method begin() returns an iterator in all implementations, but in older ones vector<double>::iterator is only a typedef for double*.

from 4.1 of http://www.aresinstitute.org/Cantera/cantera-cxx.pdf. Points taken, anyway.

On a different note, when do you expect to introduce the Auto Diff module of eigen into cantera?

**Comment by speth** [comment]
Just to be clear, many, many things in that 15 year old document are out of date and I would not recommend consulting it for any reason other than historical interest. `vector_fp` has been a typedef for `std::vector<double>` for quite some time now.
