### ISSUE TITLE
fmt library not recognized

### ISSUE THREAD

**Issue by gpavanb-old** [Cantera/cantera#434]
### Cantera version
2.3.0

### Operating System
Linux

### Python/MATLAB version
2.7.10

### Expected Behavior
scons should recognize fmt

### Actual Behavior
ERROR: fmt is missing. Install source in ext/fmt.
See 'config.log' for details.

I've tried using both fmt-3.0.0 and fmt-3.0.1, but both are giving that issue despite having them in the ext/ directory. The config.log is complaining about ostream.h, which is clearly in the ext/fmt/ path as well.

### Steps to reproduce
1. Download Cantera repository
2. Run scons

**Comment by speth** [comment]
Please provide:
- (a) the complete output of `scons build VERBOSE=y`
- (b) The directory listing for `ext/fmt`, i.e. by running `ls -lR ext/fmt`

**Comment by gpavanb-old** [comment]
This was corrected by using system_fmt=n flag explicitly. Nothing wrong with Cantera per se. These are not displayed in the scons --help and had to go through the scons file to figure it out.
