### ISSUE TITLE
Copy construtor and assignment operator for Kinetics objects

### ISSUE THREAD

**Issue by haowu80s** [Cantera/cantera#440]
### Cantera version
2.40a

###
In the 2.40a version of cantera, the Kinetics objects are designed to be not copyable or assignable. 

I  understand that copy construtor and assignment operator in the older versions are quite cumbersome. But why prohibit the use of default copy construtor and assignment operator? 

They are not really problematic for Kinetics objects to begin with. And the lack of them makes it impossible to use Kinetics objects with STL containers, e.g. `vector<Kinetics>` would be broken as it cannot be resized.

**Comment by speth** [comment]
The default copy constructor would leave you with multiple `Kinetics` objects pointing to the same `ThermoPhase` objects, which I suspect is a recipe for disaster.

The copy-free alternative to `vector<Kinetics>` is `vector<unique_ptr<Kinetics>>`.

(I think this kind of question may be better suited to the Users' Group)

**Comment by haowu80s** [comment]
I would argue that multiple `Kinetics` objects pointing to the same `ThermoPhase` objects is actually the intended behavior for using a copy constructor. 

Anyway, I agree that Users' Group is probably more suitable for this question. I'll post discussion there.
