### ISSUE TITLE
scons test failed for 2 tests

### ISSUE THREAD

**Issue by xansc** [Cantera/cantera#445]
### Actual Behavior

*****************************
***    Testing Summary    ***
*****************************

Tests passed: 1193
Up-to-date tests skipped: 0
Tests failed: 2
Failed tests:
    - python2:test_thermo.TestSolutionArray.test_slicing_ndim
    - python2:test_thermo.TestSolutionArray.test_slicing_onedim

*****************************
scons: *** [test_results] One or more tests failed.
scons: building terminated because of errors.

Best regards
Andre

**Comment by bryanwweber** [comment]
Andre, How did you compile Cantera? How did you download the Cantera source code? Have the Cantera tests passed on this computer before? What versions of all the dependencies are you using (NumPy, cython, etc)? How did you install those dependencies? Please provide more detail so we can help.

**Comment by speth** [comment]
I think I saw these tests fail once before, and it was an issue with a specific version of numpy. So as Bryan suggests, providing that information, and the actual output from the failing tests would help.

**Comment by xansc** [comment]
Good morning everybody

I ran the test again 


======================================================================
FAIL: test_slicing_ndim (cantera.test.test_thermo.TestSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andre/Math/cantera/build/python2/cantera/test/test_thermo.py", line 1334, in test_slicing_ndim
    states.TP = 900, None
  File "/home/andre/Math/cantera/build/python2/cantera/composite.py", line 673, in setter
    A, B, _ = np.broadcast_arrays(AB[0], AB[1], self._output_dummy)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/stride_tricks.py", line 119, in broadcast_arrays
    zip(args, shapes, strides)]
  File "/usr/lib64/python2.7/site-packages/numpy/lib/stride_tricks.py", line 32, in as_strided
    array.dtype = x.dtype
TypeError: Cannot change data-type for object array.

======================================================================
FAIL: test_slicing_onedim (cantera.test.test_thermo.TestSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andre/Math/cantera/build/python2/cantera/test/test_thermo.py", line 1307, in test_slicing_onedim
    states.TD = 900, None
  File "/home/andre/Math/cantera/build/python2/cantera/composite.py", line 673, in setter
    A, B, _ = np.broadcast_arrays(AB[0], AB[1], self._output_dummy)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/stride_tricks.py", line 119, in broadcast_arrays
    zip(args, shapes, strides)]
  File "/usr/lib64/python2.7/site-packages/numpy/lib/stride_tricks.py", line 32, in as_strided
    array.dtype = x.dtype
TypeError: Cannot change data-type for object array.

----------------------------------------------------------------------
Ran 507 tests in 39.324s

FAILED (failures=2, expected failures=3)
printReport(["test_results"], [])

*****************************
***    Testing Summary    ***
*****************************

Tests passed: 502
Up-to-date tests skipped: 46
Tests failed: 2
Failed tests:
    - python2:test_thermo.TestSolutionArray.test_slicing_ndim
    - python2:test_thermo.TestSolutionArray.test_slicing_onedim

*****************************
scons: *** [test_results] One or more tests failed.
scons: building terminated because of errors.

I have done a git clone to download the source. After installing the prerequisites, it was a bit of pain, I have done scons build without errors, although the config.log indicates some configurations were not done. Afterwards I ran scons test.

numpy version is 1.8.0-3.5

Thanks for your assistance
Andre

**Comment by xansc** [comment]
and cython version is 0.23.4

**Comment by bryanwweber** [comment]
Can you try to upgrade the version of NumPy and see if it fixes it?

**Comment by xansc** [comment]
I will try it! What version is necessary?

**Comment by bryanwweber** [comment]
The most recent version is 1.12. Try 1.9 or higher.

**Comment by xansc** [comment]
*****************************
***    Testing Summary    ***
*****************************

Tests passed: 1195
Up-to-date tests skipped: 0
Tests failed: 0

*****************************
scons: done building targets.

I've done it with 1.12 from science repository. Also sudo scons install worked fine.

Thanks again for your help!

Best regards
André

**Comment by speth** [comment]
Yes, I think Numpy 1.8 was the version I had trouble with before. Interestingly, this works fine with numpy 1.6.1, which is what the Linux Travis build is using, so I guess this was a regression that was fixed in 1.9.

**Comment by bryanwweber** [comment]
Let's leave this open as a reminder to update the docs then.

**Comment by xansc** [comment]
Should I "Close and comment" this issue now?

**Comment by speth** [comment]
What's the proposed action here? I would be content to just set the required Numpy version to 1.9, since we know that there are problems with at least some earlier versions.

**Comment by bryanwweber** [comment]
We might need to do something about this for our Travis builds, as they're rolling out Trusty Tahr starting today, and the most recent build of NumPy available in the PPAs is 1.8.2 (https://launchpad.net/ubuntu/trusty/+source/python-numpy). Since we'll no longer be testing with older versions of NumPy, I agree with setting the minimum version to 1.9 is a good solution.

This has to be updated in the docs and in the conda recipe.

**Comment by speth** [comment]
I did some more testing of this, using conda, and it seems that numpy 1.8.0 is the *only* version that exhibits this problem. Upgrading to even 1.8.1 is sufficient to fix it. So we can avoid this bug and preserve support for Trusty by just setting the minimum to 1.8.1.
