### ISSUE TITLE
Species Thermal Conductivity 

### ISSUE THREAD

**Issue by ardhendubarman** [Cantera/cantera#448]
Hello all,

I am trying to access the transport properties in a 1D flame simulation (GRI3.0 Mechanism), specifically I would like to change species diffusivities and thermal conductivity. I am using Cantera 2.3.0 and Python. From my understanding reading the transport properties documentation, I can only compute them. I have also identified sections in the source code where the calculation has been done.  
Do you see a way accessing the internally calculated species transport properties such as species thermal conductivity? 

Thanks a lot in advance. The specific problem is to calculate the species thermal conductivity for a 1D flame simulation.
I have also posted about it to google cantera forum

**Comment by bryanwweber** [comment]
I think this discussion belongs on Google Groups for now... if it turns into something we need to fix in the code, we can re-open this issue.
