### ISSUE TITLE
transport model calculated irrespective of Solution flag

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#457]
### Cantera version
2.3.0a
### Operating System
linux (Fedora 24)
### Python/MATLAB version
2.7.13 (anaconda2-4.3.0)
### Expected Behavior
providing the transportmodel=None flag (i.e. cantera.Solution(<xmlfile>,transportmodel=None) per documentation http://www.cantera.org/docs/sphinx/html/cython/importing.html) should load an xml file containing transport data in the same time as an xml file created without transport data, as the initialization of the Transport object is skipped.
### Actual Behavior
Transport model calculations appear to be performed irrespective of the flag status. Tests with one large mechanism (2840 species, 13254 reactions) yield the following execution times for no flag provided and transport model=None, respectively (using a timeit timer):
* xml compiled with transport data: 210.6s / 209.7s (!!)
* xml compiled without transport data: 1.12s / 0.72s
For AramcoMech 2.0 (http://www.nuigalway.ie/c3/aramco2/frontmatter.html, 493 spcs, 2716 rxns), the numbers are:
* xml compiled with transport data: 6.53s / 6.85s 
* xml compiled without transport data: 0.24s / 0.14s

### Steps to reproduce
1. create cti/xml files with and without transport (via ck2cti / ctml_writer).
2. load chemistry with and without transportmodel=None flag
3. workaround is to keep two copies of the model;

**Comment by speth** [comment]
You're missing an underscore in `transport_model=None`.
