### ISSUE TITLE
Cantera Docker?

### ISSUE THREAD

**Issue by wandadars** [Cantera/cantera#472]
Would Cantera benefit at all from having a public Docker image available to users? That would sidestep any compilation issues that people might have. Just run docker and run a script and boom a terminal pops up with an image that has Cantera compiled. I'm just thinking purely about improving user access.

**Comment by bryanwweber** [comment]
@wandadars Please feel free to create an image and upload it to Hub, if you would like; I think we would just ask that you don't imply that is "officially" supported, which is to say that questions should be directed to you and/or you will monitor the Google group closely to pick up any issues posted there. Speaking for myself, I don't have any particular desire to maintain something like that at this time, but there's no saying what the future holds 😄

**Comment by bryanwweber** [comment]
@wandadars I'm going to close this issue, but please feel free to post a link to your Docker image here or on the Google Group, if you'd like
