### ISSUE TITLE
Question regarding the reaction_path cantera

### ISSUE THREAD

**Issue by BinWgatech** [Cantera/cantera#484]
### Python 2.7.13

Hi All,

I'm now trying to figure out the reaction pathway of reaction. Since the reaction I'm interested in is at room temperature and pressure, so I just modified the reaction_path.py from Cantera, changing the original reactor into a constant P and T reactor. And I'm looking for the equilibrium products of that reaction, so I set the time of the reactor 30s. However, as I run the program even though I could get a pathway diagram but it looks very weird, the C (carbon) not even starting from fuel (C2H4 in my case). But if I change the time to like 10s, the diagram looks more reasonable.

So I was wondering if anyone could tell me why the 30s case looks weird. I'm new to cantera and I would really appreciate if anyone could help me. Thanks a lot!
![10s reactor](https://user-images.githubusercontent.com/33647098/32791954-32416ecc-c930-11e7-9633-122fd8ae025c.png)
![30s reactor](https://user-images.githubusercontent.com/33647098/32791955-32e90f74-c930-11e7-8b73-9878973530f7.png)
<img width="694" alt="2017-11-14 11 36 38" src="https://user-images.githubusercontent.com/33647098/32791968-39a2498e-c930-11e7-88e0-95704530b9cb.png">

**Comment by bryanwweber** [comment]
Hi! Welcome to Cantera. This issues list is generally for bugs or changes that are requested to Cantera, not so much a discussion forum or question list. Can you please post this question over on our Google Group: https://groups.google.com/forum/#!forum/cantera-users

When you make that post, please include a copy of the Python script (not an image; search engines cannot index the text in an image, so no one else can find your post, and blind users cannot read it at all), a copy of the CTI file you're using, what OS you're on, and what version of Cantera you're using.

Thank you!

**Comment by BinWgatech** [comment]
Bryan, thanks a lot I will do that!

**Comment by bryanwweber** [comment]
See https://groups.google.com/forum/#!topic/cantera-users/xmG1_woIAHg
