### ISSUE TITLE
Pull Request into Homebrew/core from Homebrew/science failing w/ fmt dependency

### ISSUE THREAD

**Issue by alishahm** [Cantera/cantera#494]
### Cantera version
v.2.3.0

### Operating System
macOS High Sierra

### Python/MATLAB version
2.7

### Expected Behavior
brew install cantera to install.

### Actual Behavior
Fails because of deprecation of homebrew/science. Pull request initiated to move into homebrew/core here: https://github.com/Homebrew/homebrew-core/pull/22720.
Tests failing because of fmt-4.0.0 vs. fmt-3.0.2. See https://github.com/Cantera/cantera/issues/470.

Seems like a fixed issue if installing using --HEAD, so waiting for a patch or version update release. Anything that can be done here, like maybe a minor release? 

### Steps to reproduce
1. brew install cantera

**Comment by brandonloong** [comment]
Are there any updates on this installation issue?

**Comment by speth** [comment]
The developers of Homebrew are not interested in supporting our use case (see https://github.com/Homebrew/homebrew-core/pull/31308), so we've dropped support for it. The best way to install Cantera on macOS ([instructions here](https://cantera.org/install/macos-install.html)) is to use conda for the Python package and the new `.pkg` installer for the Matlab toolbox.
