### ISSUE TITLE
Update/Fix the MacPorts Recipe

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#496]
### Cantera version
2.3
### Operating System
macOS, MacPorts installation option
### Python/MATLAB version
N/A
### Expected Behavior
Proper installation
### Actual Behavior
Failed installation, see https://groups.google.com/d/msg/cantera-users/rPdKLpC2uys/vIk4jDHTCAAJ for a thread with links

Also as discussed at KinCodeCon 2017

**Comment by ischoegl** [comment]
This has been open for 4 years at this point. Are there any plans to fix this or can it be assumed that other avenues (`pip`, `conda`, etc.) have superseded this approach?

**Comment by bryanwweber** [comment]
I think it's fair to say that this is superseded by other approaches. Closing!
