### ISSUE TITLE
Homebrew installation failed due to "No formulae found in taps"

### ISSUE THREAD

**Issue by xianshiuci** [Cantera/cantera#498]
### Cantera version
2.3.0

### Operating System
macOS High Sierra

### Python/MATLAB version
MATLAB 2017b

### Actual Behavior
$ brew install cantera --HEAD --with-matlab=/Applications/MATLAB_R2017b.app/

Error: No available formula with the name "cantera" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

It seems that Cantera was not migrated to the homebrew/core from homebrew/science (which is deprecated). In that case, isn't it impossible to install the Matlab version on Mac? Will this be fixed soon?

**Comment by brandonloong** [comment]
I'm also having this error. Does there happen to be a fix in the works so that the Matlab installation can be enabled?

**Comment by speth** [comment]
This is effectively a duplicate of #494.
