### ISSUE TITLE
[Burner_flame] - How to choose an adequate value for mdot?

### ISSUE THREAD

**Issue by fmquintino** [Cantera/cantera#504]
I am experiencing problems when it comes to set the value of mdot in a burner stabilizes frame in CANTERA. 

I have been choosing it based on the laminar burning velocity obtained with a freely propagating routine, but with the simply refines the grid indefinitely. I was able to achieve a solution with a very small mdot, but this is not consistent with the value it should have.

Can anybody help?

**Comment by speth** [comment]
The burner-stabilized flame has no steady-state solution if the inlet velocity is greater than the laminar burning velocity. If you have further questions on this, I would suggest that the Users' Group on Google Groups would be the appropriate place to discuss them.

**Comment by fmquintino** [comment]
What about very low inlet velocities? I tested an inlet velocity about 10 times smaller than it should be but the solver was able to achieve a steady-state solution.
