### ISSUE TITLE
README.rst has broken hyperlink

### ISSUE THREAD

**Issue by wandadars** [Cantera/cantera#505]
### Cantera version 
2.3

### Operating System 
Any

### Python/MATLAB version 
Any

### Expected Behavior 
Click a link to see compilation instructions

### Actual Behavior 
404

### Steps to reproduce
1. Open README.rst
2. Go to "Installation" Section
3. Click "Compilation Instructions"

I think the link should probably be: http://cantera.github.io/docs/sphinx/html/compiling/index.html

**Comment by bryanwweber** [comment]
Thanks! Can you make a PR to fix it?

**Comment by wandadars** [comment]
@bryanwweber  I have made a PR.
