### ISSUE TITLE
error fmt is missing. Install source in ext/fmt

### ISSUE THREAD

**Issue by Blue-Beetle-13** [Cantera/cantera#512]
### Cantera version
2.3.0
### Operating System
Linux Mint 18.3
### Python/MATLAB version
Python 2.7, Matlab R2017b
### Expected Behavior
Actual successful build of Cantera 2.3
### Actual Behavior
Error on scons build:
Checking for C++ header file fmt/ostream.h. . . no
INFO: Using private installation of fmt library.
ERROR: fmt is missing. Install source in ext/fmt.
See 'config.log' for details.
### Steps to reproduce
1. Follow directions for installing cantera explicitly, as listed in 
http://cantera.org/docs/sphinx/html/compiling/installation-reqs.html#linux
http://cantera.org/docs/sphinx/html/compiling/configure-build.html#compile-cantera-test
2. scons build
3. get frustrated

**Comment by Blue-Beetle-13** [comment]
Cantera 2.2.0 compiled without error.
Will try an install on a virtual machine instance.

**Comment by Blue-Beetle-13** [comment]
While Cantera 2.2.0 compiled and installed, the software did not work. Running scons test showed all tests passed until Matlab test which failed. Listed that 3to2 was missing which would cause errors. Installed 3to2, still failed on Matlab test. Said that Cython for Python 3 was ver 0.0.0. Installed cython using pip3 and now listed Cython for python 3 as 0.27.3. Test fails. 

1. Thank you for trying to make software. I understand that it is a hobby and not your job. 
2. Following the install directions on the Cantera website I have not been successful in installing Cantera for linux or Mac OS. 
3. I have wasted three months trying to solve installation errors and now my two OS's are profuse with various program packages that may interfere with reinstalls. Please, we must systematize our installation procedure so that it will work universally. This random piecemeal approach at making an installation is poor at best. 
4. If anyone successfully installed Cantera with Debian Linux please say so that I may at least have a little hope.

**Comment by wandadars** [comment]
That's odd. It installs without issue on OpenSuse 13.2.

**Comment by wandadars** [comment]
Could be related to closed issue #470. See last reply in the thread.

**Comment by decaluwe** [comment]
Installation stuff is mostly a mystery to me, but I can see how this would be frustrating.  Installation used to be a total headache for me, as well.  A few general questions: 
1. Am I correct that you just opened this issue yesterday?  
2. Did you post a question to the User's group, or reach out in any other way, before "wasting three months?" (this is an honest question, the difference in email names vs. github handles makes it tough to know for sure, and like I said, installation issues are mostly over my head, so those posts barely register, for me).
3. Lastly, Cantera is made up of its users, and contributions are from users (this is how I got involved with contributing to the code; I was a user for 7 years, then wanted to add some capabilities that weren't present for high-pressure flows).  If there is a better way to do something, please contribute to the code!

**Comment by bryanwweber** [comment]
@Blue-Beetle-13 Hi! Unfortunately, it's really hard for us to help you with this kind of error report. You need to include much more detail. I'll try to be more specific.

1. From your first post, it seems like you might not have Git installed properly. How did you get the source code onto your computer? We say at the very top of the Installation Prerequisites instructions "To download the source code, installing `git` is highly recommended."
2. It looks like you're using Linux Mint; you should be aware that we have an Ubuntu PPA for Cantera, so installation on Debian-based OS will work.
3. Cantera 2.2.0 is no longer supported, so I'm not surprised that it didn't work. You should focus on building Cantera 2.3.0
4. What are the contents of your cantera.conf file when you try to build Cantera 2.3.0?
5. I'm not sure what you mean by systematic procedure, as I find that documentation fairly systematic. Is there something in particular you would like to improve? Where did you get confused? What instructions did you follow/not follow?
6. If you're building Cantera for Python 2.7, why did you install Cython for Python 3?
7. What is the output of the tests that fail?

**Comment by Blue-Beetle-13** [comment]
Hey Bryan, 
You are a warrior, I really appreciate how active you are in chasing down solutions with people who have problems. I have been scouring the Google group when I can (I live in China so difficult) and here on github. I will try to answer your points as best I can. 
1. I originally tried to download the Cantera source code from github, using the latest version. Then, seeing the recommendation I (assume) that I cleaned the Cantera scraps, installed git and followed the recommended procedure. When I try to compile Cantera 2.3.0 I get an error: "fmt is missing. Install source in ext/fmt." 
2. I am using Mint and installed Cantera from the repository through aptitude as well. However, I am trying to use Matlab to interface with Cantera, this was not successful using any procedure yet attempted. 
3. Cantera 2.2.0 compiled correctly, without throwing the missing fmt error. However, when I tried the matlab samples there was an error in converting between xml and cti. 
4. Sorry, I deleted the Cantera files on my Mint instance, but the only commands that I added were to set the Matlab path and the define the installation folder using the prefix command.
5. By systematic I mean that I am a complete idiot and I need a linear pathway through the installation. For example, looking at the installation procedure it appears that Conda is the way to go, during that procedure I install Cantera to a Conda Environment(?) and then I use Ipython in the Conda Environment that I have created(?) to setup the Cantera model. However, this doesn't let me use Matlab, so I continue down to the Ubuntu section. When I install Cantera from the Speth repository it says that this does not include packages for use with Matlab. I get confused with the difference between the various python installations, and apparently so does my system which tries to use an outdated version of pip from the matlab install (8.x.x) instead of the updated one (9.x.x) and throws an error on installing ipython or ipython-matplotlib. However, when I try to update I am told that my pip is currently 9.x.x and there is no available update. Whatever way I try to resolve the pip path to the python 2.7 installation has failed thus far.  So, I guess from my point of view I want to make a systematic install procedure, with procedures to solve commonly encountered errors, to install Cantera for use with Matlab in Linux (or OSX where I have encountered the same series of problems). Trying to follow the various instructions from multiple websites has left me a muddled mess. 
6. After trying to build with python 2.7 and failing I looked for reasons why. I realized that installed all of the Cantera packages I included Cantera3. Frankly, I was very exasperated at this point- I have failed to install with OSX, and now I am failing to install in Linux and I don't know what the problem is. Bing is terrible, and the search results yield myriad different directions to follow. I don't know how to remove everything to start again and I am unable to roll back to a time before I made changes. 
7. Assuming that I need to build Cantera from source in order to use it with Matlab, I try compiling and get the ext/fmt error I mentioned previously.  When I have been able to install, through a procedure so convoluted that I don't know what lead to success, I try the matlab tutorials and get an error in the cti2xml procedure. Again, at that point I don't know if the problem is with Cantera or with the idiot (me) that set it up. 

Why- I live and work in China at a University. They pirate software like crazy here, but I refuse- thus Linux and Cantera instead of Windows and Chemkin. I am trying to get my students to stop stealing software, but I need a bulletproof system to offer them. (I have a personal license I purchase for Matlab, the University also has a site-license) -- Thank you guys so much for your hard work! I know the cost of the commercial software, I want programmers to have jobs and good lives, I appreciate that free alternatives are available (like cantera, openfoam and octave). 
I have set up VM's of Ubuntu and OpenSUSE to try installing Cantera and Matlab so that I can learn to use it and teach my students. I will use fresh OS instances to perform installation and solve only 1 problem at a time. When I am finished I hope to have a systematic approach to installing Cantera for use with Matlab and the processes necessary to solve problems as they arise. I want the procedure to work for everyone; the current instructions I have read from various websites do not.

**Comment by Blue-Beetle-13** [comment]
@decaluwe  
I am a new professor at a Chinese University, I am stretched with trying to perform experiments, write papers and teach. And learn Chinese. Mostly the students, faculty and many Chinese companies pirate software. I am doing my best to avoid it, and only now have had the time to get stuck-in to the problem. I originally began in December with my Mac and Homebrew, utter failure. I decided to set up a Linux system specifically for Cantera and OpenFoam. I thought Cantera should be straightforward as OpenFOAM but it didn't turn out so. I have tried solving the problems I face using things I found on Bing and here, but I got more muddled. Sadly, my programming skills are limited to LabVIEW (if you can call that programming) and Matlab for image and data processing. However, I am good at setting up experiments, so I thought I could treat this like an experiment: first figure what I don't know, isolate the unknown aspects and test until I understand the result. I am sorry if I came off too abrasive. I don't mean to, I am frustrated with work, with China, with terrible internet, all while knowing it would be easier but morally wrong to just give in and use illegal software. I will let you know. 
p.s. Sorry, I didn't realize I had closed the conversation earlier, didn't mean for this to appear like a drive by mud-slinging

**Comment by speth** [comment]
I would strongly suggest that this topic be moved to the Users' Group, or perhaps Gitter. The GitHub Issues tracker is not the ideal place to debug individual compilation/installation problems.

**Comment by Blue-Beetle-13** [comment]
Okay, I have been practicing installing Cantera on Ubuntu. I try until I hit an Error and then I wipe the VM and start again. 
1. Using Anaconda seemed to work without incident. However, this requires using Python? I would prefer to use Matlab. 
2. Using Ubuntu packages does not include Matlab packages, so I skip this. 
3. Downloading the Cantera Source tarball and running "scons test" gave errors for missing fmt in the ext/fmt path. This must be solved by downloading fmtlib3.0 from fmtlib.net. Downloading using curl as mentioned in closed issue #470 did not work for me, the zip file was invalid. Again running "scons test" gave an error for missing Googletest. run sudo apt install libgtest-dev fixed this problem. Finally there is a fatal error: cantera/ext/Eigen/Dense no such file or directory. I got stuck on this error.
4. Fresh Ubuntu instance, installed git, used git to download Cantera. Running 'scons test' fmt and Googletest were automatically included. Two errors shown. Missing 3to2 package. Fixed by installing pip (sudo apt install python-pip) and then running pip install 3to2. Do not update pip because you will get a permission error when trying to install 3to2 which can be overcome by using sudo -H pip install 3to2 , also, it doesn't actually update pip --version will show that 9.0.1 is installed, but running pip install will still give a prompt that you should update pip 8.1.1 to 9.0.1
Now scons test stops on the "fatal error: cantera/ext/Eigen/Dense: No such file or directory. Compilation terminated." I tried to download and extract the Eigen3 package, but the Great Firewall is being touchy about eigen.tuxfamily.org tonight. I will try again tomorrow.

**Comment by bryanwweber** [comment]
Hi @Blue-Beetle-13 I agree with Ray (and I think I just replied to your email) that Gitter is a better place for this.

**Comment by speth** [comment]
I'm going to close this issue. If you're still having trouble, please feel free to bring this up on Gitter or the Users' Group and we'll do what we can to help.

**Comment by charryzzz** [comment]
> 
> 
> Okay, I have been practicing installing Cantera on Ubuntu. I try until I hit an Error and then I wipe the VM and start again.
> 
>     1. Using Anaconda seemed to work without incident. However, this requires using Python? I would prefer to use Matlab.
> 
>     2. Using Ubuntu packages does not include Matlab packages, so I skip this.
> 
>     3. Downloading the Cantera Source tarball and running "scons test" gave errors for missing fmt in the ext/fmt path. This must be solved by downloading fmtlib3.0 from fmtlib.net. Downloading using curl as mentioned in closed issue [Unable to build Cantera 2.3.0 with fmt 4.0.0 #470](https://github.com/Cantera/cantera/issues/470) did not work for me, the zip file was invalid. Again running "scons test" gave an error for missing Googletest. run sudo apt install libgtest-dev fixed this problem. Finally there is a fatal error: cantera/ext/Eigen/Dense no such file or directory. I got stuck on this error.
> 
>     4. Fresh Ubuntu instance, installed git, used git to download Cantera. Running 'scons test' fmt and Googletest were automatically included. Two errors shown. Missing 3to2 package. Fixed by installing pip (sudo apt install python-pip) and then running pip install 3to2. Do not update pip because you will get a permission error when trying to install 3to2 which can be overcome by using sudo -H pip install 3to2 , also, it doesn't actually update pip --version will show that 9.0.1 is installed, but running pip install will still give a prompt that you should update pip 8.1.1 to 9.0.1
>        Now scons test stops on the "fatal error: cantera/ext/Eigen/Dense: No such file or directory. Compilation terminated." I tried to download and extract the Eigen3 package, but the Great Firewall is being touchy about eigen.tuxfamily.org tonight. I will try again tomorrow.

I am facing a same problem like you, do you solve this problem?

**Comment by charryzzz** [comment]
> 
> 
> Okay, I have been practicing installing Cantera on Ubuntu. I try until I hit an Error and then I wipe the VM and start again.
> 
>     1. Using Anaconda seemed to work without incident. However, this requires using Python? I would prefer to use Matlab.
> 
>     2. Using Ubuntu packages does not include Matlab packages, so I skip this.
> 
>     3. Downloading the Cantera Source tarball and running "scons test" gave errors for missing fmt in the ext/fmt path. This must be solved by downloading fmtlib3.0 from fmtlib.net. Downloading using curl as mentioned in closed issue [Unable to build Cantera 2.3.0 with fmt 4.0.0 #470](https://github.com/Cantera/cantera/issues/470) did not work for me, the zip file was invalid. Again running "scons test" gave an error for missing Googletest. run sudo apt install libgtest-dev fixed this problem. Finally there is a fatal error: cantera/ext/Eigen/Dense no such file or directory. I got stuck on this error.
> 
>     4. Fresh Ubuntu instance, installed git, used git to download Cantera. Running 'scons test' fmt and Googletest were automatically included. Two errors shown. Missing 3to2 package. Fixed by installing pip (sudo apt install python-pip) and then running pip install 3to2. Do not update pip because you will get a permission error when trying to install 3to2 which can be overcome by using sudo -H pip install 3to2 , also, it doesn't actually update pip --version will show that 9.0.1 is installed, but running pip install will still give a prompt that you should update pip 8.1.1 to 9.0.1
>        Now scons test stops on the "fatal error: cantera/ext/Eigen/Dense: No such file or directory. Compilation terminated." I tried to download and extract the Eigen3 package, but the Great Firewall is being touchy about eigen.tuxfamily.org tonight. I will try again tomorrow.


solved by

cp -rf /usr/include/eigen3/Eigen /usr/include/Eigen -R
