### ISSUE TITLE
Optional "googletest" package dependency to build Cantera

### ISSUE THREAD

**Issue by band-a-prend** [Cantera/cantera#515]
### Cantera version 
2.3.0 and 2.4.0b1(development)

### Operating System 
Linux

### Python/MATLAB version 
none

### Expected Behavior 
Successful build the Cantera package in case of without planing to run `scons test`

### Actual Behavior
config error: Googletest not found and submodule checkout failed.

### Steps to reproduce

1. Unpack cantera tarball.
2. Ensure that googletest package isn't installed in system (and maybe disable internet connection).
3. Run in terminal in cantera root working directory command `scons build`

Result: `config error: Googletest not found and submodule checkout failed.`

Issue Message:
As I understand "googletest" (gtest/gmock) package is needed only for performing "regression" code test and is unnecessary itself to build and use Cantera libraries, isn't it? 

Attached simple patches (one is for cantera-2.3.0 and another is for current "master"-branch) add "googletest" configuration option to disable/enable checking of googletest package presence in system and if it's enable (is set to "y") or isn't set ('default') then check "system_googletest" configuration option.

E.i. if call `scons build googletest='n'` then the absence of gtest/gmock will not give error message and cantera is successfully compile.

[cantera_is_googletest_patches.zip](https://github.com/Cantera/cantera/files/1811253/cantera_is_googletest_patches.zip)

Sorry for absence of pull request right now. I'm not good with git(hub) and that take some time to create PR and attache it to issue.

**Comment by bryanwweber** [comment]
The `system_googletest` option already exists in the configuration that should handle this. What is going wrong with your build that you need to add a second option for this? Can you please provide the contents of `config.log` and `cantera.conf`?

**Comment by band-a-prend** [comment]
As I could see the `system_googletest` option handle whether use system gtest.h or use it from `<cantera_build_dir>/ext/googletest` where it must be placed. It currently doesn't disable dependence of googletest while scons sonfiguration.

Does this package (googletest) is really necessary for cantera compilation? After disabling cheking of this gtest.h header by offered patch and without gtest.h elsewhere the cantera libraries are successfully build and I successfully compile and run distributed c++ and fortran samples (copied to my home directory).

Is it possible to add a new option to disable the searching gtest.h during scons configuration phase or modify `system_googletest` option to be possible to set it to `disable` to switch off such checking pr to add additional conditional statement without exit with error?

Maybe if just change `if env['system_googletest'] in ('n', 'default'):` to `if env['system_googletest'] in ('default'):` then `system_googletest="default"` will try to receive package from git and otherwise if `system_googletest="n"` there will not be any checking of `gtest.h` presence and configuration will be successful in this case?

For example the behaviour described above could be seen from SConstruct script of cantera-2.3.0.tar.gz that contains code:
```
# Check for googletest and checkout submodule if needed
if env['system_googletest'] in ('y', 'default'):
    if conf.CheckCXXHeader('gtest/gtest.h', '""'):
        env['system_googletest'] = True
    elif env['system_googletest'] == 'y':
        config_error('Expected system installation of Googletest, but it '
                     'could not be found.')

if env['system_googletest'] in ('n', 'default'):
    env['system_googletest'] = False
    if not os.path.exists('ext/googletest/include/gtest/gtest.h'):
        if not os.path.exists('.git'):
            config_error('Googletest is missing. Install source in ext/googletest.')

        try:
            code = subprocess.call(['git','submodule','update','--init',
                                    '--recursive','ext/googletest'])
        except Exception:
            code = -1
        if code:
            config_error('Googletest not found and submodule checkout failed.\n'
                         'Try manually checking out the submodule with:\n\n'
                         '    git submodule update --init --recursive ext/googletest\n')
```


> Can you please provide the contents of config.log and cantera.conf?

Yes. I use local untared cantera-2.3.0.tar.gz (not git-directory with `.git` folder inside it). This is scons verbose output that contains both `config.log` and `cantera.conf`:

```
$ scons build system_googletest=n system_fmt=y system_sundials=y system_eigen=y extra_inc_dirs="/usr/include/eigen3" VERBOSE=yes"
scons: Reading SConscript files ...
INFO: SCons is using the following Python interpreter: /usr/bin/python2.7
Configuration variables read from 'cantera.conf' and command line:
    system_eigen = 'y'
    system_fmt = 'y'
    system_sundials = 'y'
    system_googletest = 'n'
    extra_inc_dirs = '/usr/include/eigen3'
    VERBOSE = True

Checking for C++ header file cmath... yes
Checking for C++ header file fmt/ostream.h... yes
INFO: Using system installation of fmt library.
ERROR: Googletest is missing. Install source in ext/googletest.
************************* Contents of config.log: *************************
file /home/user/Downloads/cantera/cantera-2.3.0/SConstruct,line 749:
	Configure(confdir = .sconf_temp)
scons: Configure: Checking for C++ header file cmath... 
.sconf_temp/conftest_0.cpp <-
  |
  |#include <cmath>
  |
  |
g++ -o .sconf_temp/conftest_0.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG -I/usr/include/eigen3 .sconf_temp/conftest_0.cpp
scons: Configure: yes

scons: Configure: Checking for C++ header file fmt/ostream.h... 
.sconf_temp/conftest_1.cpp <-
  |
  |#include "fmt/ostream.h"
  |
  |
g++ -o .sconf_temp/conftest_1.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG -I/usr/include/eigen3 .sconf_temp/conftest_1.cpp
scons: Configure: yes


**************************** End of config.log ****************************
```

**Comment by band-a-prend** [comment]
> Maybe if just change if env['system_googletest'] in ('n', 'default'): to if env['system_googletest'] in ('default'): then system_googletest="default" will try to receive package from git and otherwise if system_googletest="n" there will not be any checking of gtest.h presence and configuration will be successful in this case?

E.g. something like this patches: [cantera_select_is_gtest_patches.zip](https://github.com/Cantera/cantera/files/1813186/cantera_select_is_gtest_patches.zip)

**Comment by bryanwweber** [comment]
Googletest is necessary to run the test suite (`scons test`). Is there a reason you cannot/do not want to get it?

**Comment by speth** [comment]
I think a PR which allows compilation and installation without requiring googletest to be available would be acceptable, but I do not want to change the existing functionality (i.e. the meaning of `system_googletest=n`), which is what the suggested patch does.

**Comment by band-a-prend** [comment]
> Googletest is necessary to run the test suite (scons test). Is there a reason you cannot/do not want to get it?

@bryanwweber, sorry for delay with my reply. The reason I want to disable test dependency (e.g. `googletest` package) in some cases is that I'm writing a build-script (ebuild-file) for Gentoo (it's source-based linux distributive). It's my first experience of ebuild writing from scratch so it take some time to run many tests of build with different set of options and installation checking to live system (in virtual machine of course). So this script is under development yet and require some reworking and clean-up before I could offer it to official package tree.

The common build and installation process in gentoo is described [here](https://devmanual.gentoo.org/ebuild-writing/functions/index.html) and one of the optional step to run test suite is [src_test()](https://devmanual.gentoo.org/ebuild-writing/functions/src_test/index.html) function. The test-suite scripts are expected to run inside src_test() but this function isn't run by default  by users during package installation and src_test() is used mainly by gentoo developers to ensure that build options and flags doesn't brake package.

The installation via "ebuild-file" allows user to choose build options via USE-flags that are associated with build configuration options. Even if `scons test` will run the user doesn't see the results because there will be more other log messages about installation package process.

Moreover currently if scons config. options is set to `python_package = 'none' python3_package = 'n'"` then there is the `ck2cti`absent in build package (as there is no python scripts) and while running `scons test` some of tests FAILs because of `CanteraError thrown by ct2ctml: python cti to ctml conversion requested for file, ./<file_name.cti> but not available in this computational environment`. So this will confuse user if he get this error messages when he doesn't choose not `python_package=minimal` nor `python3_package=y`. Such error is found about 37 cpp tests/cases that try to call `ck2cti` and couldn't find it.

@speth, what about new additional option `googletest: ['y', 'n','default']` that was offered in the initial issue post and within first attached patches (cantera_is_googletest_patches.zip)?

It's seems that it only need to add additional condition there: 
```
if env['googletest'] in ('y','default'):
    print "- To run the test suite, type 'scons test'."
```
to hide this message if user set `googletest='n'`.

I can try to make appropriate PR this weekend for master branch.

**Comment by bryanwweber** [comment]
@band-a-prend 
> Moreover currently if scons config. options is set to python_package = 'none' python3_package = 'n'" then there is the ck2ctiabsent in build package (as there is no python scripts) and while running scons test some of tests FAILs

This has been changed in the current `master` branch, where the test script will use the necessary Python files for the conversion when appropriate, even if neither Python package is being built. If this is not the case on the `master` branch, it is a bug we need to fix. Also, please note that the Python options have changed as well, `python_package` refers to whichever Python is running SCons, which could be Python 2 or 3. If you want to be explicit, there are `python2_package` and `python3_package` options that you can set.

I think an option for this it would be better named `enable_googletest` or something similar, rather than just plain `googletest`, to clarify what it is for. In addition, if the user disables GoogleTest, they should still be able to run the rest of the test suite (the Python and Matlab tests, and the C++ test_problems), so `scons test` will still be a useful command, i.e., the user should still be informed that it exists.

**Comment by speth** [comment]
Sorry, I had only looked at the second patch on the assumption that it superseded the first one. Having to download a zip file and open the patch file is much less convenient than having a pull request to look at. Even putting the patch in a Gist would be more accessible.

I would like to avoid introducing yet another config option, when all we really need is a fourth choice to the existing one. The only tricky bit is that I think we need to rename the option, since there's no sensical way to have the option be `system_googletest=actually_never_mind`. Would it make sense to have the option be named `googletest` with the options being `system`, `submodule`, `default`, and `none`? I think that in this case `default` should maintain the current behavior of failing if neither the `system` nor `submodule` options works. If we do this, I would want to have both options present in the current version, with the `system_googletest` option deprecated.

I'm a bit ambivalent about having `scons test` still function if googletest is not present, especially if you're contemplating building without the Python module. In this case, all that's left is the legacy regression test suite (which is gradually being migrated into the googletest tests), and passing just those tests might give you a false sense that you're passing a comprehensive test suite when you really aren't.

**Comment by band-a-prend** [comment]
Sorry for very long delay. I only recently tested new feature and now create a pull request about it.
