### ISSUE TITLE
Cloning with SSH does not clone submodules

### ISSUE THREAD

**Issue by gpavanb-old** [Cantera/cantera#516]
### Cantera version
2.3.0 

### Operating System
Linux

### Python/MATLAB version
2.7.11
Matlab not used

### Expected Behavior
Cloned repository should contain all the submodules when done with SSH

### Actual Behavior
Clone of submodule fails as it defaults to HTTPS

### Steps to reproduce
1. git clone --recursive git@github.com:Cantera/cantera.git

This is because the .gitmodules file is in the commit. I made a patch where I edit it online on Github and then clone. That works like a charm.

**Comment by speth** [comment]
I can't replicate the problem described, running Git 2.7.4 on Ubuntu. Running the specified command fails with the error
```
fatal: Remote branch --recursive not found in upstream origin
```
With the spurious `-b` flag removed, git clones the submodules as expected. What version of Git are you using? Cloning over HTTPS should work fine -- what is the exact error that you are getting?

**Comment by gpavanb-old** [comment]
I should mention this happens only when HTTPS cloning is incompatible. I'm on a cluster with a rather old version of OpenSSL and I have to use SSH cloning. In that case, the submodules are cloned based on the address in .gitmodules.

Basically, when you choose to clone the repository as a whole with SSH, the submodules however default to HTTPS

**Comment by speth** [comment]
Yes, of course the submodules are cloned based on the addresses in `.gitmodules`. That is how submodules are defined. I don't think there is a way of specifying different submodule URLs based on the URL used to clone the parent project.

**Comment by bryanwweber** [comment]
If you can clone without the `--recursive`, can't you edit the `.gitmodules` file locally to specify SSH cloning, and then do `git submodule update --init --recursive`? No need to edit in the web interface on GitHub...
