### ISSUE TITLE
Multiple runs of ck2cti.Parser result in incorrect duplicate species error

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#528]
### Cantera version
2.4.0b1 (3d59914e6)

### Operating System
Any

### Python/MATLAB version
Any

### Expected Behavior
The ck2cti parser should raise an error about problems in the thermo.txt file regarding an incorrect specification of the thermo entry:
```
ERROR: Unable to parse 'mech_debug/thermo.txt' near line 526:
```

### Actual Behavior
Instead, the parser raises an error about an additional declaration of species `H`, although there are not duplicated species in the mechanism:
```
InputParseError: Found additional declaration of species H
```

It appears that some information is cached between runs of the parser, resulting in this duplicate species declaration. If this is actually the expected behavior, it is not clear that this would happen, especially when input files are changed.

### Steps to reproduce
```python
import cantera.ck2cti as ck2cti
parser = ck2cti.Parser()
parser.convertMech('mech.txt', 'thermo.txt', 'tran.txt', outName='mech.cti')
parser.convertMech('mech_fixed.txt', 'thermo.txt', 'tran.txt', outName='mech.cti')
```

[mech_fixed.txt](https://github.com/Cantera/cantera/files/1934520/mech_fixed.txt)
[mech.txt](https://github.com/Cantera/cantera/files/1934521/mech.txt)
[thermo.txt](https://github.com/Cantera/cantera/files/1934522/thermo.txt)
[tran.txt](https://github.com/Cantera/cantera/files/1934523/tran.txt)

**Comment by speth** [comment]
The parser is essentially a single-use object. If you want to parse another mechanism, you should create a new parser. See for example how it's used in `test_convert.py`. I agree that this is confusing, but I think it comes from the fact that `ck2cti` is mainly meant to be called as a script, and the route of instantiating the `Parser` object directly and calling `convertMech` is an undocumented, internal interface.

**Comment by ghost** [comment]
Xml format may help because it is standard format. The cti parser code seems like a specialized python interpreter, so a lot of internal state is cached. 

@speth 
I think it should cast a RuntimeError when it is reused if it is designed to be non-reusable.
