### ISSUE TITLE
Updating only certain properties after temperature/pressure/composition changes.

### ISSUE THREAD

**Issue by ma-sadeghi** [Cantera/cantera#530]
I'm not sure if this is the right place to ask, so sorry in advance.

I'm using Cantera to estimate transport properties in some CFD simulations. I have a bunch of nodes with different temperature/pressure/composition. I'm using Cantera's `SolutionArray` to represent the nodes in my simulation.

Now suppose the temperature profile changes and I want to update the thermal conductivity of each node. The way I currently do this is by changing the temperature of the `SolutionArray`. As far as I know, when I update the temperature in a `SolutionArray`, it automatically tries to update whatever properties that are attached to it including thermal conductivity and many others, which makes it slow. 

My question is whether or not I can update only a subset of properties attached to the `SolutionArray` (for instance, I only need to update thermal conductivity).

Thanks,
Amin

**Comment by bryanwweber** [comment]
@ma-sadeghi A better place for this question would be on the User Group: https://groups.google.com/forum/#!forum/cantera-users along with a sample code demonstrating the problem and any associated CTI files. Can you also include your OS and version of Cantera?

**Comment by ma-sadeghi** [comment]
@bryanwweber Thank you for your reply. I'm not exactly reporting a bug/problem. I'm rather asking whether or not a feature is present in Cantera. More specifically, my question is can I force `cantera` to only calculate a specific property (say thermal conductivity) when I change the `Solution` temperature? I also posted the question on the forum as you recommended.

The reason I'm asking for this feature is that when working with huge `SolutionArray`s, one might be only interested in how thermal conductivity changes with temperature. However, as far as I know, `cantera` tries to update every model attached to the `SolutionArray`, which takes a lot of time.

**Comment by speth** [comment]
Your understanding of how the `SolutionArray` class works is not correct. Only the requested properties are ever specifically calculated.

I also agree with Bryan that the User's Group is the right place for this discussion, and so that we can have do this in only one place, I am going to close this issue.
