### ISSUE TITLE
ck2cti InputParseError: unmarked duplicate reaction, twice on same line

### ISSUE THREAD

**Issue by mazeau** [Cantera/cantera#532]
### Cantera version
2.3.0
### Operating System
mac 10.13.4
### Python/MATLAB version
2.7

### Actual Behavior
input:
```
ck2cti --input=chem.inp.txt --thermo=chem.inp.txt --permissive
```
output:
```
InputParseError: Encountered unmarked duplicate reaction CX(24) + CH2X(48) <=> CHX(26) + CHX(26) (See lines 463 and 463 of the input file.).
```
but as far as we can tell there is no duplicate, certainly not twice on line 463.
On multiple reruns the error will come up for different reactions (always found on the same line of the chemkin input file) for some reason and it is unable to generate a cantera file.

Some notes:
* We don't actually have chemkin, so cant test if it works there!
* It contains heterogeneous surfce reactions with sticking coefficients
* It was generated by RMG-Cat

Here's the chemkin file:
[chem.inp.txt](https://github.com/Cantera/cantera/files/1964899/chem.inp.txt)

**Comment by speth** [comment]
Well, I can't replicate the error indicated with the file provided -- I get the error `Undefined elements: {'X'}` instead.

If you have all of your thermo data in the `chem.inp` file, you shouldn't specify the same file again using the `--thermo` method. My guess is that is why you are getting duplicate reaction errors -- the parser is grabbing the reactions from both files.

I'm also not sure I understand how Cantera is supposed to understand this as a surface mechanism. There is only one species list, so how should Cantera know which species are in the gas phase versus on the surface? I thought the usual way of handling this was to have a separate file for the gas phase species, which you would pass as `--input`, and then pass the surface mechanism using the `--surface` option to `ck2cti`.

**Comment by speth** [comment]
In the absence of an update including a replicable error, I'm going to close this issue. Feel free to re-open if you can provide such information.
