### ISSUE TITLE
Cantera 2.3 / intel fortran(2018)

### ISSUE THREAD

**Issue by lrcancino** [Cantera/cantera#533]
Hello, 

It is somebody using cantera 2.3 & Intel Fortran XE 2018?

I have to build cantera by using scons... but I do not know how to do it.

https://www.cantera.org/docs/sphinx/html/compiling/config-options.html#f90-interface

if some body already did, I will be very happy to know how to do it.

Best regards,

Leonel.,

**Comment by bryanwweber** [comment]
Hi! Is this the same post as on the User's Group? https://groups.google.com/forum/#!topic/cantera-users/2779hW12FRA If so, can you please close this issue to focus discussion over at the UG, which is the appropriate forum for this kind of question?

Thank you!

**Comment by lrcancino** [comment]
Hello, 
Yes, it is the same issue.
Thanks!

Leonel.
