### ISSUE TITLE
test failed with icc on RHEL6

### ISSUE THREAD

**Issue by ghost** [Cantera/cantera#545]
### Cantera version
2.4.0b1
commit: 4b4128aebd02140ac26fc84627d618b70c5e82dc
### Operating System
RHEL 6.7
### Python/MATLAB version
Anaconda 3.6.3
### Expected Behavior
flame speed of methane flame, phi=1atm, Tu=300K, P=1atm, using GRI3.0 mechanism

// 2.4.0a2, compiled @ RHEL6 
0.40030061918765686  //mix, default refinement criteria
0.37200615737581444  //mix, ratio=2, slope=curve=0.01 
0.371381604260468  //multi, soret, ratio=2, slope=curve=0.01

//2.4.0b1, install from anaconda @ Win10
0.400300619187
0.372006157353
0.371381603208

### Actual Behavior

// 2.4.0b1 compiled @ RHEL6 
0.2872826505876035
0.25911168860205597
0.2608384264165271

And I cannot pass tests
```
Comparing 'output_blessed.txt' with 'output_output.txt'
Values differ:        1050.06        1050.07; rel. err = 1.048e-05; abs. err = 1.100e-02
Values differ:        1050.19        1050.26; rel. err = 6.475e-05; abs. err = 6.800e-02
Values differ:        1050.36        1050.52; rel. err = 1.514e-04; abs. err = 1.590e-01
Values differ:        1050.58        1050.88; rel. err = 2.903e-04; abs. err = 3.050e-01
Values differ:        1050.86        1051.39; rel. err = 5.099e-04; abs. err = 5.360e-01
Values differ:        1051.22        1052.13; rel. err = 8.700e-04; abs. err = 9.150e-01
Values differ:        1051.68        1053.23; rel. err = 1.475e-03; abs. err = 1.552e+00
Values differ:        1052.29        1054.98; rel. err = 2.558e-03; abs. err = 2.695e+00
Values differ:        1053.09        1058.09; rel. err = 4.734e-03; abs. err = 4.997e+00
Values differ:        1054.17        1065.08; rel. err = 1.029e-02; abs. err = 1.090e+01
Values differ:        1055.69        1109.34; rel. err = 4.956e-02; abs. err = 5.365e+01
Values differ:        1057.92        2883.13; rel. err = 9.263e-01; abs. err = 1.825e+03
Values differ:        1061.45        2883.13; rel. err = 9.236e-01; abs. err = 1.822e+03
Values differ:         1067.9        2883.13; rel. err = 9.189e-01; abs. err = 1.815e+03
Values differ:        1084.64        2883.13; rel. err = 9.065e-01; abs. err = 1.798e+03
Values differ:        2894.01        2883.13; rel. err = 3.766e-03; abs. err = 1.088e+01
Values differ:           2894        2883.13; rel. err = 3.764e-03; abs. err = 1.087e+01
Values differ:           2894        2883.13; rel. err = 3.764e-03; abs. err = 1.087e+01
Values differ:           2894        2883.13; rel. err = 3.764e-03; abs. err = 1.087e+01
Values differ:           2894        2883.13; rel. err = 3.764e-03; abs. err = 1.087e+01
Found differences between /home/**/down/cantera/test_problems/clib_test/output_blessed.txt and /home/**/down/cantera/test_problems/clib_test/output_output.txt:
```
```
test_fixed_temp (cantera.test.test_onedim.TestBurnerFlame) ... FAIL
test_mixture_averaged (cantera.test.test_onedim.TestCounterflowPremixedFlame) ... FAIL
```
... cannot finish in reasonable time
### Steps to reproduce
1. cantera.config
```
CXX = 'icpc'
CC = 'icc'
python2_package = 'none'
f90_interface = 'n'
blas_lapack_libs = 'mkl_rt'
blas_lapack_dir = '/apps2/intelics/2017/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64'
env_vars = 'all'
cxx_flags = '-std=c++11'
cc_flags = '-diag-disable 1478'
boost_inc_dir = '/apps2/boost/1.66.0/include'
```
2.
scons build
// during compilation, a lot of unimportant warnings are thrown by icpc because of fmt lib.
3.
run following code at `cantera/build/python3`. The `pwd` will be added to `sys.path` and shadow original cantera version.
```
import cantera as ct
print(ct.__version__)
gas=ct.Solution('gri30.xml')
gas.TPX=300,ct.one_atm,'CH4:1.0, O2:2.0, N2: 7.52'
ff=ct.FreeFlame(gas,width=0.5)
ff.set_max_grid_points(ff.domains[1],100000)
ff.solve(loglevel=0,auto=True)
print(ff.u[0])

ff.set_refine_criteria(ratio=2.0, slope=0.01, curve=0.01, prune=0.001)
ff.solve(loglevel=0,refine_grid=True)
print(ff.u[0])

ff.set_max_grid_points(ff.domains[1],100000)
ff.transport_model='Multi'
ff.soret_enabled=True
ff.solve(loglevel=0,refine_grid=True)
print(ff.u[0])
```

**Comment by ghost** [comment]
Same result for commit aac8eb92a, which is identical to that of v2.4.0b1 conda package on anaconda. I doubt problem comes from icc. Trying gcc.

**Comment by ghost** [comment]
gcc 4.8.5 without MKL works for commit aac8eb9. It passes test.

```
*****************************
***    Testing Summary    ***
*****************************

Tests passed: 746
Up-to-date tests skipped: 0
Tests failed: 0

*****************************
```
And the flame speed output is:
```
0.40030061918886145
0.3720061574194787
0.37139534237391447
```
Subjectively, it runs even faster than MKL version.

**Comment by speth** [comment]
This sounds a lot like an issue that was reported on the Users' Group a while back (https://groups.google.com/d/topic/cantera-users/A7UWb9pZe3A/discussion) which turned out to be a bug in the Intel compiler. I would suggest trying the debugging steps I suggested there (e.g., compile with optimizations disabled, run the other subsections of the test suite besides `test-python2-onedim` (see output of `scons test-help`).

**Comment by ghost** [comment]
I used icc with MKL but w/o optimization. It passed all tests

```
$ scons -j `nproc` build CXX=icpc CC=icc f90_interface=n python2_package=none boost_inc_dir=/apps2/boost/1.66.0/include blas_lapack_libs=mkl_rt blas_lapack_dir=${MKLROOT}/lib/intel64 env_vars=all optimize=no
$ scons -j `nproc` test
*****************************
***    Testing Summary    ***
*****************************

Tests passed: 746
Up-to-date tests skipped: 0
Tests failed: 0

*****************************
```

I should run tests before use it.

**Comment by ghost** [comment]
I found `cc_flags='--no-ansi-alias'` solves the problem.

According to the discussion @speth supplied. It is related to two pointers point to same memory. And `--no-ansi-alias` is related to this phenomena and it tells the compiler do not assume the pointers are pointing different location.

**Comment by ghost** [comment]
I think a better solution is add a patch to scons build script to specify `--no-ansi-alias` option to only a few source code files if buggy intel compiler is used.

**Comment by speth** [comment]
The best solution is to not use a buggy compiler. The code in Cantera that triggers this problem:
```cpp
void incrementSpecies(const doublereal* R, doublereal* S) const {
    S[m_ic0] += R[m_rxn];
    S[m_ic1] += R[m_rxn];
}
```
does not violate the ANSI aliasing rules, which only apply when the two pointers are of different types. Here, these are not only pointers to the same type, they are pointers into the same array. The Intel compiler is making the baseless assumption that `m_ic0` is never equal to `m_ic1`.

I do not think it would be wise to start polluting the Cantera build scripts with workarounds for bizarre compiler bugs.

**Comment by ghost** [comment]
I understand it is not cantera's problem.

How about throw a warning when known buggy problem is encountered? Is it a better practice?

**Comment by bryanwweber** [comment]
Di, it will be better to add a note to the documentation, if anything I think. Adding to the build script means we have to do a lot of extra checking to be sure we're only warning in the right situation. I'm updating the docs right now anyways, I will add a note.

**Comment by speth** [comment]
I'm :+1: on mentioning this in the documentation. My preference would be to update the list of supported compilers and note that Intel compiler is specifically disrecommended due to known bugs in certain compiler versions, with a link to the bug report (for which no resolution has been reported).

**Comment by skyreflectedinmirrors** [comment]
@speth from my experience, you shouldn't expect a bug report filed on the intel forums to come to much (if you can get them to acknowledge it)

**Comment by speth** [comment]
I have no expectations for action from Intel on this. I think it's more of
a cautionary tale for users that might make them re-think using the Intel
compiler.

**Comment by bryanwweber** [comment]
For future reference, this is the link to the thread/bug report at Intel: https://software.intel.com/en-us/forums/intel-c-compiler/topic/684987

**Comment by ghost** [comment]
I understand and agree with @speth 's idea. It is a bug of external dependence. Modify the source code or build script may introduce problem in software maintainability and save the knowledge we already know to document is good enough.
