### ISSUE TITLE
"scons install" doesn't install doxygen documentation subdirectories recursively

### ISSUE THREAD

**Issue by band-a-prend** [Cantera/cantera#553]
### Cantera version
2.4.0

### Operating System
Linux

### Python/MATLAB version
none

### Expected Behavior
Successful install doxygen documentation subdirectories
### Actual Behavior
Absence of doxygen documentation subdirectories i "../cantera/doc/doxygen/html/" folder

### Steps to reproduce
1. Set scons "doxygen_docs" configuration option to "y"
2. Build Cantera (scons build)and notify that doxygen documentation subdirectories are presented in appropriate build subfolder
3. Run "scons install" and check the "../cantera/doc/doxygen/html/" folder under installation path. Notice that it contains only some of files laying in one level without subdirectories.

I'm try to modify my installation script of Cantera for Gentoo Linux for upcoming Cantera version 2.4.0 that is available as tarball under release link of project
and encounter that now doxygen documentation uses "CREATE_SUBDIRS = YES" rule
that was implemented in commit https://github.com/Cantera/cantera/commit/b84d3e3f79c63b9d496fcc4d413f49cec1c04111

The problem is that generated "cantera/doc/doxygen/html/" subdirectories aren't installed for me by scons install command. So navigation through the doxygen documentation isn't possible due to absence of many files.

If I revert mentioned commit by patching than documentation navigation is OK due to all files lay in one level.

I'm not sure but could it be due to the "doc/Sconscript" rule for install wasn't changed to recursively install directories?

> 94 if localenv['doxygen_docs']: 
>    ...
> 
> 102     env.Alias('doxygen', docs) 
> 103     install('$inst_docdir/doxygen/html', 
> 104             mglob(localenv, '#/build/docs/doxygen/html', 'html', 'svg', 'css', 'png'))

**Comment by bryanwweber** [comment]
@band-a-prend Thank you for this report. I think your diagnosis is correct. I will look into how to fix this.

**Comment by speth** [comment]
I think #555 fixes this. Can you confirm this works for you?

**Comment by band-a-prend** [comment]
Yes, I can confirm that #555 fixed the problem with navigation. 

Also this patch resolves issue that I didn't notice: 
*.js files were not installed previously after build so searching through generated doxygen documentation and additional menus were unavailable. Now it's has Search field and menus and their are working.

Great thanks!

P.S.
Will last few fixes be implemented into resulting Cantera 2.4.0 release and will release source tarballs be re-uploaded?

**Comment by band-a-prend** [comment]
@speth 
Thank you for updating release tarballs.

Sorry for bothering you. If there will be cantera 2.4.0 documentation tarball under https://github.com/Cantera/docs/releases ? It's very useful for offline reading of documentation.

Thank you in advance.
