### ISSUE TITLE
undefined reference to 'Cantera::

### ISSUE THREAD

**Issue by ChristianOL** [Cantera/cantera#556]
### Expected Behavior
  I would like to test the library in C++. I am trying to compile an example file of C++ but I get several errors of "undefined reference to 'Cantera::.." I followed the installation steps for Windows. 
https://cantera.org/install/windows-install.html which seem very simple.
It is not told to run any scripts or configuration (as in other OS installations), only executing installation files. 
Do I need to do an extra setup?

### Actual Behavior
When compiling several errors appear to diferent functions of Cantera.
"undefined reference to 'Cantera::.."

### Steps to reproduce
1. Follow steps of https://cantera.org/install/windows-install.html
2. Setup the include/headers directory of Cantera in DevC++ software.
3. Compile sample file: "Cantera/samples/cxx/demo.cpp".

**Comment by speth** [comment]
The current version of Cantera is 2.4.0 (released just this past Friday), so please update to that version first.

I suspect this is mainly a configuration issue, which would be better handled on the Cantera Users' Group, and I suggest you post your question there. When you do, please provide additional details on what compiler you are using -- I guess DevC++ uses one of the MinGW compilers? To use the precompiled Cantera libraries, you may need to use the same compiler as was used to compile Cantera (Visual Studio 2015). To use a different compiler, it may be preferable to compile Cantera yourself. Also, It is not clear that you are actually linking to the Cantera library, so please provide the full command line call issued to the compiler, and the full output.
