### ISSUE TITLE
Where is the mechanism_reduction.py's reduced mechanism stored?

### ISSUE THREAD

**Issue by QBPA** [Cantera/cantera#559]
Respected experts：
  I am a learning cantera's rookie, and i have run the Mechanism_reduction.py successfully and want to read the reduced mechanism but don't know where the reduced mechanism is.  
### Cantera version
2.3.0
### Operating System
windows conda spyder
### Python/MATLAB version
python 3.6
### Expected Behavior
using the cantera_test_mechanism_reduction.py and want to read the reduced mechanism
### Actual Behavior
Mechanism_reduction.py runs successfully but don't know where is the reduced mechanism
### Steps to reproduce
1.open spyder
2.open mechanism_reduction.py
3.get a polt about mechanism

Thanks for any help.

**Comment by bryanwweber** [comment]
Hi,

This question would be better posted on the Cantera User's Group: https://groups.google.com/forum/#!forum/cantera-users

Thank you,
Bryan
