### ISSUE TITLE
[Docs] Misleading default value in documentation for "versioned_shared_library"

### ISSUE THREAD

**Issue by band-a-prend** [Cantera/cantera#565]
### Cantera version
2.4.0

### Operating System
Gentoo Linux x86_64

### Python/MATLAB version
python 2.7.14, 3.6.5

------------
The [Cantera Configuration Options documentation](https://cantera.org/compiling/config-options.html) states

> **versioned_shared_library: [ yes | no ]**
> If enabled, create a versioned shared library, with symlinks to the more generic library name, e.g. libcantera_shared.so.2.4.0 as the actual library and libcantera_shared.so and libcantera_shared.so.2 as symlinks.
> default: 'no'

while the actual default behaviour is 'y' (SConstruct):
```
655      BoolVariable(
656          'versioned_shared_library',
657          """If enabled, create a versioned shared library, with symlinks to the
658             more generic library name, e.g. 'libcantera_shared.so.2.4.0' as the
659             actual library and 'libcantera_shared.so' and 'libcantera_shared.so.2'
660             as symlinks.
661             """,
662          defaults.versionedSharedLibrary),
```
where `defaults.versionedSharedLibrary` is described as
```
  303  # InstallVersionedLib only fully functional in SCons >= 2.4.0
   304  # SHLIBVERSION fails with MinGW: http://scons.tigris.org/issues/show_bug.cgi?id=3035
   305  if (env['toolchain'] == 'mingw'
   306      or StrictVersion(SCons.__version__) < StrictVersion('2.4.0')):
   307      defaults.versionedSharedLibrary = False
   308  else:
   309      defaults.versionedSharedLibrary = True
```
So the default value is "True" (versioned_shared_library="yes")  in common case.  The exclusion is only for mingw or/and SCons < 2.4.0 (SConstruct). Without explicit setting of "versioned_shared_library" to any value the Cantera is build by GCC with versioned shared libraries names. Maybe this fact is worth mentioning directly in documentation.

**Comment by speth** [comment]
Agreed, this is rarely the default value. Representing this caveat (and similar ones where the "default" option is platform-dependent) will be a tricky issue to handle when resolving Cantera/cantera-website#26.

**Comment by gaurlakshya** [comment]
Hey @speth @band-a-prend 
 I want to work on this issue(documentation) . Will you please guide me that how can i start?

**Comment by bryanwweber** [comment]
Hi @gaurlakshya! Thanks for your interest. I think the best thing to do to start will be to propose some modified text of this configuration option here in this issue, before you make a pull request.
