### ISSUE TITLE
Missing functors in matlab toolbox

### ISSUE THREAD

**Issue by ghost** [Cantera/cantera#567]
### Cantera version
2.4.0

### Operating System
Win10

### Python/MATLAB version
Matlab2016b

### Expected Behavior
func = Func('pow', base, exponent);
-> func = base^exponent

### Actual Behavior
Pow-Functor and other functors are missing in Matlab Toolbox (https://groups.google.com/forum/#!searchin/cantera-users/matlab$20functor$20in$20matlab%7Csort:date/cantera-users/jBWBBjilFxg/ilkOCfwoBgAJ). 

### Steps to reproduce
omega = 1500/30*pi;
offset   = 263/180*pi;
ct.x       = Func('polynomial', 1, [omega -offset]);
ct.func = Func('pow', ct.x, 0.5);

### Also not working to arbitrarily combine functors
ct.sin = Func('fourier', ct.x, 1, [0 0 omega 1]);
-> ct.sin = sin(Omega*x-Offset)

**Comment by arjavvashi** [comment]
I am working on this issue.

**Comment by ischoegl** [comment]
PR #1513 implements factory constructors for `Func1` objects that avoids hard-coding of functor names (or corresponding magic numbers).

**Comment by ischoegl** [comment]
After removal of the legacy MATLAB toolbox via #1670, all functors will be supported in the experimental toolbox after #1741.
