### ISSUE TITLE
The examples should use except ct.CanteraError where appropriate

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#569]
In some of the flame examples [here](https://github.com/Cantera/cantera/blob/5c783c708f0c08def6f6a3d8328b336d65842357/interfaces/cython/cantera/examples/reactors/ic_engine.py#L149), [here](https://github.com/Cantera/cantera/blob/5c783c708f0c08def6f6a3d8328b336d65842357/interfaces/cython/cantera/examples/onedim/diffusion_flame_extinction.py#L116), [here](https://github.com/Cantera/cantera/blob/5c783c708f0c08def6f6a3d8328b336d65842357/interfaces/cython/cantera/examples/onedim/diffusion_flame_batch.py#L119), and [here](https://github.com/Cantera/cantera/blob/5c783c708f0c08def6f6a3d8328b336d65842357/interfaces/cython/cantera/examples/onedim/diffusion_flame_batch.py#L170) we use a bare `except Exception`, probably as a leftover from before `CanteraError`s could be caught in Python. The latter two examples rely on catching a bare `Exception` to determine extinction, but it would probably be better to give a class name to that exception to distinguish solver errors vs. extinction.

**Comment by CyberDrudge** [comment]
I'm unsure about the exception to distinguish solver errors vs. extinction, should i keep that as it is (that `if-else` clause) or implement a new error class for maybe each of them or something else.

**Comment by bryanwweber** [comment]
@CyberDrudge The "Flame extinguished" string comes from this line: https://github.com/Cantera/cantera/blob/5c783c708f0c08def6f6a3d8328b336d65842357/interfaces/cython/cantera/examples/onedim/diffusion_flame_batch.py#L56 I would suggest adding a simple class that derives from `Exception` to indicate that the flame has extinguished, like
```python
class FlameExtinguished(Exception): pass
```
That should be defined outside the interrupt function and then `raise`d inside the interrupt. Then, you should have two `except` statements I think
```python
try:
    f.solve(...)
    ...
except FlameExtinguished:
    print('Flame extinguished')
    break
except ct.CanteraError as e:
    print('Error occurred while solving', e)
    break
```
That way, something like an `OSError` isn't caught and stops the simulation, but we handle the errors we know how to handle. Please also try to fix as many typos as you can find in that file. Thanks!

**Comment by CyberDrudge** [comment]
I was thinking about implementing something similar, just wasn't sure.
