### ISSUE TITLE
Returned entropy contains NaN from ReactorNet

### ISSUE THREAD

**Issue by Heathckliff** [Cantera/cantera#571]
### Cantera version
2.3.0
### Operating System
win7
### Python/MATLAB version
py35, MATLAB2017b
### Expected Behavior
Returned entropy should be a real number by a ReactorNet.
### Actual Behavior
Calculated entropy contains NaN in matlab toolbox.
### Steps to reproduce
p31 = 691488.236664879;
T31 = 1020.391657320222;

cFuel = Solution('n-Decane_MRZ_V0.cti');

set(cFuel, 'T',T31, 'P',p31, 'Y','NC10H22:1')
h0 = enthalpy_mass(cFuel);
s0 = entropy_mass(cFuel);

rctr = IdealGasConstPressureReactor(cFuel);
setEnergy(rctr,'off');
rcnt = ReactorNet({rctr});

tim = 10;
t = [linspace(1e-8,1,1e3),linspace(1.001,tim,1e3)];
dhc = zeros(size(t));
dsc = zeros(size(t));

for ii = 1:length(t)
    advance(rcnt,t(ii));
    dhc(ii) = enthalpy_mass(cFuel) - h0;
    dsc(ii) = entropy_mass(cFuel) - s0;  % !== dsc contains NaN ==!
end
### Required reaction mechanism file
mechanism file "n-Decane_MRZ_V0.cti" can be found in [https://github.com/Heathckliff/ReactionMechanism](url)

**Comment by speth** [comment]
There is no guarantee that the state of the `Solution` object `cFuel` corresponds to the state of the `Reactor` object `rctr` after the call to `advance`, so this should not be relied on. If you want to calculate properties based on the `Reactor`s state, you should use methods which access the state of the `Reactor` and use those to set the state of the `Solution`, e.g.:

```matlab
for ii = 1:length(t)
    advance(rcnt,t(ii));
    set(cFuel, 'T', temperature(rctr), 'Rho', density(rctr), 'Y', massFractions(rctr));
    dhc(ii) = enthalpy_mass(cFuel) - h0;
    dsc(ii) = entropy_mass(cFuel) - s0;
end
```
What is happening here is that sometimes, some of the mass fractions in the `Reactor` can be small negative values which don't cause any problems for the integrator, but are a problem when calculating other properties such as the mixture entropy. Setting the `Solution` state with the `set(...)` function automatically clips these values to be non-negative, eliminating the `NaN` problem.

**Comment by Heathckliff** [comment]
Thank you for your reply. Problem fixed~！
