### ISSUE TITLE
AttributeError when creating a ct.Solution object

### ISSUE THREAD

**Issue by mhansinger** [Cantera/cantera#599]
### Cantera version
2.5

### Operating System
Ubuntu 16.04

### Python/MATLAB version
python2.7

### Expected Behavior
Should create a gas object

### Actual Behavior
AttributeError: 'module' object has no attribute 'Solution'

### Steps to reproduce
1. I build and install cantera with scons
That seems to work 

2. Running a minimal example such as:
import cantera as ct
gas = ct.Solution('gri30.xml')
gas.TPY = 1000.0, ct.one_atm, 'CH4:0.055,O2:0.232,N2:713'
r = ct.IdealGasConstPressureReactor(name='adiabatic_reactor', contents=gas)
sim = ct.ReactorNet([r])
time = 1.e-3
print(r.T)
sim.advance(time)
print(r.T)

3. I get the following error message:

AttributeError                            Traceback (most recent call last)
<ipython-input-2-df7584ac6c65> in <module>()
----> 1 gas = ct.Solution('gri30.xml')
      2 gas.TPY = 1000.0, ct.one_atm, 'CH4:0.055,O2:0.232,N2:713'
      3 r = ct.IdealGasConstPressureReactor(name='adiabatic_reactor', contents=gas)
      4 sim = ct.ReactorNet([r])
      5 time = 1.e-3

AttributeError: 'module' object has no attribute 'Solution'

Does any one have an idea what went wrong? 
Thx, Max

**Comment by bryanwweber** [comment]
Please attach your cantera.conf and config.log files, as well as the output from the `scons build` step. In addition, legacy Python 2 is not supported for Cantera > 2.4. You have to use modern Python 3.

**Comment by speth** [comment]
Presumably what's happened here is that SCons automatically fell back to building the 'minimal' Python module, which of course doesn't include the `Solution` class. Since this seems to be a fairly common source of confusion, I'm wondering whether we should remove the automatic fallback and have failure to find a usable copy of Python terminate the build process unless the user explicitly specifies `python_package=minimal` or `python_package=n`.

**Comment by mhansinger** [comment]
Thanks @bryanwweber  and @speth for the comments!

I built it for python3. The installation runs through, however, when I get then another error within pyhton3 as soon as I try to import cantera:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: /usr/local/lib/python2.7/dist-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cantera/__init__.py", line 4, in <module>
    from ._cantera import *
  File "__init__.pxd", line 206, in init cantera._cantera
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /usr/local/lib/python2.7/dist-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Somehow it is still installed for python2.7??
I attached also my cantera.confg and config.log

**cantera.confg**
python_package = 'n'
python3_package = 'y'
python3_cmd = '/usr/bin/python3.5'


**config.log**
file /home/max/cantera_git/cantera/SConstruct,line 788:
	Configure(confdir = .sconf_temp)
scons: Configure: Checking for C++ header file cmath... 
scons: Configure: ".sconf_temp/conftest_0.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_0.cpp <-
  |  |
  |  |#include <cmath>
  |  |
  |  |
  |
scons: Configure: ".sconf_temp/conftest_0.o" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_0.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_0.cpp
  |
scons: Configure: (cached) yes

scons: Configure: Checking for C++ header file fmt/ostream.h... 
scons: Configure: ".sconf_temp/conftest_1.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_1.cpp <-
  |  |
  |  |#include "fmt/ostream.h"
  |  |
  |  |
  |
scons: Configure: Building ".sconf_temp/conftest_1.o" failed in a previous run and all its sources are up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_1.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_1.cpp
  |
scons: Configure: (cached) no

scons: Configure: ".sconf_temp/conftest_2.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_2.cpp <-
  |  |#include "../ext/fmt/include/fmt/format.h"
  |  |#define Q(x) #x
  |  |#define QUOTE(x) Q(x)
  |  |#include <iostream>
  |  |#ifndef SUNDIALS_PACKAGE_VERSION
  |  |#define SUNDIALS_PACKAGE_VERSION SUNDIALS_VERSION
  |  |#endif
  |  |int main(int argc, char** argv) {
  |  |    std::cout << FMT_VERSION << std::endl;
  |  |    return 0;
  |  |}
  |  |
  |
scons: Configure: ".sconf_temp/conftest_2.o" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_2.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_2.cpp
  |
scons: Configure: ".sconf_temp/conftest_2" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_2 -pthread .sconf_temp/conftest_2.o
  |
scons: Configure: ".sconf_temp/conftest_2.out" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_2 > .sconf_temp/conftest_2.out
  |
scons: Configure: Checking for C++ header file gtest/gtest.h... 
scons: Configure: ".sconf_temp/conftest_3.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_3.cpp <-
  |  |
  |  |#include "gtest/gtest.h"
  |  |
  |  |
  |
scons: Configure: Building ".sconf_temp/conftest_3.o" failed in a previous run and all its sources are up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_3.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_3.cpp
  |
scons: Configure: (cached) no

scons: Configure: Checking for C++ header file gmock/gmock.h... 
scons: Configure: ".sconf_temp/conftest_4.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_4.cpp <-
  |  |
  |  |#include "gmock/gmock.h"
  |  |
  |  |
  |
scons: Configure: Building ".sconf_temp/conftest_4.o" failed in a previous run and all its sources are up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_4.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_4.cpp
  |
scons: Configure: (cached) no

scons: Configure: Checking for C++ header file Eigen/Dense... 
scons: Configure: ".sconf_temp/conftest_5.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_5.cpp <-
  |  |
  |  |#include <Eigen/Dense>
  |  |
  |  |
  |
scons: Configure: Building ".sconf_temp/conftest_5.o" failed in a previous run and all its sources are up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_5.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_5.cpp
  |
scons: Configure: (cached) no

scons: Configure: ".sconf_temp/conftest_6.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_6.cpp <-
  |  |#include "../ext/eigen/Eigen/Core"
  |  |#define Q(x) #x
  |  |#define QUOTE(x) Q(x)
  |  |#include <iostream>
  |  |#ifndef SUNDIALS_PACKAGE_VERSION
  |  |#define SUNDIALS_PACKAGE_VERSION SUNDIALS_VERSION
  |  |#endif
  |  |int main(int argc, char** argv) {
  |  |    std::cout << QUOTE(EIGEN_WORLD_VERSION) "." QUOTE(EIGEN_MAJOR_VERSION) "." QUOTE(EIGEN_MINOR_VERSION) << std::endl;
  |  |    return 0;
  |  |}
  |  |
  |
scons: Configure: ".sconf_temp/conftest_6.o" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_6.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_6.cpp
  |
scons: Configure: ".sconf_temp/conftest_6" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_6 -pthread .sconf_temp/conftest_6.o
  |
scons: Configure: ".sconf_temp/conftest_6.out" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_6 > .sconf_temp/conftest_6.out
  |
scons: Configure: Checking whether __GLIBCXX__ is declared... 
scons: Configure: ".sconf_temp/conftest_7.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_7.cpp <-
  |  |#include <iostream>
  |  |int main()
  |  |{
  |  |#ifndef __GLIBCXX__
  |  |    (void) __GLIBCXX__;
  |  |#endif
  |  |    ;
  |  |    return 0;
  |  |}
  |  |
  |
scons: Configure: ".sconf_temp/conftest_7.o" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_7.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_7.cpp
  |
scons: Configure: (cached) yes

scons: Configure: Checking whether _LIBCPP_VERSION is declared... 
scons: Configure: ".sconf_temp/conftest_8.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_8.cpp <-
  |  |#include <iostream>
  |  |int main()
  |  |{
  |  |#ifndef _LIBCPP_VERSION
  |  |    (void) _LIBCPP_VERSION;
  |  |#endif
  |  |    ;
  |  |    return 0;
  |  |}
  |  |
  |
scons: Configure: Building ".sconf_temp/conftest_8.o" failed in a previous run and all its sources are up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_8.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_8.cpp
  |
scons: Configure: (cached) no

scons: Configure: Checking whether __clang__ is declared... 
scons: Configure: ".sconf_temp/conftest_9.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_9.cpp <-
  |  |
  |  |int main()
  |  |{
  |  |#ifndef __clang__
  |  |    (void) __clang__;
  |  |#endif
  |  |    ;
  |  |    return 0;
  |  |}
  |  |
  |
scons: Configure: Building ".sconf_temp/conftest_9.o" failed in a previous run and all its sources are up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_9.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_9.cpp
  |
scons: Configure: (cached) no

scons: Configure: ".sconf_temp/conftest_10.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_10.cpp <-
  |  |#include <boost/version.hpp>
  |  |#define Q(x) #x
  |  |#define QUOTE(x) Q(x)
  |  |#include <iostream>
  |  |#ifndef SUNDIALS_PACKAGE_VERSION
  |  |#define SUNDIALS_PACKAGE_VERSION SUNDIALS_VERSION
  |  |#endif
  |  |int main(int argc, char** argv) {
  |  |    std::cout << BOOST_LIB_VERSION << std::endl;
  |  |    return 0;
  |  |}
  |  |
  |
scons: Configure: ".sconf_temp/conftest_10.o" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_10.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_10.cpp
  |
scons: Configure: ".sconf_temp/conftest_10" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_10 -pthread .sconf_temp/conftest_10.o
  |
scons: Configure: ".sconf_temp/conftest_10.out" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_10 > .sconf_temp/conftest_10.out
  |
scons: Configure: Checking for CVodeCreate(CV_BDF, CV_NEWTON) in C++ library sundials_cvodes... 
scons: Configure: ".sconf_temp/conftest_11.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_11.cpp <-
  |  |
  |  |
  |  |#include "cvodes/cvodes.h"
  |  |int
  |  |main() {
  |  |  CVodeCreate(CV_BDF, CV_NEWTON);
  |  |return 0;
  |  |}
  |  |
  |
scons: Configure: ".sconf_temp/conftest_11.o" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_11.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_11.cpp
  |
scons: Configure: ".sconf_temp/conftest_11" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_11 -pthread .sconf_temp/conftest_11.o -lsundials_cvodes
  |
scons: Configure: (cached) yes

scons: Configure: Checking for double x; log(x) in C library None... 
scons: Configure: ".sconf_temp/conftest_12.c" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_12.c <-
  |  |
  |  |
  |  |#include "math.h"
  |  |
  |  |int
  |  |main() {
  |  |  double x; log(x);
  |  |return 0;
  |  |}
  |  |
  |
scons: Configure: ".sconf_temp/conftest_12.o" is up to date.
scons: Configure: The original builder output was:
  |gcc -o .sconf_temp/conftest_12.o -c -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_12.c
  |
scons: Configure: Building ".sconf_temp/conftest_12" failed in a previous run and all its sources are up to date.
scons: Configure: The original builder output was:
  |gcc -o .sconf_temp/conftest_12 -pthread .sconf_temp/conftest_12.o
  |
scons: Configure: (cached) no

scons: Configure: ".sconf_temp/conftest_13.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_13.cpp <-
  |  |#include "sundials/sundials_config.h"
  |  |#define Q(x) #x
  |  |#define QUOTE(x) Q(x)
  |  |#include <iostream>
  |  |#ifndef SUNDIALS_PACKAGE_VERSION
  |  |#define SUNDIALS_PACKAGE_VERSION SUNDIALS_VERSION
  |  |#endif
  |  |int main(int argc, char** argv) {
  |  |    std::cout << QUOTE(SUNDIALS_PACKAGE_VERSION) << std::endl;
  |  |    return 0;
  |  |}
  |  |
  |
scons: Configure: ".sconf_temp/conftest_13.o" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_13.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_13.cpp
  |
scons: Configure: ".sconf_temp/conftest_13" is up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_13 -pthread .sconf_temp/conftest_13.o
  |
scons: Configure: ".sconf_temp/conftest_13.out" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_13 > .sconf_temp/conftest_13.out
  |
scons: Configure: Checking whether SUNDIALS_BLAS_LAPACK is declared... 
scons: Configure: ".sconf_temp/conftest_14.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_14.cpp <-
  |  |#include "sundials/sundials_config.h"
  |  |int main()
  |  |{
  |  |#ifndef SUNDIALS_BLAS_LAPACK
  |  |    (void) SUNDIALS_BLAS_LAPACK;
  |  |#endif
  |  |    ;
  |  |    return 0;
  |  |}
  |  |
  |
scons: Configure: Building ".sconf_temp/conftest_14.o" failed in a previous run and all its sources are up to date.
scons: Configure: The original builder output was:
  |g++ -o .sconf_temp/conftest_14.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG .sconf_temp/conftest_14.cpp
  |
scons: Configure: (cached) no

scons: Configure: ".sconf_temp/conftest_15.f90" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_15.f90 <-
  |  |
  |  |program main
  |  |   write(*,'(a)') 'Hello, world!'
  |  |end program main
  |  |    
  |
scons: Configure: ".sconf_temp/conftest_15.o" is up to date.
scons: Configure: The original builder output was:
  |gfortran -o .sconf_temp/conftest_15.o -c -O3 .sconf_temp/conftest_15.f90
  |
scons: Configure: ".sconf_temp/conftest_15" is up to date.
scons: Configure: The original builder output was:
  |gfortran -o .sconf_temp/conftest_15 -pthread .sconf_temp/conftest_15.o
  |
scons: Configure: ".sconf_temp/conftest_15.out" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_15 > .sconf_temp/conftest_15.out
  |

**Comment by speth** [comment]
Since this isn't specifically a problem with Cantera (you would presumably get the same output from running `import numpy` at the Python prompt), I don't think this is a good forum for resolving this issue. You could consider posting to the Cantera Users' group, but if you do, please provide **all** of the information that Bryan mentioned -- namely, what is important here for diagnostic purposes is the outputs of the `scons build` and `scons install` commands.
