### ISSUE TITLE
Add `set_equivalence_ratio` to `SolutionArray` objects

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#604]
Currently, the Python `SolutionArray` class has no equivalent of `ThermoPhase.set_equivalence_ratio`. A version of this function could be added to the `SolutionArray` class so that one can set the equivalence ratio to a range of values. This would make calculation of an adiabatic flame temperature curve very simple:
```py
states = ct.SolutionArray(gas, 100)
phi = np.arange(0, 2, 100)
states.set_equivalence_ratio(phi, 'CH4:1.0', 'O2:1.0, N2:3.76')
states.equilibrate('HP')
plt.plot(phi, states.T)
```

This function could also enable specifying a range of fuel and/or oxidizer compositions, in the case where a `dict` is used for the composition:
```py
states.set_equivalence_ratio(phi, {'CH4': np.linspace(0, 1, 100), 'H2': np.linspace(1, 0, 100)})
```

**Comment by bryanwweber** [comment]
Should the size of the arrays in `set_equivalence_ratio` match the existing size of the `SolutionArray`?

**Comment by speth** [comment]
Yes, I would expect this to work the same way as the other setters, e.g. `states.TPX = ...` work, with the length of an input in each dimension needing to have either the same length as the `states` object, or be a scalar in which case the values are broadcast in that dimension. An example of how this works now is already in [the SolutionArray documentation](https://cantera.org/documentation/docs-2.4/sphinx/html/cython/importing.html#cantera.SolutionArray).

**Comment by ischoegl** [comment]
I do have a question regarding the envisioned scope of `SolutionArray`. At the moment, it only exists as a pure python class. On the other hand, there is ongoing work to phase out ctml (see pull request #584), which may also mean that the XML output for `oneD` simulations may be revised (@speth posted  _1D Flame Development Ideas_ mentioning _"Introduce HDF5 or CSV or JSON or YAML or some other output format for 1D flames to replace XML"_). Would the idea be to build on `SolutionArray`?

**Comment by bryanwweber** [comment]
@ischoegl I suspect that any serialization output routine for 1-D classes will be in the C++ layer so that any interface could use it. However, I think it's possible that having a specialized subclass of `SolutionArray` in Python for 1-D cases would be useful.

**Comment by ischoegl** [comment]
Thanks for the insights: I agree that a subclass of SolutionArray handling 1D would be useful, which is what also prompted my inquiry. Has there been any discussion on what the new C++ layer replacing XML could entail?
