### ISSUE TITLE
Allow setting of integrator options for InterfaceKinetics.advanceCoverages

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#608]
Right now, there is nothing a user can do to resolve integration failures in `InterfaceKinetics.advanceCoverages`. Providing access to some of the integrator options would allow users to work around at least some failures. The following methods (from the `CVodesIntegrator` class) come to mind as the most useful:
- `setTolerances`
- `setMaxErrTestFails`
- `setMaxStepSize`

**Comment by skyreflectedinmirrors** [comment]
You beat me to it! I'll submit a fix for this tomorrow.
