### ISSUE TITLE
ctml_writer.py applies rounding to Arrhenius pre-exponential factors

### ISSUE THREAD

**Issue by skyreflectedinmirrors** [Cantera/cantera#614]
### Cantera version
Dev

### Operating System
All

### Python/MATLAB version
3.6

### Expected Behavior
Reaction rate pre-exponential Arrhenius factor should exactly match the specified value in a solution file.

### Actual Behavior
Slight discrepancy due to floating-point rounding [applied here](https://github.com/Cantera/cantera/blob/master/interfaces/cython/cantera/ctml_writer.py#L1060)

### Steps to reproduce
1.  Save [test.cti.txt](https://github.com/Cantera/cantera/files/2967414/test.cti.txt) as 'test.cti'
2.  Load latest dev Cantera and run:
```
import cantera as ct
print(ct.Solution('test.cti').reaction(0).rate.pre_exponential_factor - 53761000.99052169)
>>>-0.9905216917395592
```

### Comments

I'm not sure why we apply fixed-point float formatting specifically for the pre-exponential factor, and `gas_transport` values, but nothing else.  This results in some rather wonky rounding as well.  

I wouldn't have even noticed, except I'm working on an optimization code, and the model the optimizer spit-out was suddenly outside my bounds for the pre-exponential factor once I saved it to a CTI file and read it back in.

@speth If we agree this is worth fixing (it may not be, as the YAML format will supersede it shortly) I'll put together a quick PR for this (and possibly the transport values?)

**Comment by speth** [comment]
I recently applied a band-aid for this problem where it applies to Redlich-Kwong parameters (ec7f7794), and would certainly welcome a more comprehensive solution. `ctml_writer` will still be with us for a while, so I think it's worth fixing.

Consider this also an invitation to look at the YAML PR and whether how this is handled there makes sense -- see the functions `represent_float` and `applyUnits` in [ck2yaml.py](https://github.com/speth/cantera/blob/yaml/interfaces/cython/cantera/ck2yaml.py) and [cti2yaml.py](https://github.com/speth/cantera/blob/yaml/interfaces/cython/cantera/cti2yaml.py).

**Comment by ischoegl** [comment]
Fix looks simple: replace `14.6E` by `.10g` on lines 1060ff?

**Comment by ischoegl** [comment]
FYI: out of curiosity, I just replaced the three instances of `14.6E` with `24.16E` (or: alternatively to `.16g`), which reduces @arghdos' test to zero.

However, this also results in unit test failures, with `AsserNear` barely failing a relative tolerance
```
    - python:test_convert.chemkinConverterTest.test_explicit_forward_order
    - python:test_convert.chemkinConverterTest.test_negative_order_permissive
    - python:test_convert.chemkinConverterTest.test_reaction_units
```
on lines 284, 299, and 324, respectively (setting tol=2e-7 in the call to `checkKinetics` would make them go away). I'm obviously not suggesting to relax tolerances (rtol=1e-8 is pretty standard), but it's curious that a *more accurate* number representation would cause unit test failures? Further,

```python
In [1]: import cantera as ct
In [2]: arr = 53761000.99052169
In [3]: print(ct.Solution('test.cti').reaction(0).rate.pre_exponential_factor - arr)
0.0
```
suggests that the numbers are parsed correctly?

**Comment by speth** [comment]
Given that the XML and CTI formats are now officially deprecated, and I don't think there's an equivalent problem with the YAML format, I'm going to close this.
