### ISSUE TITLE
Feature request: C++ factories for flow devices and walls

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#618]
### Feature Request

A consistent use of `Factory` objects would simplify the inclusion of custom `Wall` or `FlowDevice` classes in C++. The `ReactorFactory` approach (mostly) avoids hard-coding, and illustrates how custom objects can be included in reactor networks.

### Cantera version
2.5.0a2

### Expected Behavior
Consistent handling of `ReactorNet` related objects in clib and cython interfaces allows for addition of new derived objects with minimal effort.

### Actual Behavior
Only `ReactorBase` objects are flexible. Instantiation of `FlowDevice` objects is hardcoded, whereas there are no alternatives to a single `Wall` class.

**Comment by ischg** [comment]
PS: a working illustration for a custom `ReactorBase` class compiled against unmodified cantera is illustrated in the repository [ischg/cantera-app](https://github.com/ischg/cantera-app)

**Comment by ischoegl** [comment]
The above code pertains to the C interface. Similar hard-coded creation routines exist in the cython interface.

**Comment by ischoegl** [comment]
The feature is implemented in PR #632 and is ready for review.
