### ISSUE TITLE
Converting surface reactions with explicit reverse ratesdoes not generat a pair of surface_reactions

### ISSUE THREAD

**Issue by mazeau** [Cantera/cantera#634]
@rwest and I were trying to convert a chemkin file to cantera and were running into a bad_cast error, but the only difference between the 2 cti files is that the reverse is uncommented out and it gives:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-1520979663cc> in <module>()
----> 1 surf = ct.Interface('./vlachos2007-bad_cast.cti','PT_SURFACE', [gas])

interfaces/cython/cantera/base.pyx in cantera._cantera._SolutionBase.__cinit__()

interfaces/cython/cantera/base.pyx in cantera._cantera._SolutionBase._init_cti_xml()

RuntimeError: std::bad_cast
```
any ideas why?  it does the same thing in 2.4.0 and 2.3.0

[vlachos2007-bad_cast.cti.txt](https://github.com/Cantera/cantera/files/3139601/vlachos2007-bad_cast.cti.txt)
[vlachos2007-works2.cti.txt](https://github.com/Cantera/cantera/files/3139602/vlachos2007-works2.cti.txt)

**Comment by rwest** [comment]
The difference between the two cti files is just the broken one has the extra reaction
```
reaction('CO(S) => CO + PT(S)', [6.120000e+14, 0.39, (41320.4, 'cal/mol')],
         id='PT_SURFACE-3')
```

The error `RuntimeError: std::bad_cast` occurs either when validating the recently-generated .cti file in ck2cti, or when trying to import the phase into an interface in cantera.  _(post edited, to correct the reaction)_

**Comment by mazeau** [comment]
We can also cause a bad_cast error with 
```
reaction('2 O(S) <=> O2 + 2 PT(S)', [8.410000e+12, 0.93, 50396.5],
         id='PT_SURFACE-2')
```

**Comment by ischoegl** [comment]
Shouldn’t those be surface reactions? I’m not familiar with the parser details, but the difference between the working and the non-working cti files is the use of surface_reaction vs reaction.

**Comment by rwest** [comment]
Ahah! Well spotted. Somehow missed that. 

So I think this reveals an error in the ck2cti when converting surface reactions with explicit reverse rates into coupled irreversible pairs, the reverse is not generated as a surface_reaction.

**Comment by ischoegl** [comment]
@rwest / @mazeau ... could you upload the original chemkin files so the reported behavior can be reproduced?

**Comment by mazeau** [comment]
[surf_vlachos-copy.inp.txt](https://github.com/Cantera/cantera/files/3859725/surf_vlachos-copy.inp.txt)
I think this is it

**Comment by ischoegl** [comment]
> I think this is it

Not sure: the information appears to be incomplete. Could you please be more specific on how you used `ck2cti` to produce the cti file that resulted in the `bad_cast` error?

**Comment by rwest** [comment]
Need the corresponding gas phase chemkin file as well in order to convert in ck2cti.  Do you still have that Emily?

**Comment by mazeau** [comment]
[chem_annotated-gas-copy.inp.txt](https://github.com/Cantera/cantera/files/3859999/chem_annotated-gas-copy.inp.txt)
sorry about that

**Comment by rwest** [comment]
This doesn't match up with the vlachos surface file you just posted. They have different species names, for a start (the different file names is also a clue).

**Comment by mazeau** [comment]
these are the only files I have left
[reactions-copy.py.txt](https://github.com/Cantera/cantera/files/3860075/reactions-copy.py.txt)
[dictionary.txt](https://github.com/Cantera/cantera/files/3860076/dictionary.txt)

**Comment by rwest** [comment]
OK, here's a minimal example of the problem (I think).

[Archive.zip](https://github.com/Cantera/cantera/files/3860221/Archive.zip)

chem-gas.inp
```
ELEMENTS
	C
	O
    PT
END

SPECIES        
    CO              
END

THERM ALL
    300.000  1000.000  5000.000
CO                      C   1O   1          G   100.000  5000.000 1571.63      1
 2.91305202E+00 1.64659937E-03-6.88625686E-07 1.21039677E-10-7.84035796E-15    2
-1.41808768E+04 6.71054299E+00 3.56838038E+00-8.52129500E-04 2.48918819E-06    3
-1.56331996E-09 3.13598127E-13-1.42842550E+04 3.57912028E+00                   4

END

REACTIONS    KCAL/MOLE   MOLES

CO = CO                                2.890000e+09 1.160     82.100   
 
END
```
chem-surface-works.inp
```
SITE   SDEN/2.9E-9/
    PT(S)
    CO(S)
END

THERMO ALL
  300.0   1000.0   3000.0
PT(S)                   PT  1               S    300.0    3000.0  1000.0       1
 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00    2
 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00    3
 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00                   4

CO(S)                  0C   1O   1PT  1     S    298.0    3000.0  1138.4       1
 3.30157467E+00 3.22585673E-03-1.64522037E-06 3.97203847E-10-3.71825129E-14    2
-3.52648108E+04-1.68693853E+01 7.42447308E-02 1.58440607E-02-2.12660054E-05    3
 1.44089301E-08-3.83670599E-12-3.45484584E+04-1.10342685E+00                   4

END

REACTIONS    KCAL/MOLE   MOLES

! CO Oxidation
CO + PT(S) 	            <=>	CO(S)	                    1.00E+00	0.000	0.0! Hauptmann
STICK
COV/CO(S)   	                                        0.00        0.00    -15047.3

END
```
chem-surface-broken.inp
```
SITE   SDEN/2.9E-9/
    PT(S)
    CO(S)
END

THERMO ALL
  300.0   1000.0   3000.0
PT(S)                   PT  1               S    300.0    3000.0  1000.0       1
 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00    2
 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00    3
 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00                   4

CO(S)                  0C   1O   1PT  1     S    298.0    3000.0  1138.4       1
 3.30157467E+00 3.22585673E-03-1.64522037E-06 3.97203847E-10-3.71825129E-14    2
-3.52648108E+04-1.68693853E+01 7.42447308E-02 1.58440607E-02-2.12660054E-05    3
 1.44089301E-08-3.83670599E-12-3.45484584E+04-1.10342685E+00                   4

END

REACTIONS    KCAL/MOLE   MOLES

! CO Oxidation
CO + PT(S) 	            <=>	CO(S)	                    1.00E+00	0.000	0.0! Hauptmann
STICK
REV/			                                        6.12E+14	0.39	41320.4/
COV/CO(S)   	                                        0.00        0.00    -15047.3

END
```

The broken one with the extra `REV` line creates a `reaction` for the explicit reverse instead of a `surface_reaction` in the resulting `cti` file.  The archive contains all the files and a demo shell script.

**Comment by ischoegl** [comment]
@rwest ... thanks for the minimal example. With a (minimal) fix, I get
```
$ sh demo.sh 
27a28
> REV/			                                        6.12E+14	0.39	41320.4/
Wrote CTI mechanism file to 'chem-works.cti'.
Mechanism contains 1 species and 2 reactions.
Validating mechanism...PASSED.
Wrote CTI mechanism file to 'chem-broken.cti'.
Mechanism contains 1 species and 3 reactions.
Validating mechanism...PASSED.
65c65
< surface_reaction('CO + PT(S) <=> CO(S)', stick(1.000000e+00, 0.0, 0.0),
---
> surface_reaction('CO + PT(S) => CO(S)', stick(1.000000e+00, 0.0, 0.0),
66a67,70
> 
> # surface1 Reaction 2
> surface_reaction('CO(S) => CO + PT(S)', [6.120000e+14, 0.39, 41320.4],
>                  id='surface1-2')
```
