### ISSUE TITLE
Conservation of Nitrogen Atoms Violation

### ISSUE THREAD

**Issue by corchise** [Cantera/cantera#655]
### Cantera version
2.4
### Operating System
Linux 3.10.0-862.14.4.el7.x86_64 
### Python/MATLAB version
Python 3.6.4 :: Anaconda, Inc.

### Expected Behavior
Atoms are conserved throughout the steady state, laminar, premixed flame.
### Actual Behavior
The number of atoms of Nitrogen at least are not constant throughout said flame, varying by more than 0.5% (See attached spreadsheet)

### Steps to reproduce
1. Run the attached 1D flame case using GRI 3.0 (issue has also been observed on other mechanisms)
2. Analyze the resulting output spreadsheet for conservation of N atoms.

[conservation_of_atoms_violation_example.zip](https://github.com/Cantera/cantera/files/3307583/conservation_of_atoms_violation_example.zip)

**Comment by bryanwweber** [comment]
Is this the same post error as https://groups.google.com/forum/#!topic/cantera-users/N4tRNRgS3fo?

**Comment by decaluwe** [comment]
Yes, I assume so. It is the same user, at least. I view this as the appropriate avenue to address the concern, though.

**Comment by corchise** [comment]
Yes, I also posted that.  Another member of the lab I work in has noticed a similar issue in counterflow diffusion flames, but I don't have an example for that at the moment. It's also with the amount of Nitrogen not following expected behaviour.

**Comment by bryanwweber** [comment]
@corchise Has this been resolved by the post on the Google Group?

**Comment by corchise** [comment]
Ah yes, sorry.
