### ISSUE TITLE
BinarySolutionTabulatedThermo should use snake_case in Python

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#658]
### Cantera version
2.5.0a2

Some of the variables and class names associated with the new `BinarySolutionTabulatedThermo` classes use camelCase in Python, rather than the standard TitleCase (for class names) or snake_case (for variable and function names). In my opinion, we should conform to usual Python standards here. These will need to be changed in ctml_writer.py and cti2yaml.py.

From a comment by @speth 

> If you want to fix the camelCasing of the new classes / arguments associate[d] with the addition of the `BinarySolutionTabulatedThermo` class, it will have to be done both here and in ctml_writer. I think we can make this change, since the class is new with this version of Cantera, but this should probably be brought up with @decaluwe.

@decaluwe Please also provide your thoughts 😃

**Comment by ischoegl** [comment]
It appears that this issue is isolated to a single name definition in the CTI input (`moleFraction` vs `mole_fractions` used elsewhere).

**Comment by ischoegl** [comment]
Issue should be closed per discussion of #753
