### ISSUE TITLE
The build script requires NumPy and ruamel_yaml for YAML conversions

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#662]
### Cantera version
2.5.0a3 (with YAML PR merged)

### Operating System
Any

### Python/MATLAB version
Any

With the new YAML input files, we are converting CK input files to YAML with the ck2yaml.py script during the build process. This script requires NumPy and ruamel_yaml (or ruamel.yaml), even if the Python interface is not being built. These packages should be checked for during the build process and a useful error message should be shown to the user. The current behavior is a `ModuleNotFoundError` on the first attempted conversion.

**Comment by bryanwweber** [comment]
Related to #669

**Comment by band-a-prend** [comment]
I recently tried to build cantera from git archive (>1 month old archive) and build process continued after several errors `ModuleNotFoundError` without `ruamel-yaml` package installed within local build environment. But the build process failed in gentoo package build environment after first such error. I.e. the `ruamel-yaml` and  the `numpy` packages are mandatory during build process even if user doesn't want to build cantera python interface while at this case the mentioned packages are not required by C++ interface runtime environment.

Thus at current state for gentoo package if converted yaml files are required for tests or for examples they seem to be added via patching as ready files before build process and the section for conversation should be then removed from SConstruct script. It's to avoid of unnecessary packages to be installed to build C++ interface.
