### ISSUE TITLE
Update ic_engine.py example

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#665]
### Cantera version

2.4 / 2.5a3

### Operating System

all

### Python/MATLAB version

python

### Expected Behavior

The example should run simulations in an efficient manner (i.e. use `Func1` routines for valve train and injection timing)

### Actual Behavior

Implementing valve train and injection in the main simulation loop (between sim.advance steps) requires a time step that is set much smaller than necessary, making the example highly inefficient.

### Steps to reproduce
1. run stock example `ic_engine.py`

**Comment by bryanwweber** [comment]
Could you be more specific about where `Func1` routines should be used? When Python functions are passed to methods like `set_velocity()` it is equivalent to directly creating a `Func1` class instance (to my understanding). I think the example could certainly be improved (and see the comments on #587 as well) but I'm not sure what you mean here.

**Comment by ischoegl** [comment]
The `Func1` approach should be used for `inlet_valve.set_valve_coeff`, `outlet_valve.set_valve_coeff` and ` injector_mfc.set_mass_flow_rate`. I haven't run any tests yet, but there is potential to simplify (eliminate?) the refinement machinery also (using the newly implemented `r.set_advance_limit` capabilies). I will submit a PR before long.

**Comment by ischoegl** [comment]
@bryanwweber ... I ran some tests and realized that `Func1` for valves does not accept time as an input, which effectively blocks this approach. I consider this a bug, as the `set_valve_coeff` should replace the valve coefficient, not replace the valve equation, see:
```C++
void Valve::updateMassFlowRate(double time)
{
    if (!ready()) {
        throw CanteraError("Valve::updateMassFlowRate",
                           "Device is not ready; some parameters have not been set.");
    }
    double delta_P = in().pressure() - out().pressure();
    if (m_func) {
        m_mdot = m_func->eval(delta_P);
    } else {
        m_mdot = m_coeffs[0]*delta_P;
    }
    m_mdot = std::max(m_mdot, 0.0);
}
```
Imho, the function should be implemented as:
```C++
void Valve::updateMassFlowRate(double time)
{
    if (!ready()) {
        throw CanteraError("Valve::updateMassFlowRate",
                           "Device is not ready; some parameters have not been set.");
    }
    double delta_P = in().pressure() - out().pressure();
    if (m_func) {
        m_mdot = m_func->eval(time)*delta_P;
    } else {
        m_mdot = m_coeffs[0]*delta_P;
    }
    m_mdot = std::max(m_mdot, 0.0);
}
```

PS: the python documentation does describe the implemented behavior, which, however, does not correspond to the expected function name.

**Comment by bryanwweber** [comment]
Thanks @ischoegl I think this is probably what @speth was referring to on #587

**Comment by ischoegl** [comment]
Correct. As @speth commented

> The other is to set the parameters from a function that is called as part of the ODE evaluation, e.g. the way we allow MassFlowController to have a mass flow rate as a function of time.

I opened a new issue (#666) that seeks to clarify some of the inconsistencies of the interface.
