### ISSUE TITLE
Inconsistent parameter names in equilibrate

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#675]
### Cantera version

2.5.0a3

### Operating System

all

### Python/MATLAB version

Python 3.6

### Expected Behavior

Calling `equilibrate` for `ThermoPhase` or `Mixture` objects should use consistent parameter names. 

### Actual Behavior

`ThermoPhase.equilibrate` takes `maxsteps`, `maxiter` and `loglevel`, whereas `Mixture.equilibrate` takes `max_steps`, `max_iter` and `log_level`. For consistency, one or the other should be deprecated.

### Steps to reproduce
1. Open python console and run
```
import cantera as ct
print(ct.ThermoPhase.equilibrate.__doc__)
print(ct.Mixture.equilibrate.__doc__)
```
As an aside: issue #130 may be closed.

**Comment by sameshl** [comment]
I would like to work on this. @bryanwweber should I deprecate `maxsteps` or `max_steps`?

**Comment by ischoegl** [comment]
My thoughts on this are that `ThermoPhase.equilibrate` is probably being used more commonly, i.e. less existing code will be affected if the parameters are changed from `max_steps` to `maxsteps`. Also, a `DeprecationWarning` should be raised.

**Comment by sameshl** [comment]
@ischoegl Cool. Will make that change

**Comment by speth** [comment]
I would agree that `ThermoPhase.equilibrate` is probably more frequently used. However, I doubt that these arguments are used very often.

I think the names with the underscores are more in accordance with [PEP8](https://www.python.org/dev/peps/pep-0008/), so there is an argument for that set of names.

**Comment by sameshl** [comment]
I would like to take this up, but can you explain how to use `DeprecationWarning` for keyword arguments?

**Comment by ischoegl** [comment]
A fix is straightforward: rename parameters and add `**kwargs` to the argument list. Then, check for old parameter names in this dictionary ... if one is found, reassign and use the `warnings` module. I added some `DeprecationWarnings` in `reactor.pyx` recently. This shouldn’t take more than a couple of lines.

**Comment by sameshl** [comment]
@ischoegl Thanks for the explanation. Will make the required change
