### ISSUE TITLE
CanteraError thrown by CVodesIntegrator::step: CVodes error encountered. Error code: -3

### ISSUE THREAD

**Issue by shenghuiqin** [Cantera/cantera#697]
### I got the CVodes error, and go back to change corresponding temperature (eg, error point is at Temperature=823.2, I changed it into T=823), and the problem solved
 * need to mention, I have a series T to do simulation, [999.45, 929.5, 882.31, 823.2, 744.24], but only the datapoint T=823.2 got the error, so people like me don't know how to debug could use this way to let cantera continue working.

**Comment by ischoegl** [comment]
Without knowing further details, it is quite difficult to figure out the context of this error (i.e. provide a test script, etc.). I'd also encourage you to ask on [Cantera's user group](https://groups.google.com/forum/#!forum/cantera-users) first, and post a specific issue here only once the exact cause is identified.

PS: with regard to your note about debugging, there may be a point of converting CVodes error code numbers to plain text.

**Comment by shenghuiqin** [comment]
thanks for your advice

**Comment by ischoegl** [comment]
It may make sense to post a specific issue regarding the CVodes error code conversion as a Feature request. Regarding the user group, it gets more traffic than the issue tracker ...

**Comment by shenghuiqin** [comment]
I follow this instruction :
https://groups.google.com/forum/#!searchin/cantera-users/https$3A$2F$2Fgithub.com$2FCantera$2Fncm-2019-materials$2Fblob$2Fmaster$2Fthermo_debugging.ipynb%7Csort:date/cantera-users/9kA7C5GJ-qs/BUyBPtC3BAAJ
using this tool (https://groups.google.com/forum/#!searchin/cantera-users/https$3A$2F$2Fgithub.com$2FCantera$2Fncm-2019-materials$2Fblob$2Fmaster$2Fthermo_debugging.ipynb%7Csort:date/cantera-users/9kA7C5GJ-qs/BUyBPtC3BAAJ)
found too high k values of my cit file, removed them and solved the problem!

**Comment by speth** [comment]
For what it's worth, the error messages already contain the translation of the error code to (more or less) human readable form. For instance, in the error:
```
CanteraError: 
***********************************************************************
CanteraError thrown by CVodesIntegrator::step:
CVodes error encountered. Error code: -3

At t = 0.000295852 and h = 9.29322e-16, the error test failed repeatedly or with |h| = hmin.
Components with largest weighted error estimates:
660: 141.876
657: -122.15
7: 8.71207
2: -0.00422197
664: 0.000340841
661: -0.000103909
14: 2.29653e-05
665: 1.91783e-05
663: 1.54839e-05
76: 1.78792e-06
***********************************************************************
```

The error code of -3 corresponds to "At t = xxxxx and h = yyyyy, the error test failed repeatedly or with |h| = hmin.".

**Comment by 9527Andrew** [comment]
Everybody who knows that how to solve the following error:
*******************************************************************************
CanteraError thrown by CVodesIntegrator::integrate:
Maximum number of timesteps (20000) taken without reaching output time (233.20000000000002).
Current integrator time: 233.14664459131703
******************************************************************************* 
Software version: Matlab/Simulink 2022b, Cantera 3.0.0.
