### ISSUE TITLE
Update issue templates

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#698]
The Github repo uses an [old version of issue templates](https://github.com/Cantera/cantera/blob/master/ISSUE_TEMPLATE.md). The new [issue template workflow](https://help.github.com/en/articles/about-issue-and-pull-request-templates) appears to allow for differentiation of __Bug Reports__ and __Feature Request__ (potentially more). 

There also is a [SUPPORT file](https://help.github.com/en/articles/adding-support-resources-to-your-project) that may be useful in redirecting generic inquiries to the user group.

**Comment by bryanwweber** [comment]
@ischoegl any reason to close this?

**Comment by ischoegl** [comment]
@bryanwweber ... not sure that it belongs here.

**Comment by ischoegl** [comment]
Just looked into this on another repo. This is what the default templates look like ... [commit containing template defaults](https://github.com/ischoegl/cantera-toolchain/pull/1/commits/228b3ca041203f87df6a0f6516cef8e1b7224228). The SUPPORT.md file is also straight-forward.  

~~It probably needs to be set up by someone having access to the repo settings though (there are some switches that aren't handled by the commit, e.g. assigning labels automatically)~~ ... actually, it's all there. I may suggest something before long.
