### ISSUE TITLE
scons: *** [build\src\base\AnyMap.o] Error 1

### ISSUE THREAD

**Issue by Austin-Bell269** [Cantera/cantera#702]
### Cantera version
2.5.0a3

### Operating System
Anaconda

### Python/MATLAB version
3.7.4

### Expected Behavior
AnyMap.o would build

### Actual Behavior
scons: *** [build\src\base\AnyMap.o] Error 1
scons: building terminated because of errors

### Steps to reproduce
1. I followed these steps "https://github.com/ischoegl/cantera-toolchain/blob/master/win10-conda-VS.md#create-a-conda-environment"

If anyone has a solution to this I would deeply appreciate it.

**Comment by ischoegl** [comment]
What Windows / Visual Studio version are you using? Also, please attach a more complete log (cut and paste into a file and attach), so it's clear what actually caused the compilation error.

**Comment by Austin-Bell269** [comment]
I am using windows 10, as well as visual studio 2019. I apologize I don't know what you mean by a log. What I did was get to the scons build stage and finally got passed the boost file error I previously talked to you about. but after this build error occurred. I have attached what the screen looks like.
![Screenshot (145)](https://user-images.githubusercontent.com/52332777/63472551-62b04a80-c427-11e9-9845-9a85d9046799.png)

**Comment by Austin-Bell269** [comment]
by the way, the error message is at the bottom.

**Comment by Austin-Bell269** [comment]
I created a list of the exact steps I have taken and attached it here. sorry for the barrage of messages.
[Steps I have taken to get Cantera to run so far.docx](https://github.com/Cantera/cantera/files/3527609/Steps.I.have.taken.to.get.Cantera.to.run.so.far.docx)

**Comment by ischoegl** [comment]
ok. that's at the very beginning, which points at some small step you may have missed (or may not have been clear in my instructions): it is essential that you locate the *equivalent* of 
```
CALL %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
```
(it may be slightly different on your system), and, - after creating the environment, - to activate it.

Based on what you posted, I don't think that there is an issue with scons (or cantera), and thus this should probably be handled on the user forum. I'll update the instructions based on the outcome.

PS: the log is just the output you see above, albeit saved as a text file :wink:

**Comment by Austin-Bell269** [comment]
I have looked for that file and the file address is the same as yours. when I used that command with that address it ran fine. it was not until I tried to do the "scons build" command after accessing the cantera-dev environment. That is where that error had occured . I have attached the config.log file here lol thanks 
[file C.docx](https://github.com/Cantera/cantera/files/3527631/file.C.docx)

**Comment by ischoegl** [comment]
Boost is missing from your environment. Did you have it in your setup, i.e.
```
conda create -n cantera-dev scons numpy cython ruamel_yaml libboost git
```
Also, as mentioned, the issue tracker is probably not the right venue ...

**Comment by Austin-Bell269** [comment]
I posted in the cantera group chat on google. it will pop up in a while, I will talk more over there. I did use that though and was able to get the environment. I will try it again though

**Comment by ischoegl** [comment]
:+1:

**Comment by bryanwweber** [comment]
@Austin-Bell269 can you please repost your message to the Google Group where you copy the terminal output text either directly into the post or into a text file attached to the post? There are a couple of reasons for this, the biggest one being that text in images can't be found in a search, so the next person who has this problem has to ask the same question. Also, visually impaired folks can't read the image at all. Thank you!

**Comment by Austin-Bell269** [comment]
ok I apologize I will post again
