### ISSUE TITLE
Problems with code coverage

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#703]
### Steps to reproduce
1. Open a pull request
2. Push commits multiple times
3. Coverage changes on files that weren't modified in the pull request

This seems to be a problem with the file `src/transport/GasTransport.cpp`. It is not clear why the coverage should be changing in this file. We should look at what is changing and try to fix either the test suite or the code to resolve this issue.

**Comment by bryanwweber** [comment]
The comments here https://github.com/Cantera/cantera/pull/693#issuecomment-529120245 are a good example of what can happen

**Comment by speth** [comment]
The change in coverage that's being reported is in `GasTransport::getMixDiffCoeffsMole`:

```c++
if (!m_bindiff_ok) {
   updateDiff_T();
}
```

Where the conditional is apparently reached 10 times in the test suite, and the predicate is reached either 0 or 1 time. What's strange is that I can only find two calls to `getMixDiffCoeffsMole` (or the Python property `mix_diff_coeffs_mole`) in the test suite. These occur in the Python test `TestTransport.test_mixtureAveraged`:

```python
    def test_mixtureAveraged(self):
        self.assertEqual(self.phase.transport_model, 'Mix')
        Dkm1 = self.phase.mix_diff_coeffs
        Dkm1b = self.phase.mix_diff_coeffs_mole
        Dkm1c = self.phase.mix_diff_coeffs_mass
        Dbin1 = self.phase.binary_diff_coeffs

        self.phase.transport_model = 'Multi'
        Dkm2 = self.phase.mix_diff_coeffs
        Dkm2b = self.phase.mix_diff_coeffs_mole
        Dkm2c = self.phase.mix_diff_coeffs_mass
        Dbin2 = self.phase.binary_diff_coeffs
        self.assertArrayNear(Dkm1, Dkm2)
        self.assertArrayNear(Dkm1b, Dkm2b)
        self.assertArrayNear(Dkm1c, Dkm2c)
        self.assertArrayNear(Dbin1, Dbin2)
        self.assertArrayNear(Dbin1, Dbin1.T)
```

I think this test should always exercise the code path that does not update the binary diffusion coefficients (they should be updated by earlier access to `mix_diff_coeffs`).
