### ISSUE TITLE
Python SpeciesThermo wrapper classes missing for NASA9 and piecewise Gibbs (Mu0Poly)

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#705]
In `speciesthermo.pyx`, wrapper classes are defined for the most commonly used species thermo models (`NasaPoly2`, `ShomatePoly2`, and `ConstantCp`) but not for the other available models (`Nasa9PolyMultiTempRegion` and `Mu0Poly`).

**Comment by ischoegl** [comment]
PR #711 adds the wrappers (plus a missing C++ constructor).
