### ISSUE TITLE
Nothing to check or ensure that Sticking Coefficients are in the range [0,1]

### ISSUE THREAD

**Issue by rwest** [Cantera/cantera#717]
### Summary
Cantera doesn't check or ensure that Sticking Coefficients are in the range [0,1].

The documentation both at
at https://cantera.github.io/docs/sphinx/html/cti/reactions.html#sticking-coefficients
and https://cantera.org/science/reactions.html#sticking-coefficients
states

> "The values of these constants must be specified so that the sticking coefficient γ is between 0 and 1 for all temperatures.“

but the code does nothing to enforce or check this.

### Cantera version
2.3.0 (and earlier)

### Operating System
All

### Expected Behavior

Copying the CHEMKIN approach would be one option, and may be what some users expect.

The 1996 Sandia technical report manual to SURFACE CHEMKIN-III  https://doi.org/10.2172/481906 page 38 has a footnote
“CAUTION: Because γi is defined as a probability, it must lie between 0 and 1 to make physical sense. Therefore, SURFACE CHEMKIN-III checks the value of γi, and an unphysical sticking coefficient greater than 1 is changed to the value 1. Some earlier versions of SURFACE CHEMKIN did not truncate the values at 1."
It seems this note is also in [more recent versions](http://www.cvd.louisville.edu/Course/Chemical%20Vapour%20Deposition/Manuals/chemkin/chemkin11surfacechemkin.pdf) of the commercial Chemkin manual.

The CHEMKIN definition is thus
<img width="344" alt="Screen Shot 2019-10-01 at 4 43 39 PM" src="https://user-images.githubusercontent.com/93807/65999065-a193e000-e46a-11e9-9404-9893d9f840d1.png">
whereas the Cantera definition is this
<img width="162" alt="Screen Shot 2019-10-01 at 4 58 41 PM" src="https://user-images.githubusercontent.com/93807/66000148-d3a64180-e46c-11e9-8359-658e611d61b0.png">

Another option would be to include a sanity/consistency/validation check, a bit like when negative A factors are encountered.  This could at very least give the user a warning. Or it could raise an error unless users add a special flag to "allow greater than 1".

Or some hybrid: allow greater than 1 if the user specifies it with a flag, else truncate it. 
Or truncate it if the user specifies with a flag. 
Probably the code that translates from CHEMKIN files (ck2cti or ck2yaml) should set whatever flags reproduce the CHEMKIN behaviour?

### Actual Behavior

As far as I can tell from [this](https://github.com/Cantera/cantera/blob/c4aff04418851d159ae9ca7709f823b3969b15d7/src/kinetics/InterfaceKinetics.cpp#L619) bit of code, Cantera does nothing to enforce or check that sticking coefficients are between 0 and 1. If parameters are provided that evaluate to 1e8 at some temperature, then very non-physical (and probably stiff) rates will result.

**Comment by ischoegl** [comment]
While #1038 fixes this for reactions that do not specify coverage dependencies, the approach will not work when those are provided? (This came up when porting code in #1181). @rwest / @12Chao ... 

I am mostly posting to see whether there are any suggestions to resolve this?
