### ISSUE TITLE
Setting the state of PureLiquidWater with T,P raises a CanteraError

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#721]
### Cantera version
2.5.0a3

### Operating System
macOS, but probably not specific

### Python/MATLAB version
3.7, but probably not specific

### Expected Behavior
Setting the state of `PureLiquidWater` with T, P works when going from gas to liquid states

### Actual Behavior
Setting the state of `PureLiquidWater` with T, P raises a `CanteraError` when going from gas to liquid states

### Steps to reproduce
```In [1]: import cantera as ct

In [2]: water = ct.PureFluid('/Users/bryan/GitHub/cantera/build/python/cantera/test/data/liquid-water.xml')

In [3]: water.TP
Out[3]: (300.0, 101325.00046662119)

In [4]: water.TP = 2000, ct.one_atm

In [5]: water.TP = 298, ct.one_atm
---------------------------------------------------------------------------
CanteraError                              Traceback (most recent call last)
<ipython-input-5-c5704cc5079b> in <module>
----> 1 water.TP = 298, ct.one_atm

~/GitHub/cantera/interfaces/cython/cantera/thermo.pyx in cantera._cantera.ThermoPhase.TP.__set__()
   1030             T = values[0] if values[0] is not None else self.T
   1031             P = values[1] if values[1] is not None else self.P
-> 1032             self.thermo.setState_TP(T, P)
   1033
   1034     property TPX:

CanteraError:
***********************************************************************
CanteraError thrown by setPressure:
error: dens = 0.109769, rc = 322, waterState = 0
***********************************************************************

In [6]: water.density
Out[6]: 0.10976927970023702

In [7]: water.critical_density
Out[7]: 322.0

In [8]: water.TP
Out[8]: (298.0, 14910.063602909962)

In [9]: water.TP = 2000, ct.one_atm

In [10]: water.density
Out[10]: 0.10976927970023702

In [11]: water.TP
Out[11]: (2000.0, 101325.00000000144)
```

(I modified the function to produce more useful error output)

The definition of the relevant function is:

https://github.com/Cantera/cantera/blob/fe7be79552433c3779ffbd5b018a493114fffdbc/src/thermo/WaterSSTP.cpp#L267-L281

where `WATER_GAS` is defined as `0`.

One possible solution is to check the value of the pressure passed in relative to the saturation pressure at the system temperature and determine the guessed phase that way, depending on how the saturation pressure is defined.

**Comment by ischoegl** [comment]
I'm not very familiar with non-standard water classes. However, `WaterSSTP` contains some references that it is intended for liquid water, e.g.
https://github.com/Cantera/cantera/blob/fe7be79552433c3779ffbd5b018a493114fffdbc/include/cantera/thermo/WaterSSTP.h#L277-L283

**Comment by bryanwweber** [comment]
As it turns out, handling this error in a coherent manner is about one step beyond where I feel comfortable at the moment. I looked into fixing this, but I don't really understand what is going on in the class. A few notes for future investigators:

1) The `WaterSSTP` phase, as implied by the name in the XML file (`PureLiquidWater`), is intended to represent only the liquid states of water. It is based on the `WaterPropsIAPWS` class, which can represent liquid to vapor states, but the `WaterSSTP` class is used in a few places where liquids only are the assumption. Hypothetically, a different class that implements the full behavior of the EOS could be written using `WaterPropsIAPWS`, but this ain't it.
2) The real problem here is not that the solver can't get back to a liquid state after being set to a gas state, but that it is able to be set to a gas state at all (see the previous point).
3) The `WaterPropsIAPWS` class provides the `phaseState()` method, which returns an integer representing the phase (liquid, vapor, etc.). Presumably, this could be checked to ensure a state consistent with the assumptions of `WaterSSTP` is set.
4) It would be really nice if setting the state were atomic; in this case, the failure to set `TP` still results in changing `T`, but at the current value of the density.
5) Forcing the density guess in `WaterSSTP::setPressure()` to be `1000.` results in the density solver finding liquid states even for pressures well below the saturation pressure (e.g., T=500, p=101325 results in a liquid phase, despite p_sat=26 bar). The `WaterPropsIAPWS` class can allegedly represent unstable (metastable?) states by checking against the spinodal, but for the cases I checked, `phaseState()` still returned that the phase was a liquid.

**Comment by bryanwweber** [comment]
Also, there's this bit from `WaterSSTP.h`:
https://github.com/Cantera/cantera/blob/fe7be79552433c3779ffbd5b018a493114fffdbc/include/cantera/thermo/WaterSSTP.h#L277-L283

which is initialized to `false` and then never checked again.

**Comment by ischoegl** [comment]
I believe that Cantera/enhancements#6 deserves additional thoughts :wink:

**Comment by ischoegl** [comment]
To provide additional detail, the `Phase::setState_TP` routine first calls `WaterSSTP::setTemperature`, which changes temperature at constant density (i.e. here is where the state changes to `WATER_GAS`). The second step involves calling `WaterSSTP::SetPressure`, which is where the error is thrown.
