### ISSUE TITLE
AttributeError: 'cantera._cantera.Valve' object has no attribute 'set_time_function'

### ISSUE THREAD

**Issue by sajit5678** [Cantera/cantera#728]
### Cantera version
'2.3.0'
### Operating System
Windows7
### Python/MATLAB version
Python
### Steps to reproduce
1.
2.
3.

**Comment by bryanwweber** [comment]
Hi, thanks for posting here. Can you please fill out the rest of the suggested template, especially the part asking for the steps to reproduce this error?

**Comment by ischoegl** [comment]
Could it be that this error occurs for the example posted here: [https://cantera.org/examples/python/reactors/ic_engine.py.html](https://cantera.org/examples/python/reactors/ic_engine.py.html)?

**Comment by sajit5678** [comment]
> Could it be that this error occurs for the example posted here: https://cantera.org/examples/python/reactors/ic_engine.py.html?

Yes this is the example. 
Also, another error is:
`inlet_valve.valve_coeff = inlet_valve_coeff`
gives AttributeError: 'cantera._cantera.Valve' object has no attribute 'valve_coeff'
If valve_coeff is set like this 
`inlet_valve.set_valve_coeff(inlet_valve_coeff)` , it works

**Comment by ischoegl** [comment]
This example requires a newer version of cantera (development version, I.e. v2.5a3). Please use the version that comes with your installation (v2.3) instead.

**Comment by sajit5678** [comment]
@ischoegl Thank you very much for your time and advice.

**Comment by ischoegl** [comment]
You’re welcome.

**Comment by bryanwweber** [comment]
Hmmm I guess we never sorted out how we wanted to handle this on the website side of things. Guess we'd better do that... Related to Cantera/cantera-website#86

**Comment by bryanwweber** [comment]
Thank you @ischoegl for helping out here!

**Comment by ischoegl** [comment]
@bryanwweber ... no problem. Yes, I think you had anticipated version conflicts as a potential issue. I believe that simply adding a version dependence to the example description may be an effective precaution (already added a PR towards that end).
