### ISSUE TITLE
Heat flux through the wall is not working for certain conditions

### ISSUE THREAD

**Issue by mjrahimi** [Cantera/cantera#730]
### Cantera version
2.4.0
### Operating System
macOS
### Python/MATLAB version
3.7.2
### Expected Behavior
The heat flux function defined for the wall should transfer heat from reactor 1 to reactor 2. Therefore increasing the temperature in reactor 2.
### Actual Behavior
The temperature does not change for any of the reactors. 
### Steps to reproduce
```python
import numpy as np
import cantera as ct
import matplotlib.pyplot as plt
def qdot(t):
    t0 = 50e-3
    t1 = t0+10e-3
    return 5e5*(np.sign(t-t0)-np.sign(t-t1))
gas1 = ct.Solution('gri30.xml')
gas1.TPX = 1000.0, ct.one_atm, 'N2:1'
gas2 = ct.Solution('gri30.xml')
gas2.TPX = 1000.0, ct.one_atm, 'N2:1'
r1 = ct.IdealGasReactor(gas1)
r1.volume = 0.5
r2 = ct.IdealGasReactor(gas2)
r2.volume = 1.0
w = ct.Wall(r1, r2, A=10,Q=qdot)
sim = ct.ReactorNet([r1, r2])
states1 = ct.SolutionArray(r1.thermo, extra=['t'])
states2 = ct.SolutionArray(r2.thermo, extra=['t'])
for n in range(100):
    time = (n+1)*0.001
    sim.advance(time)
    states1.append(r1.thermo.state, t=1000*time)
    states2.append(r2.thermo.state, t=1000*time)
plt.figure(1)
plt.plot(states1.t, states1.T, 'b-',label='r1')
plt.plot(states2.t, states2.T, 'r-',label='r2')
plt.legend()
plt.xlabel('Time (ms)')
plt.ylabel('Temperature (K)')
plt.show()
```

![fig1](https://user-images.githubusercontent.com/26416064/67149414-40407f00-f268-11e9-8cfe-697b0149b28a.png)

### Extra step to find the Bug
Adding a mass flow controller seems to suddenly activate the heat flux.
By adding this line after the wall definition:
```python
mfc=ct.MassFlowController(r1, r2, mdot=0.1)
```
![fig2](https://user-images.githubusercontent.com/26416064/67149506-34a18800-f269-11e9-9776-395dcbcdff2d.png)

**Comment by bryanwweber** [comment]
Hi! Thanks for this report. We'll investigate and let you know if we have any further questions.

**Comment by ischoegl** [comment]
Since there aren't any changes in your network, the integrator that solves the 0D network starts to take large time steps, thus missing the timed heat transfer function you implemented. Adding this
```python
sim.set_max_time_step(1e-3)
```
after the creation of the network should fix things for you (I tested this on the development branch of cantera, but do not expect any difference for 2.4).

I.e. the only issue that may remain is that the default setting for `max_time_step` may be too high (none is used by default).

**Comment by mjrahimi** [comment]
Thanks @ischoegl. That worked for me as well. I think the ReactorNet max_time_step should not exceed the sim.advance(time) marching steps. May be helpful to internally force that limitation.

**Comment by ischoegl** [comment]
> I think the ReactorNet max_time_step should not exceed the sim.advance(time) marching steps. May be helpful to internally force that limitation.

The current implementation reinitializes the system every time `max_time_step` is changed. I haven't looked beyond `ReactorNet::setMaxStep`, but I am afraid that continuously enforcing step size may interfere with the inner workings of CVODE. Imho, not letting the time step grow arbitrarily large (which is the current default behavior) may be sufficient.

**Comment by ischoegl** [comment]
per @bryanwweber's comment in #731
> I think it is on the user to determine for their use case if that needs to be limited somehow. I don't think we can pick a value that is both 1) large enough that we don't limit the CVODES unnecessarily and 2) small enough to actually effect any change.

I agree that this rationale for leaving the behavior as is is sound.
