### ISSUE TITLE
Cython: functions routed through wrapper.h do not display C++ errors & warnings

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#746]
**System information**

- Cantera version: 2.5.0a3
- OS: Ubuntu 18.04 LTS (all?)
- Python/MATLAB version: Python 3.6

**Expected behavior**

Errors and warnings issued in C++ layer should be raised/displayed on the Python console

**Actual behavior**

Errors and warnings are not raised/displayed for any function routed through `cython/wrapper.h`

**To Reproduce**

1. Example: add `warn_deprecated` or `warn_user` to `Phase::setMoleFractions` and compile
2. Open Python and run
```
In [1]: import cantera as ct
   ...: sol = ct.Solution('interfaces/cython/cantera/test/data/thermo-models.yaml', 'NaCl(s)')
   ...: 

In [2]: sol.X = 1

In [3]: sol.X = 'NaCl(s): 1.'
[warning message is displayed]
```

3. **Edit:** Same for C++ errors: add `CanteraError` to `Phase::setMoleFractions` and compile
4. Open Python and run
```
In [1]: import cantera as ct
   ...: sol = ct.Solution('interfaces/cython/cantera/test/data/thermo-models.yaml', 'NaCl(s)')
   ...: 

In [2]: sol.X = 1

In [3]: sol.X = 'NaCl(s): 1.'
CanteraError: 
***********************************************************************
CanteraError thrown by [...]
***********************************************************************
```

**Additional context**

The root cause is in the `property X` setter:
```python
        def __set__(self, X):
            if isinstance(X, (str, bytes)):
                self.thermo.setMoleFractionsByName(stringify(X))
            elif isinstance(X, dict):
                self.thermo.setMoleFractionsByName(comp_map(X))
            else:
                self._setArray1(thermo_setMoleFractions, X)
```
where the `In [2]` call is routed through `_setArray1` whereas the `In [3]` call goes directly to C++.

**Afterthought:** for functions routed through `wrapper.h` it would be relatively straight-forward to raise native python warnings.

**Comment by ischoegl** [comment]
@bryanwweber ... why no **bug** label? Errors/warnings passing *silently* (no user feedback whatsoever even if C++ throws an error(!)) is quite problematic. (worst case scenario: this behavior may mask existing unrelated bugs or undesired behaviors)

**Comment by bryanwweber** [comment]
Honestly, because I didn't read the issue closely 😄 Added now

**Comment by speth** [comment]
I think the diagnosis here is incorrect.

The reason that no warning or error from `Phase::setMoleFractions` is issued for the `NaCl(s)` phase, or any other phase which is implemented by the `SingleSpeciesTP` class, is because `SingleSpeciesTP` overrides `setMoleFractions` to do nothing, and the base class method is never called. If you use  `gri30.yaml` instead, you will see the warnings or errors as expected.

Also, I cannot replicate the behavior of seeing a warning or error from `Phase::setMoleFractions` for single-species phases when setting the mole fractions using a string or dict.

**Comment by ischoegl** [comment]
@speth ... this issue arose when I had manually added warnings/errors to the base classes for single species assignments (the code triggering this behavior is long gone). The override may explain the behavior, but I’m not convinced (I don’t recall details after two months). Not sure that it’s worth keeping this open.

**Comment by speth** [comment]
I'm not speculating based on how I think the code works. I verified this behavior myself.

**Comment by ischoegl** [comment]
@speth ... sorry if this came across wrong. No offense was intended.
