### ISSUE TITLE
'composite' Func in Matlab

### ISSUE THREAD

**Issue by ane-sh** [Cantera/cantera#752]
**System information**

- Cantera version: 2.4.0
- OS: Windows 10
- MATLAB version:

Following the post in the google group forum titled 'composite' Functor Matlab, the problem is with composing Functors. One member advised that the code was incorrectly written/implemented.

**To Reproduce**
Taking the example of a function (1- (sin(x)^2))^(1/2), the following code was used

```matlab
fs = Func('fourier',1,[0,0,1,1])  % sin(x)
fs2 = Func('prod',fs,fs)  % (sin(x)^2) 
fs2_1 = Func('diff',Func('polynomial',0,1),fs2)  % 1-(sin(x))^2 
sqrtF = Func('arrhenius',1,[1,0.5,0])  % sqrt function
% now is the challenging part
Func('composite', sqrtF, fs2_1)
```

**Actual behavior**
Either always results in 0 or NaN.
I also tried composing other (simpler) functions but to no avail.

Nonetheless, Cantera great software and indispensable in my toolbox.
Thanks
Aneesh

**Comment by bryanwweber** [comment]
Thank you for posting this issue! For reference, the Google Group discussion is at https://groups.google.com/forum/#!topic/cantera-users/I12aznWPpAk

**Comment by ischoegl** [comment]
Implementing the reported composite function after updates in #1513 in `clib` does not reproduce the error. 

At least when using `clib`, the correct correspondence - $\left|\cos(x)\right|$ - is reproduced.

**Comment by ischoegl** [comment]
Tested this after merging #1513, which included a unit test for the exact example, see: https://github.com/Cantera/cantera/blob/25fee187c474210c14ff45e8647e20507843b075/test/clib/test_ctfunc.cpp#L256-L293
While the unit test passes, the MATLAB result for the composite function defined at the top is still incorrect, although it now yields different results:
```
>> fun = Func('composite', sqrtF, fs2_1)
 
fun = 
 
   0
 
>> fun(.5)

ans =

    0.6924

>> cos(.5)

ans =

    0.8776
```

**Comment by ischoegl** [comment]
As the issue is now isolated to the legacy MATLAB toolbox, which itself was removed via #1670, this will not be fixed.
