### ISSUE TITLE
Document requirements of Python examples

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#755]
The examples shown at https://cantera.org/examples/python/index.html do not list the required version of Cantera or other dependencies. This leads to problems when users try to run them with incompatible versions of Cantera (see #728). A standard method for documenting these requirements was established in #729, and implemented for the [ic_engine.py](https://github.com/Cantera/cantera/blob/master/interfaces/cython/cantera/examples/reactors/ic_engine.py) example, adding the line:
```
Requires: Cantera >= 2.5.0, scipy >= 0.19, matplotlib >= 2.0
```
to the script's docstring.

Similar `Requires:` sections should be added to the other Python examples. To simplify determining the appropriate minimum versions, I would suggest:
* the only Cantera versions that need to be checked are 2.4.0 and 2.5.0
* Cantera dependencies such as NumPy do not need to be documented unless an especially new version is required
* The minimum version of other dependencies can be just the minimum tested version, rather than having to install very old versions just for the sake of testing

**Comment by bryanwweber** [comment]
I believe this was completed in #768
