### ISSUE TITLE
ctml writer (I believe incorrectly) divides by factors of 10 for some surface pre-exponentials

### ISSUE THREAD

**Issue by AdityaSavara** [Cantera/cantera#760]
**System information**

- Cantera version: 2.4
- OS: Windows 10
- Python/MATLAB version: Python

**Expected behavior**
When ctml_writer operates on a cti file, we expect all of the Arrhenius factors (including pre-exponentials) to remain the same in the xml file generated. For example, A=3.7E21 should remain A=3.7E21.

**Actual behavior**
For some surface reactions, but not all, the pre-exponentials are divided by a factor of 10 during xml creation. For example: A=3.7e21 becomes A=3.7E20   .  The difference in capitalization is not the issue, the issue is 21 becomes 20.

**To Reproduce**

1. Open 'methane_pox_on_pt.cti' scroll to end and look at the very last pre-exponential in the file. 
2. Run 'cti_to_xml_script.py'
3. Open 'methane_pox_on_pt.xml' scroll to end and look at the very last pre-exponential in the file.
The values will be different as described above.

**Attachments**
See attached.

**Additional context**
This happens for some pre-exponentials but not others. This is not a cti file that I made, it is one of the cantera example files. I've renamed my xml to methane_pox_on_pt_my_output.xml so you can be assured when you run the script that you are really looking at a new file. I have not figured out what distinguishes the cases where it occurs versus not -- but it does seem to happen more often for A > 1E20.

[cti_to_xml_bug.zip](https://github.com/Cantera/cantera/files/3903409/cti_to_xml_bug.zip)

**Comment by bryanwweber** [comment]
Hi! Thank you for reporting this. Have you checked that the reaction rates calculated by Cantera are different than what you'd expect from a have calculation? ctml_writer adjusts the units of the A factor from the units in the CTI file to be SI units (except kmol instead of mol), and those units depend on the order of the reaction.

**Comment by AdityaSavara** [comment]
Hi Bryan, I agree a 'by hand' unit conversion should answer this question.  Someone with more knowledge would need to answer if I am mistaken about the expected behavoir. I did not see any differences in the units noted in the cti file or the xml file, and when I looked at the Deutschmann paper that the example came from, I had the impression that the surface reactions are supposed to be in relative coverage. In that case, it should just be per second.  I don't know what cantera does "under the hood" or during ctml creation. Does the site_density get removed during ctml creation, and surface pre-exponentials already get converted into molecules/m^2/s at the ctml stage?  Even then, it's not clear to me what is happening here since these are exact factors of 10^n and vary across different species (and, I thought cantera uses relative coverage to calculate surface rates, which means the ctml should be in the same units as the cti file, I think).  There is a setting of "Surface site density: 2.72E-9 mol/cm**2" , but what I observed looks more like a metric unit conversion factor. But if it's a metric unit conversion factor, then it is puzzling (to me) why some pre-exponentials are getting a factor of 10^1 and others 10^4.   I did find the following lines in the ctml_writer:

```
        # if a pure number is entered for A, multiply by the conversion
        # factor to SI and write it to CTML as a pure number. Otherwise,
        # pass it as-is through to CTML with the unit string.
        if isnum(self._c[0]):
            addFloat(a,'A',self._c[0]*self.unit_factor, fmt = '%14.6E')
        elif len(self._c[0]) == 2 and self._c[0][1] == '/site':
            addFloat(a,'A',self._c[0][0]/self.rxn_phase._sitedens,
                     fmt = '%14.6E')
        else:
            addFloat(a,'A',self._c[0], fmt = '%14.6E')
```
Though based on what I wrote above, it does not seem to me like what I observed was correct behavior.

**Comment by AdityaSavara** [comment]
Apparently, whether this is a bug or not, it does not cause any problems as long as one is only writing with cantera and reading with cantera (xml and cti file give same cantera object values, as shown below). So if there is a bug, it must exist in both directions.  I suppose this means that either it needs to be left alone or changed in both the writing and reading directions.

ct.Reaction.listFromFile("methane_pox_on_pt.xml")[35].rate
Out[29]: Arrhenius(A=3.7e+20, b=0, E=8.79e+07)

ct.Reaction.listFromFile("methane_pox_on_pt.cti")[35].rate
Out[30]: Arrhenius(A=3.7e+20, b=0, E=8.79e+07)

**Comment by AdityaSavara** [comment]
More info just to help anyone that tries to track the reason down... if we look at the example I attached... 
```
#the factor of 10^1 happens with these:
surface_reaction( "2 OH(S) => H2O(S) + O(S)",
                  Arrhenius(7.4e20, 0, 74000))

surface_reaction( "H2O(S) + O(S) => 2 OH(S)",
                  Arrhenius(1.0e20, 0, 43100,
                            coverage = ['O(S)', 0.0, 0.0, 240600]))

surface_reaction( "CH3(S) + OH(S) => CH4 + O(S) + PT(S)",
                  Arrhenius(3.7e21, 0, 87900))

#But it does not happen with these ones:
surface_reaction( "CH2(S) => C(S) + H2",
                  Arrhenius(7.69e13, 0, 25100,
                            coverage = ['C(S)', 0.0, 0.0, 50000]))


surface_reaction( "CO2(S) => CO2 + PT(S)",   [1.00000E+13, 0, 27100])

#These ones get a factor of 10^4 reduction rather than 10^1
surface_reaction( "CH4 + PT(S) + O(S) => CH3(S) + OH(S)",
                  Arrhenius(5.0e18, 0.7, 42000.0,
                            coverage = ['O(S)', 0.0, 0.0, 8000]))


surface_reaction( "O2 + 2 PT(S) => 2 O(S)",
                  Arrhenius(1.89000E+21, -0.5, 0))
```

**Comment by speth** [comment]
Unit conversions for the rate constant are tricky, especially for surface reactions, but Cantera is doing the correct thing in all cases here. The CTI input file says that its units are in cm and (gram) mole, while the XML files always default to meters and kmol (unless overridden on an individual value). Note that rates in the referenced paper are in cm, mol, and s, according to the heading of Table 2, not molecules or coverage fractions. Taking two examples from the input file provided should illustrate that the conversions are correct.

**Reaction 2:**
```
surface_reaction( "O2 + 2 PT(S) => 2 O(S)", Arrhenius(1.89000E+21, -0.5, 0))
```
The rate constant *R* for the surface reaction is computed as:
```
R = A * [O2] * [PT(s)]^2
```
where the rate constant has units of mol / cm^2 / s, the concentration of O2 (and other gas phase species) has units of mol/cm^3 and the units of concentration for PT(S) (and other surface species) has units of mol/cm^2. Taking these together, the units of A must be cm^5 / mol^2. To convert this to m^5 / mol^2, we need to multiply by (0.01)^5 / (0.001^2) = 1e-4, which you can see is the conversion factor applied in the XML file.

**Reaction 9:**
```
surface_reaction( "2 H(S) => H2 + 2 PT(S)",
                  Arrhenius(3.70000E+21, 0, 67400,
                            coverage = ['H(S)', 0.0, 0.0, -10000.0]))
```
The rate constant *R* for the surface reaction is computed as:
```
R = A * [H(s)]^2
```
where the rate constant again has units of mol / cm^2 / s and the units of concentration for H(S) has units of mol/cm^2. Taking these together, the units of A must be cm^2 / mol. To convert this to m^2 / mol, we need to multiply by (0.01)^2 / (0.001) = 0.1, which you can see is the conversion factor applied in the XML file.

Hopefully this will give you some confidence in what Cantera is doing.

**Comment by AdityaSavara** [comment]
Thank you very much for clarifying this for me.  I think that what you meant is that the CTML converts the A into units based on meters and kmol.   If I understand what you are saying and what Cantera does, I can think of it like this: the site_density is *only* used to convert between relative-surface-coverage to absolute-surface-coverage (and possibly vice versa), and that the absolute-surface-coverage is what goes into the 'conventional-form' rate equation. [Having the correct site_density number is still important, since the normal situation is to define our coverages using relative coverages in cantera]

I'm pasting below my attempt to do the unit conversions for both myself and others to find (it will remain archived even if the issue is closed).  This is consistent with what Cantera documentation says for net_production_rates (that for surfaces they are in kmol/m^2/s).  

FIRST...
Deutschmann Units for A, u_A_D:

R = A * [O2] * [PT(s)]^2

given:
mol/cm^2/s  = u_A_D  * mol/cm^3  * ( mol/cm^2 )^2

We get:
1 = u_A_D * mol/cm^3 * mol/cm^2 * s
u_A_D = cm^5 / mol^2  * s

THEN...
We decide that we want to have the following units for CTML rate, concentrations, and A, u_A_C:
R = A * [O2] * [PT(s)]^2
kmol/m^2/s = u_A_C * kmol/m^3 * (kmol/m^2)^2   [Fixed after Speth's comment below]

We get:
u_A_C = m^5 / kmol^2  * s

FINALLY:
u_A_C/u_A_D = (m^5 / kmol^2  * s)/ (cm^5 / mol^2  * s) = (0.01^5 / 0.001^2)

**Comment by speth** [comment]
That is correct, except that you left off the `^2` on the last term of your equation for units in the equation:
```
kmol/m^2/s = u_A_C * kmol/m^3 * (kmol/m^2)
```
But you have the right answer an any case.

If you're satisfied, please go ahead and close this issue.

**Comment by AdityaSavara** [comment]
Thank you!
