### ISSUE TITLE
Exceptions raised by PureFluidPhase::phaseOfMatter

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#786]
**System information**
- Cantera version: current master (237936c74)

**Expected behavior**
The phase of matter should be correctly reported.

**Actual behavior**
An exception is raised for some cases, originating in `Substance::Tsat`.

**To Reproduce**
In Python:
```python
import cantera as ct
co2 = ct.CarbonDioxide()
co2.report()
```

Produces the error:
```
~/src/cantera/interfaces/cython/cantera/thermo.pyx in cantera._cantera.ThermoPhase.report()
    288         >>> print(phase.report())
    289         """
--> 290         return pystr(self.thermo.report(bool(show_thermo), threshold))
    291 
    292     def __call__(self, *args, **kwargs):

CanteraError: 
***********************************************************************
CanteraError thrown by Substance::Tsat:
No convergence
***********************************************************************
```

Similarly:
```python
import cantera as ct
n2 = ct.Nitrogen()
n2.TP = 100, 1000
n2.phase_of_matter
```
Produces an exception which is not caught by Python:
```
terminate called after throwing an instance of 'Cantera::CanteraError'
  what():  
***********************************************************************
CanteraError thrown by Substance::Tsat:
No convergence
***********************************************************************

Aborted (core dumped)
```

**Comment by bryanwweber** [comment]
I would guess this is because the pressure results in a saturation temperature that's out of range somehow. If you don't fix it before the YAML PR is finished, I'll take a look.

**Comment by speth** [comment]
I don't think this had anything to do with the YAML PR.

Given that the equations of state have explicit temperature bounds but no pressure bounds, it makes sense that there are valid pressures where the saturation temperature is not defined. I think this can be fixed by inverting the test, i.e. testing for `pressure() < satPressure(temperature())`, since the saturation pressure will be defined for every temperature below the critical temperature.

**Comment by bryanwweber** [comment]
> I don't think this had anything to do with the YAML PR.

I meant in terms of having time/ability to focus on something new 😄 

> I think this can be fixed by inverting the test

OK, I'll start there.

**Comment by bryanwweber** [comment]
So inverting the test results in errors because

```
src/thermo/PureFluidPhase.cpp:96:29: error: 'this' argument to member function 'satPressure' has type 'const Cantera::PureFluidPhase', but function is not marked const
    } else if (pressure() > satPressure(temperature())) {
                            ^~~~~~~~~~~
include/cantera/thermo/PureFluidPhase.h:186:24: note: 'satPressure' declared here
    virtual doublereal satPressure(doublereal t);
                       ^
1 error generated.
```

This seems to be because `phaseOfMatter()` is a `const` function. I'm not sure what all of this means, except that all of the variations I tried of removing `const` and modifying `satPressure()` to account for that change also resulted in errors or `-Woverloaded-virtual`. I wonder if a check of the temperature to make sure it is in the appropriate bounds would be easier?

**Comment by speth** [comment]
Well, you would need to change definitions of `satPressure` in all derived classes that overload this as well. It unfortunately seems like it turns into a bit of a mess, since it's not easy to make all of the implementations `const`.

How would you do this check a different way? The issue is that the saturation curve isn't defined for sufficiently low pressures, and we don't know what this limiting pressure is a priori.

**Comment by bryanwweber** [comment]
I would use a `try...catch` block to check if the `satTemperature()` returned an error. If there was an error, return `"undefined"`. Otherwise, the check remains the same. Not very elegant, but should at least prevent crashing Python (which can also be done by adding `+ except_translate` to `cantera.pyx` for `phaseOfMatter()`)...

**Comment by speth** [comment]
The phase isn't undefined - the examples I gave are perfectly reasonable definitions of gaseous states. But I also wouldn't want to assume that all errors are in `satTemperature()` correspond to gaseous states.

The addition of `+translate_exception` is a good idea regardless, given that some implementations of `phaseOfMatter` can throw exceptions.

**Comment by bryanwweber** [comment]
> The phase isn't undefined - the examples I gave are perfectly reasonable definitions of gaseous states. But I also wouldn't want to assume that all errors are in `satTemperature()` correspond to gaseous states.

I agree with all of this. I got around the `const` errors by changing the condition to `else if (pressure() < m_sub->Ps())` but I'm not sure if that will cause any problems.

**Comment by speth** [comment]
That seems like an reasonable workaround to me. I wouldn't anticipate any problems with that solution.

**Comment by bryanwweber** [comment]
The concern that I have is that `Substance::Ps()` changes the state of `m_sub` (I think), and I'm not sure if that means that `phaseOfMatter()` should no longer be `const`. I guess the compiler would catch that, but I wasn't sure if this was one of those "there be dragons" cases.

**Comment by speth** [comment]
The reason the compiler allows calling the non-const method `Substance::Ps` from the const method `phaseOfMatter` is because `m_sub` is marked as a `mutable` member of `PureFluidPhase`. `mutable` variables can sometimes be a code smell, but I think it's fine in this case because the method is still logically `const` -- while it does involve temporarily modifying the state of the `m_sub` variable, the state of `m_sub` is restored in the end.

**Comment by bryanwweber** [comment]
Thanks @speth! Makes sense. I'll push the fix when I get a few minutes, hopefully today
