### ISSUE TITLE
Unit tests fail on master branch

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#807]
**System information**

- Cantera version: 2.5.0a5, commit 01a4e904be2aa3bfbccb594c93ee0916f6ce3a6c
- OS: ubuntu
- Python/MATLAB version: 3.6.8

**Expected behavior**

Unit tests work

**Actual behavior**

~2~ One unit tests fails on master (!)

**To Reproduce**

1. Pull newest commit 01a4e904be2aa3bfbccb594c93ee0916f6ce3a6c
2. Run:
```
scons build
scons test-python-purefluid
```
3. See error:

```
======================================================================
FAIL: test_X_deprecated (cantera.test.test_purefluid.TestPureFluid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/src/build/python/cantera/test/test_purefluid.py", line 87, in test_X_deprecated
    self.water.TPX = 300, 101325, 1
  File "interfaces/cython/cantera/thermo.pyx", line 1760, in cantera._cantera.PureFluid.TPX.__set__
  File "interfaces/cython/cantera/thermo.pyx", line 1775, in cantera._cantera.PureFluid.TPQ.__set__
cantera._cantera.CanteraError: 
***********************************************************************
CanteraError thrown by ThermoPhase::setState_TPQ:
Temperature (300.0), pressure (101325.0) and vapor fraction (1.0) are inconsistent.
Psat at this T: 3528.213802290444
Consider specifying the state using two fully independent properties (e.g. temperature and density)
***********************************************************************
```
**PS:** Deleted a second (spurious) failure.

**Comment by speth** [comment]
#808 resolves the first test failure.

I think the second one is a transient failure which can be resolved by running `scons test-clean` first.

**Comment by ischoegl** [comment]
That was quick!

> I think the second one is a transient failure which can be resolved by running `scons test-clean` first.

I am confirming - I removed the log from the issue description.

**Comment by bryanwweber** [comment]
> That was quick!

Yeah, we get emails when Travis builds fail so we usually know pretty quickly.
