### ISSUE TITLE
NotImplementedError while calculating Viscosity (All transport Properties)

### ISSUE THREAD

**Issue by mvinovivek** [Cantera/cantera#818]
Here is a sample code I tried to run in Python. 

```python
import cantera as ct 

gas=ct.Solution('gri30.xml')
gas.TPX=200,40e5,'CH4:1.1,O2:3.4'
gas.equilibrate('HP')
print(gas.viscosity)
```

When I run the above code, I get the error as follows:

***********************************************************
NotImplementedError thrown by Transport::viscosity:
Not implemented
***********************************************************

When I checked whether the Transport model is enabled, and it is showing the output as 'Transport'. 
```python
>>>gas.transport_model
>>>'Transport'
```
What could be the reason for the error?

Thanks

**Comment by bryanwweber** [comment]
Hi, the default phase in `gri30.xml` does not include a transport class. One way to fix this is to specify a phase name that happens to include a transport model, like

```
gas = ct.Solution('gri30.xml', 'gri30_mix')
```

for mixture-averaged transport properties, or `'gri30_multi'` for multicomponent.

**Comment by bryanwweber** [comment]
The other, more general, way to do this is to add the `transport_model` keyword argument to the `Solution` call:

```python
gas = ct.Solution("gri30.xml", transport_model="Mix")
```
or `"Multi"`.

**Comment by mvinovivek** [comment]
Wow! 

Thank you so much. It worked. 

Closing the issue.
