### ISSUE TITLE
Indexed assignment of extra columns in SolutionArray fails

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#829]
**System information**

- Cantera version: 2.5.0a4
- OS: ubuntu
- Python/MATLAB version: Python 3.6.9

**Expected behavior**

The following works
```
In [1]: import cantera as ct
   ...: gas = ct.Solution('gri30.yaml')
   ...: arr = ct.SolutionArray(gas, 10, extra={'new_column': range(10)})

In [2]: arr.new_column[0] = 10
```

**Actual behavior**

The assignment does not work, i.e.
```
In [3]: arr.new_column
Out[3]: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

**To Reproduce**

See above.

**Additional context**

Comments in #805.

**Comment by sin-ha** [comment]
I wish to work on this 
I guess storing the created extra object in some namespace should solve this.

**Comment by ischoegl** [comment]
@sin-ha ... no objections from my perspective. Please be aware that `_extra` may become an `OrderedDict` per #832/#834.

**Comment by sin-ha** [comment]
@ischoegl can you kindly review the above pr.
