### ISSUE TITLE
Binary diffusion coefficients change with composition

### ISSUE THREAD

**Issue by bassenj** [Cantera/cantera#849]
I wanted to use Cantera's implementation of multicomponent diffusion as reference to benchmark my own code but found that Cantera has a problem with binary diffusion coefficients which change depending on the number of species in the phase and its composition.

The binary diffusion coefficients in the gas phase are defined as functions of temperature, pressure and species Lennard-Jones parameters. Without higher order approximations they do not depend on the composition of the phase. 
https://github.com/Cantera/cantera/blob/aacceebe8ec2433bc56d7febc1872820cc76f687/src/transport/GasTransport.cpp#L708-L709

Higher order corrections are calculated with dummy fractions `1.0, 1.0` but never used.
https://github.com/Cantera/cantera/blob/aacceebe8ec2433bc56d7febc1872820cc76f687/src/transport/GasTransport.cpp#L714

Accordingly, the binary diffusion coefficient of any pair of species must be the same for a given set of temperature, pressure and material properties independent on the number of species that appear in the phase and the phase's compositions.

From my inspection of the source code I cannot see how the coefficients should depend on composition.

Unit tests only cover the comparison of computed values for the same system and composition.
https://github.com/Cantera/cantera/blob/aacceebe8ec2433bc56d7febc1872820cc76f687/test/transport/transportFromScratch.cpp#L76-L78

**System information**

- Cantera version: 2.4.0 (installed with `conda install --channel cantera cantera`)
- OS: [Linux Docker container](https://hub.docker.com/r/jupyter/scipy-notebook)
- Python version: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]

**To Reproduce**

Run the following script which tests two systems where the first system has one extra species. Two different compositions are tested.
```python
import cantera as ct
import numpy as np

assert ct.__version__ == '2.4.0'
print('Using Cantera {}'.format(ct.__version__))

systems = [['C2H6', 'N2', 'H2'], ['C2H6', 'H2']]

def only_first(n, value):
    x = np.zeros(n)
    x[:1] = value
    x[-1] = 1.0 - sum(x)
    return x

def all_but_last(n, value):
    x = np.zeros(n)
    x[:-1] = 0.1
    x[-1] = 1.0 - sum(x)
    return x

for x_func in [only_first, all_but_last]:
    results = {}
    for species in systems:
        name = '-'.join(species)
        results[name] = {}
        gas = ct.Solution(source='''
            ideal_gas(name='{name:}', 
                      elements='C H N',
                      species='gri30: {species:}',
                      transport='Multi',
                      initial_state=state(temperature=298, pressure=100000))
                      '''.format(name=name, species=' '.join(species)))
        gas.TP = 300, 101325
        assert species == list(map(lambda s: s.name, gas.species()))
        assert np.allclose((300, 101325), gas.TP), 'gas.TP {}'.format(gas.TP)
        gas.X = x_func(gas.n_species, 0.1)
        Dij = gas.binary_diff_coeffs
        results[name]['Xi'] = gas.X
        results[name]['Dij'] = {s1: {s2: Dkl for s2, Dkl in zip(species, Dkj)} for s1, Dkj in zip(species, Dij)}

    print('Relative error in binary diffusion coefficients:')
    r0, r1 = results.values()
    species = systems[1]
    for s1 in species:
        for s2 in species:
            print('D_{}_{}:\t {:.2f}%'.format(s1, s2, 100*(r0['Dij'][s1][s2] - r1['Dij'][s1][s2])/r0['Dij'][s1][s2]))
```
I receive the following output. The first case shows no problem but the second is demonstrating the problem.
```
Using Cantera 2.4.0
Relative error in binary diffusion coefficients:
D_C2H6_C2H6:	 -0.20%
D_C2H6_H2:	 -0.03%
D_H2_C2H6:	 -0.03%
D_H2_H2:	 0.02%
Relative error in binary diffusion coefficients:
D_C2H6_C2H6:	 34.90%
D_C2H6_H2:	 35.01%
D_H2_C2H6:	 35.01%
D_H2_H2:	 35.04%
```

**Comment by bryanwweber** [comment]
Hi! Thanks for posting this. This is indeed quite confusing behavior. Unfortunately, I don't have an answer, but we'll do our best to take a look.

If possible, could you use a debugger to try and step through the functions and see what's being called? I've had success using `lldb` on macOS, with something like
```
PYTHONPATH=build/python lldb python test.py
```
and then adding breakpoints within my Python script. I believe you'll have to build Cantera from source to be able to use this method, that's why the `PYTHONPATH` is there, it points to the `build` directory that's within the checked out source folder after you run `scons build`.

**Comment by speth** [comment]
Calling
```py
        gas.X = x_func(gas.n_species, 0.1)
```
Does not hold the pressure constant, but rather the intrinsic state variables for the phase (temperature and density for Cantera's ideal gas model). If you want to set the composition while holding temperature and pressure constant, you should write:
```py
        gas.TPX = None, None, x_func(gas.n_species, 0.1)
```
Changing this eliminates the ~35% difference seen in the second case.

The differences of <1% seen when changing the set of species comes from the polynomial fits as a function of temperature that are done at the time the `Solution` is instantiated. The temperature range used is the range where the thermodynamic properties are valid for all species. However, different species have different valid temperature ranges.

In this case, the thermo data for N2 is indicated as being valid between 300 K and 5000 K, while the data for C2H6 and H2 is indicated as being valid from 200 K to 3500 K. So for the 2-species phase, the temperature range used is 200 - 3500, while for the 3-species phase, the temperature range used is 300 - 3500. If you change the set of species to three species which all have the same temperature range, you'll see that this difference in the binary diffusion coefficients vanishes.

**Comment by bassenj** [comment]
Thank you for the quick reply. I wasn't aware of this behavior. I can confirm that this resolves the issue.
