### ISSUE TITLE
Error when parsing ck2cti or ck2yaml with large element number(more than 3 digits)

### ISSUE THREAD

**Issue by 12Chao** [Cantera/cantera#853]
**System information**

- Cantera version: 2.5.0
- OS: Ubuntu 18.0.4
- Python/MATLAB version: 3.8.0

**Expected behavior**

Regarding to the [issue](https://groups.google.com/forum/?fromgroups=#!topic/cantera-users/JK5HM5wTgys) on Cantera google user group.  The expected behavior is a successful conversion.
**Actual behavior**

It was not clear where is the error position when the user used ck2cti in Cantera 2.4.0 and python 3.7, so I tried Cantera 2.5.0 and python 3.8. The reason was that there are several species has element numbers more than 3 digits, for example, `BIN7AJ                 C 1250H 812          G    300.00   3500.00 1260.00      1`.
The function in ck2cti,  [readThermoEntry](https://github.com/Cantera/cantera/blob/7d87534bb7ef0a55bca2ab3dc4282a2ae7ddd8d5/interfaces/cython/cantera/ck2cti.py#L1015)(line 1032 `composition = self.parseComposition(lines[0][24:44], 4, 5) ` ) does not split the string correctly, `[24:44] `only covers part of the element symbols and numbers, especially when the element number is very large (species `BIN12AJ ` in the thermo file). Besides, the input value to function [parseComposition](https://github.com/Cantera/cantera/blob/7d87534bb7ef0a55bca2ab3dc4282a2ae7ddd8d5/interfaces/cython/cantera/ck2cti.py#L966) on line 1032 only successfully converts when the element number has less than 3 digits.

I am not sure if these large number are added in the file accidentally, but should Cantera add some feature to enable conversion for species with large element number?

**To Reproduce**

1. Open the directory where the chemkin files are saved
2. Run` ck2cti --input=input.CKI --thermo=thermo.CKT --transport=trans.TRC --output=new.cti --debug --permissive`
3. See error 
```
Traceback (most recent call last):
  File "/home/chao/anaconda3/envs/cantera38/bin/ck2cti", line 11, in <module>
    load_entry_point('Cantera==2.5.0a4', 'console_scripts', 'ck2cti')()
  File "/home/chao/anaconda3/envs/cantera38/lib/python3.8/site-packages/cantera/ck2cti.py", line 2352, in script_entry_point
    main(sys.argv[1:])
  File "/home/chao/anaconda3/envs/cantera38/lib/python3.8/site-packages/cantera/ck2cti.py", line 2323, in main
    surfaces = Parser.convertMech(inputFile, thermoFile, transportFile,
  File "/home/chao/anaconda3/envs/cantera38/lib/python3.8/site-packages/cantera/ck2cti.py", line 2264, in convertMech
    surface_names = parser.writeCTI(name=phaseName, outName=outName)
  File "/home/chao/anaconda3/envs/cantera38/lib/python3.8/site-packages/cantera/ck2cti.py", line 2068, in writeCTI
    speciesNames = self.getSpeciesString(self.speciesList, 21)
  File "/home/chao/anaconda3/envs/cantera38/lib/python3.8/site-packages/cantera/ck2cti.py", line 2012, in getSpeciesString
    raise InputParseError("Undefined elements in species '{}':"
cantera.ck2cti.InputParseError: Undefined elements in species 'BIN7AJ': '1'
```

**Attachments**

[input.txt](https://github.com/Cantera/cantera/files/4690917/input.txt)
[thermo.txt](https://github.com/Cantera/cantera/files/4690919/thermo.txt)
[trans.txt](https://github.com/Cantera/cantera/files/4690920/trans.txt)

**Additional context**

**Comment by speth** [comment]
I don't think the values here are accidental / erroneous, but they don't seem to follow input file format rules. Those rules pretty clearly describe the format for the elemental composition in columns 25–44 as consisting of 4 entries of 5 characters where the first two characters are for the element name and the remaining three characters are for the number of atoms of that element. This file doesn't even work in a certain commercial tool where one might expect it to.

To allow for additional elements / longer element names / larger molecules, the format does allow a syntax where those are given on additional lines of the input file, e.g. as shown here: https://github.com/Cantera/cantera/blob/7d87534bb7ef0a55bca2ab3dc4282a2ae7ddd8d5/test/data/soot-therm.dat#L39-L49

I think the only modification that should be made to Cantera here would be to provide a more helpful error message, for example showing the entire thermo entry for the offending species, like we do for some other thermo errors.

**Comment by 12Chao** [comment]
Thanks for the response @speth , I think showing entire entry is helpful and I can work on it. I forgot to mention that the conversion was completed with CanteraError when I was using ck2yaml as converter. The message is shown as
```
Wrote YAML mechanism file to 'new.yaml'.
Mechanism contains 576 species and 27369 reactions.
Validating mechanism...FAILED.

***********************************************************************
CanteraError thrown by Phase::addSpecies:
Species 'BIN7AJ' contains an undefined element '1'.
***********************************************************************
``` 
In this case, if I want to make changes like showing the entire entry, should I make it in the .cpp file or should I add another function into ck2yaml file to prevent the completed conversion by ck2yaml with wrong species compositions in it and throw an error message?

Here is the yaml file.
[new.txt](https://github.com/Cantera/cantera/files/4691996/new.txt)

**Comment by 12Chao** [comment]
I would try to raise error with the entire thermo entry from ck2yaml. To my understanding, the `Phase.cpp` file only validates the converted yaml file, and it cannot show the entire thermo entry same with the original format in the `thermo.txt` file because they are already converted. Please correct me if I am wrong.

**Comment by speth** [comment]
Yes, that sounds correct. I think this could be detected at the time the composition is parsed, perhaps using the fact that an element name shouldn't start with a number as a criterion for identifying this kind of error.
