### ISSUE TITLE
Eigen submodule references a deprecated repository. Consider switching to the official one

### ISSUE THREAD

**Issue by ilyapopov** [Cantera/cantera#861]
Currently, Eigen submodule at `ext/eigen` references the repository at [https://github.com/eigenteam/eigen-git-mirror](https://github.com/eigenteam/eigen-git-mirror) which is declared deprecated by Eigen mantainers. They have switched the official repository to git and moved it to [https://gitlab.com/libeigen/eigen](https://gitlab.com/libeigen/eigen), after which they deprecated the old git mirror.

Consider switching to using official git repository at [https://gitlab.com/libeigen/eigen](https://gitlab.com/libeigen/eigen) instead.

**Comment by bryanwweber** [comment]
Thank you! We've started this process, please see PR #803.

**Comment by bryanwweber** [comment]
Will close pending resolution of #803.

**Comment by speth** [comment]
#803 has been merged, so this is now resolved.
