### ISSUE TITLE
Broken diffusion_flame_extinction.py example

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#872]
**System information**

- Cantera version: current development branch
- OS: Ubuntu 18.04
- Python/MATLAB version: 3.6.9

**Expected behavior**

`diffusion_flame_extinction.py` terminates and produces plot.

**Actual behavior**

`diffusion_flame_extinction.py` appears to be stuck in indefinite loop.

**To Reproduce**

1. Run `python `
2. After the temperature drops below `temperature_limit_extinction`, the loop gets stuck:
```
Flame extinguished at n = 284. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 285. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 286. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 287. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 288. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 289. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 290. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 291. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 292. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 293. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 294. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 295. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 296. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 297. Restoring n = 283 with alpha = 284.0
Flame extinguished at n = 298. Restoring n = 283 with alpha = 284.0
[...]
```
3. The above keeps running beyond `n = 2000`

**Additional Context:**

Issue was found in the context of #871.

**PS:** It is relatively straight-forward to ensure that the loop exits, but there appear to be some issues with the implementation of the termination criterion itself.

**Comment by bryanwweber** [comment]
Thanks for reporting this! Can you locate when this problem started happening? Is it a problem for the 2.4.0 release?

**Comment by ischoegl** [comment]
@bryanwweber ... example works on 2.4.

**Comment by ischoegl** [comment]
Recent commits appear to have resolved the issue - I no longer can reproduce it.
