### ISSUE TITLE
AppVeyor CI apparently broken

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#878]
**System information**

N/A - failure occurs on AppVeyor build

**Expected behavior**

Changes only affecting Python *samples* should not break unit tests.

**Actual behavior**

AppVeyor build fails - see #876

One of the many failures point towards a deprecation in `"interfaces\cython\cantera\base.pyx", line 69`, i.e.
```
======================================================================
FAIL: test_blank_line_in_header (cantera.test.test_convert.ck2ctiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\cantera\build\python\cantera\test\test_convert.py", line 435, in test_blank_line_in_header
    gas = ct.Solution('blank_line_in_header' + self.ext)
  File "interfaces\cython\cantera\base.pyx", line 69, in cantera._cantera
._SolutionBase.__cinit__
DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable 
results use may want to use `np.int64` or `np.int32`.
```

**Additional context**

Breakage appears to be recent (upstream changes?), and should affect the current master branch (!).

**Comment by bryanwweber** [comment]
This appears to be related to https://github.com/numpy/numpy/pull/15534 (just cross-linking for reference)

**Comment by bryanwweber** [comment]
And also, it only affects Appveyor here because Travis is using Python 3.5, for which NumPy 1.19 is not available.
