### ISSUE TITLE
New CI test "CI / Build docs (pull_request)" fails

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#882]
**System information**

- Cantera version: development branch
- OS: N/A - GitHub CI
- Python/MATLAB version: N/A

**Expected behavior**

CI tests run successfully if `scons test` and `scons build` pass.

**Actual behavior**

The **CI / Build docs (pull_request)** test errors:
```
Set up SSH key and host for deploy
1s
##[error]Input required and not supplied: key
Run shimataro/ssh-key-action@v2
##[error]Input required and not supplied: key
```

**Additional context**

See failed test at: #881

**Comment by bryanwweber** [comment]
~Well, the build on the main branch failed with the same error so it seems like this isn't quite resolved yet.~

Just kidding, old email notification of the failure!

**Comment by speth** [comment]
Okay, good. I was going crazy trying to find a failure indication anywhere!
