### ISSUE TITLE
CI has excessive timeout / does not cancel redundant jobs

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#893]
**Problem description**

The new GitHub actions CI appears to not time out (or only after an exorbitantly long time - I've seen runs beyond 16 hours at this point), and there may not be a way for contributors to stop runners once they are deployed.

**Steps to reproduce**

Presumably, any unit test with an infinite loop will trigger this behavior.

**Behavior**

Runners become unresponsive; an attempt to terminate by pushing a new/corrected version will result in the new version remaining queued.

**System information**

N/A

**Additional context**

How to [specify a timeout for GitHub actions](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes)

Action to [cancel current runners](https://github.com/marketplace/actions/cancel-workflow-action)

Current [Actions overview](https://github.com/Cantera/cantera/actions) on Cantera/cantera

There appear to be several unresponsive runners in #892 that I am unable to terminate.

**Comment by bryanwweber** [comment]
I think the problem is moreso that builds aren't cancelled when the branch is updated. Unfortunately this isn't built-in to GitHub Actions yet, but there does seem to be a workaround: https://github.community/t/github-actions-cancel-redundant-builds-not-solved/16025

**Comment by ischoegl** [comment]
Agreed. I had erroneously assumed that redundant runs would be canceled as on other CI I had seen. Regardless, the 360 minute timeout default appears to be excessive; see suggestion in #894.

**Comment by ischoegl** [comment]
While I find the 360 minute timeout problematic from an ecological viewpoint, 'hung-up' CI runs are presumably rare. Hopefully GitHub's CI will improve in the near future: e.g. allow for canceling of redundant jobs, and building on outputs from another job in a true pipeline (see, e.g. GitLab's CI).

**Comment by bryanwweber** [comment]
I would prefer to leave this open to see if we can implement the workaround suggested by GitHub staff that I linked to earlier.

**Comment by ischoegl** [comment]
Beyond, this would be easy to try: https://github.com/technote-space/auto-cancel-redundant-job

I still am somewhat partial to reducing the timeout limit, except perhaps on coverages.

**Comment by bryanwweber** [comment]
This seems like it should be possible now via the `concurrency` field: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idconcurrency 🎉 

Specifically, adding

```yaml
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

at the top-level of the workflow file seems like it will do what we want!
