### ISSUE TITLE
Sequences can be appended as extra items on a SolutionArray

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#895]
When appending a state to a `SolutionArray`, an item of length greater than 1 can be passed for any `extra` items. This raises a `DeprecationWarning` from NumPy, and gives a... less than useful result:

```python
>>> gas = ct.Solution("air.yaml")
>>> states = ct.SolutionArray(gas, 3, extra={"prop": [5, 6, 7]}
>>> states.append(TPX=(1100, 3e5, "AR:1.0"), prop=[1, 2, 3])
>>> states.prop
/Users/bryan/GitHub/cantera/build/python/cantera/composite.py:576: VisibleDeprecationWarning:
Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays
with different lengths or shapes) is deprecated. If you meant to do this, you must specify 
'dtype=object' when creating the ndarray
  return np.array(self._extra[name])
array([5, 6, 7, list([1, 2, 3])], dtype=object)
```

Yes, that's a list as an item in a NumPy array.

Fixing this is not super straightforward, because we may need to also account for the possibility of strings as values, so a simple `if len(item) > 1` check is not sufficient, see #896.

**Comment by ischoegl** [comment]
A resolution will depend on finalization of #838 (or it could be resolved by the same PR). 

Strings are interesting: while they presumably do not throw an error, I am not sure that they should be enabled at all. E.g. they may break CSV/HDF input/output etc.; it had always been my assumption that `SolutionArray` would be strictly numeric data with a consistent `dtype`. **PS:** I added a comment to #838 as it is apparently in consideration.

**Comment by bryanwweber** [comment]
> or it could be resolved by the same PR

I'm not at all interested in further expanding the scope of that PR. I replied to the other comments over at #838.

**Comment by speth** [comment]
How does this line work?
```python
states = ct.SolutionArray(gas, 3, extra=("prop"))
```
I get the error message:
```
ValueError: Initial values for extra properties must be supplied in a dict if the SolutionArray is not initially empty
```
Which I think has been in place since the `SolutionArray` class was added.

**Comment by bryanwweber** [comment]
@speth You need to checkout the branch from #838 for the code to work. That will create a single `extra` item with the name `prop` associated with an empty array.

**Comment by speth** [comment]
So at least part of this problem is an issue with that PR, then, right? You shouldn't get that uninitialized garbage in your array because the currently existing error check should catch the case of not providing initial values for extra properties. If I create the array with values in place for `prop`, this seems to work (although I agree it's super weird and not necessarily something we want to support as-is):
```python
>>> states = ct.SolutionArray(gas, 3, extra={"prop": [5, 6, 4]})
>>> states.append(TPX=(1100, 3e5, "AR:1.0"), prop=[1, 2, 3])
>>> states.prop
array([5, 6, 4, list([1, 2, 3])], dtype=object)
```

Also, what version of Numpy are you using? I don't get that warning with Numpy 1.18.1.

**Comment by bryanwweber** [comment]
> Also, what version of Numpy are you using? I don't get that warning with Numpy 1.18.1.

1.19.0.

> So at least part of this problem is an issue with that PR, then, right? You shouldn't get that uninitialized garbage in your array because the currently existing error check should catch the case of not providing initial values for extra properties.

I don't think so, since you can reproduce what I think is the problem (having a sequence embedded in the array) with the existing code. The uninitialized garbage depends on whether or not we want to support initializing empty arrays if the user passes a sequence of names. The ability to do that seems to be a suggested addition by @sin-ha (https://github.com/Cantera/cantera/pull/838#discussion_r407226542) that I didn't catch as a new addition to the code. If you think we shouldn't add that, we should probably discuss that on #838. I'll update the original message here with your code that doesn't rely on #838.

> If I create the array with values in place for prop, this seems to work (although I agree it's super weird and not necessarily something we want to support as-is)

Yeah, it works in the original code above too, so this issue is about whether or not we want to support this behavior, and IMO we do not.
