### ISSUE TITLE
A Python script containing the Cantera library packaged into exe failed

### ISSUE THREAD

**Issue by wazedxwxx** [Cantera/cantera#914]
**Problem description**
To make it easier to use, I wrote a cantera script that I wanted to package as exe so that I could use it without having to download other software.But running after packaging always fails

**Steps to reproduce**

 1.I packaged the script with Pyinstaller
2.Seconds back after running
3.Error displayed after running with CMD

**Behavior**

![X0 P53VBS%`HHC(9LTTLQ6_WPS图片](https://user-images.githubusercontent.com/59836980/90326029-ddb62d80-dfb5-11ea-827b-9a5f38136241.png)
He showed no Interrupts, but they did
![F@@AOECC%_2CM3R5K$HRKMJ_WPS图片](https://user-images.githubusercontent.com/59836980/90326055-2b329a80-dfb6-11ea-8893-9650e625d6af.png)

**System information**

- Cantera version: [2.4]
- OS: [for example, Windows 8]
- Python/MATLAB/other software versions:python3.7

**Attachments**

**Additional context**

**Comment by bryanwweber** [comment]
Hi! Thank you for reporting this. Can you please post how you created the EXE file? I'm not sure whether this is a problem with Cantera or PyInstaller, which I think sometimes has problems packaging compiled C-code libraries, like Cantera.

**Comment by tsikes** [comment]
@wazedxwxx PyInstaller is likely not detecting the implicit call of interrupts from cantera. To resolve this you should explicitly load it  in your python file with:

`from cantera import interrupts`

So long as this is done in one of your files, PyInstaller should package it correctly.

**Comment by ischoegl** [comment]
I have seen a similar dependency as reported by @tsikes in a derivative application where I use `setuptools`
https://github.com/microcombustion/ctmicro/blob/a2d4fbb23b488a89f4b763fce3c09e187a931b26/setup.py#L23

So it’s likely not a Cantera issue.

**Comment by speth** [comment]
It may not be an issue with Cantera, but would it save people some headaches if we added `import cantera.interrupts` to `cantera/__init__.py` to help these tools that aren't fully Cython-aware?

**Comment by tsikes** [comment]
This would definitely make things easier for someone new to using such tools. I think that would be a good change.

**Comment by speth** [comment]
@tsikes Can you test that change on a local copy of Cantera with Frhodo to confirm that it works? I don't have any easy way of testing it myself.

**Comment by tsikes** [comment]
@speth I tested this change with Frhodo and it was successful.
