### ISSUE TITLE
Replace gri30.yaml in examples that use H2-O2 chemistry

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#932]
**Problem description**

Several examples use GRI3.0 despite only using H2 as fuel (e.g. Python `custom.py` and the proposed C++ custom example). As discussed in #922, `h2o2.yaml` would be a more appropriate choice under those circumstances. While run time and storage size may not be a major concern, I believe it sends the wrong message (always automatically default to `gri30.yaml`, despite this having been long superseded by better choices). Forcing users to replace the mechanism file is an opportunity to make them stop and think about alternatives (which may help clarify that GRI3.0 mainly serves illustration purposes).

The ‘fix’ is obviously not difficult. 

**PS:** As a minor ‘complication’, `N2` *could* be added as an alternative *diluent* to `h2o2.yaml` (I am *not* advocating for inclusion of any nitrogen reactions).

**System information**

- Cantera version: 2.5.0b1
- OS: all 
- Python/MATLAB/other software versions: all

**Comment by bryanwweber** [comment]
Thanks for creating this issue @ischoegl! This will be a good one for someone new to the codebase

**Comment by speth** [comment]
I'm happy to leave updating the examples for a new contributor, but the one item that I think need to be addressed before releasing 2.5.0 is adding N2 as a species to `h2o2.yaml`. I think this is generally a good idea, but doing it later would introduce the pain of having versions of `h2o2.yaml` from Cantera 2.5.0 and later versions containing different species.

**Comment by mefuller** [comment]
I'd like to work on this one (updating the examples)

**Comment by ischoegl** [comment]
@mefuller … terrific! Thanks for taking this on.
