### ISSUE TITLE
test_reactor.TestReactorSensitivities fails on Gentoo Linux

### ISSUE THREAD

**Issue by band-a-prend** [Cantera/cantera#937]
**Problem description**  

The `test_ignition_delay_sensitivity` test fails on Gentoo Linux system (build package script), with error:

```
======================================================================
FAIL: test_ignition_delay_sensitivity (cantera.test.test_reactor.TestReactorSensitivities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/sci-libs/cantera-9999/work/cantera-9999/build/python/cantera/test/test_reactor.py", line 1475, in test_ignition_delay_sensitivity
    dtigdh_cvodes = self.calc_dtdh(species)
  File "/var/tmp/portage/sci-libs/cantera-9999/work/cantera-9999/build/python/cantera/test/test_reactor.py", line 1458, in calc_dtdh
    net.step()
  File "interfaces/cython/cantera/reactor.pyx", line 1065, in cantera._cantera.ReactorNet.step
cantera._cantera.CanteraError: 
***********************************************************************
CanteraError thrown by CVodesIntegrator::step:
CVodes error encountered. Error code: -4

At t = 0.562504 and h = 4.44705e-06, the corrector convergence test failed repeatedly or with |h| = hmin.
Components with largest weighted error estimates:
9: 1.2619950208598112e-05
4: -6.431475030555704e-06
7: 4.2722540933959235e-06
5: 3.980344782879773e-06
10: -3.117565486817308e-06
3: -2.1114139462037163e-06
6: -2.0358380637250202e-07
2: -1.74791732251511e-07
8: -1.5568570503092485e-07
1: 2.2362501273472058e-20
***********************************************************************
```

**System information**

- Cantera version: [2.5.0b1 commit # 2cd0619]
- OS: [Gentoo Linux]
- Software versions:
  - gcc 9.3.0
  - python 3.7.8
  - scons 4.0.1
  - numpy 1.19.0
  - sundials 5.2.0
  - google-test 1.10.0
  - boost 1.72.0

**Comment by band-a-prend** [comment]
The same result after downgrading to sundials 3.2.1 and build Cantera in local directory:
```
...
git clone https://github.com/Cantera/cantera.git
cd ./cantera
scons build system_fmt="y" system_sundials="y" system_eigen="y" extra_inc_dirs="/usr/include/eigen3" python_package="full"
scons test


======================================================================
FAIL: test_ignition_delay_sensitivity (cantera.test.test_reactor.TestReactorSensitivities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/Downloads/cantera/ct2.5.0b1/cantera/build/python/cantera/test/test_reactor.py", line 1475, in test_ignition_delay_sensitivity
    dtigdh_cvodes = self.calc_dtdh(species)
  File "/home/user/Downloads/cantera/ct2.5.0b1/cantera/build/python/cantera/test/test_reactor.py", line 1458, in calc_dtdh
    net.step()
  File "interfaces/cython/cantera/reactor.pyx", line 1065, in cantera._cantera.ReactorNet.step
cantera._cantera.CanteraError: 
***********************************************************************
CanteraError thrown by CVodesIntegrator::step:
CVodes error encountered. Error code: -4

At t = 0.562504 and h = 4.44705e-06, the corrector convergence test failed repeatedly or with |h| = hmin.
Components with largest weighted error estimates:
9: 1.2619950208598112e-05
4: -6.431475030555704e-06
7: 4.2722540933959235e-06
5: 3.980344782879773e-06
10: -3.117565486817308e-06
3: -2.1114139462037163e-06
6: -2.0358380637250202e-07
2: -1.74791732251511e-07
8: -1.5568570503092485e-07
1: 2.2362501273472058e-20
***********************************************************************
```

**Comment by bryanwweber** [comment]
Can you determine whether or not this is due to the `gcc` version? If you use GCC 8, does it work?

**Comment by band-a-prend** [comment]
I tried to build cantera with clang 10.0.1 (without rebuild with clang any system dependencies) and got the same error.
I could try rebuild sundials and cantera with other GCC 8.4.0 or 10.2.0 tomorrow

p.s. (cython version is 0.29.20)

**Comment by band-a-prend** [comment]
Build with cantera provided ext non-system sundials 5.3.0 (sundials and cantera build with clang-10.0.1) with the same error result.
Build options  
`scons -j4 build system_fmt="y" system_sundials="n" system_eigen="y" extra_inc_dirs="/usr/include/eigen3" python_package="full" f90_interface="n" CC="clang" CXX="clang++"`

**Comment by band-a-prend** [comment]
Test with gcc 8.4.0 and rebuild for that system eigen, cython, sundials on other gentoo machine. The same test fail.

I also tried to use with gcc 9.3.0 several versions of cython because initially used had some regressions. No success.

I need to investigate problem more carefully.

**Comment by band-a-prend** [comment]
I tried to test it with `scons -j4 build system_fmt="n" system_sundials="n" system_eigen="n" python_package="full" f90_interface="n"` with the same result. I tried with several versions of cython 0.29.15, 0.29.20, 0.29.21 - with no succes (on the another gentoo sysytem). 

Could this issue be related to numpy or boost version?

**Comment by band-a-prend** [comment]
@bryanwweber 
this issue is partially related to commit https://github.com/Cantera/cantera/commit/9832c883bc5212133bf671fa99e5a0bdc47be651.
If I `set net.rtol_sensitivity` to it's default value `1e-4` or change to `5e-6` the test successfully passed. If I set it to `1.1e-6` it fails again. With value `1e-6` this test runs too long.

I tried to add `net.rtol_sensitivity = 1e-5` string to cantera-2.4.0 appropreate test and it passed with some warnings like (don't remember exactly) about numpy deprecation of `integer` or `insignedinterger` to dtype that is related to `ct.Solution()` for *.xml or *.cti files.

**Comment by inducer** [comment]
@band-a-prend FYI https://github.com/conda-forge/staged-recipes/pull/13414#issuecomment-742778250

**Comment by band-a-prend** [comment]
@inducer thank you for information.

I don't used `blas_lapack_libs = 'lapack,blas'` option  explicitly but one of lapack implementation could be presented in my system as dependency for other packages.

**Comment by speth** [comment]
I was finally able to replicate at least one version of this problem, using packages installed using Spack on top of Ubuntu 20.04. Using the exact versions of GCC, Python, SCons, Numpy, Sundials, and Boost listed in the original post, I don't get the error report from CVODES, but I do get the behavior where the integrator stalls and will just take hundreds of thousands of timesteps without reaching the desired end time. 

Switching to our vendored version of Sundials (5.3.0), I see that using `rtol_sensitivity = 1e-5` seems to be a uniquely bad choice for some reason, even though the test does pass. Here, it takes ~11,000 steps to reach the end time, while setting it to looser values of 2e-5, 5e-5, or 1e-4, or even a tighter value of 5e-6 allows the integration to complete in ~2000 steps, about the same as the number of steps taken when not solving the sensitivity ODEs.

The test failure mentioned in 9832c88 was the macOS build in our CI system - there's some discussion of this in #851, which that commit was part of. Cantera/enhancements#55 describes what I think is the underlying issue here.

Based on all of this, I'm going to try a PR to adjust this tolerance to 2e-5 to see if we can thread the needle between having integrator problems and getting unreliable sensitivities. @band-a-prend, I'd appreciate confirmation on whether this change fixes the problem as identified on Gentoo.

**Comment by band-a-prend** [comment]
@speth 
Great thanks for problem investigation!

I re-tested cantera-2.5.0b1 for my updated system  
* gcc 9.3.0
* python 3.8.6
* scons 4.0.1
* numpy 1.19.4
* sundials 5.2.0
* eigen 3.3.7
* google-test 1.10.0
* boost 1.74.0
* libfmt 7.0.3

and got following results for **test_ignition_dalay_sensitivity**  

| net.rtol_sensitivity | test result |
| --- | --- |
| 2e-6 | ok |
| 5e-6 | ok |
| 1e-5 | FAILED |
| 2e-5 | ok |
| 5e-5 | ok |
| 1e-4 | ok |
