### ISSUE TITLE
Parameters for SRI expression of Falloff reactions cannot be parsed correctly

### ISSUE THREAD

**Issue by 12Chao** [Cantera/cantera#940]
**Problem description**
When I was using ck2yaml to convert a CHEMKIN file with one SRI expression, 5 parameters were provided for that reaction, but only 4 were written in the yaml file.  The last parameter `E` is `0.0000` in the CHEMKIN file, which was not written in the converted yaml file. When I used `ct.Solution` to load the yaml file, it threw the error:
```
cantera._cantera.CanteraError: 
***********************************************************************
CanteraError thrown by SRI::init:
Incorrect number of parameters. 3 or 5 required. Received 4.
***********************************************************************
```
I have checked that all the 5 parameters can be correctly read from CHEMKIN file by `Parser.read_kinetics_entry()` and saved in `class Sri()`, so there must be something wrong when writing things into yaml file, but I couldn't figure it out.

**Steps to reproduce**

1. `ck2yaml --input=YOUR_PATH_TO_MECH --thermo=YOUR_PATH_TO_THERMO --transport=YOUR_PATH_TO_TRANSPORT `
2. `ct.Solution(OUTPUT_FILE)`
see error:
```
cantera._cantera.CanteraError: 
***********************************************************************
CanteraError thrown by SRI::init:
Incorrect number of parameters. 3 or 5 required. Received 4.
***********************************************************************
```

**Behavior**

**System information**

- Cantera version: 2.5.0
- OS: Ubuntu 20.04
- Python/MATLAB/other software versions: Python 3.8

**Attachments**
[mechanism.txt](https://github.com/Cantera/cantera/files/5302071/mechanism.txt)
[thermo.txt](https://github.com/Cantera/cantera/files/5302072/thermo.txt)
[transport.txt](https://github.com/Cantera/cantera/files/5302073/transport.txt)

**Comment by ischoegl** [comment]
Looks like `E=0` would evaluate as `False` here:
https://github.com/Cantera/cantera/blob/2cd06194e80aa0f43cba36575ecf1cdc6c073391/interfaces/cython/cantera/ck2yaml.py#L675
which may explain the behavior. Should be easy to verify/fix.
