### ISSUE TITLE
ctml_writer.py ignores beta=0 for electrochemical reactions

### ISSUE THREAD

**Issue by simonrihm** [Cantera/cantera#954]
**Problem description**
If I define an electrochemical surface_reaction in my .cti file and specify beta=0, the ctml_writer does not write a `<electrochem beta="0">` node but treats it as a non-electrochemical reaction. The problem is that "importKinetics" then recognizes this reaction as electrochemical and assigns a default value of beta=0.5. 
This makes it impossible to define an electrochemical reaction that has a potential-independent energy barrier without either manually manipulating the XML file or setting beta to a very small value (e.g. 1e-20) as workaround. While these are easy fixes, the main problem is that the described behaviour is not expected.

**Steps to reproduce**

1. Create CTI file with electrochemical surface reaction where beta=0
2. Run ctml_writer.py on it to create XML input file
3. Import surface phase via "get_XML_File" and "findXMLPhase"
4. Create "InterfaceKinetics" object via "importKinetics"

**Behavior**

The ctml_writer seems to consider beta=0 as indicative of a reaction without charge transfer and therefore does not write a <electrochem> node to the XML file. The C++ import functions then recognize the reaction as indeed having charge transfer and apply the "standard" value of 0.5.

The main problem is line 132 in "ctml_writer.py"

>         if self._type == 'edge' or self._type == 'surface':
>            if self._beta > 0:
>                electro = kfnode.addChild('electrochem')
>                electro['beta'] = repr(self._beta)

**System information**

- Cantera version: 2.4.0
- OS: Windows 10
- Python/MATLAB/other software versions: Python/C++

**Attachments**

Example CTI file for reproduction:

> t_0 = 298.15	 # standard temperature in K
> p_0 = 101325	 # standard pressure in Pa
> 
> incompressible_solid(
> 	 name='liquid',
> 	 elements='H E',	 
> 	 species=('H+'),
> 	 density=(997,'kg/m3')
> ) 
> 
> species( 
> 	 name='H+', 
> 	 atoms='H:1 E:-1'
> )
> 
> metal(
> 	 name='solid',
> 	 elements='E',	 species=('e-')
> )
> 
> species( 
> 	 name='e-', 
> 	 atoms='E:1'
> ) 
> 
> ideal_interface(
> 	 name='surface',
> 	 elements='H',	 
> 	 species=('(Cu)','H(Cu)')
> )
> 
> species( 
> 	 name='(Cu)', 
> 	 atoms='H:0'
> ) 
> 
> species( 
> 	 name='H(Cu)', 
> 	 atoms='H:1'
> )
> 
> surface_reaction(
> 	id='H2_ads',
> 	equation='1 H+ + 1 e- + 1 (Cu) <=> 1 H(Cu)',
> 	kf=(6.214e+12,0,1), 
> 	beta=0
> )

**Additional context**

Unfortunately, just changing line 1322 to `if self._beta > 0:` will result in another problem: Now if we do not specify a beta for an electrochemical reaction, it will be automatically set to zero and written as such to the XML. This defies the idea of having beta=0.5 as a default value. Maybe the `__init__` in the ctml_writer should set beta to a negative value. This way we can distinguish between a non-specified beta and a beta=0.

**Comment by decaluwe** [comment]
Hi @simonrihm thanks for posting this.  Setting the beta default to < 0 was the idea I was toying with, as well.

Just in case somebody might want to play with a negative beta (I can't figure out what this would mean, but you never know...), I'm playing with beta = -100, and so now the `self._beta > 0` catch will be replaced with `self._beta > -100.0`.  Just running through the tests right now, then will load a CTI file and see if it is resolved.

Just FYI, Cantera is moving away from CTI and to a new, yaml-based input format.  I wonder if this problem persists there, as well...

**Comment by bryanwweber** [comment]
I seem to recall this issue having been discussed before, but I can't recall where...

In any case, it would probably be better (in Python) to set a "check value" of `None`, rather than a floating point number. That better captures the meaning behind what the goal is. Then the check becomes `if self.bet is not None`. I haven't checked whether this is sensible though, but that's the typical thing to do in Python.

**Comment by decaluwe** [comment]
So, if the argument has a default in the class initialization, will it still evaluate to `None`?
 
I guess I can just change the default to `None`.

**Comment by decaluwe** [comment]
@simonrihm I just made a pull request (#955 ) that solves this, I think.

It is currently failing the tests for reasons that I cannot comprehend (@bryanwweber any help here?), but you are welcome to pull from my repo and play around to see if it suits your needs.

**Comment by bryanwweber** [comment]
@decaluwe I don't know about the macOS failures, but the Ubuntu failure is known and I also don't know why it's failing :joy:
