### ISSUE TITLE
ck2yaml converter gives empty values for coverage_dependancies

### ISSUE THREAD

**Issue by gkogekar** [Cantera/cantera#956]
**Problem description**

When a surface mechanism from Chemkin is converted into YAML format using the `ck2yaml `command, the field `coverage_dependancies`  for surface reactions is empty.  Another issue is that the reaction numbers are also not updated. (Always shows `# Reaction -1`). 

If the same mechanism is used to convert to CTI format using the `ck2cti `command, `coverage_dependancies` are updated accurately.

**To reproduce**
Run the command : 
`python.exe -m cantera.ck2yaml --input=chem.inp --thermo=therm.dat --transport=tran.dat --surface=surf.inp --permissive`

**Behavior**

The surface reactions in the original Chemkin surface file are - 
```
N2 +Ru(s) +Ru(s) =>N(s) +N(s)             5.160E-05  0.000      32.842 
    STICK 
    COV/N(s)  						0.000E+00  0.000      -27.000/
H2 +Ru(s) +Ru(s) =>H(s) +H(s)             5.625E-03  0.000      -0.371 
    STICK 
H(s) +H(s) =>Ru(s) +Ru(s) +H2             1.492E+17  0.489      85.249 
    COV/H(s)                                0.000E+00  0.000      -5.000/
```
The converted YAML file shows
```
- equation: N2 + Ru(s) + Ru(s) => N(s) + N(s)  # Reaction -1
  sticking-coefficient: {A: 5.16e-05, b: 0.0, Ea: 32.842}
  coverage-dependencies: {}
- equation: H2 + Ru(s) + Ru(s) => H(s) + H(s)  # Reaction -1
  sticking-coefficient: {A: 5.625e-03, b: 0.0, Ea: -0.371}
- equation: H(s) + H(s) => Ru(s) + Ru(s) + H2  # Reaction -1
  rate-constant: {A: 1.492e+17, b: 0.489, Ea: 85.249}
  coverage-dependencies: {}
```

**System information**

- Cantera version: 2.5.0b1
- OS: Windows 10

**Attachments**
[convertedYAML.txt](https://github.com/Cantera/cantera/files/5803730/convertedYAML.txt)
[convertedCTI.txt](https://github.com/Cantera/cantera/files/5803743/convertedCTI.txt)
[surf.txt](https://github.com/Cantera/cantera/files/5803744/surf.txt)
[chem.txt](https://github.com/Cantera/cantera/files/5803745/chem.txt)
[therm.txt](https://github.com/Cantera/cantera/files/5803748/therm.txt)

**Comment by speth** [comment]
Can you please provide a full example, e.g. including the complete Chemkin surface, thermo, and gas phase input files?

**Comment by gkogekar** [comment]
I have attached the mechanism in .txt format here. It doesn't allow me to attach *.inp files.

**Comment by khaledcomb** [comment]
> **Problem description**
> 
> When a surface mechanism from Chemkin is converted into YAML format using the `ck2yaml `command, the field `coverage_dependancies` for surface reactions is empty. Another issue is that the reaction numbers are also not updated. (Always shows `# Reaction -1`).
> 
> If the same mechanism is used to convert to CTI format using the `ck2cti `command, `coverage_dependancies` are updated accurately.
> 
> **To reproduce** Run the command : `python.exe -m cantera.ck2yaml --input=chem.inp --thermo=therm.dat --transport=tran.dat --surface=surf.inp --permissive`
> 
> **Behavior**
> 
> The surface reactions in the original Chemkin surface file are -
> 
> ```
> N2 +Ru(s) +Ru(s) =>N(s) +N(s)             5.160E-05  0.000      32.842 
>     STICK 
>     COV/N(s)  						0.000E+00  0.000      -27.000/
> H2 +Ru(s) +Ru(s) =>H(s) +H(s)             5.625E-03  0.000      -0.371 
>     STICK 
> H(s) +H(s) =>Ru(s) +Ru(s) +H2             1.492E+17  0.489      85.249 
>     COV/H(s)                                0.000E+00  0.000      -5.000/
> ```
> 
> The converted YAML file shows
> 
> ```
> - equation: N2 + Ru(s) + Ru(s) => N(s) + N(s)  # Reaction -1
>   sticking-coefficient: {A: 5.16e-05, b: 0.0, Ea: 32.842}
>   coverage-dependencies: {}
> - equation: H2 + Ru(s) + Ru(s) => H(s) + H(s)  # Reaction -1
>   sticking-coefficient: {A: 5.625e-03, b: 0.0, Ea: -0.371}
> - equation: H(s) + H(s) => Ru(s) + Ru(s) + H2  # Reaction -1
>   rate-constant: {A: 1.492e+17, b: 0.489, Ea: 85.249}
>   coverage-dependencies: {}
> ```
> 
> **System information**
> 
> * Cantera version: 2.5.0b1
> * OS: Windows 10
> 
> **Attachments** [convertedYAML.txt](https://github.com/Cantera/cantera/files/5803730/convertedYAML.txt) [convertedCTI.txt](https://github.com/Cantera/cantera/files/5803743/convertedCTI.txt) [surf.txt](https://github.com/Cantera/cantera/files/5803744/surf.txt) [chem.txt](https://github.com/Cantera/cantera/files/5803745/chem.txt) [therm.txt](https://github.com/Cantera/cantera/files/5803748/therm.txt)

did you tray to convert from yaml to ck? if yes can you please share with us the script?
