### ISSUE TITLE
Error starting the program

### ISSUE THREAD

**Issue by Dmitriy-Filatov-A** [Cantera/cantera#969]
Hello! 
I am trying to run "A Very Simple C++ Program" and I have a problem:

***********************************************************************
CanteraError thrown by ct2ctml_string:
Error converting input file "/usr/local/share/cantera/data/h2o2.cti" to CTML.
Python command was: 'python'
The exit code was: 1
-------------- start of converter log --------------
sys.path: ['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
ImportError: No module named cantera
--------------- end of converter log ---------------
***********************************************************************
I have successfully compiled the source code on the ubuntu 20.04 operating system and successfully installed cantera.

The following programs are installed on my computer:
Python 2.7.18
Python 3.8.5
GNU (gcc v.9.3.0)
pip 20.0.2 (for Python 3)
Boost
SUNDIALS

I also installed other programs for the successful compilation and installation of cantera.

I am confused by the type of error and I do not know how to fix it

Please help me! Thank you in advance!

**Comment by speth** [comment]
It looks like the Cantera Python module is not installed in the expected location. This module is required for working with CTI input  files. How did you download Cantera, and what version did you compile? Do you have the output from the `scons build` command available? I'm interested specifically in the first ~40 lines or so, where it shows all the configuration checks and what versions of software it found. The last handful of lines from `scons install` would also be helpful, for understanding which components were installed where.

As a workaround, if you do not need to use CTI format mechanisms (that is, you are using either the XML format, or, if you're using the 2.5.0 development version, YAML format) you can use those without having the Python module installed. For the example program, you would just replace `h2o2.cti` with `h2o2.xml` or `h2o2.yaml`.

**Comment by Dmitriy-Filatov-A** [comment]
1) I downloaded Cantera from an official source https://github.com/Cantera/cantera.git and I followed the instructions of this site:  https://cantera.org/install/compiling-install.html.
I compiled version 2.4 (tags/v2.4.0).

2) The output from the scons build command:
$ scons build
scons: Reading SConscript files ...
INFO: SCons is using the following Python interpreter: /usr/bin/python3
Configuration variables read from 'cantera.conf' and command line:

Checking for C++ header file cmath... (cached) yes
Checking for C++ header file fmt/ostream.h... (cached) no
INFO: Using private installation of fmt library.
INFO: Found fmt version 5.0.0
Checking for C++ header file gtest/gtest.h... (cached) no
Checking for C++ header file gmock/gmock.h... (cached) no
INFO: Using Googletest from Git submodule
Checking for C++ header file Eigen/Dense... (cached) no
INFO: Using private installation of Eigen.
INFO: Found Eigen version 3.3.4
Checking whether __GLIBCXX__ is declared... (cached) yes
Checking whether _LIBCPP_VERSION is declared... (cached) no
INFO: Found Boost version 1.71
Checking for CVodeCreate(CV_BDF, CV_NEWTON) in C++ library sundials_cvodes... (cached) no
Checking for double x; log(x) in C library None... (cached) no
INFO: Using private installation of Sundials version 3.1.
INFO: Using 'gfortran' to build the Fortran 90 interface
WARNING: Cython could not be imported by the Python interpreter running SCons.
INFO: Building the minimal Python package for Python 2.7
INFO: Building the minimal Python package for Python 3.8
scons: done reading SConscript files.
scons: Building targets ...
ConfigBuilder(["build/src/config.h.build"], ["include/cantera/base/config.h.in"])
Generating build/src/config.h.build with the following settings:
    CANTERA_SHORT_VERSION               "2.4"
    CANTERA_VERSION                     "2.4.0"
    CT_SUNDIALS_USE_LAPACK              0
    CT_SUNDIALS_VERSION                 31
    FTN_TRAILING_UNDERSCORE             1
    LAPACK_FTN_STRING_LEN_AT_END        1
    LAPACK_FTN_TRAILING_UNDERSCORE      1
    LAPACK_NAMES_LOWERCASE              1
ConfigBuilder(["include/cantera/ext/sundials/sundials_config.h"], ["ext/sundials_config.h.in"])
Generating include/cantera/ext/sundials/sundials_config.h with the following settings:
    SUNDIALS_USE_GENERIC_MATH           1
    SUNDIALS_BLAS_LAPACK                *undefined*
postBuildMessage(["finish_build"], [])
*******************************************************
Compilation completed successfully.

- To run the test suite, type 'scons test'.
- To install, type '[sudo] scons install'.
*******************************************************
scons: done building targets.

3) The output from the scons install command:
$ sudo scons install
................
.................
Cantera has been successfully installed.

File locations:

  applications                /usr/local/bin
  library files               /usr/local/lib
  C++ headers                 /usr/local/include
  samples                     /usr/local/share/cantera/samples
  data files                  /usr/local/share/cantera/data
Setup scripts to configure the environment for Cantera are at:

  setup script (bash)         /usr/local/bin/setup_cantera
  setup script (csh/tcsh)     /usr/local/bin/setup_cantera.csh

It is recommended that you run the script for your shell by typing:

  source /usr/local/bin/setup_cantera

before using Cantera, or else include its contents in your shell login script.

scons: done building targets.


4) Your advice really worked! I replace h2o2.cti with h2o2.xml and "A Very Simple C++ Program" is working! Thanks a million for your advice!

5) I still have a question about the Cantera Python module. Do I have to set this for the Cantera to work properly? How do I install the Cantera Python module?

**Comment by speth** [comment]
In answer to (5), you do not need the full Cantera Python module to use Cantera from C++, but you do at least need the "minimal" Python module in order to read CTI mechanism files. 

According to the build log, the "minimal" module was installed, but I can't tell where. Given that you've installed Cantera to the default location, I would have expected this Python module to be on the Python search path. Could you attach the full output of the `scons install` command? The information I'm looking for unfortunately isn't printed in the summary at the end.

**Comment by Dmitriy-Filatov-A** [comment]
Result of scons install command:
$ sudo scons install
scons: Reading SConscript files ...
INFO: SCons is using the following Python interpreter: /usr/bin/python3
Configuration variables read from 'cantera.conf' and command line:

Checking for C++ header file cmath... (cached) yes
Checking for C++ header file fmt/ostream.h... (cached) no
INFO: Using private installation of fmt library.
INFO: Found fmt version 5.0.0
Checking for C++ header file gtest/gtest.h... (cached) no
Checking for C++ header file gmock/gmock.h... (cached) no
INFO: Using Googletest from Git submodule
Checking for C++ header file Eigen/Dense... (cached) no
INFO: Using private installation of Eigen.
INFO: Found Eigen version 3.3.4
Checking whether __GLIBCXX__ is declared... (cached) yes
Checking whether _LIBCPP_VERSION is declared... (cached) no
INFO: Found Boost version 1.71
Checking for CVodeCreate(CV_BDF, CV_NEWTON) in C++ library sundials_cvodes... (cached) no
Checking for double x; log(x) in C library None... (cached) no
INFO: Using private installation of Sundials version 3.1.
INFO: Using 'gfortran' to build the Fortran 90 interface
WARNING: Cython could not be imported by the Python interpreter running SCons.
INFO: Building the minimal Python package for Python 2.7
INFO: Building the minimal Python package for Python 3.8
scons: done reading SConscript files.
scons: Building targets ...
ConfigBuilder(["build/src/config.h.build"], ["include/cantera/base/config.h.in"])
Generating build/src/config.h.build with the following settings:
    CANTERA_SHORT_VERSION               "2.4"
    CANTERA_VERSION                     "2.4.0"
    CT_SUNDIALS_USE_LAPACK              0
    CT_SUNDIALS_VERSION                 31
    FTN_TRAILING_UNDERSCORE             1
    LAPACK_FTN_STRING_LEN_AT_END        1
    LAPACK_FTN_TRAILING_UNDERSCORE      1
    LAPACK_NAMES_LOWERCASE              1
ConfigBuilder(["include/cantera/ext/sundials/sundials_config.h"], ["ext/sundials_config.h.in"])
Generating include/cantera/ext/sundials/sundials_config.h with the following settings:
    SUNDIALS_USE_GENERIC_MATH           1
    SUNDIALS_BLAS_LAPACK                *undefined*
cd interfaces/python_minimal && "python2" setup2.py build --build-lib=../../build/python2 install --user --record=../../build/python2-installed-files.txt --single-version-externally-managed
running build
running build_py
running install
running install_lib
running install_egg_info
running egg_info
writing Cantera_minimal.egg-info/PKG-INFO
writing top-level names to Cantera_minimal.egg-info/top_level.txt
writing dependency_links to Cantera_minimal.egg-info/dependency_links.txt
writing entry points to Cantera_minimal.egg-info/entry_points.txt
reading manifest file 'Cantera_minimal.egg-info/SOURCES.txt'
writing manifest file 'Cantera_minimal.egg-info/SOURCES.txt'
removing '/usr/local/lib/python2.7/site-packages/Cantera_minimal-2.4.0.egg-info' (and everything under it)
Copying Cantera_minimal.egg-info to /usr/local/lib/python2.7/site-packages/Cantera_minimal-2.4.0.egg-info
running install_scripts
Installing ck2cti script to /usr/local/bin
Installing ctml_writer script to /usr/local/bin
writing list of installed files to '../../build/python2-installed-files.txt'
find_module_dir(["interfaces/python_minimal/dummy2"], ["build/python2/cantera/__init__.py"])
cd interfaces/python_minimal && "/usr/bin/python3" setup3.py build --build-lib=../../build/python3 install --user --record=../../build/python3-installed-files.txt --single-version-externally-managed
running build
running build_py
running install
running install_lib
running install_egg_info
running egg_info
writing Cantera_minimal.egg-info/PKG-INFO
writing dependency_links to Cantera_minimal.egg-info/dependency_links.txt
writing entry points to Cantera_minimal.egg-info/entry_points.txt
writing top-level names to Cantera_minimal.egg-info/top_level.txt
reading manifest file 'Cantera_minimal.egg-info/SOURCES.txt'
writing manifest file 'Cantera_minimal.egg-info/SOURCES.txt'
removing '/usr/local/lib/python3.8/site-packages/Cantera_minimal-2.4.0.egg-info' (and everything under it)
Copying Cantera_minimal.egg-info to /usr/local/lib/python3.8/site-packages/Cantera_minimal-2.4.0.egg-info
running install_scripts
Installing ck2cti script to /usr/local/bin
Installing ctml_writer script to /usr/local/bin
writing list of installed files to '../../build/python3-installed-files.txt'
find_module_dir(["interfaces/python_minimal/dummy3"], ["build/python3/cantera/__init__.py"])
postInstallMessage(["finish_install"], [])

Cantera has been successfully installed.

File locations:

  applications                /usr/local/bin
  library files               /usr/local/lib
  C++ headers                 /usr/local/include
  samples                     /usr/local/share/cantera/samples
  data files                  /usr/local/share/cantera/data
Setup scripts to configure the environment for Cantera are at:

  setup script (bash)         /usr/local/bin/setup_cantera
  setup script (csh/tcsh)     /usr/local/bin/setup_cantera.csh

It is recommended that you run the script for your shell by typing:

  source /usr/local/bin/setup_cantera

before using Cantera, or else include its contents in your shell login script.

scons: done building targets.

**Comment by speth** [comment]
Thanks for providing the additional information. It looks like there is a problem with the logic for the installation path of the 'minimal' Python module on Debian-based systems. I've made a pull request that includes what I think should be a fix.

As a workaround for Cantera 2.4.0, you can try adding the argument `python_prefix=USER` to the `scons build` command. This will result in the Python module being installed in your home directory, in a path that should be on the Python search path automatically.
