### ISSUE TITLE
Building the Matlab interface fails

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#978]
**Problem description**

With the current `main` (https://github.com/Cantera/cantera/commit/643fdea8208d619d5168f4d66f80f684ca2d876d) branch, building the Matlab interface fails:

```
src/matlab/flowdevicemethods.cpp:77:21: error: no matching function for call to 'flowdev_massFlowRate'
                r = flowdev_massFlowRate(i, v);
                    ^~~~~~~~~~~~~~~~~~~~
include/cantera/clib/ctreactor.h:57:25: note: candidate function not viable: requires single argument 'i', but 2 arguments were provided
    CANTERA_CAPI double flowdev_massFlowRate(int i);
```

**Steps to reproduce**

1. `git switch main && scons build matlab_toolbox=y`

- OS: macOS 10.14 with the Apple clang compiler

**Additional context**

https://github.com/Cantera/conda-recipes/runs/1927627896#step:10:1212

Cantera/conda-recipes#24

**Comment by ischoegl** [comment]
I can reproduce the error on a windows build using VS19 ([see setup](https://gist.github.com/ischoegl/ab777f871a48d7f40ecc32c1c849faa3)) at the `scons build` stage:
```
[...]
flowdevicemethods.cpp 
src\matlab\flowdevicemethods.cpp(77): error C2660: 'flowdev_massFlowRate': function does not take 2 arguments
C:\Users\ischo\GitHub\cantera\include\cantera/clib/ctreactor.h(57): note: see declaration of 'flowdev_massFlowRate'
scons: *** [build\src\matlab\flowdevicemethods.obj] Error 2
scons: building terminated because of errors.
```
**PS:** Adding a reference to #977 here (specifically abff4359096df92bee49cb5a2051f348b4fa095e)

**Comment by ischoegl** [comment]
@bryanwweber ... will push fix shortly.
