### ISSUE TITLE
Boost will be removed from GitHub Actions

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#990]
**Problem description**

Boost will be removed from Ubuntu and Windows GitHub Actions environments on March 8 (today!). https://github.com/actions/virtual-environments/issues/2667

**Comment by speth** [comment]
For us, I think we should be able to adapt and use this cross-platform solution, since we only require the header-only portions of Boost: https://github.com/actions/virtual-environments/issues/2667#issuecomment-778655341

**Comment by ischoegl** [comment]
It appears that CI is starting to break - at the moment in **CI / windows-2019**.
